// C code generated by Lisaac compiler (www.isaacOS.com) //
int arg_count;
char **arg_vector;

//==========================//
// EXTERNAL                 //
//==========================//

// MEMORY

#define MINIMUM_SIZE 256  
void *table_size[MINIMUM_SIZE/sizeof(void *)];
void *last_block[64];

// FLOAT_REAL
#include <math.h>
// SYSTEM_IO

#include <stdio.h>
#include <stdlib.h>
  
// Hardware 'print_char'
void print_char(char car)
{
  fputc(car,stdout);
}

// Hardware 'exit'
int die_with_code(int code)
{
  exit(code);
}


// SYSTEM
#include <time.h>

//==========================//
// TYPE                     //
//==========================//

// Generic Object
struct ___OBJ {
  unsigned long __id;
};

// NULL
#ifndef NULL
#define NULL ((void *)0)
#endif

// POINTER
typedef void * __POINTER;

// UINTEGER_32
typedef unsigned long __UINTEGER_32;

// INTEGER
typedef int __INTEGER;

// CHARACTER
typedef char __CHARACTER;

// STRING
#define __STRING__ 4
typedef struct STRING_struct __STRING;
struct STRING_struct {
  unsigned long __id;
  __INTEGER count__EDE;
  __INTEGER capacity__O1H;
  __CHARACTER *storage__X1H;
};
__STRING STRING_={__STRING__};
#define STRING__ (&STRING_)

// MEMORY
#define __MEMORY__ 0
typedef struct MEMORY_struct __MEMORY;
struct MEMORY_struct {
  volatile __UINTEGER_32 previous_linear__RM;
  volatile __UINTEGER_32 size_and_id__SM;
  __MEMORY *next_free__TM;
  __MEMORY *previous_free__UM;
} __attribute__ ((packed));
__MEMORY MEMORY_;
#define MEMORY__ (&MEMORY_)

// STRING_CONSTANT
#define __STRING_CONSTANT__ 5
typedef struct STRING_CONSTANT_struct __STRING_CONSTANT;
struct STRING_CONSTANT_struct {
  unsigned long __id;
  __INTEGER count__5BE;
  __CHARACTER *storage__L5F;
};
__STRING_CONSTANT STRING_CONSTANT_={__STRING_CONSTANT__};
#define STRING_CONSTANT__ (&STRING_CONSTANT_)

// NUMERIC
#define __NUMERIC__ 1
typedef struct NUMERIC_struct __NUMERIC;
struct NUMERIC_struct {
  void *Nothing;
};
__NUMERIC NUMERIC_;
#define NUMERIC__ (&NUMERIC_)

// ARRAYED_COLLECTION[STRING]
#define __ARRAYED_COLLECTIONoSTRINGo__ 2
typedef struct ARRAYED_COLLECTIONoSTRINGo_struct __ARRAYED_COLLECTIONoSTRINGo;
struct ARRAYED_COLLECTIONoSTRINGo_struct {
  __INTEGER upper__KG;
  __INTEGER capacity__DAC;
  void **storage__OAC;
};
__ARRAYED_COLLECTIONoSTRINGo ARRAYED_COLLECTIONoSTRINGo_;
#define ARRAYED_COLLECTIONoSTRINGo__ (&ARRAYED_COLLECTIONoSTRINGo_)

// FAST_ARRAY[STRING]
#define __FAST_ARRAYoSTRINGo__ 3
typedef struct FAST_ARRAYoSTRINGo_struct __FAST_ARRAYoSTRINGo;
struct FAST_ARRAYoSTRINGo_struct {
  __ARRAYED_COLLECTIONoSTRINGo parent_arrayed_collection__HG;
};
__FAST_ARRAYoSTRINGo FAST_ARRAYoSTRINGo_;
#define FAST_ARRAYoSTRINGo__ (&FAST_ARRAYoSTRINGo_)

// OBJECT
#define __OBJECT__ 4
typedef struct OBJECT_struct __OBJECT;
struct OBJECT_struct {
  void *Nothing;
};
__OBJECT OBJECT_;
#define OBJECT__ (&OBJECT_)

// TRUE
#define TRUE__ 1

// FALSE
#define FALSE__ 0

// ARRAYED_COLLECTION[Expanded UINTEGER_32]
#define __ARRAYED_COLLECTIONoExpanded_UINTEGER_32o__ 5
typedef struct ARRAYED_COLLECTIONoExpanded_UINTEGER_32o_struct __ARRAYED_COLLECTIONoExpanded_UINTEGER_32o;
struct ARRAYED_COLLECTIONoExpanded_UINTEGER_32o_struct {
  __INTEGER capacity__Y2B;
  __INTEGER upper__R3B;
  __UINTEGER_32 *storage__D3B;
};
__ARRAYED_COLLECTIONoExpanded_UINTEGER_32o ARRAYED_COLLECTIONoExpanded_UINTEGER_32o_;
#define ARRAYED_COLLECTIONoExpanded_UINTEGER_32o__ (&ARRAYED_COLLECTIONoExpanded_UINTEGER_32o_)

// FAST_ARRAY[Expanded UINTEGER_32]
#define __FAST_ARRAYoExpanded_UINTEGER_32o__ 6
typedef struct FAST_ARRAYoExpanded_UINTEGER_32o_struct __FAST_ARRAYoExpanded_UINTEGER_32o;
struct FAST_ARRAYoExpanded_UINTEGER_32o_struct {
  __ARRAYED_COLLECTIONoExpanded_UINTEGER_32o parent_arrayed_collection__OC;
};
__FAST_ARRAYoExpanded_UINTEGER_32o FAST_ARRAYoExpanded_UINTEGER_32o_;
#define FAST_ARRAYoExpanded_UINTEGER_32o__ (&FAST_ARRAYoExpanded_UINTEGER_32o_)

// NSIEVE_BITS
#define __NSIEVE_BITS__ 7
typedef struct NSIEVE_BITS_struct __NSIEVE_BITS;
struct NSIEVE_BITS_struct {
  void *Nothing;
};
__NSIEVE_BITS NSIEVE_BITS_;
#define NSIEVE_BITS__ (&NSIEVE_BITS_)

// INTEGER_8
typedef signed char __INTEGER_8;

// BOOLEAN
typedef char __BOOLEAN;


void *table_type[8];

//==========================//
// GLOBAL                   //
//==========================//

void *parent_numeric__H;
__POINTER begin_memory__D4;
__UINTEGER_32 nb_page__XLB;
__UINTEGER_32 capacity_max__4VC;
__MEMORY *first_free__1JF;
void *string_tmp__M2C;
__UINTEGER_32 clone_allocation_size__HM;
void *primes__VC;

//==========================//
// STRING CONSTANT          //
//==========================//

__STRING_CONSTANT __string_1={__STRING_CONSTANT__,13,"Primes up to "};
__STRING_CONSTANT __string_2={__STRING_CONSTANT__,19,"Not enough memory.\n"};

//==========================//
// FUNCTION HEADER          //
//==========================//

// Debug Manager
void print_string(char *str);
// Source code
static __POINTER new_lab__FLB(__UINTEGER_32 t__HLB);
static void** create__BTF(__INTEGER nb_elements__DTF);
static __STRING* create__I5C(__INTEGER needed_capacity__K5C);
static void add_last__PDJ(__STRING *Self__QDJ,__CHARACTER ch__RDJ);
static __POINTER realloc_dynamic__old_size__new_size__T1I(__POINTER p__V1I,__UINTEGER_32 old_sz__W1I,__UINTEGER_32 new_sz__X1I);
static __MEMORY* search__YIF(__UINTEGER_32 new_size__0IF);
static void print__31C(__STRING_CONSTANT *Self__41C);
static void print_format__J2C(__UINTEGER_32 Self__K2C);
static __MEMORY* new_page__UVC();
static __CHARACTER* create__ZYL(__INTEGER nb_elements__1YL);
static void to_busy__index__1DI(__MEMORY *Self__2DI,__UINTEGER_32 sz__3DI,__UINTEGER_32 idx__4DI);
static void put_string__VMD(void *s__XMD);

//==========================//
// SOURCE CODE              //
//==========================//

int main(int argc,char **argv)
{
  void *str__FJ;
  __INTEGER new_count__PN,typ_id__BR,Self__0N,limit_up__1N,idx__Y3C;
  __INTEGER i__UYH,new_capacity__R5C,__tmp__VAD,__tmp__MDI,Self__K5N;
  __INTEGER state__PKN,result__SKN,i__OKN,__tmp__DOW,__tmp__FOW;
  __INTEGER new_count__JI,typ_id__ZL,Self__EPI,__tmp__43B,Self__3CL;
  __INTEGER Self__PI,Self__00C,limit_up__10C,Self__M1C,limit_up__N1C;
  __POINTER ptr__2Q,ptr_table__4RW,next__3RW,result__5RW,ptr_table__ESW;
  __POINTER next__DSW,result__FSW,ptr__UL,ptr_table__KSW,next__JSW;
  __POINTER result__LSW,ptr_table__QSW,next__PSW,result__RSW;
  __POINTER result__FQW,ptr_table__J2,next__O2,result__M2;
  __UINTEGER_32 sz__4Q,a__NNW,new_size__ONW,t__XNW,a__UNW,new_size__HSW;
  __UINTEGER_32 lab_type__GSW,param__4,count__BB,n__EB,j__HB,sz__1;
  __UINTEGER_32 sz__WL,a__QKW,new_size__JW,t__SX,a__WKW,new_size__TSW;
  __UINTEGER_32 lab_type__SSW,sz__HQW,a__GQW,new_size__IQW;
  __UINTEGER_32 new_size2__JQW,a__KQW,new_size__LQW,m__ZC,__tmp__1D;
  __UINTEGER_32 i__AE,idx__MCM;
  __STRING *Self__SYH,*Self__MKN;
  __CHARACTER *arg__EJ,*Self__M3C,*p__TYH,*__tmp__EOW;
  __FAST_ARRAYoSTRINGo *result__1Q,*Self__05B,*Self__P5C;
  void *result__DJ;
  __BOOLEAN __tmp__55C,negative__RKN,__tmp__4LN,result__BIT,__tmp__RMN;
  __BOOLEAN __tmp__GNN,result__ZAS,__tmp__NON,result__LBS,result__3QH;
  __BOOLEAN __tmp__F3B;
  void **__tmp__UAD,**new__ZCI;
  __CHARACTER cc__QKN;
  __FAST_ARRAYoExpanded_UINTEGER_32o *result__TL,*Self__O2B;
  __UINTEGER_32 *Result__YJD,*__tmp__33B,*Self__JJK,*__tmp__ZQW;
  __UINTEGER_32 *__tmp__2QW,*__tmp__3QW,*__tmp__4QW,*__tmp__WSW;
  arg_count  = argc;
  arg_vector = argv;
  parent_numeric__H=NUMERIC__;
  ARRAYED_COLLECTIONoSTRINGo__->upper__KG= 0;
  ARRAYED_COLLECTIONoSTRINGo__->capacity__DAC= 0;
  ARRAYED_COLLECTIONoSTRINGo__->storage__OAC=NULL;
  FAST_ARRAYoSTRINGo__->parent_arrayed_collection__HG=(*ARRAYED_COLLECTIONoSTRINGo__);
  clone_allocation_size__HM= 0;
  STRING_CONSTANT__->count__5BE=((__INTEGER )((0)));
  STRING__->count__EDE= 0;
  STRING_CONSTANT__->storage__L5F=((__CHARACTER *)(NULL));
  STRING__->storage__X1H=NULL;
  nb_page__XLB= 0;
  MEMORY__->size_and_id__SM= 0;
  capacity_max__4VC= 0;
  begin_memory__D4=((__POINTER )(NULL));
  MEMORY__->previous_linear__RM= 0;
  first_free__1JF=NULL;
  MEMORY__->next_free__TM=NULL;
  MEMORY__->previous_free__UM=NULL;
  STRING__->capacity__O1H= 0;
  arg__EJ=NULL;
  str__FJ=NULL;
  new_count__PN=((__INTEGER )(arg_count));
  result__1Q=NULL;
  ptr__2Q=((__POINTER )(NULL));
  typ_id__BR= 0;
  sz__4Q=((__UINTEGER_32 )sizeof(__FAST_ARRAYoSTRINGo));
  if ((sz__4Q ==  0)) {
    result__1Q=FAST_ARRAYoSTRINGo__;
  } else {
    typ_id__BR=__FAST_ARRAYoSTRINGo__;
    clone_allocation_size__HM=sz__4Q;
    if ((typ_id__BR == (__INTEGER)(-  1))) {
      a__NNW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__ONW=(__UINTEGER_32)((__UINTEGER_32)(sz__4Q + a__NNW) & (__UINTEGER_32)(~ a__NNW));
      ptr_table__4RW=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__ONW / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__3RW=((__POINTER )(NULL));
      result__5RW=((__POINTER *)ptr_table__4RW)[ 0];
      if ((result__5RW == (void *)NULL)) {
        result__5RW=new_lab__FLB(new_size__ONW);
        next__3RW=(void *)((unsigned long)result__5RW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__ONW)));
        ((__POINTER *)next__3RW)[ 0]=NULL;
        ((__POINTER *)ptr_table__4RW)[ 0]=next__3RW;
      } else {
        next__3RW=((__POINTER *)result__5RW)[ 0];
        if ((next__3RW == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__5RW - (unsigned long)begin_memory__D4)))) &  4095) + (__UINTEGER_32)(new_size__ONW <<  1)) <=  4096)) {
            next__3RW=(void *)((unsigned long)result__5RW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__ONW)));
          } else {
            next__3RW=new_lab__FLB(new_size__ONW);
          };
          ((__POINTER *)next__3RW)[ 0]=NULL;
          ((__POINTER *)ptr_table__4RW)[ 0]=next__3RW;
        } else {
          ((__POINTER *)result__5RW)[ 0]=(void *)((unsigned long)((__POINTER *)next__3RW)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__5RW=next__3RW;
        };
      };
      ptr__2Q=result__5RW;
    } else {
      t__XNW=((__UINTEGER_32 )typ_id__BR);
      a__UNW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__HSW=(__UINTEGER_32)((__UINTEGER_32)(sz__4Q + a__UNW) & (__UINTEGER_32)(~ a__UNW));
      ptr_table__ESW=((__POINTER )(&(table_type[(t__XNW)])));
      lab_type__GSW=(__UINTEGER_32)(t__XNW |  1);
      next__DSW=((__POINTER )(NULL));
      result__FSW=((__POINTER *)ptr_table__ESW)[ 0];
      if ((result__FSW == (void *)NULL)) {
        result__FSW=new_lab__FLB(lab_type__GSW);
        next__DSW=(void *)((unsigned long)result__FSW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__HSW)));
        ((__POINTER *)next__DSW)[ 0]=NULL;
        ((__POINTER *)ptr_table__ESW)[ 0]=next__DSW;
      } else {
        next__DSW=((__POINTER *)result__FSW)[ 0];
        if ((next__DSW == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__FSW - (unsigned long)begin_memory__D4)))) &  4095) + (__UINTEGER_32)(new_size__HSW <<  1)) <=  4096)) {
            next__DSW=(void *)((unsigned long)result__FSW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__HSW)));
          } else {
            next__DSW=new_lab__FLB(lab_type__GSW);
          };
          ((__POINTER *)next__DSW)[ 0]=NULL;
          ((__POINTER *)ptr_table__ESW)[ 0]=next__DSW;
        } else {
          ((__POINTER *)result__FSW)[ 0]=(void *)((unsigned long)((__POINTER *)next__DSW)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__FSW=next__DSW;
        };
      };
      ptr__2Q=result__FSW;
    };
    result__1Q=((__FAST_ARRAYoSTRINGo *)ptr__2Q);
    *(result__1Q) = *(FAST_ARRAYoSTRINGo__);
  };
  Self__05B=((__FAST_ARRAYoSTRINGo *)result__1Q);
  if ((Self__05B->parent_arrayed_collection__HG.capacity__DAC < new_count__PN)) {
    Self__05B->parent_arrayed_collection__HG.storage__OAC=create__BTF(new_count__PN);
    Self__05B->parent_arrayed_collection__HG.capacity__DAC=new_count__PN;
  };
  Self__05B->parent_arrayed_collection__HG.upper__KG=(__INTEGER)(-  1);
  result__DJ=result__1Q;
  Self__0N= 0;
  limit_up__1N=(__INTEGER)(((__INTEGER )(arg_count)) -  1);
  while ((Self__0N <= limit_up__1N)) {
    arg__EJ=((__CHARACTER *)(arg_vector[(Self__0N)]));
    Self__M3C=((__CHARACTER *)arg__EJ);
    idx__Y3C= 0;
    while ((! ((idx__Y3C >  1024) || ('\0' == Self__M3C[idx__Y3C])))) {
      idx__Y3C=(__INTEGER)(idx__Y3C +  1);
    };
    str__FJ=create__I5C(idx__Y3C);
    Self__SYH=((__STRING *)str__FJ);
    p__TYH=arg__EJ;
    i__UYH= 0;
    Self__SYH->count__EDE= 0;
    while ((((__CHARACTER *)p__TYH)[i__UYH] != '\0')) {
      add_last__PDJ(Self__SYH,((__CHARACTER *)p__TYH)[i__UYH]);
      i__UYH=(__INTEGER)(i__UYH +  1);
    };
    Self__P5C=((__FAST_ARRAYoSTRINGo *)result__DJ);
    new_capacity__R5C= 0;
    if (((__INTEGER)(Self__P5C->parent_arrayed_collection__HG.upper__KG +  1) <= (__INTEGER)(Self__P5C->parent_arrayed_collection__HG.capacity__DAC -  1))) {
      Self__P5C->parent_arrayed_collection__HG.upper__KG=(__INTEGER)(Self__P5C->parent_arrayed_collection__HG.upper__KG +  1);
      __tmp__55C=TRUE__;
    } else {
      __tmp__55C=FALSE__;
    };
    if ((! __tmp__55C)) {
      if ((Self__P5C->parent_arrayed_collection__HG.capacity__DAC ==  0)) {
        Self__P5C->parent_arrayed_collection__HG.storage__OAC=create__BTF( 2);
        Self__P5C->parent_arrayed_collection__HG.capacity__DAC= 2;
        Self__P5C->parent_arrayed_collection__HG.upper__KG= 0;
      } else {
        new_capacity__R5C=(__INTEGER)(Self__P5C->parent_arrayed_collection__HG.capacity__DAC <<  1);
        __tmp__UAD=Self__P5C->parent_arrayed_collection__HG.storage__OAC;
        __tmp__VAD=Self__P5C->parent_arrayed_collection__HG.capacity__DAC;
        new__ZCI=((void **)realloc_dynamic__old_size__new_size__T1I(((__POINTER )((void **)__tmp__UAD)),((__UINTEGER_32 )(__INTEGER)(__tmp__VAD * ((__INTEGER )(sizeof(void *))))),((__UINTEGER_32 )(__INTEGER)(new_capacity__R5C * ((__INTEGER )(sizeof(void *)))))));
        __tmp__MDI=(__INTEGER)(new_capacity__R5C -  1);
        Self__K5N=__tmp__VAD;
        while ((Self__K5N <= __tmp__MDI)) {
          new__ZCI[Self__K5N]=NULL;
          Self__K5N=(__INTEGER)(Self__K5N +  1);
        };
        Self__P5C->parent_arrayed_collection__HG.storage__OAC=new__ZCI;
        Self__P5C->parent_arrayed_collection__HG.capacity__DAC=new_capacity__R5C;
        Self__P5C->parent_arrayed_collection__HG.upper__KG=(__INTEGER)(Self__P5C->parent_arrayed_collection__HG.upper__KG +  1);
      };
    };
    ((void **)Self__P5C->parent_arrayed_collection__HG.storage__OAC)[Self__P5C->parent_arrayed_collection__HG.upper__KG]=str__FJ;
    Self__0N=(__INTEGER)(Self__0N +  1);
  };
  ARRAYED_COLLECTIONoExpanded_UINTEGER_32o__->capacity__Y2B= 0;
  ARRAYED_COLLECTIONoExpanded_UINTEGER_32o__->storage__D3B=NULL;
  ARRAYED_COLLECTIONoExpanded_UINTEGER_32o__->upper__R3B= 0;
  FAST_ARRAYoExpanded_UINTEGER_32o__->parent_arrayed_collection__OC=(*ARRAYED_COLLECTIONoExpanded_UINTEGER_32o__);
  primes__VC=NULL;
  string_tmp__M2C=create__I5C( 32);
  param__4= 0;
  count__BB= 0;
  n__EB= 0;
  j__HB= 0;
  if ((result__1Q->parent_arrayed_collection__HG.upper__KG ==  1)) {
    Self__MKN=((__STRING *)((void **)((__FAST_ARRAYoSTRINGo *)result__1Q)->parent_arrayed_collection__HG.storage__OAC)[ 1]);
    state__PKN= 0;
    cc__QKN='\0';
    negative__RKN=FALSE__;
    result__SKN= 0;
    i__OKN= 1;
    __tmp__DOW=Self__MKN->count__EDE;
    __tmp__EOW=Self__MKN->storage__X1H;
    __tmp__FOW=Self__MKN->count__EDE;
    while ((i__OKN <= __tmp__DOW)) {
      cc__QKN=((__CHARACTER *)__tmp__EOW)[(__INTEGER)(i__OKN -  1)];
      if ((state__PKN ==  0)) {
        if ((((((((cc__QKN == ' ') || (cc__QKN == '\t')) || (cc__QKN == '\n')) || (cc__QKN == '\r')) || (cc__QKN == '\0')) || (cc__QKN == '\f')) || (cc__QKN == '\v'))) {
          __tmp__4LN=TRUE__;
        } else {
          result__BIT=(cc__QKN == '+');
          if (result__BIT) {
            state__PKN= 1;
          };
          __tmp__4LN=result__BIT;
        };
        if ((! __tmp__4LN)) {
          if ((cc__QKN == '-')) {
            negative__RKN=TRUE__;
            state__PKN= 1;
          } else {
            result__SKN=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__QKN)) -  48);
            state__PKN= 2;
          };
        };
        __tmp__RMN=TRUE__;
      } else {
        __tmp__RMN=FALSE__;
      };
      if (__tmp__RMN) {
        __tmp__GNN=TRUE__;
      } else {
        result__ZAS=(state__PKN ==  1);
        if (result__ZAS) {
          result__SKN=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__QKN)) -  48);
          if (negative__RKN) {
            result__SKN=(__INTEGER)(- result__SKN);
          };
          state__PKN= 2;
        };
        __tmp__GNN=result__ZAS;
      };
      if (__tmp__GNN) {
        __tmp__NON=TRUE__;
      } else {
        result__LBS=(state__PKN ==  2);
        if (result__LBS) {
          result__3QH=FALSE__;
          if ((((__INTEGER_8 )cc__QKN) >= ((__INTEGER_8 )'0'))) {
            result__3QH=(((__INTEGER_8 )cc__QKN) <= ((__INTEGER_8 )'9'));
          };
          if (result__3QH) {
            if (negative__RKN) {
              result__SKN=(__INTEGER)((__INTEGER)( 10 * result__SKN) - (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__QKN)) -  48));
            } else {
              result__SKN=(__INTEGER)((__INTEGER)( 10 * result__SKN) + (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__QKN)) -  48));
            };
          } else {
            state__PKN= 3;
          };
        };
        __tmp__NON=result__LBS;
      };
      if ((! __tmp__NON)) {
        if ((state__PKN ==  3)) {
          i__OKN=__tmp__FOW;
        };
      };
      i__OKN=(__INTEGER)(i__OKN +  1);
    };
    param__4=((__UINTEGER_32 )result__SKN);
  } else {
    param__4= 1;
  };
  sz__1=((__UINTEGER_32 )(__INTEGER)( 10000 << ((__INTEGER )param__4)));
  new_count__JI=((__INTEGER )(__UINTEGER_32)((__UINTEGER_32)(sz__1 >>  3) +  4));
  result__TL=NULL;
  ptr__UL=((__POINTER )(NULL));
  typ_id__ZL= 0;
  sz__WL=((__UINTEGER_32 )sizeof(__FAST_ARRAYoExpanded_UINTEGER_32o));
  if ((sz__WL ==  0)) {
    result__TL=FAST_ARRAYoExpanded_UINTEGER_32o__;
  } else {
    typ_id__ZL=__FAST_ARRAYoExpanded_UINTEGER_32o__;
    clone_allocation_size__HM=(__UINTEGER_32)(clone_allocation_size__HM + sz__WL);
    if ((typ_id__ZL == (__INTEGER)(-  1))) {
      a__QKW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__JW=(__UINTEGER_32)((__UINTEGER_32)(sz__WL + a__QKW) & (__UINTEGER_32)(~ a__QKW));
      ptr_table__KSW=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__JW / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__JSW=((__POINTER )(NULL));
      result__LSW=((__POINTER *)ptr_table__KSW)[ 0];
      if ((result__LSW == (void *)NULL)) {
        result__LSW=new_lab__FLB(new_size__JW);
        next__JSW=(void *)((unsigned long)result__LSW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__JW)));
        ((__POINTER *)next__JSW)[ 0]=NULL;
        ((__POINTER *)ptr_table__KSW)[ 0]=next__JSW;
      } else {
        next__JSW=((__POINTER *)result__LSW)[ 0];
        if ((next__JSW == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__LSW - (unsigned long)begin_memory__D4)))) &  4095) + (__UINTEGER_32)(new_size__JW <<  1)) <=  4096)) {
            next__JSW=(void *)((unsigned long)result__LSW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__JW)));
          } else {
            next__JSW=new_lab__FLB(new_size__JW);
          };
          ((__POINTER *)next__JSW)[ 0]=NULL;
          ((__POINTER *)ptr_table__KSW)[ 0]=next__JSW;
        } else {
          ((__POINTER *)result__LSW)[ 0]=(void *)((unsigned long)((__POINTER *)next__JSW)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__LSW=next__JSW;
        };
      };
      ptr__UL=result__LSW;
    } else {
      t__SX=((__UINTEGER_32 )typ_id__ZL);
      a__WKW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__TSW=(__UINTEGER_32)((__UINTEGER_32)(sz__WL + a__WKW) & (__UINTEGER_32)(~ a__WKW));
      ptr_table__QSW=((__POINTER )(&(table_type[(t__SX)])));
      lab_type__SSW=(__UINTEGER_32)(t__SX |  1);
      next__PSW=((__POINTER )(NULL));
      result__RSW=((__POINTER *)ptr_table__QSW)[ 0];
      if ((result__RSW == (void *)NULL)) {
        result__RSW=new_lab__FLB(lab_type__SSW);
        next__PSW=(void *)((unsigned long)result__RSW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__TSW)));
        ((__POINTER *)next__PSW)[ 0]=NULL;
        ((__POINTER *)ptr_table__QSW)[ 0]=next__PSW;
      } else {
        next__PSW=((__POINTER *)result__RSW)[ 0];
        if ((next__PSW == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__RSW - (unsigned long)begin_memory__D4)))) &  4095) + (__UINTEGER_32)(new_size__TSW <<  1)) <=  4096)) {
            next__PSW=(void *)((unsigned long)result__RSW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__TSW)));
          } else {
            next__PSW=new_lab__FLB(lab_type__SSW);
          };
          ((__POINTER *)next__PSW)[ 0]=NULL;
          ((__POINTER *)ptr_table__QSW)[ 0]=next__PSW;
        } else {
          ((__POINTER *)result__RSW)[ 0]=(void *)((unsigned long)((__POINTER *)next__PSW)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__RSW=next__PSW;
        };
      };
      ptr__UL=result__RSW;
    };
    result__TL=((__FAST_ARRAYoExpanded_UINTEGER_32o *)ptr__UL);
    *(result__TL) = *(FAST_ARRAYoExpanded_UINTEGER_32o__);
  };
  Self__O2B=((__FAST_ARRAYoExpanded_UINTEGER_32o *)result__TL);
  if ((new_count__JI > Self__O2B->parent_arrayed_collection__OC.capacity__Y2B)) {
    sz__HQW=((__UINTEGER_32 )(__INTEGER)(new_count__JI <<  2));
    result__FQW=((__POINTER )(NULL));
    a__GQW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__IQW=(__UINTEGER_32)((__UINTEGER_32)(sz__HQW + a__GQW) & (__UINTEGER_32)(~ a__GQW));
    new_size2__JQW=(__UINTEGER_32)(new_size__IQW + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
    if ((new_size2__JQW <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
      a__KQW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__LQW=(__UINTEGER_32)((__UINTEGER_32)(new_size2__JQW + a__KQW) & (__UINTEGER_32)(~ a__KQW));
      ptr_table__J2=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__LQW / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__O2=((__POINTER )(NULL));
      result__M2=((__POINTER *)ptr_table__J2)[ 0];
      if ((result__M2 == (void *)NULL)) {
        result__M2=new_lab__FLB(new_size__LQW);
        next__O2=(void *)((unsigned long)result__M2 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__LQW)));
        ((__POINTER *)next__O2)[ 0]=NULL;
        ((__POINTER *)ptr_table__J2)[ 0]=next__O2;
      } else {
        next__O2=((__POINTER *)result__M2)[ 0];
        if ((next__O2 == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__M2 - (unsigned long)begin_memory__D4)))) &  4095) + (__UINTEGER_32)(new_size__LQW <<  1)) <=  4096)) {
            next__O2=(void *)((unsigned long)result__M2 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__LQW)));
          } else {
            next__O2=new_lab__FLB(new_size__LQW);
          };
          ((__POINTER *)next__O2)[ 0]=NULL;
          ((__POINTER *)ptr_table__J2)[ 0]=next__O2;
        } else {
          ((__POINTER *)result__M2)[ 0]=(void *)((unsigned long)((__POINTER *)next__O2)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__M2=next__O2;
        };
      };
      ((__POINTER *)result__M2)[ 0]=((__POINTER ) 3);
      result__FQW=(void *)((unsigned long)result__M2 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
    } else {
      result__FQW=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__YIF(new_size__IQW))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
    };
    Result__YJD=((__UINTEGER_32 *)result__FQW);
    Self__EPI=(__INTEGER)(new_count__JI -  1);
    while ((Self__EPI >=  0)) {
      Result__YJD[Self__EPI]= 0;
      Self__EPI=(__INTEGER)(Self__EPI -  1);
    };
    Self__O2B->parent_arrayed_collection__OC.storage__D3B=Result__YJD;
    Self__O2B->parent_arrayed_collection__OC.capacity__Y2B=new_count__JI;
    __tmp__F3B=TRUE__;
  } else {
    __tmp__F3B=FALSE__;
  };
  if ((! __tmp__F3B)) {
    if (((Self__O2B->parent_arrayed_collection__OC.capacity__Y2B >  0) && (Self__O2B->parent_arrayed_collection__OC.upper__R3B >=  0))) {
      __tmp__33B=Self__O2B->parent_arrayed_collection__OC.storage__D3B;
      __tmp__43B=Self__O2B->parent_arrayed_collection__OC.upper__R3B;
      Self__JJK=((__UINTEGER_32 *)__tmp__33B);
      Self__3CL= 0;
      while ((Self__3CL <= __tmp__43B)) {
        Self__JJK[Self__3CL]= 0;
        Self__3CL=(__INTEGER)(Self__3CL +  1);
      };
    };
  };
  Self__O2B->parent_arrayed_collection__OC.upper__R3B=(__INTEGER)(new_count__JI -  1);
  primes__VC=result__TL;
  Self__PI= 0;
  while ((Self__PI <=  2)) {
    m__ZC=((__UINTEGER_32 )Self__PI);
    count__BB= 0;
    n__EB=(__UINTEGER_32)(sz__1 >> ((__INTEGER )m__ZC));
    __tmp__1D=(__UINTEGER_32)((__UINTEGER_32)((__UINTEGER_32)(n__EB >>  3) +  4) >>  2);
    Self__00C= 0;
    limit_up__10C=((__INTEGER )__tmp__1D);
    __tmp__ZQW=((__FAST_ARRAYoExpanded_UINTEGER_32o *)primes__VC)->parent_arrayed_collection__OC.storage__D3B;
    while ((Self__00C <= limit_up__10C)) {
      ((__UINTEGER_32 *)__tmp__ZQW)[Self__00C]=((__UINTEGER_32 )(__INTEGER)(~  0));
      Self__00C=(__INTEGER)(Self__00C +  1);
    };
    Self__M1C= 2;
    limit_up__N1C=((__INTEGER )n__EB);
    __tmp__2QW=((__FAST_ARRAYoExpanded_UINTEGER_32o *)primes__VC)->parent_arrayed_collection__OC.storage__D3B;
    __tmp__3QW=((__FAST_ARRAYoExpanded_UINTEGER_32o *)primes__VC)->parent_arrayed_collection__OC.storage__D3B;
    __tmp__4QW=((__FAST_ARRAYoExpanded_UINTEGER_32o *)primes__VC)->parent_arrayed_collection__OC.storage__D3B;
    __tmp__WSW=((__FAST_ARRAYoExpanded_UINTEGER_32o *)primes__VC)->parent_arrayed_collection__OC.storage__D3B;
    while ((Self__M1C <= limit_up__N1C)) {
      i__AE=((__UINTEGER_32 )Self__M1C);
      if (((__UINTEGER_32)(((__UINTEGER_32 *)__tmp__2QW)[((__INTEGER )(__UINTEGER_32)(i__AE >>  5))] & ((__UINTEGER_32 )(__INTEGER)( 1 << ((__INTEGER )(__UINTEGER_32)(i__AE &  31))))) !=  0)) {
        count__BB=(__UINTEGER_32)(count__BB +  1);
        j__HB=(__UINTEGER_32)(i__AE + i__AE);
        while ((j__HB <= n__EB)) {
          if (((__UINTEGER_32)(((__UINTEGER_32 *)__tmp__3QW)[((__INTEGER )(__UINTEGER_32)(j__HB >>  5))] & ((__UINTEGER_32 )(__INTEGER)( 1 << ((__INTEGER )(__UINTEGER_32)(j__HB &  31))))) !=  0)) {
            idx__MCM=(__UINTEGER_32)(j__HB >>  5);
            ((__UINTEGER_32 *)__tmp__WSW)[((__INTEGER )idx__MCM)]=(__UINTEGER_32)(((__UINTEGER_32 *)__tmp__4QW)[((__INTEGER )idx__MCM)] ^ ((__UINTEGER_32 )(__INTEGER)( 1 << ((__INTEGER )(__UINTEGER_32)(j__HB &  31)))));
          };
          j__HB=(__UINTEGER_32)(j__HB + i__AE);
        };
      };
      Self__M1C=(__INTEGER)(Self__M1C +  1);
    };
    print__31C((&__string_1));
    print_format__J2C(n__EB);
    fputc((int)(' '),stdout);
    print_format__J2C(count__BB);
    fputc((int)('\n'),stdout);
    Self__PI=(__INTEGER)(Self__PI +  1);
  };
  return( 0);
}

static __POINTER new_lab__FLB(__UINTEGER_32 t__HLB)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 idx__JLB,pv__QLB;
  __MEMORY *blc__MLB,*prev__NLB,*Self__E0V,*Self__NJW,*prev__OJW;
  __MEMORY *next__PJW;
  __POINTER result__OLB;
  __BOOLEAN __tmp__QMB;
  idx__JLB= 0;
  blc__MLB=NULL;
  prev__NLB=NULL;
  pv__QLB= 0;
  while_do__IQB:
  {
    if ((idx__JLB < nb_page__XLB)) {
      blc__MLB=((__MEMORY *)(last_block[(idx__JLB)]));
      __tmp__QMB=(((__UINTEGER_32)(((__MEMORY *)blc__MLB)->size_and_id__SM &  4294967292LU) <  4096) || ((__UINTEGER_32)(((__MEMORY *)blc__MLB)->size_and_id__SM &  1) ==  1));
    } else {
      __tmp__QMB=FALSE__;
    };
    if (__tmp__QMB) {
      idx__JLB=(__UINTEGER_32)(idx__JLB +  1);
      goto while_do__IQB;
    };
  };
  if ((idx__JLB >= nb_page__XLB)) {
    blc__MLB=new_page__UVC();
  };
  ((__MEMORY *)blc__MLB)->size_and_id__SM=(__UINTEGER_32)(blc__MLB->size_and_id__SM -  4096);
  Self__E0V=((__MEMORY *)blc__MLB);
  result__OLB=((__POINTER )((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__E0V) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__E0V->size_and_id__SM &  4294967292LU))))));
  if (((__UINTEGER_32)(((__MEMORY *)blc__MLB)->size_and_id__SM &  4294967292LU) < ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    Self__NJW=((__MEMORY *)blc__MLB);
    prev__OJW=Self__NJW->previous_free__UM;
    next__PJW=Self__NJW->next_free__TM;
    if (((void *)prev__OJW == (void *)NULL)) {
      first_free__1JF=next__PJW;
    } else {
      ((__MEMORY *)prev__OJW)->next_free__TM=next__PJW;
    };
    if (((void *)next__PJW != (void *)NULL)) {
      ((__MEMORY *)next__PJW)->previous_free__UM=prev__OJW;
    };
    pv__QLB=blc__MLB->previous_linear__RM;
    if ((pv__QLB !=  4294967295LU)) {
      prev__NLB=((__MEMORY *)(void *)((unsigned long)begin_memory__D4 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )pv__QLB))));
      ((__MEMORY *)prev__NLB)->size_and_id__SM=(__UINTEGER_32)((__UINTEGER_32)(prev__NLB->size_and_id__SM + blc__MLB->size_and_id__SM) +  8);
      last_block[(idx__JLB)] = (prev__NLB);
    };
  };
  ((__POINTER *)result__OLB)[ 0]=((__POINTER )t__HLB);
  return((void *)((unsigned long)result__OLB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))))));
}

static void** create__BTF(__INTEGER nb_elements__DTF)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__RQW,a__QQW,new_size__SQW,new_size2__TQW,a__UQW;
  __UINTEGER_32 new_size__VQW;
  __POINTER result__PQW,ptr_table__ARW,next__5QW,result__BRW;
  __INTEGER Self__OFJ;
  void **Result__ICG;
  sz__RQW=((__UINTEGER_32 )(__INTEGER)(nb_elements__DTF * ((__INTEGER )(sizeof(void *)))));
  result__PQW=((__POINTER )(NULL));
  a__QQW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__SQW=(__UINTEGER_32)((__UINTEGER_32)(sz__RQW + a__QQW) & (__UINTEGER_32)(~ a__QQW));
  new_size2__TQW=(__UINTEGER_32)(new_size__SQW + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__TQW <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__UQW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__VQW=(__UINTEGER_32)((__UINTEGER_32)(new_size2__TQW + a__UQW) & (__UINTEGER_32)(~ a__UQW));
    ptr_table__ARW=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__VQW / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
    next__5QW=((__POINTER )(NULL));
    result__BRW=((__POINTER *)ptr_table__ARW)[ 0];
    if ((result__BRW == (void *)NULL)) {
      result__BRW=new_lab__FLB(new_size__VQW);
      next__5QW=(void *)((unsigned long)result__BRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__VQW)));
      ((__POINTER *)next__5QW)[ 0]=NULL;
      ((__POINTER *)ptr_table__ARW)[ 0]=next__5QW;
    } else {
      next__5QW=((__POINTER *)result__BRW)[ 0];
      if ((next__5QW == (void *)NULL)) {
        if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__BRW - (unsigned long)begin_memory__D4)))) &  4095) + (__UINTEGER_32)(new_size__VQW <<  1)) <=  4096)) {
          next__5QW=(void *)((unsigned long)result__BRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__VQW)));
        } else {
          next__5QW=new_lab__FLB(new_size__VQW);
        };
        ((__POINTER *)next__5QW)[ 0]=NULL;
        ((__POINTER *)ptr_table__ARW)[ 0]=next__5QW;
      } else {
        ((__POINTER *)result__BRW)[ 0]=(void *)((unsigned long)((__POINTER *)next__5QW)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
        result__BRW=next__5QW;
      };
    };
    ((__POINTER *)result__BRW)[ 0]=((__POINTER ) 3);
    result__PQW=(void *)((unsigned long)result__BRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__PQW=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__YIF(new_size__SQW))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__ICG=((void **)result__PQW);
  Self__OFJ=(__INTEGER)(nb_elements__DTF -  1);
  while ((Self__OFJ >=  0)) {
    Result__ICG[Self__OFJ]=NULL;
    Self__OFJ=(__INTEGER)(Self__OFJ -  1);
  };
  return(Result__ICG);
}

static __STRING* create__I5C(__INTEGER needed_capacity__K5C)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __STRING *result__URD,*Self__50H;
  __POINTER ptr__VRD,ptr_table__GRW,next__FRW,result__HRW;
  __POINTER ptr_table__MRW,next__LRW,result__NRW;
  __INTEGER typ_id__0RD;
  __UINTEGER_32 sz__XRD,a__1KW,new_size__2KW,t__FLW,a__CLW;
  __UINTEGER_32 new_size__PRW,lab_type__ORW;
  result__URD=NULL;
  ptr__VRD=((__POINTER )(NULL));
  typ_id__0RD= 0;
  sz__XRD=((__UINTEGER_32 )sizeof(__STRING));
  if ((sz__XRD ==  0)) {
    result__URD=STRING__;
  } else {
    typ_id__0RD=-1;
    clone_allocation_size__HM=(__UINTEGER_32)(clone_allocation_size__HM + sz__XRD);
    if ((typ_id__0RD == (__INTEGER)(-  1))) {
      a__1KW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__2KW=(__UINTEGER_32)((__UINTEGER_32)(sz__XRD + a__1KW) & (__UINTEGER_32)(~ a__1KW));
      ptr_table__GRW=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__2KW / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__FRW=((__POINTER )(NULL));
      result__HRW=((__POINTER *)ptr_table__GRW)[ 0];
      if ((result__HRW == (void *)NULL)) {
        result__HRW=new_lab__FLB(new_size__2KW);
        next__FRW=(void *)((unsigned long)result__HRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__2KW)));
        ((__POINTER *)next__FRW)[ 0]=NULL;
        ((__POINTER *)ptr_table__GRW)[ 0]=next__FRW;
      } else {
        next__FRW=((__POINTER *)result__HRW)[ 0];
        if ((next__FRW == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__HRW - (unsigned long)begin_memory__D4)))) &  4095) + (__UINTEGER_32)(new_size__2KW <<  1)) <=  4096)) {
            next__FRW=(void *)((unsigned long)result__HRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__2KW)));
          } else {
            next__FRW=new_lab__FLB(new_size__2KW);
          };
          ((__POINTER *)next__FRW)[ 0]=NULL;
          ((__POINTER *)ptr_table__GRW)[ 0]=next__FRW;
        } else {
          ((__POINTER *)result__HRW)[ 0]=(void *)((unsigned long)((__POINTER *)next__FRW)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__HRW=next__FRW;
        };
      };
      ptr__VRD=result__HRW;
    } else {
      t__FLW=((__UINTEGER_32 )typ_id__0RD);
      a__CLW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__PRW=(__UINTEGER_32)((__UINTEGER_32)(sz__XRD + a__CLW) & (__UINTEGER_32)(~ a__CLW));
      ptr_table__MRW=((__POINTER )(&(table_type[(t__FLW)])));
      lab_type__ORW=(__UINTEGER_32)(t__FLW |  1);
      next__LRW=((__POINTER )(NULL));
      result__NRW=((__POINTER *)ptr_table__MRW)[ 0];
      if ((result__NRW == (void *)NULL)) {
        result__NRW=new_lab__FLB(lab_type__ORW);
        next__LRW=(void *)((unsigned long)result__NRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__PRW)));
        ((__POINTER *)next__LRW)[ 0]=NULL;
        ((__POINTER *)ptr_table__MRW)[ 0]=next__LRW;
      } else {
        next__LRW=((__POINTER *)result__NRW)[ 0];
        if ((next__LRW == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__NRW - (unsigned long)begin_memory__D4)))) &  4095) + (__UINTEGER_32)(new_size__PRW <<  1)) <=  4096)) {
            next__LRW=(void *)((unsigned long)result__NRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__PRW)));
          } else {
            next__LRW=new_lab__FLB(lab_type__ORW);
          };
          ((__POINTER *)next__LRW)[ 0]=NULL;
          ((__POINTER *)ptr_table__MRW)[ 0]=next__LRW;
        } else {
          ((__POINTER *)result__NRW)[ 0]=(void *)((unsigned long)((__POINTER *)next__LRW)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__NRW=next__LRW;
        };
      };
      ptr__VRD=result__NRW;
    };
    result__URD=((__STRING *)ptr__VRD);
    *(result__URD) = *(STRING__);
  };
  Self__50H=((__STRING *)result__URD);
  if ((needed_capacity__K5C >  0)) {
    if ((Self__50H->capacity__O1H < needed_capacity__K5C)) {
      Self__50H->storage__X1H=create__ZYL(needed_capacity__K5C);
      Self__50H->capacity__O1H=needed_capacity__K5C;
    };
  };
  Self__50H->count__EDE= 0;
  return(result__URD);
}

static void add_last__PDJ(__STRING *Self__QDJ,__CHARACTER ch__RDJ)
// ({STRING},{CHARACTER}) VoidNo recursive, No inlinable.
{
  __INTEGER new_capacity__SDJ,__tmp__LEJ,__tmp__UZN,Self__EDR;
  __CHARACTER *__tmp__KEJ,*new__BZN;
  new_capacity__SDJ= 0;
  if ((Self__QDJ->capacity__O1H <= Self__QDJ->count__EDE)) {
    if ((Self__QDJ->capacity__O1H ==  0)) {
      Self__QDJ->capacity__O1H= 32;
      Self__QDJ->storage__X1H=create__ZYL( 32);
    } else {
      new_capacity__SDJ=(__INTEGER)(Self__QDJ->capacity__O1H <<  1);
      __tmp__KEJ=Self__QDJ->storage__X1H;
      __tmp__LEJ=Self__QDJ->capacity__O1H;
      new__BZN=((__CHARACTER *)realloc_dynamic__old_size__new_size__T1I(((__POINTER )((__CHARACTER *)__tmp__KEJ)),((__UINTEGER_32 )__tmp__LEJ),((__UINTEGER_32 )new_capacity__SDJ)));
      __tmp__UZN=(__INTEGER)(new_capacity__SDJ -  1);
      Self__EDR=__tmp__LEJ;
      while ((Self__EDR <= __tmp__UZN)) {
        new__BZN[Self__EDR]='\0';
        Self__EDR=(__INTEGER)(Self__EDR +  1);
      };
      Self__QDJ->storage__X1H=new__BZN;
      Self__QDJ->capacity__O1H=new_capacity__SDJ;
    };
  };
  ((__CHARACTER *)Self__QDJ->storage__X1H)[Self__QDJ->count__EDE]=ch__RDJ;
  Self__QDJ->count__EDE=(__INTEGER)(Self__QDJ->count__EDE +  1);
}

static __POINTER realloc_dynamic__old_size__new_size__T1I(__POINTER p__V1I,__UINTEGER_32 old_sz__W1I,__UINTEGER_32 new_sz__X1I)
// ({POINTER},{UINTEGER_32},{UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *mem__C2I,*Self__1KL,*nxt__5KL,*result__ALL,*next__MCN;
  __MEMORY *new_free__LCN,*prev__4LW,*next__5LW;
  __POINTER result__D2I,result__S2D,ptr_table__SRW,next__RRW;
  __POINTER result__TRW,p__RJL,last__E5L,src__LIL,dst__MIL;
  __UINTEGER_32 a__KLW,old_size__Z1I,old_size2__21I,a__OLW;
  __UINTEGER_32 new_size__51I,a__K0,new_size__M2D,new_size2__P2D,a__GMW;
  __UINTEGER_32 new_size__HMW,a__SLW,__tmp__U3I,sz__ELL,old_size__BLL;
  __UINTEGER_32 prev__NCN,new_size__QCN;
  __INTEGER siz__YSW,Self__3SW,siz__QIL,Self__X2L;
  __POINTER *na_src__0SW,*na_dst__2SW,*na_src__OIL,*na_dst__PIL;
  mem__C2I=NULL;
  result__D2I=((__POINTER )(NULL));
  a__KLW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  old_size__Z1I=(__UINTEGER_32)((__UINTEGER_32)(old_sz__W1I + a__KLW) & (__UINTEGER_32)(~ a__KLW));
  old_size2__21I=(__UINTEGER_32)(old_size__Z1I + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  a__OLW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__51I=(__UINTEGER_32)((__UINTEGER_32)(new_sz__X1I + a__OLW) & (__UINTEGER_32)(~ a__OLW));
  if ((old_size2__21I <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    result__S2D=((__POINTER )(NULL));
    a__K0=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__M2D=(__UINTEGER_32)((__UINTEGER_32)(new_size__51I + a__K0) & (__UINTEGER_32)(~ a__K0));
    new_size2__P2D=(__UINTEGER_32)(new_size__M2D + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
    if ((new_size2__P2D <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
      a__GMW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__HMW=(__UINTEGER_32)((__UINTEGER_32)(new_size2__P2D + a__GMW) & (__UINTEGER_32)(~ a__GMW));
      ptr_table__SRW=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__HMW / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__RRW=((__POINTER )(NULL));
      result__TRW=((__POINTER *)ptr_table__SRW)[ 0];
      if ((result__TRW == (void *)NULL)) {
        result__TRW=new_lab__FLB(new_size__HMW);
        next__RRW=(void *)((unsigned long)result__TRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__HMW)));
        ((__POINTER *)next__RRW)[ 0]=NULL;
        ((__POINTER *)ptr_table__SRW)[ 0]=next__RRW;
      } else {
        next__RRW=((__POINTER *)result__TRW)[ 0];
        if ((next__RRW == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__TRW - (unsigned long)begin_memory__D4)))) &  4095) + (__UINTEGER_32)(new_size__HMW <<  1)) <=  4096)) {
            next__RRW=(void *)((unsigned long)result__TRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__HMW)));
          } else {
            next__RRW=new_lab__FLB(new_size__HMW);
          };
          ((__POINTER *)next__RRW)[ 0]=NULL;
          ((__POINTER *)ptr_table__SRW)[ 0]=next__RRW;
        } else {
          ((__POINTER *)result__TRW)[ 0]=(void *)((unsigned long)((__POINTER *)next__RRW)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__TRW=next__RRW;
        };
      };
      ((__POINTER *)result__TRW)[ 0]=((__POINTER ) 3);
      result__S2D=(void *)((unsigned long)result__TRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
    } else {
      result__S2D=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__YIF(new_size__M2D))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
    };
    result__D2I=result__S2D;
    siz__YSW=((__INTEGER )old_size__Z1I);
    siz__YSW=(__INTEGER)(siz__YSW / ((__INTEGER )(sizeof(void *))));
    na_src__0SW=((__POINTER *)p__V1I);
    na_dst__2SW=((__POINTER *)result__S2D);
    Self__3SW=(__INTEGER)(siz__YSW -  1);
    while ((Self__3SW >=  0)) {
      na_dst__2SW[Self__3SW]=na_src__0SW[Self__3SW];
      Self__3SW=(__INTEGER)(Self__3SW -  1);
    };
    p__RJL=(void *)((unsigned long)p__V1I - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))));
    a__SLW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    last__E5L=((__POINTER *)((__POINTER )(&(table_size[((__UINTEGER_32)((__UINTEGER_32)((__UINTEGER_32)(old_size2__21I + a__SLW) & (__UINTEGER_32)(~ a__SLW)) / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))))[ 0];
    ((__POINTER *)p__RJL)[ 0]=(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)(void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER *)last__E5L)[ 0]) - (unsigned long)((__POINTER ) 1)) & (unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 3)) - (unsigned long)((__POINTER ) 1)))) - (unsigned long)((__POINTER ) 1));
    ((__POINTER *)last__E5L)[ 0]=p__RJL;
  } else {
    mem__C2I=((__MEMORY *)(void *)((unsigned long)p__V1I - (unsigned long)((__POINTER ) 8)));
    __tmp__U3I=(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)p__V1I - (unsigned long)begin_memory__D4)))) >>  26);
    Self__1KL=((__MEMORY *)mem__C2I);
    nxt__5KL=NULL;
    result__ALL=NULL;
    sz__ELL= 0;
    old_size__BLL=(__UINTEGER_32)(Self__1KL->size_and_id__SM &  4294967292LU);
    if ((new_size__51I > old_size__BLL)) {
      if ((! ((__UINTEGER_32)(Self__1KL->size_and_id__SM &  2) !=  0))) {
        nxt__5KL=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__1KL) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__1KL->size_and_id__SM &  4294967292LU)))));
        sz__ELL=(__UINTEGER_32)((__UINTEGER_32)(new_size__51I - old_size__BLL) -  8);
        if ((((__UINTEGER_32)(((__MEMORY *)nxt__5KL)->size_and_id__SM &  1) ==  0) && ((__UINTEGER_32)(((__MEMORY *)nxt__5KL)->size_and_id__SM &  4294967292LU) >= sz__ELL))) {
          to_busy__index__1DI(nxt__5KL,sz__ELL,__tmp__U3I);
          Self__1KL->size_and_id__SM=(__UINTEGER_32)((__UINTEGER_32)(Self__1KL->size_and_id__SM + (__UINTEGER_32)(nxt__5KL->size_and_id__SM &  4294967294LU)) +  8);
          if (((__UINTEGER_32)(Self__1KL->size_and_id__SM &  2) !=  0)) {
            last_block[(__tmp__U3I)] = (Self__1KL);
          } else {
            nxt__5KL=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__1KL) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__1KL->size_and_id__SM &  4294967292LU)))));
            ((__MEMORY *)nxt__5KL)->previous_linear__RM=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__1KL) - (unsigned long)begin_memory__D4))));
          };
          result__ALL=Self__1KL;
        };
      };
      if (((void *)result__ALL == (void *)NULL)) {
        result__ALL=search__YIF(new_size__51I);
        src__LIL=(void *)((unsigned long)((__POINTER )Self__1KL) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
        dst__MIL=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__ALL)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
        siz__QIL=((__INTEGER )old_size__BLL);
        siz__QIL=(__INTEGER)(siz__QIL / ((__INTEGER )(sizeof(void *))));
        na_src__OIL=((__POINTER *)src__LIL);
        na_dst__PIL=((__POINTER *)dst__MIL);
        Self__X2L=(__INTEGER)(siz__QIL -  1);
        while ((Self__X2L >=  0)) {
          na_dst__PIL[Self__X2L]=na_src__OIL[Self__X2L];
          Self__X2L=(__INTEGER)(Self__X2L -  1);
        };
        prev__NCN=Self__1KL->previous_linear__RM;
        next__MCN=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__1KL) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__1KL->size_and_id__SM &  4294967292LU)))));
        new_free__LCN=((__MEMORY *)(void *)((unsigned long)begin_memory__D4 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )prev__NCN))));
        new_size__QCN=(__UINTEGER_32)(Self__1KL->size_and_id__SM &  4294967294LU);
        if (((prev__NCN ==  4294967295LU) || ((__UINTEGER_32)(new_free__LCN->size_and_id__SM &  1) !=  0))) {
          new_free__LCN=Self__1KL;
          Self__1KL->next_free__TM=first_free__1JF;
          Self__1KL->previous_free__UM=NULL;
          if (((void *)first_free__1JF != (void *)NULL)) {
            ((__MEMORY *)first_free__1JF)->previous_free__UM=Self__1KL;
          };
          first_free__1JF=Self__1KL;
        } else {
          new_size__QCN=(__UINTEGER_32)((__UINTEGER_32)(new_size__QCN + new_free__LCN->size_and_id__SM) +  8);
        };
        if (((! ((__UINTEGER_32)(Self__1KL->size_and_id__SM &  2) !=  0)) && ((__UINTEGER_32)(next__MCN->size_and_id__SM &  1) ==  0))) {
          new_size__QCN=(__UINTEGER_32)((__UINTEGER_32)(new_size__QCN + next__MCN->size_and_id__SM) +  8);
          prev__4LW=next__MCN->previous_free__UM;
          next__5LW=next__MCN->next_free__TM;
          if (((void *)prev__4LW == (void *)NULL)) {
            first_free__1JF=next__5LW;
          } else {
            ((__MEMORY *)prev__4LW)->next_free__TM=next__5LW;
          };
          if (((void *)next__5LW != (void *)NULL)) {
            ((__MEMORY *)next__5LW)->previous_free__UM=prev__4LW;
          };
        };
        new_free__LCN->size_and_id__SM=new_size__QCN;
        if (((__UINTEGER_32)(new_free__LCN->size_and_id__SM &  2) !=  0)) {
          last_block[(__tmp__U3I)] = (new_free__LCN);
        } else {
          next__MCN=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__1KL) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__1KL->size_and_id__SM &  4294967292LU)))));
          next__MCN->previous_linear__RM=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )new_free__LCN) - (unsigned long)begin_memory__D4))));
        };
      };
    } else {
      result__ALL=Self__1KL;
    };
    result__D2I=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__ALL)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  return(result__D2I);
}

static __MEMORY* search__YIF(__UINTEGER_32 new_size__0IF)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *result__2IF;
  result__2IF=first_free__1JF;
  while ((((void *)result__2IF != (void *)NULL) && ((__UINTEGER_32)(((__MEMORY *)result__2IF)->size_and_id__SM &  4294967292LU) < new_size__0IF))) {
    result__2IF=result__2IF->next_free__TM;
  };
  if (((void *)result__2IF == (void *)NULL)) {
    result__2IF=new_page__UVC();
  };
  to_busy__index__1DI(result__2IF,new_size__0IF,(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)result__2IF)) - (unsigned long)begin_memory__D4)))) >>  26));
  return(result__2IF);
}

static void print__31C(__STRING_CONSTANT *Self__41C)
// ({STRING_CONSTANT}) VoidRecursive, No inlinable.
{
  put_string__VMD(Self__41C);
}

static void print_format__J2C(__UINTEGER_32 Self__K2C)
// ({UINTEGER_32}) VoidNo recursive, No inlinable.
{
  __INTEGER old_count__JDE,i__1VE,j__2VE,__tmp__PDE,Self__ZUI,i__YZL;
  __UINTEGER_32 val__YVE;
  __STRING *Self__C0K,*Self__Q3H;
  __CHARACTER tmp__F0K;
  __CHARACTER *__tmp__WPW,*__tmp__XPW;
  ((__STRING *)string_tmp__M2C)->count__EDE= 0;
  old_count__JDE=((__STRING *)string_tmp__M2C)->count__EDE;
  val__YVE= 0;
  i__1VE= 0;
  j__2VE= 0;
  if ((Self__K2C ==  0)) {
    add_last__PDJ(((__STRING *)string_tmp__M2C),'0');
  } else {
    i__1VE=(__INTEGER)(((__STRING *)string_tmp__M2C)->count__EDE +  1);
    val__YVE=Self__K2C;
    while ((val__YVE !=  0)) {
      add_last__PDJ(((__STRING *)string_tmp__M2C),((__CHARACTER )(((__INTEGER_8)(((__INTEGER_8 )(__UINTEGER_32)(val__YVE %  10)) + ((__INTEGER_8 )'0'))))));
      val__YVE=(__UINTEGER_32)(val__YVE /  10);
    };
    j__2VE=((__STRING *)string_tmp__M2C)->count__EDE;
    while ((i__1VE < j__2VE)) {
      Self__C0K=((__STRING *)string_tmp__M2C);
      tmp__F0K=((__CHARACTER *)Self__C0K->storage__X1H)[(__INTEGER)(i__1VE -  1)];
      ((__CHARACTER *)Self__C0K->storage__X1H)[(__INTEGER)(i__1VE -  1)]=((__CHARACTER *)Self__C0K->storage__X1H)[(__INTEGER)(j__2VE -  1)];
      ((__CHARACTER *)Self__C0K->storage__X1H)[(__INTEGER)(j__2VE -  1)]=tmp__F0K;
      j__2VE=(__INTEGER)(j__2VE -  1);
      i__1VE=(__INTEGER)(i__1VE +  1);
    };
  };
  __tmp__PDE=(__UINTEGER_32)( 8 - (__INTEGER)(((__STRING *)string_tmp__M2C)->count__EDE - old_count__JDE));
  Self__Q3H=((__STRING *)string_tmp__M2C);
  Self__ZUI= 1;
  while ((Self__ZUI <= __tmp__PDE)) {
    i__YZL=Self__Q3H->count__EDE;
    add_last__PDJ(Self__Q3H,' ');
    __tmp__WPW=Self__Q3H->storage__X1H;
    __tmp__XPW=Self__Q3H->storage__X1H;
    while ((i__YZL != old_count__JDE)) {
      ((__CHARACTER *)__tmp__XPW)[(__INTEGER)((__INTEGER)(i__YZL +  1) -  1)]=((__CHARACTER *)__tmp__WPW)[(__INTEGER)(i__YZL -  1)];
      i__YZL=(__INTEGER)(i__YZL -  1);
    };
    ((__CHARACTER *)Self__Q3H->storage__X1H)[(__INTEGER)((__INTEGER)(old_count__JDE +  1) -  1)]=' ';
    Self__ZUI=(__INTEGER)(Self__ZUI +  1);
  };
  put_string__VMD(((__STRING *)string_tmp__M2C));
}

static __MEMORY* new_page__UVC()
// () With resultNo recursive, No inlinable.
{
  __POINTER mem__YLE;
  __UINTEGER_32 cap__VLE,old_size__XVC;
  __MEMORY *block__3VC;
  if ((capacity_max__4VC ==  0)) {
    mem__YLE=((__POINTER )(NULL));
    cap__VLE= 33554432;
    do {
      cap__VLE=(__UINTEGER_32)(cap__VLE <<  1);
      mem__YLE=((__POINTER )(malloc((cap__VLE))));
      if ((mem__YLE != (void *)NULL)) {
        free((mem__YLE));
      };
    } while ((! ((mem__YLE == (void *)NULL) || (cap__VLE ==  2147483648LU))));
    if ((mem__YLE == (void *)NULL)) {
      cap__VLE=(__UINTEGER_32)(cap__VLE >>  1);
    };
    capacity_max__4VC=cap__VLE;
    begin_memory__D4=((__POINTER )(malloc((cap__VLE))));
  };
  old_size__XVC=(__UINTEGER_32)(nb_page__XLB <<  26);
  nb_page__XLB=(__UINTEGER_32)(nb_page__XLB +  1);
  if (((__UINTEGER_32)(old_size__XVC +  67108864) > capacity_max__4VC)) {
    print__31C((&__string_2));
    exit(( 1));
  };
  block__3VC=((__MEMORY *)(void *)((unsigned long)begin_memory__D4 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )old_size__XVC))));
  block__3VC->previous_linear__RM= 4294967295LU;
  block__3VC->size_and_id__SM= 67108858;
  block__3VC->next_free__TM=first_free__1JF;
  block__3VC->previous_free__UM=NULL;
  if (((void *)first_free__1JF != (void *)NULL)) {
    ((__MEMORY *)first_free__1JF)->previous_free__UM=block__3VC;
  };
  first_free__1JF=block__3VC;
  last_block[((__UINTEGER_32)(nb_page__XLB -  1))] = (block__3VC);
  return(block__3VC);
}

static __CHARACTER* create__ZYL(__INTEGER nb_elements__1YL)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__3PW,a__2PW,new_size__4PW,new_size2__5PW,a__AQW;
  __UINTEGER_32 new_size__BQW;
  __POINTER result__1PW,ptr_table__YRW,next__XRW,result__ZRW;
  __INTEGER Self__MCO;
  __CHARACTER *Result__MJM;
  sz__3PW=((__UINTEGER_32 )nb_elements__1YL);
  result__1PW=((__POINTER )(NULL));
  a__2PW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__4PW=(__UINTEGER_32)((__UINTEGER_32)(sz__3PW + a__2PW) & (__UINTEGER_32)(~ a__2PW));
  new_size2__5PW=(__UINTEGER_32)(new_size__4PW + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__5PW <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__AQW=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__BQW=(__UINTEGER_32)((__UINTEGER_32)(new_size2__5PW + a__AQW) & (__UINTEGER_32)(~ a__AQW));
    ptr_table__YRW=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__BQW / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
    next__XRW=((__POINTER )(NULL));
    result__ZRW=((__POINTER *)ptr_table__YRW)[ 0];
    if ((result__ZRW == (void *)NULL)) {
      result__ZRW=new_lab__FLB(new_size__BQW);
      next__XRW=(void *)((unsigned long)result__ZRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__BQW)));
      ((__POINTER *)next__XRW)[ 0]=NULL;
      ((__POINTER *)ptr_table__YRW)[ 0]=next__XRW;
    } else {
      next__XRW=((__POINTER *)result__ZRW)[ 0];
      if ((next__XRW == (void *)NULL)) {
        if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__ZRW - (unsigned long)begin_memory__D4)))) &  4095) + (__UINTEGER_32)(new_size__BQW <<  1)) <=  4096)) {
          next__XRW=(void *)((unsigned long)result__ZRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__BQW)));
        } else {
          next__XRW=new_lab__FLB(new_size__BQW);
        };
        ((__POINTER *)next__XRW)[ 0]=NULL;
        ((__POINTER *)ptr_table__YRW)[ 0]=next__XRW;
      } else {
        ((__POINTER *)result__ZRW)[ 0]=(void *)((unsigned long)((__POINTER *)next__XRW)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
        result__ZRW=next__XRW;
      };
    };
    ((__POINTER *)result__ZRW)[ 0]=((__POINTER ) 3);
    result__1PW=(void *)((unsigned long)result__ZRW - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__1PW=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__YIF(new_size__4PW))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__MJM=((__CHARACTER *)result__1PW);
  Self__MCO=(__INTEGER)(nb_elements__1YL -  1);
  while ((Self__MCO >=  0)) {
    Result__MJM[Self__MCO]='\0';
    Self__MCO=(__INTEGER)(Self__MCO -  1);
  };
  return(Result__MJM);
}

static void to_busy__index__1DI(__MEMORY *Self__2DI,__UINTEGER_32 sz__3DI,__UINTEGER_32 idx__4DI)
// ({MEMORY},{UINTEGER_32},{UINTEGER_32}) VoidNo recursive, No inlinable.
{
  __MEMORY *new__FEI,*prev__LAJ,*next__MAJ,*Self__PZH,*Self__AUV;
  __UINTEGER_32 siz__5DI,new_size__CEI;
  new__FEI=NULL;
  prev__LAJ=Self__2DI->previous_free__UM;
  next__MAJ=Self__2DI->next_free__TM;
  if (((void *)prev__LAJ == (void *)NULL)) {
    first_free__1JF=next__MAJ;
  } else {
    ((__MEMORY *)prev__LAJ)->next_free__TM=next__MAJ;
  };
  if (((void *)next__MAJ != (void *)NULL)) {
    ((__MEMORY *)next__MAJ)->previous_free__UM=prev__LAJ;
  };
  siz__5DI=Self__2DI->size_and_id__SM;
  new_size__CEI=(__UINTEGER_32)(siz__5DI - sz__3DI);
  if ((new_size__CEI > (__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )(MINIMUM_SIZE)) +  2) +  8))) {
    siz__5DI=sz__3DI;
    new__FEI=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__2DI) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )sz__3DI))));
    ((__MEMORY *)new__FEI)->previous_linear__RM=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__2DI) - (unsigned long)begin_memory__D4))));
    ((__MEMORY *)new__FEI)->size_and_id__SM=(__UINTEGER_32)(new_size__CEI -  8);
    Self__PZH=((__MEMORY *)new__FEI);
    Self__PZH->next_free__TM=first_free__1JF;
    Self__PZH->previous_free__UM=NULL;
    if (((void *)first_free__1JF != (void *)NULL)) {
      ((__MEMORY *)first_free__1JF)->previous_free__UM=Self__PZH;
    };
    first_free__1JF=Self__PZH;
    if (((__UINTEGER_32)(((__MEMORY *)new__FEI)->size_and_id__SM &  2) !=  0)) {
      last_block[(idx__4DI)] = (new__FEI);
    } else {
      Self__AUV=((__MEMORY *)new__FEI);
      ((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__AUV) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__AUV->size_and_id__SM &  4294967292LU)))))->previous_linear__RM=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)new__FEI)) - (unsigned long)begin_memory__D4))));
    };
  };
  Self__2DI->size_and_id__SM=(__UINTEGER_32)(siz__5DI |  1);
}

static void put_string__VMD(void *s__XMD)
// ({STRING_CONSTANTxSTRING}) VoidNo recursive, No inlinable.
{
  __INTEGER __tmp__KND,Self__ECE,limit_up__FCE;
  __CHARACTER *__tmp__FNW,*__tmp__GNW;
  __CHARACTER __tmp__RND;
  if (((struct ___OBJ *)s__XMD)->__id==__STRING_CONSTANT__) {
  };
  if (((struct ___OBJ *)s__XMD)->__id==__STRING_CONSTANT__) {
    __tmp__KND=((__STRING_CONSTANT *)s__XMD)->count__5BE;
  } else {
    __tmp__KND=((__STRING *)s__XMD)->count__EDE;
  };
  Self__ECE= 1;
  limit_up__FCE=__tmp__KND;
  __tmp__FNW=((__STRING_CONSTANT *)s__XMD)->storage__L5F;
  __tmp__GNW=((__STRING *)s__XMD)->storage__X1H;
  while ((Self__ECE <= limit_up__FCE)) {
    if (((struct ___OBJ *)s__XMD)->__id==__STRING_CONSTANT__) {
      __tmp__RND=((__CHARACTER *)__tmp__FNW)[(__INTEGER)(Self__ECE -  1)];
    } else {
      __tmp__RND=((__CHARACTER *)__tmp__GNW)[(__INTEGER)(Self__ECE -  1)];
    };
    fputc((int)(__tmp__RND),stdout);
    Self__ECE=(__INTEGER)(Self__ECE +  1);
  };
}

//==========================//
// DEBUG MANAGER            //
//==========================//

void print_string(char *str) 
{ 
  while (*str!=0) {
    print_char(*str); 
    str++; 
  };
}  

