// C code generated by Lisaac compiler (www.isaacOS.com) //
int arg_count;
char **arg_vector;

//==========================//
// EXTERNAL                 //
//==========================//

// SYSTEM_IO

#include <stdio.h>
#include <stdlib.h>
  
// Hardware 'print_char'
void print_char(char car)
{
  fputc(car,stdout);
}

// Hardware 'exit'
int die_with_code(int code)
{
  exit(code);
}


// MEMORY

#define MINIMUM_SIZE 256  
void *table_size[MINIMUM_SIZE/sizeof(void *)];
void *last_block[64];

// FLOAT_REAL
#include <math.h>
// SYSTEM
#include <time.h>

//==========================//
// TYPE                     //
//==========================//

// Generic Object
struct ___OBJ {
  unsigned long __id;
};

// NULL
#ifndef NULL
#define NULL ((void *)0)
#endif

// POINTER
typedef void * __POINTER;

// UINTEGER_32
typedef unsigned long __UINTEGER_32;

// CHARACTER
typedef char __CHARACTER;

// INTEGER
typedef int __INTEGER;

// MEMORY
#define __MEMORY__ 0
typedef struct MEMORY_struct __MEMORY;
struct MEMORY_struct {
  volatile __UINTEGER_32 previous_linear__NL;
  volatile __UINTEGER_32 size_and_id__OL;
  __MEMORY *next_free__PL;
  __MEMORY *previous_free__QL;
} __attribute__ ((packed));
__MEMORY MEMORY_;
#define MEMORY__ (&MEMORY_)

// STRING
#define __STRING__ 1
typedef struct STRING_struct __STRING;
struct STRING_struct {
  __INTEGER count__XZB;
  __INTEGER capacity__I1B;
  __CHARACTER *storage__R1B;
};
__STRING STRING_;
#define STRING__ (&STRING_)

// NUMERIC
#define __NUMERIC__ 2
typedef struct NUMERIC_struct __NUMERIC;
struct NUMERIC_struct {
  void *Nothing;
};
__NUMERIC NUMERIC_;
#define NUMERIC__ (&NUMERIC_)

// STD_INPUT
#define __STD_INPUT__ 3
typedef struct STD_INPUT_struct __STD_INPUT;
struct STD_INPUT_struct {
  void *Nothing;
};
__STD_INPUT STD_INPUT_;
#define STD_INPUT__ (&STD_INPUT_)

// STRING_CONSTANT
#define __STRING_CONSTANT__ 4
typedef struct STRING_CONSTANT_struct __STRING_CONSTANT;
struct STRING_CONSTANT_struct {
  __INTEGER count__FGD;
  __CHARACTER *storage__TKE;
};
__STRING_CONSTANT STRING_CONSTANT_;
#define STRING_CONSTANT__ (&STRING_CONSTANT_)

// INPUT_STREAM
#define __INPUT_STREAM__ 5
typedef struct INPUT_STREAM_struct __INPUT_STREAM;
struct INPUT_STREAM_struct {
  void *Nothing;
};
__INPUT_STREAM INPUT_STREAM_;
#define INPUT_STREAM__ (&INPUT_STREAM_)

// FALSE
#define FALSE__ 0

// TRUE
#define TRUE__ 1

// INTEGER_8
typedef signed char __INTEGER_8;

// BOOLEAN
typedef char __BOOLEAN;


void *table_type[6];

//==========================//
// GLOBAL                   //
//==========================//

void *parent_numeric__H;
__POINTER begin_memory__I1;
__UINTEGER_32 nb_page__1IB;
__UINTEGER_32 capacity_max__LGC;
__MEMORY *first_free__UVD;
__CHARACTER memory__YE;
void *last_string__OB;

//==========================//
// STRING CONSTANT          //
//==========================//

__STRING_CONSTANT __string_1={19,"Not enough memory.\n"};

//==========================//
// FUNCTION HEADER          //
//==========================//

// Debug Manager
void print_string(char *str);
// Source code
static __POINTER micro_alloc__table__lab__LZ(__UINTEGER_32 new_size__NZ,__POINTER ptr_table__OZ,__UINTEGER_32 lab_type__PZ);
static __CHARACTER* create__D2D(__INTEGER nb_elements__F2D);
static void read_line__XB();
static void print_positif__Y3D(__INTEGER Self__Z3D);
static __POINTER new_lab__JIB(__UINTEGER_32 t__LIB);
static __MEMORY* search__NOF(__UINTEGER_32 new_size__POF);
static void extend__ZEC(__STRING *Self__0EC,__CHARACTER c__1EC);
static __MEMORY* new_page__BGC();
static void to_busy__index__4QG(__MEMORY *Self__5QG,__UINTEGER_32 sz__ARG,__UINTEGER_32 idx__BRG);
static void copy__to__size__JDI(__POINTER src__LDI,__POINTER dst__MDI,__UINTEGER_32 sz__NDI);

//==========================//
// SOURCE CODE              //
//==========================//

int main(int argc,char **argv)
{
  __STRING *result__NK,*Self__Z0B,*Self__XIC;
  __POINTER ptr__OK;
  __INTEGER typ_id__VK,sum__Z,state__0IC,result__3IC,i__ZIC,__tmp__D3M;
  __INTEGER __tmp__F3M;
  __UINTEGER_32 sz__SK,a__LX,new_size__JT,t__SU,a__W1M;
  __CHARACTER cc__1IC;
  __BOOLEAN negative__2IC,__tmp__JKC,result__43K,__tmp__2KC,__tmp__RLC;
  __BOOLEAN result__4GE,__tmp__YMC,result__QHE,result__MEG,__tmp__XC;
  __CHARACTER *__tmp__E3M;
  arg_count  = argc;
  arg_vector = argv;
  parent_numeric__H=NUMERIC__;
  memory__YE='\0';
  STRING_CONSTANT__->count__FGD=((__INTEGER )((0)));
  STRING_CONSTANT__->storage__TKE=((__CHARACTER *)(NULL));
  nb_page__1IB= 0;
  MEMORY__->size_and_id__OL= 0;
  capacity_max__LGC= 0;
  begin_memory__I1=((__POINTER )(NULL));
  MEMORY__->previous_linear__NL= 0;
  first_free__UVD=NULL;
  MEMORY__->next_free__PL=NULL;
  MEMORY__->previous_free__QL=NULL;
  STRING__->capacity__I1B= 0;
  STRING__->storage__R1B=NULL;
  STRING__->count__XZB= 0;
  result__NK=NULL;
  ptr__OK=((__POINTER )(NULL));
  typ_id__VK= 0;
  sz__SK=((__UINTEGER_32 )sizeof(__STRING));
  if ((sz__SK ==  0)) {
    result__NK=STRING__;
  } else {
    typ_id__VK=__STRING__;
    if ((typ_id__VK == (__INTEGER)(-  1))) {
      a__LX=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__JT=(__UINTEGER_32)((__UINTEGER_32)(sz__SK + a__LX) & (__UINTEGER_32)(~ a__LX));
      ptr__OK=micro_alloc__table__lab__LZ(new_size__JT,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__JT / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__JT);
    } else {
      t__SU=((__UINTEGER_32 )typ_id__VK);
      a__W1M=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      ptr__OK=micro_alloc__table__lab__LZ((__UINTEGER_32)((__UINTEGER_32)(sz__SK + a__W1M) & (__UINTEGER_32)(~ a__W1M)),((__POINTER )(&(table_type[(t__SU)]))),(__UINTEGER_32)(t__SU |  1));
    };
    result__NK=((__STRING *)ptr__OK);
    *(result__NK) = *(STRING__);
  };
  Self__Z0B=((__STRING *)result__NK);
  if ((Self__Z0B->capacity__I1B <  1024)) {
    Self__Z0B->storage__R1B=create__D2D( 1024);
    Self__Z0B->capacity__I1B= 1024;
  };
  Self__Z0B->count__XZB= 0;
  last_string__OB=result__NK;
  sum__Z= 0;
  read_line__XB();
  while ((memory__YE != ((__CHARACTER )(EOF)))) {
    Self__XIC=((__STRING *)last_string__OB);
    state__0IC= 0;
    cc__1IC='\0';
    negative__2IC=FALSE__;
    result__3IC= 0;
    i__ZIC= 1;
    __tmp__D3M=Self__XIC->count__XZB;
    __tmp__E3M=Self__XIC->storage__R1B;
    __tmp__F3M=Self__XIC->count__XZB;
    while ((i__ZIC <= __tmp__D3M)) {
      cc__1IC=((__CHARACTER *)__tmp__E3M)[(__INTEGER)(i__ZIC -  1)];
      if ((state__0IC ==  0)) {
        if ((((((((cc__1IC == ' ') || (cc__1IC == '\t')) || (cc__1IC == '\n')) || (cc__1IC == '\r')) || (cc__1IC == '\0')) || (cc__1IC == '\f')) || (cc__1IC == '\v'))) {
          __tmp__JKC=TRUE__;
        } else {
          result__43K=(cc__1IC == '+');
          if (result__43K) {
            state__0IC= 1;
          };
          __tmp__JKC=result__43K;
        };
        if ((! __tmp__JKC)) {
          if ((cc__1IC == '-')) {
            negative__2IC=TRUE__;
            state__0IC= 1;
          } else {
            result__3IC=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__1IC)) -  48);
            state__0IC= 2;
          };
        };
        __tmp__2KC=TRUE__;
      } else {
        __tmp__2KC=FALSE__;
      };
      if (__tmp__2KC) {
        __tmp__RLC=TRUE__;
      } else {
        result__4GE=(state__0IC ==  1);
        if (result__4GE) {
          result__3IC=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__1IC)) -  48);
          if (negative__2IC) {
            result__3IC=(__INTEGER)(- result__3IC);
          };
          state__0IC= 2;
        };
        __tmp__RLC=result__4GE;
      };
      if (__tmp__RLC) {
        __tmp__YMC=TRUE__;
      } else {
        result__QHE=(state__0IC ==  2);
        if (result__QHE) {
          result__MEG=FALSE__;
          if ((((__INTEGER_8 )cc__1IC) >= ((__INTEGER_8 )'0'))) {
            result__MEG=(((__INTEGER_8 )cc__1IC) <= ((__INTEGER_8 )'9'));
          };
          if (result__MEG) {
            if (negative__2IC) {
              result__3IC=(__INTEGER)((__INTEGER)( 10 * result__3IC) - (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__1IC)) -  48));
            } else {
              result__3IC=(__INTEGER)((__INTEGER)( 10 * result__3IC) + (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__1IC)) -  48));
            };
          } else {
            state__0IC= 3;
          };
        };
        __tmp__YMC=result__QHE;
      };
      if ((! __tmp__YMC)) {
        if ((state__0IC ==  3)) {
          i__ZIC=__tmp__F3M;
        };
      };
      i__ZIC=(__INTEGER)(i__ZIC +  1);
    };
    sum__Z=(__INTEGER)(sum__Z + result__3IC);
    read_line__XB();
  };
  if ((sum__Z ==  0)) {
    fputc((int)('0'),stdout);
    __tmp__XC=TRUE__;
  } else {
    __tmp__XC=FALSE__;
  };
  if ((! __tmp__XC)) {
    if ((sum__Z <  0)) {
      fputc((int)('-'),stdout);
      print_positif__Y3D((__INTEGER)(- sum__Z));
    } else {
      print_positif__Y3D(sum__Z);
    };
  };
  fputc((int)('\n'),stdout);
  return( 0);
}

static __POINTER micro_alloc__table__lab__LZ(__UINTEGER_32 new_size__NZ,__POINTER ptr_table__OZ,__UINTEGER_32 lab_type__PZ)
// ({UINTEGER_32},{POINTER},{UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __POINTER next__TZ,result__RZ;
  next__TZ=((__POINTER )(NULL));
  result__RZ=((__POINTER *)ptr_table__OZ)[ 0];
  if ((result__RZ == (void *)NULL)) {
    result__RZ=new_lab__JIB(lab_type__PZ);
    next__TZ=(void *)((unsigned long)result__RZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__NZ)));
    ((__POINTER *)next__TZ)[ 0]=NULL;
    ((__POINTER *)ptr_table__OZ)[ 0]=next__TZ;
  } else {
    next__TZ=((__POINTER *)result__RZ)[ 0];
    if ((next__TZ == (void *)NULL)) {
      if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__RZ - (unsigned long)begin_memory__I1)))) &  4095) + (__UINTEGER_32)(new_size__NZ <<  1)) <=  4096)) {
        next__TZ=(void *)((unsigned long)result__RZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__NZ)));
      } else {
        next__TZ=new_lab__JIB(lab_type__PZ);
      };
      ((__POINTER *)next__TZ)[ 0]=NULL;
      ((__POINTER *)ptr_table__OZ)[ 0]=next__TZ;
    } else {
      ((__POINTER *)result__RZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__TZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
      result__RZ=next__TZ;
    };
  };
  return(result__RZ);
}

static __CHARACTER* create__D2D(__INTEGER nb_elements__F2D)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__XUE,a__XZM,new_size__ZUE,new_size2__2UE,a__V3M;
  __UINTEGER_32 new_size__X3M;
  __POINTER result__5UE;
  __INTEGER Self__4XG;
  __CHARACTER *Result__IEE;
  sz__XUE=((__UINTEGER_32 )nb_elements__F2D);
  result__5UE=((__POINTER )(NULL));
  a__XZM=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__ZUE=(__UINTEGER_32)((__UINTEGER_32)(sz__XUE + a__XZM) & (__UINTEGER_32)(~ a__XZM));
  new_size2__2UE=(__UINTEGER_32)(new_size__ZUE + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__2UE <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__V3M=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__X3M=(__UINTEGER_32)((__UINTEGER_32)(new_size2__2UE + a__V3M) & (__UINTEGER_32)(~ a__V3M));
    result__5UE=micro_alloc__table__lab__LZ(new_size__X3M,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__X3M / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__X3M);
    ((__POINTER *)result__5UE)[ 0]=((__POINTER ) 3);
    result__5UE=(void *)((unsigned long)result__5UE - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__5UE=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__NOF(new_size__ZUE))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__IEE=((__CHARACTER *)result__5UE);
  Self__4XG=(__INTEGER)(nb_elements__F2D -  1);
  while ((Self__4XG >=  0)) {
    Result__IEE[Self__4XG]='\0';
    Self__4XG=(__INTEGER)(Self__4XG -  1);
  };
  return(Result__IEE);
}

static void read_line__XB()
// () VoidNo recursive, No inlinable.
{
  __CHARACTER mem__QE;
  ((__STRING *)last_string__OB)->count__XZB= 0;
  mem__QE='\0';
  memory__YE=((__CHARACTER )(fgetc(stdin)));
  if (((memory__YE != '\n') && (memory__YE != ((__CHARACTER )(EOF))))) {
    extend__ZEC(last_string__OB,memory__YE);
    mem__QE=((__CHARACTER )(fgetc(stdin)));
    while ((! ((mem__QE == ((__CHARACTER )(EOF))) || (mem__QE == '\n')))) {
      extend__ZEC(last_string__OB,mem__QE);
      mem__QE=((__CHARACTER )(fgetc(stdin)));
    };
    memory__YE=mem__QE;
  };
}

static void print_positif__Y3D(__INTEGER Self__Z3D)
// ({INTEGER}) VoidRecursive, No inlinable.
{
  __INTEGER val__C4D;
  __CHARACTER Result__2NE;
  Result__2NE=((__CHARACTER )(((__INTEGER_8)(((__INTEGER_8 )(__INTEGER)(Self__Z3D %  10)) + ((__INTEGER_8 )'0')))));
  val__C4D=(__INTEGER)(Self__Z3D /  10);
  if ((val__C4D !=  0)) {
    print_positif__Y3D(val__C4D);
  };
  fputc((int)(Result__2NE),stdout);
}

static __POINTER new_lab__JIB(__UINTEGER_32 t__LIB)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 idx__NIB,pv__UIB;
  __MEMORY *blc__QIB,*prev__RIB,*Self__OZM,*Self__B2M,*prev__C2M;
  __MEMORY *next__D2M;
  __POINTER result__SIB;
  __BOOLEAN __tmp__UJB;
  idx__NIB= 0;
  blc__QIB=NULL;
  prev__RIB=NULL;
  pv__UIB= 0;
  while_do__MNB:
  {
    if ((idx__NIB < nb_page__1IB)) {
      blc__QIB=((__MEMORY *)(last_block[(idx__NIB)]));
      __tmp__UJB=(((__UINTEGER_32)(((__MEMORY *)blc__QIB)->size_and_id__OL &  4294967292LU) <  4096) || ((__UINTEGER_32)(((__MEMORY *)blc__QIB)->size_and_id__OL &  1) ==  1));
    } else {
      __tmp__UJB=FALSE__;
    };
    if (__tmp__UJB) {
      idx__NIB=(__UINTEGER_32)(idx__NIB +  1);
      goto while_do__MNB;
    };
  };
  if ((idx__NIB >= nb_page__1IB)) {
    blc__QIB=new_page__BGC();
  };
  ((__MEMORY *)blc__QIB)->size_and_id__OL=(__UINTEGER_32)(blc__QIB->size_and_id__OL -  4096);
  Self__OZM=((__MEMORY *)blc__QIB);
  result__SIB=((__POINTER )((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__OZM) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__OZM->size_and_id__OL &  4294967292LU))))));
  if (((__UINTEGER_32)(((__MEMORY *)blc__QIB)->size_and_id__OL &  4294967292LU) < ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    Self__B2M=((__MEMORY *)blc__QIB);
    prev__C2M=Self__B2M->previous_free__QL;
    next__D2M=Self__B2M->next_free__PL;
    if (((void *)prev__C2M == (void *)NULL)) {
      first_free__UVD=next__D2M;
    } else {
      ((__MEMORY *)prev__C2M)->next_free__PL=next__D2M;
    };
    if (((void *)next__D2M != (void *)NULL)) {
      ((__MEMORY *)next__D2M)->previous_free__QL=prev__C2M;
    };
    pv__UIB=blc__QIB->previous_linear__NL;
    if ((pv__UIB !=  4294967295LU)) {
      prev__RIB=((__MEMORY *)(void *)((unsigned long)begin_memory__I1 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )pv__UIB))));
      ((__MEMORY *)prev__RIB)->size_and_id__OL=(__UINTEGER_32)((__UINTEGER_32)(prev__RIB->size_and_id__OL + blc__QIB->size_and_id__OL) +  8);
      last_block[(idx__NIB)] = (prev__RIB);
    };
  };
  ((__POINTER *)result__SIB)[ 0]=((__POINTER )t__LIB);
  return((void *)((unsigned long)result__SIB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))))));
}

static __MEMORY* search__NOF(__UINTEGER_32 new_size__POF)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *result__ROF;
  result__ROF=first_free__UVD;
  while ((((void *)result__ROF != (void *)NULL) && ((__UINTEGER_32)(((__MEMORY *)result__ROF)->size_and_id__OL &  4294967292LU) < new_size__POF))) {
    result__ROF=result__ROF->next_free__PL;
  };
  if (((void *)result__ROF == (void *)NULL)) {
    result__ROF=new_page__BGC();
  };
  to_busy__index__4QG(result__ROF,new_size__POF,(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)result__ROF)) - (unsigned long)begin_memory__I1)))) >>  26));
  return(result__ROF);
}

static void extend__ZEC(__STRING *Self__0EC,__CHARACTER c__1EC)
// ({STRING},{CHARACTER}) VoidNo recursive, No inlinable.
{
  __INTEGER new_capacity__VNC,__tmp__OOC,__tmp__TNG,Self__OKJ;
  __POINTER old_ptr__BNG,result__L1G,result__B0M,p__REI,last__EPI;
  __UINTEGER_32 __tmp__NNG,__tmp__PNG,a__1ZM,old_size__B1G;
  __UINTEGER_32 old_size2__E1G,a__5ZM,new_size__H1G,a__F0M;
  __UINTEGER_32 new_size__G0M,new_size2__H0M,a__13M,new_size__33M;
  __UINTEGER_32 a__K0M,__tmp__22G,sz__EGI,old_size__BGI,prev__M1I;
  __UINTEGER_32 new_size__P1I;
  __MEMORY *mem__K1G,*Self__1FI,*nxt__5FI,*result__AGI,*next__L1I;
  __MEMORY *new_free__K1I,*prev__SZD,*next__TZD;
  __CHARACTER *__tmp__NOC,*new__ANG;
  new_capacity__VNC= 0;
  if ((Self__0EC->capacity__I1B <= Self__0EC->count__XZB)) {
    if ((Self__0EC->capacity__I1B ==  0)) {
      Self__0EC->capacity__I1B= 32;
      Self__0EC->storage__R1B=create__D2D( 32);
    } else {
      new_capacity__VNC=(__INTEGER)(Self__0EC->capacity__I1B <<  1);
      __tmp__NOC=Self__0EC->storage__R1B;
      __tmp__OOC=Self__0EC->capacity__I1B;
      old_ptr__BNG=((__POINTER )((__CHARACTER *)__tmp__NOC));
      __tmp__NNG=((__UINTEGER_32 )__tmp__OOC);
      __tmp__PNG=((__UINTEGER_32 )new_capacity__VNC);
      mem__K1G=NULL;
      result__L1G=((__POINTER )(NULL));
      a__1ZM=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      old_size__B1G=(__UINTEGER_32)((__UINTEGER_32)(__tmp__NNG + a__1ZM) & (__UINTEGER_32)(~ a__1ZM));
      old_size2__E1G=(__UINTEGER_32)(old_size__B1G + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
      a__5ZM=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__H1G=(__UINTEGER_32)((__UINTEGER_32)(__tmp__PNG + a__5ZM) & (__UINTEGER_32)(~ a__5ZM));
      if ((old_size2__E1G <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
        result__B0M=((__POINTER )(NULL));
        a__F0M=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        new_size__G0M=(__UINTEGER_32)((__UINTEGER_32)(new_size__H1G + a__F0M) & (__UINTEGER_32)(~ a__F0M));
        new_size2__H0M=(__UINTEGER_32)(new_size__G0M + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
        if ((new_size2__H0M <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
          a__13M=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
          new_size__33M=(__UINTEGER_32)((__UINTEGER_32)(new_size2__H0M + a__13M) & (__UINTEGER_32)(~ a__13M));
          result__B0M=micro_alloc__table__lab__LZ(new_size__33M,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__33M / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__33M);
          ((__POINTER *)result__B0M)[ 0]=((__POINTER ) 3);
          result__B0M=(void *)((unsigned long)result__B0M - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
        } else {
          result__B0M=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__NOF(new_size__G0M))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
        };
        result__L1G=result__B0M;
        copy__to__size__JDI(old_ptr__BNG,result__B0M,old_size__B1G);
        p__REI=(void *)((unsigned long)old_ptr__BNG - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))));
        a__K0M=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        last__EPI=((__POINTER *)((__POINTER )(&(table_size[((__UINTEGER_32)((__UINTEGER_32)((__UINTEGER_32)(old_size2__E1G + a__K0M) & (__UINTEGER_32)(~ a__K0M)) / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))))[ 0];
        ((__POINTER *)p__REI)[ 0]=(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)(void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER *)last__EPI)[ 0]) - (unsigned long)((__POINTER ) 1)) & (unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 3)) - (unsigned long)((__POINTER ) 1)))) - (unsigned long)((__POINTER ) 1));
        ((__POINTER *)last__EPI)[ 0]=p__REI;
      } else {
        mem__K1G=((__MEMORY *)(void *)((unsigned long)old_ptr__BNG - (unsigned long)((__POINTER ) 8)));
        __tmp__22G=(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)old_ptr__BNG - (unsigned long)begin_memory__I1)))) >>  26);
        Self__1FI=((__MEMORY *)mem__K1G);
        nxt__5FI=NULL;
        result__AGI=NULL;
        sz__EGI= 0;
        old_size__BGI=(__UINTEGER_32)(Self__1FI->size_and_id__OL &  4294967292LU);
        if ((new_size__H1G > old_size__BGI)) {
          if ((! ((__UINTEGER_32)(Self__1FI->size_and_id__OL &  2) !=  0))) {
            nxt__5FI=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__1FI) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__1FI->size_and_id__OL &  4294967292LU)))));
            sz__EGI=(__UINTEGER_32)((__UINTEGER_32)(new_size__H1G - old_size__BGI) -  8);
            if ((((__UINTEGER_32)(((__MEMORY *)nxt__5FI)->size_and_id__OL &  1) ==  0) && ((__UINTEGER_32)(((__MEMORY *)nxt__5FI)->size_and_id__OL &  4294967292LU) >= sz__EGI))) {
              to_busy__index__4QG(nxt__5FI,sz__EGI,__tmp__22G);
              Self__1FI->size_and_id__OL=(__UINTEGER_32)((__UINTEGER_32)(Self__1FI->size_and_id__OL + (__UINTEGER_32)(nxt__5FI->size_and_id__OL &  4294967294LU)) +  8);
              if (((__UINTEGER_32)(Self__1FI->size_and_id__OL &  2) !=  0)) {
                last_block[(__tmp__22G)] = (Self__1FI);
              } else {
                nxt__5FI=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__1FI) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__1FI->size_and_id__OL &  4294967292LU)))));
                ((__MEMORY *)nxt__5FI)->previous_linear__NL=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__1FI) - (unsigned long)begin_memory__I1))));
              };
              result__AGI=Self__1FI;
            };
          };
          if (((void *)result__AGI == (void *)NULL)) {
            result__AGI=search__NOF(new_size__H1G);
            copy__to__size__JDI((void *)((unsigned long)((__POINTER )Self__1FI) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))),(void *)((unsigned long)((__POINTER )((__MEMORY *)result__AGI)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))),old_size__BGI);
            prev__M1I=Self__1FI->previous_linear__NL;
            next__L1I=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__1FI) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__1FI->size_and_id__OL &  4294967292LU)))));
            new_free__K1I=((__MEMORY *)(void *)((unsigned long)begin_memory__I1 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )prev__M1I))));
            new_size__P1I=(__UINTEGER_32)(Self__1FI->size_and_id__OL &  4294967294LU);
            if (((prev__M1I ==  4294967295LU) || ((__UINTEGER_32)(new_free__K1I->size_and_id__OL &  1) !=  0))) {
              new_free__K1I=Self__1FI;
              Self__1FI->next_free__PL=first_free__UVD;
              Self__1FI->previous_free__QL=NULL;
              if (((void *)first_free__UVD != (void *)NULL)) {
                ((__MEMORY *)first_free__UVD)->previous_free__QL=Self__1FI;
              };
              first_free__UVD=Self__1FI;
            } else {
              new_size__P1I=(__UINTEGER_32)((__UINTEGER_32)(new_size__P1I + new_free__K1I->size_and_id__OL) +  8);
            };
            if (((! ((__UINTEGER_32)(Self__1FI->size_and_id__OL &  2) !=  0)) && ((__UINTEGER_32)(next__L1I->size_and_id__OL &  1) ==  0))) {
              new_size__P1I=(__UINTEGER_32)((__UINTEGER_32)(new_size__P1I + next__L1I->size_and_id__OL) +  8);
              prev__SZD=next__L1I->previous_free__QL;
              next__TZD=next__L1I->next_free__PL;
              if (((void *)prev__SZD == (void *)NULL)) {
                first_free__UVD=next__TZD;
              } else {
                ((__MEMORY *)prev__SZD)->next_free__PL=next__TZD;
              };
              if (((void *)next__TZD != (void *)NULL)) {
                ((__MEMORY *)next__TZD)->previous_free__QL=prev__SZD;
              };
            };
            new_free__K1I->size_and_id__OL=new_size__P1I;
            if (((__UINTEGER_32)(new_free__K1I->size_and_id__OL &  2) !=  0)) {
              last_block[(__tmp__22G)] = (new_free__K1I);
            } else {
              next__L1I=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__1FI) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__1FI->size_and_id__OL &  4294967292LU)))));
              next__L1I->previous_linear__NL=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )new_free__K1I) - (unsigned long)begin_memory__I1))));
            };
          };
        } else {
          result__AGI=Self__1FI;
        };
        result__L1G=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__AGI)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
      };
      new__ANG=((__CHARACTER *)result__L1G);
      __tmp__TNG=(__INTEGER)(new_capacity__VNC -  1);
      Self__OKJ=__tmp__OOC;
      while ((Self__OKJ <= __tmp__TNG)) {
        new__ANG[Self__OKJ]='\0';
        Self__OKJ=(__INTEGER)(Self__OKJ +  1);
      };
      Self__0EC->storage__R1B=new__ANG;
      Self__0EC->capacity__I1B=new_capacity__VNC;
    };
  };
  ((__CHARACTER *)Self__0EC->storage__R1B)[Self__0EC->count__XZB]=c__1EC;
  Self__0EC->count__XZB=(__INTEGER)(Self__0EC->count__XZB +  1);
}

static __MEMORY* new_page__BGC()
// () With resultNo recursive, No inlinable.
{
  __POINTER mem__D2C;
  __UINTEGER_32 cap__A2C,old_size__EGC;
  __INTEGER Self__KGD,limit_up__LGD;
  __MEMORY *block__KGC;
  __CHARACTER *__tmp__22M;
  if ((capacity_max__LGC ==  0)) {
    mem__D2C=((__POINTER )(NULL));
    cap__A2C= 33554432;
    do {
      cap__A2C=(__UINTEGER_32)(cap__A2C <<  1);
      mem__D2C=((__POINTER )(malloc((cap__A2C))));
      if ((mem__D2C != (void *)NULL)) {
        free((mem__D2C));
      };
    } while ((! ((mem__D2C == (void *)NULL) || (cap__A2C ==  2147483648LU))));
    if ((mem__D2C == (void *)NULL)) {
      cap__A2C=(__UINTEGER_32)(cap__A2C >>  1);
    };
    capacity_max__LGC=cap__A2C;
    begin_memory__I1=((__POINTER )(malloc((cap__A2C))));
  };
  old_size__EGC=(__UINTEGER_32)(nb_page__1IB <<  26);
  nb_page__1IB=(__UINTEGER_32)(nb_page__1IB +  1);
  if (((__UINTEGER_32)(old_size__EGC +  67108864) > capacity_max__LGC)) {
    Self__KGD= 1;
    limit_up__LGD=((__STRING_CONSTANT *)(&__string_1))->count__FGD;
    __tmp__22M=((__STRING_CONSTANT *)(&__string_1))->storage__TKE;
    while ((Self__KGD <= limit_up__LGD)) {
      fputc((int)(((__CHARACTER *)__tmp__22M)[(__INTEGER)(Self__KGD -  1)]),stdout);
      Self__KGD=(__INTEGER)(Self__KGD +  1);
    };
    exit(( 1));
  };
  block__KGC=((__MEMORY *)(void *)((unsigned long)begin_memory__I1 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )old_size__EGC))));
  block__KGC->previous_linear__NL= 4294967295LU;
  block__KGC->size_and_id__OL= 67108858;
  block__KGC->next_free__PL=first_free__UVD;
  block__KGC->previous_free__QL=NULL;
  if (((void *)first_free__UVD != (void *)NULL)) {
    ((__MEMORY *)first_free__UVD)->previous_free__QL=block__KGC;
  };
  first_free__UVD=block__KGC;
  last_block[((__UINTEGER_32)(nb_page__1IB -  1))] = (block__KGC);
  return(block__KGC);
}

static void to_busy__index__4QG(__MEMORY *Self__5QG,__UINTEGER_32 sz__ARG,__UINTEGER_32 idx__BRG)
// ({MEMORY},{UINTEGER_32},{UINTEGER_32}) VoidNo recursive, No inlinable.
{
  __MEMORY *new__IRG,*prev__P1M,*next__Q1M,*Self__TVD,*Self__YUM;
  __UINTEGER_32 siz__CRG,new_size__FRG;
  new__IRG=NULL;
  prev__P1M=Self__5QG->previous_free__QL;
  next__Q1M=Self__5QG->next_free__PL;
  if (((void *)prev__P1M == (void *)NULL)) {
    first_free__UVD=next__Q1M;
  } else {
    ((__MEMORY *)prev__P1M)->next_free__PL=next__Q1M;
  };
  if (((void *)next__Q1M != (void *)NULL)) {
    ((__MEMORY *)next__Q1M)->previous_free__QL=prev__P1M;
  };
  siz__CRG=Self__5QG->size_and_id__OL;
  new_size__FRG=(__UINTEGER_32)(siz__CRG - sz__ARG);
  if ((new_size__FRG > (__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )(MINIMUM_SIZE)) +  2) +  8))) {
    siz__CRG=sz__ARG;
    new__IRG=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__5QG) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )sz__ARG))));
    ((__MEMORY *)new__IRG)->previous_linear__NL=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__5QG) - (unsigned long)begin_memory__I1))));
    ((__MEMORY *)new__IRG)->size_and_id__OL=(__UINTEGER_32)(new_size__FRG -  8);
    Self__TVD=((__MEMORY *)new__IRG);
    Self__TVD->next_free__PL=first_free__UVD;
    Self__TVD->previous_free__QL=NULL;
    if (((void *)first_free__UVD != (void *)NULL)) {
      ((__MEMORY *)first_free__UVD)->previous_free__QL=Self__TVD;
    };
    first_free__UVD=Self__TVD;
    if (((__UINTEGER_32)(((__MEMORY *)new__IRG)->size_and_id__OL &  2) !=  0)) {
      last_block[(idx__BRG)] = (new__IRG);
    } else {
      Self__YUM=((__MEMORY *)new__IRG);
      ((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__YUM) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__YUM->size_and_id__OL &  4294967292LU)))))->previous_linear__NL=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)new__IRG)) - (unsigned long)begin_memory__I1))));
    };
  };
  Self__5QG->size_and_id__OL=(__UINTEGER_32)(siz__CRG |  1);
}

static void copy__to__size__JDI(__POINTER src__LDI,__POINTER dst__MDI,__UINTEGER_32 sz__NDI)
// ({POINTER},{POINTER},{UINTEGER_32}) VoidNo recursive, No inlinable.
{
  __INTEGER siz__QDI,Self__XMI;
  __POINTER *na_src__ODI,*na_dst__PDI;
  siz__QDI=((__INTEGER )sz__NDI);
  siz__QDI=(__INTEGER)(siz__QDI / ((__INTEGER )(sizeof(void *))));
  na_src__ODI=((__POINTER *)src__LDI);
  na_dst__PDI=((__POINTER *)dst__MDI);
  Self__XMI=(__INTEGER)(siz__QDI -  1);
  while ((Self__XMI >=  0)) {
    na_dst__PDI[Self__XMI]=na_src__ODI[Self__XMI];
    Self__XMI=(__INTEGER)(Self__XMI -  1);
  };
}

//==========================//
// DEBUG MANAGER            //
//==========================//

void print_string(char *str) 
{ 
  while (*str!=0) {
    print_char(*str); 
    str++; 
  };
}  

