// C code generated by Lisaac compiler (www.isaacOS.com) //
int arg_count;
char **arg_vector;

//==========================//
// EXTERNAL                 //
//==========================//

// THREADRING

#include <pthread.h>
pthread_attr_t stack_attr;

// MUTEX
pthread_mutex_t MUTEX__;
// STACK

#include <limits.h>
struct stack {
  char x[PTHREAD_STACK_MIN];
};
struct stack STACK__;

// THREAD
pthread_t THREAD__;
// FLOAT_REAL
#include <math.h>
// SYSTEM
#include <time.h>
// MEMORY

#define MINIMUM_SIZE 256  
void *table_size[MINIMUM_SIZE/sizeof(void *)];
void *last_block[64];

// SYSTEM_IO

#include <stdio.h>
#include <stdlib.h>
  
// Hardware 'print_char'
void print_char(char car)
{
  fputc(car,stdout);
}

// Hardware 'exit'
int die_with_code(int code)
{
  exit(code);
}



//==========================//
// TYPE                     //
//==========================//

// Generic Object
struct ___OBJ {
  unsigned long __id;
};

// NULL
#ifndef NULL
#define NULL ((void *)0)
#endif

// POINTER
typedef void * __POINTER;

// UINTEGER_32
typedef unsigned long __UINTEGER_32;

// MEMORY
#define __MEMORY__ 0
typedef struct MEMORY_struct __MEMORY;
struct MEMORY_struct {
  volatile __UINTEGER_32 previous_linear__HK;
  volatile __UINTEGER_32 size_and_id__IK;
  __MEMORY *next_free__JK;
  __MEMORY *previous_free__KK;
} __attribute__ ((packed));
__MEMORY MEMORY_;
#define MEMORY__ (&MEMORY_)

// INTEGER
typedef int __INTEGER;

// CHARACTER
typedef char __CHARACTER;

// ARRAYED_COLLECTION[Expanded INTEGER]
#define __ARRAYED_COLLECTIONoExpanded_INTEGERo__ 1
typedef struct ARRAYED_COLLECTIONoExpanded_INTEGERo_struct __ARRAYED_COLLECTIONoExpanded_INTEGERo;
struct ARRAYED_COLLECTIONoExpanded_INTEGERo_struct {
  __INTEGER capacity__AEC;
  __INTEGER upper__WEC;
  __INTEGER *storage__QBC;
};
__ARRAYED_COLLECTIONoExpanded_INTEGERo ARRAYED_COLLECTIONoExpanded_INTEGERo_;
#define ARRAYED_COLLECTIONoExpanded_INTEGERo__ (&ARRAYED_COLLECTIONoExpanded_INTEGERo_)

// FAST_ARRAY[Expanded INTEGER]
#define __FAST_ARRAYoExpanded_INTEGERo__ 2
typedef struct FAST_ARRAYoExpanded_INTEGERo_struct __FAST_ARRAYoExpanded_INTEGERo;
struct FAST_ARRAYoExpanded_INTEGERo_struct {
  __ARRAYED_COLLECTIONoExpanded_INTEGERo parent_arrayed_collection__4;
};
__FAST_ARRAYoExpanded_INTEGERo FAST_ARRAYoExpanded_INTEGERo_;
#define FAST_ARRAYoExpanded_INTEGERo__ (&FAST_ARRAYoExpanded_INTEGERo_)

// NUMERIC
#define __NUMERIC__ 3
typedef struct NUMERIC_struct __NUMERIC;
struct NUMERIC_struct {
  void *Nothing;
};
__NUMERIC NUMERIC_;
#define NUMERIC__ (&NUMERIC_)

// OBJECT
#define __OBJECT__ 4
typedef struct OBJECT_struct __OBJECT;
struct OBJECT_struct {
  void *Nothing;
};
__OBJECT OBJECT_;
#define OBJECT__ (&OBJECT_)

// STRING_CONSTANT
#define __STRING_CONSTANT__ 5
typedef struct STRING_CONSTANT_struct __STRING_CONSTANT;
struct STRING_CONSTANT_struct {
  __INTEGER count__XFG;
  __CHARACTER *storage__GMH;
};
__STRING_CONSTANT STRING_CONSTANT_;
#define STRING_CONSTANT__ (&STRING_CONSTANT_)

// TRUE
#define TRUE__ 1

// FALSE
#define FALSE__ 0

// THREADRING
#define __THREADRING__ 6
typedef struct THREADRING_struct __THREADRING;
struct THREADRING_struct {
  void *Nothing;
};
__THREADRING THREADRING_;
#define THREADRING__ (&THREADRING_)

// STRING
#define __STRING__ 7
typedef struct STRING_struct __STRING;
struct STRING_struct {
  __INTEGER count__EVH;
  __INTEGER capacity__2XH;
  __CHARACTER *storage__FYH;
};
__STRING STRING_;
#define STRING__ (&STRING_)

// ARRAYED_COLLECTION[STRING]
#define __ARRAYED_COLLECTIONoSTRINGo__ 8
typedef struct ARRAYED_COLLECTIONoSTRINGo_struct __ARRAYED_COLLECTIONoSTRINGo;
struct ARRAYED_COLLECTIONoSTRINGo_struct {
  __INTEGER capacity__HJC;
  __INTEGER upper__TJC;
  void **storage__KDC;
};
__ARRAYED_COLLECTIONoSTRINGo ARRAYED_COLLECTIONoSTRINGo_;
#define ARRAYED_COLLECTIONoSTRINGo__ (&ARRAYED_COLLECTIONoSTRINGo_)

// FAST_ARRAY[STRING]
#define __FAST_ARRAYoSTRINGo__ 9
typedef struct FAST_ARRAYoSTRINGo_struct __FAST_ARRAYoSTRINGo;
struct FAST_ARRAYoSTRINGo_struct {
  __ARRAYED_COLLECTIONoSTRINGo parent_arrayed_collection__0D;
};
__FAST_ARRAYoSTRINGo FAST_ARRAYoSTRINGo_;
#define FAST_ARRAYoSTRINGo__ (&FAST_ARRAYoSTRINGo_)

// MUTEX
typedef pthread_mutex_t __MUTEX;

// ARRAYED_COLLECTION[Expanded MUTEX]
#define __ARRAYED_COLLECTIONoExpanded_MUTEXo__ 10
typedef struct ARRAYED_COLLECTIONoExpanded_MUTEXo_struct __ARRAYED_COLLECTIONoExpanded_MUTEXo;
struct ARRAYED_COLLECTIONoExpanded_MUTEXo_struct {
  __INTEGER capacity__UGC;
  __INTEGER upper__KHC;
  __MUTEX *storage__RCC;
};
__ARRAYED_COLLECTIONoExpanded_MUTEXo ARRAYED_COLLECTIONoExpanded_MUTEXo_;
#define ARRAYED_COLLECTIONoExpanded_MUTEXo__ (&ARRAYED_COLLECTIONoExpanded_MUTEXo_)

// FAST_ARRAY[Expanded MUTEX]
#define __FAST_ARRAYoExpanded_MUTEXo__ 11
typedef struct FAST_ARRAYoExpanded_MUTEXo_struct __FAST_ARRAYoExpanded_MUTEXo;
struct FAST_ARRAYoExpanded_MUTEXo_struct {
  __ARRAYED_COLLECTIONoExpanded_MUTEXo parent_arrayed_collection__VB;
};
__FAST_ARRAYoExpanded_MUTEXo FAST_ARRAYoExpanded_MUTEXo_;
#define FAST_ARRAYoExpanded_MUTEXo__ (&FAST_ARRAYoExpanded_MUTEXo_)

// STACK
typedef struct stack __STACK;

// ARRAYED_COLLECTION[Expanded STACK]
#define __ARRAYED_COLLECTIONoExpanded_STACKo__ 12
typedef struct ARRAYED_COLLECTIONoExpanded_STACKo_struct __ARRAYED_COLLECTIONoExpanded_STACKo;
struct ARRAYED_COLLECTIONoExpanded_STACKo_struct {
  __INTEGER capacity__HZH;
  __INTEGER upper__3ZH;
  __STACK *storage__WUH;
};
__ARRAYED_COLLECTIONoExpanded_STACKo ARRAYED_COLLECTIONoExpanded_STACKo_;
#define ARRAYED_COLLECTIONoExpanded_STACKo__ (&ARRAYED_COLLECTIONoExpanded_STACKo_)

// FAST_ARRAY[Expanded STACK]
#define __FAST_ARRAYoExpanded_STACKo__ 13
typedef struct FAST_ARRAYoExpanded_STACKo_struct __FAST_ARRAYoExpanded_STACKo;
struct FAST_ARRAYoExpanded_STACKo_struct {
  __ARRAYED_COLLECTIONoExpanded_STACKo parent_arrayed_collection__AC;
};
__FAST_ARRAYoExpanded_STACKo FAST_ARRAYoExpanded_STACKo_;
#define FAST_ARRAYoExpanded_STACKo__ (&FAST_ARRAYoExpanded_STACKo_)

// INTEGER_8
typedef signed char __INTEGER_8;

// THREAD
typedef pthread_t __THREAD;

// BOOLEAN
typedef char __BOOLEAN;


void *table_type[14];

//==========================//
// GLOBAL                   //
//==========================//

__POINTER begin_memory__PCB;
__UINTEGER_32 nb_page__0QB;
__UINTEGER_32 capacity_max__ZQD;
__MEMORY *first_free__ALG;
void *parent_numeric__H;
__UINTEGER_32 clone_allocation_size__3J;
void *data__5;
void *mutex__WB;

//==========================//
// STRING CONSTANT          //
//==========================//

__STRING_CONSTANT __string_1={19,"Not enough memory.\n"};

//==========================//
// FUNCTION HEADER          //
//==========================//

// Debug Manager
void print_string(char *str);
// Source code
static __POINTER new_lab__IQB(__UINTEGER_32 t__KQB);
static __MEMORY* search__3JG(__UINTEGER_32 new_size__5JG);
static void** create__4QG(__INTEGER nb_elements__ARG);
static __CHARACTER* create__MKM(__INTEGER nb_elements__OKM);
static __POINTER realloc_dynamic__old_size__new_size__Y4I(__POINTER p__04I,__UINTEGER_32 old_sz__14I,__UINTEGER_32 new_sz__24I);
__POINTER thread(__POINTER num__HF);
static __MEMORY* new_page__PQD();
static void print_positif__CMK(__INTEGER Self__DMK);

//==========================//
// SOURCE CODE              //
//==========================//

int main(int argc,char **argv)
{
  __POINTER ptr__KJ,ptr_table__DWZ,next__CWZ,result__EWZ,ptr_table__IWZ;
  __POINTER next__HWZ,result__JWZ,result__XMZ,ptr_table__NWZ,next__MWZ;
  __POINTER result__OWZ,ptr__2P,ptr_table__SWZ,next__RWZ,result__TWZ;
  __POINTER ptr_table__XWZ,next__WWZ,result__YWZ,ptr__DME;
  __POINTER ptr_table__2WZ,next__1WZ,result__3WZ,ptr_table__BXZ;
  __POINTER next__AXZ,result__CXZ,ptr__FM,ptr_table__GXZ,next__FXZ;
  __POINTER result__HXZ,ptr_table__LXZ,next__KXZ,result__MXZ;
  __POINTER result__INZ,ptr_table__QXZ,next__PXZ,result__RXZ,ptr__ZXE;
  __POINTER ptr_table__VXZ,next__UXZ,result__WXZ,ptr_table__0XZ;
  __POINTER next__ZXZ,result__1XZ,result__O1E,ptr_table__VAB,next__0AB;
  __POINTER result__YAB;
  __INTEGER typ_id__PJ,Self__XPI,__tmp__DFC,Self__CML,new_count__3K;
  __INTEGER typ_id__BQ,Self__EL,limit_up__FL,idx__2XD,typ_id__IME;
  __INTEGER i__2UH,new_capacity__SIM,__tmp__LJM,__tmp__5FP,Self__0FT;
  __INTEGER new_capacity__VZD,__tmp__Z0D,__tmp__ECI,Self__OMP;
  __INTEGER typ_id__KM,Self__4QI,__tmp__XHC,Self__KOL,typ_id__4XE;
  __INTEGER Self__VNP,__tmp__K0H,Self__OES,state__3TO,result__AUO;
  __INTEGER i__2TO,__tmp__NVZ,__tmp__PVZ,Self__JE;
  __UINTEGER_32 sz__MJ,a__FSZ,new_size__GSZ,t__PSZ,a__MSZ,new_size__LWZ;
  __UINTEGER_32 lab_type__KWZ,sz__YMZ,a__3MZ,new_size__ZMZ;
  __UINTEGER_32 new_size2__0MZ,a__TSZ,new_size__USZ,sz__4P,a__ATZ;
  __UINTEGER_32 new_size__BTZ,t__KTZ,a__HTZ,new_size__0WZ,lab_type__ZWZ;
  __UINTEGER_32 sz__FME,a__OTZ,new_size__PTZ,t__YTZ,a__VTZ;
  __UINTEGER_32 new_size__EXZ,lab_type__DXZ,sz__HM,a__IUZ,new_size__JUZ;
  __UINTEGER_32 t__SUZ,a__PUZ,new_size__OXZ,lab_type__NXZ,sz__JNZ;
  __UINTEGER_32 a__ONZ,new_size__KNZ,new_size2__LNZ,a__WUZ;
  __UINTEGER_32 new_size__XUZ,sz__1XE,a__DVZ,new_size__EVZ,t__R0,a__OOZ;
  __UINTEGER_32 new_size__3XZ,lab_type__2XZ,sz__G1E,a__SNZ;
  __UINTEGER_32 new_size__I1E,new_size2__L1E,a__IOZ,new_size__IZ;
  __STRING *result__CME,*Self__NXH,*Self__0UH,*Self__0TO;
  __MUTEX v__EXH,v__ETK;
  __STACK v__GAP,v__DKR;
  __FAST_ARRAYoExpanded_INTEGERo *result__JJ,*Self__WDC;
  __INTEGER *Result__IFE,*__tmp__CFC,*Self__GRK;
  __BOOLEAN __tmp__KEC,__tmp__D0D,__tmp__4GC,__tmp__RZH,negative__5TO;
  __BOOLEAN __tmp__MVO,result__AIW,__tmp__5VO,__tmp__UWO,result__UOU;
  __BOOLEAN __tmp__1XO,result__GPU,result__YOO;
  __CHARACTER *arg__1G,*Self__QXD,*p__1UH,*__tmp__KJM,*new__MFP;
  __CHARACTER *__tmp__OVZ;
  __FAST_ARRAYoSTRINGo *result__1P,*Self__4IC,*Self__TZD;
  void *result__0G;
  __CHARACTER __tmp__RVH,cc__4TO;
  void **__tmp__Y0D,**new__RBI;
  __FAST_ARRAYoExpanded_MUTEXo *result__EM,*Self__KGC;
  __MUTEX *Result__UHE,*__tmp__WHC,*Self__TSK,*__tmp__QVZ,*__tmp__RVZ;
  __FAST_ARRAYoExpanded_STACKo *result__YXE,*Self__3YH;
  __STACK *Result__RQL,*__tmp__J0H,*Self__SJR,*__tmp__SVZ;
  arg_count  = argc;
  arg_vector = argv;
  ARRAYED_COLLECTIONoExpanded_INTEGERo__->storage__QBC=NULL;
  ARRAYED_COLLECTIONoExpanded_INTEGERo__->capacity__AEC= 0;
  ARRAYED_COLLECTIONoExpanded_INTEGERo__->upper__WEC= 0;
  FAST_ARRAYoExpanded_INTEGERo__->parent_arrayed_collection__4=(*ARRAYED_COLLECTIONoExpanded_INTEGERo__);
  parent_numeric__H=NUMERIC__;
  clone_allocation_size__3J= 0;
  STRING_CONSTANT__->count__XFG=((__INTEGER )((0)));
  STRING_CONSTANT__->storage__GMH=((__CHARACTER *)(NULL));
  nb_page__0QB= 0;
  MEMORY__->size_and_id__IK= 0;
  capacity_max__ZQD= 0;
  begin_memory__PCB=((__POINTER )(NULL));
  MEMORY__->previous_linear__HK= 0;
  first_free__ALG=NULL;
  MEMORY__->next_free__JK=NULL;
  MEMORY__->previous_free__KK=NULL;
  result__JJ=NULL;
  ptr__KJ=((__POINTER )(NULL));
  typ_id__PJ= 0;
  sz__MJ=((__UINTEGER_32 )sizeof(__FAST_ARRAYoExpanded_INTEGERo));
  if ((sz__MJ ==  0)) {
    result__JJ=FAST_ARRAYoExpanded_INTEGERo__;
  } else {
    typ_id__PJ=__FAST_ARRAYoExpanded_INTEGERo__;
    clone_allocation_size__3J=sz__MJ;
    if ((typ_id__PJ == (__INTEGER)(-  1))) {
      a__FSZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__GSZ=(__UINTEGER_32)((__UINTEGER_32)(sz__MJ + a__FSZ) & (__UINTEGER_32)(~ a__FSZ));
      ptr_table__DWZ=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__GSZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__CWZ=((__POINTER )(NULL));
      result__EWZ=((__POINTER *)ptr_table__DWZ)[ 0];
      if ((result__EWZ == (void *)NULL)) {
        result__EWZ=new_lab__IQB(new_size__GSZ);
        next__CWZ=(void *)((unsigned long)result__EWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__GSZ)));
        ((__POINTER *)next__CWZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__DWZ)[ 0]=next__CWZ;
      } else {
        next__CWZ=((__POINTER *)result__EWZ)[ 0];
        if ((next__CWZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__EWZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__GSZ <<  1)) <=  4096)) {
            next__CWZ=(void *)((unsigned long)result__EWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__GSZ)));
          } else {
            next__CWZ=new_lab__IQB(new_size__GSZ);
          };
          ((__POINTER *)next__CWZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__DWZ)[ 0]=next__CWZ;
        } else {
          ((__POINTER *)result__EWZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__CWZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__EWZ=next__CWZ;
        };
      };
      ptr__KJ=result__EWZ;
    } else {
      t__PSZ=((__UINTEGER_32 )typ_id__PJ);
      a__MSZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__LWZ=(__UINTEGER_32)((__UINTEGER_32)(sz__MJ + a__MSZ) & (__UINTEGER_32)(~ a__MSZ));
      ptr_table__IWZ=((__POINTER )(&(table_type[(t__PSZ)])));
      lab_type__KWZ=(__UINTEGER_32)(t__PSZ |  1);
      next__HWZ=((__POINTER )(NULL));
      result__JWZ=((__POINTER *)ptr_table__IWZ)[ 0];
      if ((result__JWZ == (void *)NULL)) {
        result__JWZ=new_lab__IQB(lab_type__KWZ);
        next__HWZ=(void *)((unsigned long)result__JWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__LWZ)));
        ((__POINTER *)next__HWZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__IWZ)[ 0]=next__HWZ;
      } else {
        next__HWZ=((__POINTER *)result__JWZ)[ 0];
        if ((next__HWZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__JWZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__LWZ <<  1)) <=  4096)) {
            next__HWZ=(void *)((unsigned long)result__JWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__LWZ)));
          } else {
            next__HWZ=new_lab__IQB(lab_type__KWZ);
          };
          ((__POINTER *)next__HWZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__IWZ)[ 0]=next__HWZ;
        } else {
          ((__POINTER *)result__JWZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__HWZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__JWZ=next__HWZ;
        };
      };
      ptr__KJ=result__JWZ;
    };
    result__JJ=((__FAST_ARRAYoExpanded_INTEGERo *)ptr__KJ);
    *(result__JJ) = *(FAST_ARRAYoExpanded_INTEGERo__);
  };
  Self__WDC=((__FAST_ARRAYoExpanded_INTEGERo *)result__JJ);
  if (( 503 > Self__WDC->parent_arrayed_collection__4.capacity__AEC)) {
    sz__YMZ=((__UINTEGER_32 )(__INTEGER)( 503 * sizeof(__INTEGER)));
    result__XMZ=((__POINTER )(NULL));
    a__3MZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__ZMZ=(__UINTEGER_32)((__UINTEGER_32)(sz__YMZ + a__3MZ) & (__UINTEGER_32)(~ a__3MZ));
    new_size2__0MZ=(__UINTEGER_32)(new_size__ZMZ + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
    if ((new_size2__0MZ <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
      a__TSZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__USZ=(__UINTEGER_32)((__UINTEGER_32)(new_size2__0MZ + a__TSZ) & (__UINTEGER_32)(~ a__TSZ));
      ptr_table__NWZ=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__USZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__MWZ=((__POINTER )(NULL));
      result__OWZ=((__POINTER *)ptr_table__NWZ)[ 0];
      if ((result__OWZ == (void *)NULL)) {
        result__OWZ=new_lab__IQB(new_size__USZ);
        next__MWZ=(void *)((unsigned long)result__OWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__USZ)));
        ((__POINTER *)next__MWZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__NWZ)[ 0]=next__MWZ;
      } else {
        next__MWZ=((__POINTER *)result__OWZ)[ 0];
        if ((next__MWZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__OWZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__USZ <<  1)) <=  4096)) {
            next__MWZ=(void *)((unsigned long)result__OWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__USZ)));
          } else {
            next__MWZ=new_lab__IQB(new_size__USZ);
          };
          ((__POINTER *)next__MWZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__NWZ)[ 0]=next__MWZ;
        } else {
          ((__POINTER *)result__OWZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__MWZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__OWZ=next__MWZ;
        };
      };
      ((__POINTER *)result__OWZ)[ 0]=((__POINTER ) 3);
      result__XMZ=(void *)((unsigned long)result__OWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
    } else {
      result__XMZ=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__3JG(new_size__ZMZ))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
    };
    Result__IFE=((__INTEGER *)result__XMZ);
    Self__XPI= 502;
    while ((Self__XPI >=  0)) {
      Result__IFE[Self__XPI]= 0;
      Self__XPI=(__INTEGER)(Self__XPI -  1);
    };
    Self__WDC->parent_arrayed_collection__4.storage__QBC=Result__IFE;
    Self__WDC->parent_arrayed_collection__4.capacity__AEC= 503;
    __tmp__KEC=TRUE__;
  } else {
    __tmp__KEC=FALSE__;
  };
  if ((! __tmp__KEC)) {
    if (((Self__WDC->parent_arrayed_collection__4.capacity__AEC >  0) && (Self__WDC->parent_arrayed_collection__4.upper__WEC >=  0))) {
      __tmp__CFC=Self__WDC->parent_arrayed_collection__4.storage__QBC;
      __tmp__DFC=Self__WDC->parent_arrayed_collection__4.upper__WEC;
      Self__GRK=((__INTEGER *)__tmp__CFC);
      Self__CML= 0;
      while ((Self__CML <= __tmp__DFC)) {
        Self__GRK[Self__CML]= 0;
        Self__CML=(__INTEGER)(Self__CML +  1);
      };
    };
  };
  Self__WDC->parent_arrayed_collection__4.upper__WEC= 502;
  data__5=result__JJ;
  ARRAYED_COLLECTIONoSTRINGo__->storage__KDC=NULL;
  ARRAYED_COLLECTIONoSTRINGo__->capacity__HJC= 0;
  ARRAYED_COLLECTIONoSTRINGo__->upper__TJC= 0;
  FAST_ARRAYoSTRINGo__->parent_arrayed_collection__0D=(*ARRAYED_COLLECTIONoSTRINGo__);
  STRING__->capacity__2XH= 0;
  STRING__->storage__FYH=NULL;
  STRING__->count__EVH= 0;
  arg__1G=NULL;
  new_count__3K=((__INTEGER )(arg_count));
  result__1P=NULL;
  ptr__2P=((__POINTER )(NULL));
  typ_id__BQ= 0;
  sz__4P=((__UINTEGER_32 )sizeof(__FAST_ARRAYoSTRINGo));
  if ((sz__4P ==  0)) {
    result__1P=FAST_ARRAYoSTRINGo__;
  } else {
    typ_id__BQ=__FAST_ARRAYoSTRINGo__;
    clone_allocation_size__3J=(__UINTEGER_32)(clone_allocation_size__3J + sz__4P);
    if ((typ_id__BQ == (__INTEGER)(-  1))) {
      a__ATZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__BTZ=(__UINTEGER_32)((__UINTEGER_32)(sz__4P + a__ATZ) & (__UINTEGER_32)(~ a__ATZ));
      ptr_table__SWZ=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__BTZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__RWZ=((__POINTER )(NULL));
      result__TWZ=((__POINTER *)ptr_table__SWZ)[ 0];
      if ((result__TWZ == (void *)NULL)) {
        result__TWZ=new_lab__IQB(new_size__BTZ);
        next__RWZ=(void *)((unsigned long)result__TWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__BTZ)));
        ((__POINTER *)next__RWZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__SWZ)[ 0]=next__RWZ;
      } else {
        next__RWZ=((__POINTER *)result__TWZ)[ 0];
        if ((next__RWZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__TWZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__BTZ <<  1)) <=  4096)) {
            next__RWZ=(void *)((unsigned long)result__TWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__BTZ)));
          } else {
            next__RWZ=new_lab__IQB(new_size__BTZ);
          };
          ((__POINTER *)next__RWZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__SWZ)[ 0]=next__RWZ;
        } else {
          ((__POINTER *)result__TWZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__RWZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__TWZ=next__RWZ;
        };
      };
      ptr__2P=result__TWZ;
    } else {
      t__KTZ=((__UINTEGER_32 )typ_id__BQ);
      a__HTZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__0WZ=(__UINTEGER_32)((__UINTEGER_32)(sz__4P + a__HTZ) & (__UINTEGER_32)(~ a__HTZ));
      ptr_table__XWZ=((__POINTER )(&(table_type[(t__KTZ)])));
      lab_type__ZWZ=(__UINTEGER_32)(t__KTZ |  1);
      next__WWZ=((__POINTER )(NULL));
      result__YWZ=((__POINTER *)ptr_table__XWZ)[ 0];
      if ((result__YWZ == (void *)NULL)) {
        result__YWZ=new_lab__IQB(lab_type__ZWZ);
        next__WWZ=(void *)((unsigned long)result__YWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__0WZ)));
        ((__POINTER *)next__WWZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__XWZ)[ 0]=next__WWZ;
      } else {
        next__WWZ=((__POINTER *)result__YWZ)[ 0];
        if ((next__WWZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__YWZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__0WZ <<  1)) <=  4096)) {
            next__WWZ=(void *)((unsigned long)result__YWZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__0WZ)));
          } else {
            next__WWZ=new_lab__IQB(lab_type__ZWZ);
          };
          ((__POINTER *)next__WWZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__XWZ)[ 0]=next__WWZ;
        } else {
          ((__POINTER *)result__YWZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__WWZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__YWZ=next__WWZ;
        };
      };
      ptr__2P=result__YWZ;
    };
    result__1P=((__FAST_ARRAYoSTRINGo *)ptr__2P);
    *(result__1P) = *(FAST_ARRAYoSTRINGo__);
  };
  Self__4IC=((__FAST_ARRAYoSTRINGo *)result__1P);
  if ((Self__4IC->parent_arrayed_collection__0D.capacity__HJC < new_count__3K)) {
    Self__4IC->parent_arrayed_collection__0D.storage__KDC=create__4QG(new_count__3K);
    Self__4IC->parent_arrayed_collection__0D.capacity__HJC=new_count__3K;
  };
  Self__4IC->parent_arrayed_collection__0D.upper__TJC=(__INTEGER)(-  1);
  result__0G=result__1P;
  Self__EL= 0;
  limit_up__FL=(__INTEGER)(((__INTEGER )(arg_count)) -  1);
  while ((Self__EL <= limit_up__FL)) {
    arg__1G=((__CHARACTER *)(arg_vector[(Self__EL)]));
    Self__QXD=((__CHARACTER *)arg__1G);
    idx__2XD= 0;
    while ((! ((idx__2XD >  1024) || ('\0' == Self__QXD[idx__2XD])))) {
      idx__2XD=(__INTEGER)(idx__2XD +  1);
    };
    result__CME=NULL;
    ptr__DME=((__POINTER )(NULL));
    typ_id__IME= 0;
    sz__FME=((__UINTEGER_32 )sizeof(__STRING));
    if ((sz__FME ==  0)) {
      result__CME=STRING__;
    } else {
      typ_id__IME=__STRING__;
      clone_allocation_size__3J=(__UINTEGER_32)(clone_allocation_size__3J + sz__FME);
      if ((typ_id__IME == (__INTEGER)(-  1))) {
        a__OTZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        new_size__PTZ=(__UINTEGER_32)((__UINTEGER_32)(sz__FME + a__OTZ) & (__UINTEGER_32)(~ a__OTZ));
        ptr_table__2WZ=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__PTZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
        next__1WZ=((__POINTER )(NULL));
        result__3WZ=((__POINTER *)ptr_table__2WZ)[ 0];
        if ((result__3WZ == (void *)NULL)) {
          result__3WZ=new_lab__IQB(new_size__PTZ);
          next__1WZ=(void *)((unsigned long)result__3WZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__PTZ)));
          ((__POINTER *)next__1WZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__2WZ)[ 0]=next__1WZ;
        } else {
          next__1WZ=((__POINTER *)result__3WZ)[ 0];
          if ((next__1WZ == (void *)NULL)) {
            if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__3WZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__PTZ <<  1)) <=  4096)) {
              next__1WZ=(void *)((unsigned long)result__3WZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__PTZ)));
            } else {
              next__1WZ=new_lab__IQB(new_size__PTZ);
            };
            ((__POINTER *)next__1WZ)[ 0]=NULL;
            ((__POINTER *)ptr_table__2WZ)[ 0]=next__1WZ;
          } else {
            ((__POINTER *)result__3WZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__1WZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
            result__3WZ=next__1WZ;
          };
        };
        ptr__DME=result__3WZ;
      } else {
        t__YTZ=((__UINTEGER_32 )typ_id__IME);
        a__VTZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        new_size__EXZ=(__UINTEGER_32)((__UINTEGER_32)(sz__FME + a__VTZ) & (__UINTEGER_32)(~ a__VTZ));
        ptr_table__BXZ=((__POINTER )(&(table_type[(t__YTZ)])));
        lab_type__DXZ=(__UINTEGER_32)(t__YTZ |  1);
        next__AXZ=((__POINTER )(NULL));
        result__CXZ=((__POINTER *)ptr_table__BXZ)[ 0];
        if ((result__CXZ == (void *)NULL)) {
          result__CXZ=new_lab__IQB(lab_type__DXZ);
          next__AXZ=(void *)((unsigned long)result__CXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__EXZ)));
          ((__POINTER *)next__AXZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__BXZ)[ 0]=next__AXZ;
        } else {
          next__AXZ=((__POINTER *)result__CXZ)[ 0];
          if ((next__AXZ == (void *)NULL)) {
            if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__CXZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__EXZ <<  1)) <=  4096)) {
              next__AXZ=(void *)((unsigned long)result__CXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__EXZ)));
            } else {
              next__AXZ=new_lab__IQB(lab_type__DXZ);
            };
            ((__POINTER *)next__AXZ)[ 0]=NULL;
            ((__POINTER *)ptr_table__BXZ)[ 0]=next__AXZ;
          } else {
            ((__POINTER *)result__CXZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__AXZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
            result__CXZ=next__AXZ;
          };
        };
        ptr__DME=result__CXZ;
      };
      result__CME=((__STRING *)ptr__DME);
      *(result__CME) = *(STRING__);
    };
    Self__NXH=((__STRING *)result__CME);
    if ((idx__2XD >  0)) {
      if ((Self__NXH->capacity__2XH < idx__2XD)) {
        Self__NXH->storage__FYH=create__MKM(idx__2XD);
        Self__NXH->capacity__2XH=idx__2XD;
      };
    };
    Self__NXH->count__EVH= 0;
    Self__0UH=((__STRING *)result__CME);
    p__1UH=arg__1G;
    i__2UH= 0;
    Self__0UH->count__EVH= 0;
    while ((((__CHARACTER *)p__1UH)[i__2UH] != '\0')) {
      __tmp__RVH=((__CHARACTER *)p__1UH)[i__2UH];
      new_capacity__SIM= 0;
      if ((Self__0UH->capacity__2XH <= Self__0UH->count__EVH)) {
        if ((Self__0UH->capacity__2XH ==  0)) {
          Self__0UH->capacity__2XH= 32;
          Self__0UH->storage__FYH=create__MKM( 32);
        } else {
          new_capacity__SIM=(__INTEGER)(Self__0UH->capacity__2XH <<  1);
          __tmp__KJM=Self__0UH->storage__FYH;
          __tmp__LJM=Self__0UH->capacity__2XH;
          new__MFP=((__CHARACTER *)realloc_dynamic__old_size__new_size__Y4I(((__POINTER )((__CHARACTER *)__tmp__KJM)),((__UINTEGER_32 )__tmp__LJM),((__UINTEGER_32 )new_capacity__SIM)));
          __tmp__5FP=(__INTEGER)(new_capacity__SIM -  1);
          Self__0FT=__tmp__LJM;
          while ((Self__0FT <= __tmp__5FP)) {
            new__MFP[Self__0FT]='\0';
            Self__0FT=(__INTEGER)(Self__0FT +  1);
          };
          Self__0UH->storage__FYH=new__MFP;
          Self__0UH->capacity__2XH=new_capacity__SIM;
        };
      };
      ((__CHARACTER *)Self__0UH->storage__FYH)[Self__0UH->count__EVH]=__tmp__RVH;
      Self__0UH->count__EVH=(__INTEGER)(Self__0UH->count__EVH +  1);
      i__2UH=(__INTEGER)(i__2UH +  1);
    };
    Self__TZD=((__FAST_ARRAYoSTRINGo *)result__0G);
    new_capacity__VZD= 0;
    if (((__INTEGER)(Self__TZD->parent_arrayed_collection__0D.upper__TJC +  1) <= (__INTEGER)(Self__TZD->parent_arrayed_collection__0D.capacity__HJC -  1))) {
      Self__TZD->parent_arrayed_collection__0D.upper__TJC=(__INTEGER)(Self__TZD->parent_arrayed_collection__0D.upper__TJC +  1);
      __tmp__D0D=TRUE__;
    } else {
      __tmp__D0D=FALSE__;
    };
    if ((! __tmp__D0D)) {
      if ((Self__TZD->parent_arrayed_collection__0D.capacity__HJC ==  0)) {
        Self__TZD->parent_arrayed_collection__0D.storage__KDC=create__4QG( 2);
        Self__TZD->parent_arrayed_collection__0D.capacity__HJC= 2;
        Self__TZD->parent_arrayed_collection__0D.upper__TJC= 0;
      } else {
        new_capacity__VZD=(__INTEGER)(Self__TZD->parent_arrayed_collection__0D.capacity__HJC <<  1);
        __tmp__Y0D=Self__TZD->parent_arrayed_collection__0D.storage__KDC;
        __tmp__Z0D=Self__TZD->parent_arrayed_collection__0D.capacity__HJC;
        new__RBI=((void **)realloc_dynamic__old_size__new_size__Y4I(((__POINTER )((void **)__tmp__Y0D)),((__UINTEGER_32 )(__INTEGER)(__tmp__Z0D * ((__INTEGER )(sizeof(void *))))),((__UINTEGER_32 )(__INTEGER)(new_capacity__VZD * ((__INTEGER )(sizeof(void *)))))));
        __tmp__ECI=(__INTEGER)(new_capacity__VZD -  1);
        Self__OMP=__tmp__Z0D;
        while ((Self__OMP <= __tmp__ECI)) {
          new__RBI[Self__OMP]=NULL;
          Self__OMP=(__INTEGER)(Self__OMP +  1);
        };
        Self__TZD->parent_arrayed_collection__0D.storage__KDC=new__RBI;
        Self__TZD->parent_arrayed_collection__0D.capacity__HJC=new_capacity__VZD;
        Self__TZD->parent_arrayed_collection__0D.upper__TJC=(__INTEGER)(Self__TZD->parent_arrayed_collection__0D.upper__TJC +  1);
      };
    };
    ((void **)Self__TZD->parent_arrayed_collection__0D.storage__KDC)[Self__TZD->parent_arrayed_collection__0D.upper__TJC]=result__CME;
    Self__EL=(__INTEGER)(Self__EL +  1);
  };
  ARRAYED_COLLECTIONoExpanded_MUTEXo__->storage__RCC=NULL;
  ARRAYED_COLLECTIONoExpanded_MUTEXo__->capacity__UGC= 0;
  ARRAYED_COLLECTIONoExpanded_MUTEXo__->upper__KHC= 0;
  FAST_ARRAYoExpanded_MUTEXo__->parent_arrayed_collection__VB=(*ARRAYED_COLLECTIONoExpanded_MUTEXo__);
  result__EM=NULL;
  ptr__FM=((__POINTER )(NULL));
  typ_id__KM= 0;
  sz__HM=((__UINTEGER_32 )sizeof(__FAST_ARRAYoExpanded_MUTEXo));
  if ((sz__HM ==  0)) {
    result__EM=FAST_ARRAYoExpanded_MUTEXo__;
  } else {
    typ_id__KM=__FAST_ARRAYoExpanded_MUTEXo__;
    clone_allocation_size__3J=(__UINTEGER_32)(clone_allocation_size__3J + sz__HM);
    if ((typ_id__KM == (__INTEGER)(-  1))) {
      a__IUZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__JUZ=(__UINTEGER_32)((__UINTEGER_32)(sz__HM + a__IUZ) & (__UINTEGER_32)(~ a__IUZ));
      ptr_table__GXZ=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__JUZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__FXZ=((__POINTER )(NULL));
      result__HXZ=((__POINTER *)ptr_table__GXZ)[ 0];
      if ((result__HXZ == (void *)NULL)) {
        result__HXZ=new_lab__IQB(new_size__JUZ);
        next__FXZ=(void *)((unsigned long)result__HXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__JUZ)));
        ((__POINTER *)next__FXZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__GXZ)[ 0]=next__FXZ;
      } else {
        next__FXZ=((__POINTER *)result__HXZ)[ 0];
        if ((next__FXZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__HXZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__JUZ <<  1)) <=  4096)) {
            next__FXZ=(void *)((unsigned long)result__HXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__JUZ)));
          } else {
            next__FXZ=new_lab__IQB(new_size__JUZ);
          };
          ((__POINTER *)next__FXZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__GXZ)[ 0]=next__FXZ;
        } else {
          ((__POINTER *)result__HXZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__FXZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__HXZ=next__FXZ;
        };
      };
      ptr__FM=result__HXZ;
    } else {
      t__SUZ=((__UINTEGER_32 )typ_id__KM);
      a__PUZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__OXZ=(__UINTEGER_32)((__UINTEGER_32)(sz__HM + a__PUZ) & (__UINTEGER_32)(~ a__PUZ));
      ptr_table__LXZ=((__POINTER )(&(table_type[(t__SUZ)])));
      lab_type__NXZ=(__UINTEGER_32)(t__SUZ |  1);
      next__KXZ=((__POINTER )(NULL));
      result__MXZ=((__POINTER *)ptr_table__LXZ)[ 0];
      if ((result__MXZ == (void *)NULL)) {
        result__MXZ=new_lab__IQB(lab_type__NXZ);
        next__KXZ=(void *)((unsigned long)result__MXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__OXZ)));
        ((__POINTER *)next__KXZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__LXZ)[ 0]=next__KXZ;
      } else {
        next__KXZ=((__POINTER *)result__MXZ)[ 0];
        if ((next__KXZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__MXZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__OXZ <<  1)) <=  4096)) {
            next__KXZ=(void *)((unsigned long)result__MXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__OXZ)));
          } else {
            next__KXZ=new_lab__IQB(lab_type__NXZ);
          };
          ((__POINTER *)next__KXZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__LXZ)[ 0]=next__KXZ;
        } else {
          ((__POINTER *)result__MXZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__KXZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__MXZ=next__KXZ;
        };
      };
      ptr__FM=result__MXZ;
    };
    result__EM=((__FAST_ARRAYoExpanded_MUTEXo *)ptr__FM);
    *(result__EM) = *(FAST_ARRAYoExpanded_MUTEXo__);
  };
  Self__KGC=((__FAST_ARRAYoExpanded_MUTEXo *)result__EM);
  if (( 503 > Self__KGC->parent_arrayed_collection__VB.capacity__UGC)) {
    sz__JNZ=((__UINTEGER_32 )(__INTEGER)( 503 * sizeof(__MUTEX)));
    result__INZ=((__POINTER )(NULL));
    a__ONZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__KNZ=(__UINTEGER_32)((__UINTEGER_32)(sz__JNZ + a__ONZ) & (__UINTEGER_32)(~ a__ONZ));
    new_size2__LNZ=(__UINTEGER_32)(new_size__KNZ + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
    if ((new_size2__LNZ <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
      a__WUZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__XUZ=(__UINTEGER_32)((__UINTEGER_32)(new_size2__LNZ + a__WUZ) & (__UINTEGER_32)(~ a__WUZ));
      ptr_table__QXZ=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__XUZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__PXZ=((__POINTER )(NULL));
      result__RXZ=((__POINTER *)ptr_table__QXZ)[ 0];
      if ((result__RXZ == (void *)NULL)) {
        result__RXZ=new_lab__IQB(new_size__XUZ);
        next__PXZ=(void *)((unsigned long)result__RXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__XUZ)));
        ((__POINTER *)next__PXZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__QXZ)[ 0]=next__PXZ;
      } else {
        next__PXZ=((__POINTER *)result__RXZ)[ 0];
        if ((next__PXZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__RXZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__XUZ <<  1)) <=  4096)) {
            next__PXZ=(void *)((unsigned long)result__RXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__XUZ)));
          } else {
            next__PXZ=new_lab__IQB(new_size__XUZ);
          };
          ((__POINTER *)next__PXZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__QXZ)[ 0]=next__PXZ;
        } else {
          ((__POINTER *)result__RXZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__PXZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__RXZ=next__PXZ;
        };
      };
      ((__POINTER *)result__RXZ)[ 0]=((__POINTER ) 3);
      result__INZ=(void *)((unsigned long)result__RXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
    } else {
      result__INZ=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__3JG(new_size__KNZ))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
    };
    Result__UHE=((__MUTEX *)result__INZ);
    v__EXH=((__MUTEX )(MUTEX__));
    Self__4QI= 502;
    while ((Self__4QI >=  0)) {
      Result__UHE[Self__4QI]=v__EXH;
      Self__4QI=(__INTEGER)(Self__4QI -  1);
    };
    Self__KGC->parent_arrayed_collection__VB.storage__RCC=Result__UHE;
    Self__KGC->parent_arrayed_collection__VB.capacity__UGC= 503;
    __tmp__4GC=TRUE__;
  } else {
    __tmp__4GC=FALSE__;
  };
  if ((! __tmp__4GC)) {
    if (((Self__KGC->parent_arrayed_collection__VB.capacity__UGC >  0) && (Self__KGC->parent_arrayed_collection__VB.upper__KHC >=  0))) {
      __tmp__WHC=Self__KGC->parent_arrayed_collection__VB.storage__RCC;
      __tmp__XHC=Self__KGC->parent_arrayed_collection__VB.upper__KHC;
      Self__TSK=((__MUTEX *)__tmp__WHC);
      v__ETK=((__MUTEX )(MUTEX__));
      Self__KOL= 0;
      while ((Self__KOL <= __tmp__XHC)) {
        Self__TSK[Self__KOL]=v__ETK;
        Self__KOL=(__INTEGER)(Self__KOL +  1);
      };
    };
  };
  Self__KGC->parent_arrayed_collection__VB.upper__KHC= 502;
  mutex__WB=result__EM;
  ARRAYED_COLLECTIONoExpanded_STACKo__->storage__WUH=NULL;
  ARRAYED_COLLECTIONoExpanded_STACKo__->capacity__HZH= 0;
  ARRAYED_COLLECTIONoExpanded_STACKo__->upper__3ZH= 0;
  FAST_ARRAYoExpanded_STACKo__->parent_arrayed_collection__AC=(*ARRAYED_COLLECTIONoExpanded_STACKo__);
  result__YXE=NULL;
  ptr__ZXE=((__POINTER )(NULL));
  typ_id__4XE= 0;
  sz__1XE=((__UINTEGER_32 )sizeof(__FAST_ARRAYoExpanded_STACKo));
  if ((sz__1XE ==  0)) {
    result__YXE=FAST_ARRAYoExpanded_STACKo__;
  } else {
    typ_id__4XE=__FAST_ARRAYoExpanded_STACKo__;
    clone_allocation_size__3J=(__UINTEGER_32)(clone_allocation_size__3J + sz__1XE);
    if ((typ_id__4XE == (__INTEGER)(-  1))) {
      a__DVZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__EVZ=(__UINTEGER_32)((__UINTEGER_32)(sz__1XE + a__DVZ) & (__UINTEGER_32)(~ a__DVZ));
      ptr_table__VXZ=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__EVZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__UXZ=((__POINTER )(NULL));
      result__WXZ=((__POINTER *)ptr_table__VXZ)[ 0];
      if ((result__WXZ == (void *)NULL)) {
        result__WXZ=new_lab__IQB(new_size__EVZ);
        next__UXZ=(void *)((unsigned long)result__WXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__EVZ)));
        ((__POINTER *)next__UXZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__VXZ)[ 0]=next__UXZ;
      } else {
        next__UXZ=((__POINTER *)result__WXZ)[ 0];
        if ((next__UXZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__WXZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__EVZ <<  1)) <=  4096)) {
            next__UXZ=(void *)((unsigned long)result__WXZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__EVZ)));
          } else {
            next__UXZ=new_lab__IQB(new_size__EVZ);
          };
          ((__POINTER *)next__UXZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__VXZ)[ 0]=next__UXZ;
        } else {
          ((__POINTER *)result__WXZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__UXZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__WXZ=next__UXZ;
        };
      };
      ptr__ZXE=result__WXZ;
    } else {
      t__R0=((__UINTEGER_32 )typ_id__4XE);
      a__OOZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__3XZ=(__UINTEGER_32)((__UINTEGER_32)(sz__1XE + a__OOZ) & (__UINTEGER_32)(~ a__OOZ));
      ptr_table__0XZ=((__POINTER )(&(table_type[(t__R0)])));
      lab_type__2XZ=(__UINTEGER_32)(t__R0 |  1);
      next__ZXZ=((__POINTER )(NULL));
      result__1XZ=((__POINTER *)ptr_table__0XZ)[ 0];
      if ((result__1XZ == (void *)NULL)) {
        result__1XZ=new_lab__IQB(lab_type__2XZ);
        next__ZXZ=(void *)((unsigned long)result__1XZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__3XZ)));
        ((__POINTER *)next__ZXZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__0XZ)[ 0]=next__ZXZ;
      } else {
        next__ZXZ=((__POINTER *)result__1XZ)[ 0];
        if ((next__ZXZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__1XZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__3XZ <<  1)) <=  4096)) {
            next__ZXZ=(void *)((unsigned long)result__1XZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__3XZ)));
          } else {
            next__ZXZ=new_lab__IQB(lab_type__2XZ);
          };
          ((__POINTER *)next__ZXZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__0XZ)[ 0]=next__ZXZ;
        } else {
          ((__POINTER *)result__1XZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__ZXZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__1XZ=next__ZXZ;
        };
      };
      ptr__ZXE=result__1XZ;
    };
    result__YXE=((__FAST_ARRAYoExpanded_STACKo *)ptr__ZXE);
    *(result__YXE) = *(FAST_ARRAYoExpanded_STACKo__);
  };
  Self__3YH=((__FAST_ARRAYoExpanded_STACKo *)result__YXE);
  if (( 503 > Self__3YH->parent_arrayed_collection__AC.capacity__HZH)) {
    sz__G1E=((__UINTEGER_32 )(__INTEGER)( 503 * sizeof(__STACK)));
    result__O1E=((__POINTER )(NULL));
    a__SNZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__I1E=(__UINTEGER_32)((__UINTEGER_32)(sz__G1E + a__SNZ) & (__UINTEGER_32)(~ a__SNZ));
    new_size2__L1E=(__UINTEGER_32)(new_size__I1E + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
    if ((new_size2__L1E <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
      a__IOZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__IZ=(__UINTEGER_32)((__UINTEGER_32)(new_size2__L1E + a__IOZ) & (__UINTEGER_32)(~ a__IOZ));
      ptr_table__VAB=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__IZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__0AB=((__POINTER )(NULL));
      result__YAB=((__POINTER *)ptr_table__VAB)[ 0];
      if ((result__YAB == (void *)NULL)) {
        result__YAB=new_lab__IQB(new_size__IZ);
        next__0AB=(void *)((unsigned long)result__YAB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__IZ)));
        ((__POINTER *)next__0AB)[ 0]=NULL;
        ((__POINTER *)ptr_table__VAB)[ 0]=next__0AB;
      } else {
        next__0AB=((__POINTER *)result__YAB)[ 0];
        if ((next__0AB == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__YAB - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__IZ <<  1)) <=  4096)) {
            next__0AB=(void *)((unsigned long)result__YAB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__IZ)));
          } else {
            next__0AB=new_lab__IQB(new_size__IZ);
          };
          ((__POINTER *)next__0AB)[ 0]=NULL;
          ((__POINTER *)ptr_table__VAB)[ 0]=next__0AB;
        } else {
          ((__POINTER *)result__YAB)[ 0]=(void *)((unsigned long)((__POINTER *)next__0AB)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__YAB=next__0AB;
        };
      };
      ((__POINTER *)result__YAB)[ 0]=((__POINTER ) 3);
      result__O1E=(void *)((unsigned long)result__YAB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
    } else {
      result__O1E=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__3JG(new_size__I1E))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
    };
    Result__RQL=((__STACK *)result__O1E);
    v__GAP=((__STACK )(STACK__));
    Self__VNP= 502;
    while ((Self__VNP >=  0)) {
      Result__RQL[Self__VNP]=v__GAP;
      Self__VNP=(__INTEGER)(Self__VNP -  1);
    };
    Self__3YH->parent_arrayed_collection__AC.storage__WUH=Result__RQL;
    Self__3YH->parent_arrayed_collection__AC.capacity__HZH= 503;
    __tmp__RZH=TRUE__;
  } else {
    __tmp__RZH=FALSE__;
  };
  if ((! __tmp__RZH)) {
    if (((Self__3YH->parent_arrayed_collection__AC.capacity__HZH >  0) && (Self__3YH->parent_arrayed_collection__AC.upper__3ZH >=  0))) {
      __tmp__J0H=Self__3YH->parent_arrayed_collection__AC.storage__WUH;
      __tmp__K0H=Self__3YH->parent_arrayed_collection__AC.upper__3ZH;
      Self__SJR=((__STACK *)__tmp__J0H);
      v__DKR=((__STACK )(STACK__));
      Self__OES= 0;
      while ((Self__OES <= __tmp__K0H)) {
        Self__SJR[Self__OES]=v__DKR;
        Self__OES=(__INTEGER)(Self__OES +  1);
      };
    };
  };
  Self__3YH->parent_arrayed_collection__AC.upper__3ZH= 502;
  Self__0TO=((__STRING *)((void **)((__FAST_ARRAYoSTRINGo *)result__1P)->parent_arrayed_collection__0D.storage__KDC)[ 1]);
  state__3TO= 0;
  cc__4TO='\0';
  negative__5TO=FALSE__;
  result__AUO= 0;
  i__2TO= 1;
  __tmp__NVZ=Self__0TO->count__EVH;
  __tmp__OVZ=Self__0TO->storage__FYH;
  __tmp__PVZ=Self__0TO->count__EVH;
  while ((i__2TO <= __tmp__NVZ)) {
    cc__4TO=((__CHARACTER *)__tmp__OVZ)[(__INTEGER)(i__2TO -  1)];
    if ((state__3TO ==  0)) {
      if ((((((((cc__4TO == ' ') || (cc__4TO == '\t')) || (cc__4TO == '\n')) || (cc__4TO == '\r')) || (cc__4TO == '\0')) || (cc__4TO == '\f')) || (cc__4TO == '\v'))) {
        __tmp__MVO=TRUE__;
      } else {
        result__AIW=(cc__4TO == '+');
        if (result__AIW) {
          state__3TO= 1;
        };
        __tmp__MVO=result__AIW;
      };
      if ((! __tmp__MVO)) {
        if ((cc__4TO == '-')) {
          negative__5TO=TRUE__;
          state__3TO= 1;
        } else {
          result__AUO=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__4TO)) -  48);
          state__3TO= 2;
        };
      };
      __tmp__5VO=TRUE__;
    } else {
      __tmp__5VO=FALSE__;
    };
    if (__tmp__5VO) {
      __tmp__UWO=TRUE__;
    } else {
      result__UOU=(state__3TO ==  1);
      if (result__UOU) {
        result__AUO=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__4TO)) -  48);
        if (negative__5TO) {
          result__AUO=(__INTEGER)(- result__AUO);
        };
        state__3TO= 2;
      };
      __tmp__UWO=result__UOU;
    };
    if (__tmp__UWO) {
      __tmp__1XO=TRUE__;
    } else {
      result__GPU=(state__3TO ==  2);
      if (result__GPU) {
        result__YOO=FALSE__;
        if ((((__INTEGER_8 )cc__4TO) >= ((__INTEGER_8 )'0'))) {
          result__YOO=(((__INTEGER_8 )cc__4TO) <= ((__INTEGER_8 )'9'));
        };
        if (result__YOO) {
          if (negative__5TO) {
            result__AUO=(__INTEGER)((__INTEGER)( 10 * result__AUO) - (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__4TO)) -  48));
          } else {
            result__AUO=(__INTEGER)((__INTEGER)( 10 * result__AUO) + (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__4TO)) -  48));
          };
        } else {
          state__3TO= 3;
        };
      };
      __tmp__1XO=result__GPU;
    };
    if ((! __tmp__1XO)) {
      if ((state__3TO ==  3)) {
        i__2TO=__tmp__PVZ;
      };
    };
    i__2TO=(__INTEGER)(i__2TO +  1);
  };
  ((__INTEGER *)((__FAST_ARRAYoExpanded_INTEGERo *)result__JJ)->parent_arrayed_collection__4.storage__QBC)[ 0]=result__AUO;
  pthread_attr_init(&stack_attr);
  Self__JE= 0;
  __tmp__QVZ=((__FAST_ARRAYoExpanded_MUTEXo *)result__EM)->parent_arrayed_collection__VB.storage__RCC;
  __tmp__RVZ=((__FAST_ARRAYoExpanded_MUTEXo *)result__EM)->parent_arrayed_collection__VB.storage__RCC;
  __tmp__SVZ=((__FAST_ARRAYoExpanded_STACKo *)result__YXE)->parent_arrayed_collection__AC.storage__WUH;
  while ((Self__JE <=  502)) {
    pthread_mutex_init(&(((__MUTEX *)__tmp__QVZ)[Self__JE]), NULL);
    pthread_mutex_lock(&(((__MUTEX *)__tmp__RVZ)[Self__JE]));
    pthread_attr_setstack(&stack_attr, &(((__STACK *)__tmp__SVZ)[Self__JE]), sizeof(struct stack));
    pthread_create(&(THREAD__), &stack_attr, thread, (void*)(Self__JE));
    Self__JE=(__INTEGER)(Self__JE +  1);
  };
  pthread_mutex_unlock(&(((__MUTEX *)((__FAST_ARRAYoExpanded_MUTEXo *)result__EM)->parent_arrayed_collection__VB.storage__RCC)[ 0]));
  pthread_join((THREAD__), NULL);
  exit(( 0));
  thread(((__POINTER ) 0));
  thread(((__POINTER ) 1));
  return( 0);
}

static __POINTER new_lab__IQB(__UINTEGER_32 t__KQB)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 idx__MQB,pv__TQB;
  __MEMORY *blc__PQB,*prev__QQB,*Self__EZY,*Self__OMZ,*prev__PMZ;
  __MEMORY *next__QMZ;
  __POINTER result__RQB;
  __BOOLEAN __tmp__TRB;
  idx__MQB= 0;
  blc__PQB=NULL;
  prev__QQB=NULL;
  pv__TQB= 0;
  while_do__MVB:
  {
    if ((idx__MQB < nb_page__0QB)) {
      blc__PQB=((__MEMORY *)(last_block[(idx__MQB)]));
      __tmp__TRB=(((__UINTEGER_32)(((__MEMORY *)blc__PQB)->size_and_id__IK &  4294967292LU) <  4096) || ((__UINTEGER_32)(((__MEMORY *)blc__PQB)->size_and_id__IK &  1) ==  1));
    } else {
      __tmp__TRB=FALSE__;
    };
    if (__tmp__TRB) {
      idx__MQB=(__UINTEGER_32)(idx__MQB +  1);
      goto while_do__MVB;
    };
  };
  if ((idx__MQB >= nb_page__0QB)) {
    blc__PQB=new_page__PQD();
  };
  ((__MEMORY *)blc__PQB)->size_and_id__IK=(__UINTEGER_32)(blc__PQB->size_and_id__IK -  4096);
  Self__EZY=((__MEMORY *)blc__PQB);
  result__RQB=((__POINTER )((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__EZY) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__EZY->size_and_id__IK &  4294967292LU))))));
  if (((__UINTEGER_32)(((__MEMORY *)blc__PQB)->size_and_id__IK &  4294967292LU) < ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    Self__OMZ=((__MEMORY *)blc__PQB);
    prev__PMZ=Self__OMZ->previous_free__KK;
    next__QMZ=Self__OMZ->next_free__JK;
    if (((void *)prev__PMZ == (void *)NULL)) {
      first_free__ALG=next__QMZ;
    } else {
      ((__MEMORY *)prev__PMZ)->next_free__JK=next__QMZ;
    };
    if (((void *)next__QMZ != (void *)NULL)) {
      ((__MEMORY *)next__QMZ)->previous_free__KK=prev__PMZ;
    };
    pv__TQB=blc__PQB->previous_linear__HK;
    if ((pv__TQB !=  4294967295LU)) {
      prev__QQB=((__MEMORY *)(void *)((unsigned long)begin_memory__PCB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )pv__TQB))));
      ((__MEMORY *)prev__QQB)->size_and_id__IK=(__UINTEGER_32)((__UINTEGER_32)(prev__QQB->size_and_id__IK + blc__PQB->size_and_id__IK) +  8);
      last_block[(idx__MQB)] = (prev__QQB);
    };
  };
  ((__POINTER *)result__RQB)[ 0]=((__POINTER )t__KQB);
  return((void *)((unsigned long)result__RQB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))))));
}

static __MEMORY* search__3JG(__UINTEGER_32 new_size__5JG)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *result__BKG,*Self__HYZ,*new__GYZ,*prev__IYZ,*next__JYZ;
  __MEMORY *Self__NYZ,*Self__PYZ;
  __UINTEGER_32 idx__OYZ,siz__KYZ,new_size__MYZ;
  result__BKG=first_free__ALG;
  while ((((void *)result__BKG != (void *)NULL) && ((__UINTEGER_32)(((__MEMORY *)result__BKG)->size_and_id__IK &  4294967292LU) < new_size__5JG))) {
    result__BKG=result__BKG->next_free__JK;
  };
  if (((void *)result__BKG == (void *)NULL)) {
    result__BKG=new_page__PQD();
  };
  Self__HYZ=((__MEMORY *)result__BKG);
  idx__OYZ=(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)result__BKG)) - (unsigned long)begin_memory__PCB)))) >>  26);
  new__GYZ=NULL;
  prev__IYZ=Self__HYZ->previous_free__KK;
  next__JYZ=Self__HYZ->next_free__JK;
  if (((void *)prev__IYZ == (void *)NULL)) {
    first_free__ALG=next__JYZ;
  } else {
    ((__MEMORY *)prev__IYZ)->next_free__JK=next__JYZ;
  };
  if (((void *)next__JYZ != (void *)NULL)) {
    ((__MEMORY *)next__JYZ)->previous_free__KK=prev__IYZ;
  };
  siz__KYZ=Self__HYZ->size_and_id__IK;
  new_size__MYZ=(__UINTEGER_32)(siz__KYZ - new_size__5JG);
  if ((new_size__MYZ > (__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )(MINIMUM_SIZE)) +  2) +  8))) {
    siz__KYZ=new_size__5JG;
    new__GYZ=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__HYZ) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__5JG))));
    ((__MEMORY *)new__GYZ)->previous_linear__HK=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__HYZ) - (unsigned long)begin_memory__PCB))));
    ((__MEMORY *)new__GYZ)->size_and_id__IK=(__UINTEGER_32)(new_size__MYZ -  8);
    Self__NYZ=((__MEMORY *)new__GYZ);
    Self__NYZ->next_free__JK=first_free__ALG;
    Self__NYZ->previous_free__KK=NULL;
    if (((void *)first_free__ALG != (void *)NULL)) {
      ((__MEMORY *)first_free__ALG)->previous_free__KK=Self__NYZ;
    };
    first_free__ALG=Self__NYZ;
    if (((__UINTEGER_32)(((__MEMORY *)new__GYZ)->size_and_id__IK &  2) !=  0)) {
      last_block[(idx__OYZ)] = (new__GYZ);
    } else {
      Self__PYZ=((__MEMORY *)new__GYZ);
      ((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__PYZ) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__PYZ->size_and_id__IK &  4294967292LU)))))->previous_linear__HK=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)new__GYZ)) - (unsigned long)begin_memory__PCB))));
    };
  };
  Self__HYZ->size_and_id__IK=(__UINTEGER_32)(siz__KYZ |  1);
  return(result__BKG);
}

static void** create__4QG(__INTEGER nb_elements__ARG)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__WKZ,a__SOZ,new_size__XKZ,new_size2__YKZ,a__XOZ;
  __UINTEGER_32 new_size__YOZ;
  __POINTER result__VKZ,ptr_table__UVZ,next__TVZ,result__VVZ;
  __INTEGER Self__WGJ;
  void **Result__E3G;
  sz__WKZ=((__UINTEGER_32 )(__INTEGER)(nb_elements__ARG * ((__INTEGER )(sizeof(void *)))));
  result__VKZ=((__POINTER )(NULL));
  a__SOZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__XKZ=(__UINTEGER_32)((__UINTEGER_32)(sz__WKZ + a__SOZ) & (__UINTEGER_32)(~ a__SOZ));
  new_size2__YKZ=(__UINTEGER_32)(new_size__XKZ + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__YKZ <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__XOZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__YOZ=(__UINTEGER_32)((__UINTEGER_32)(new_size2__YKZ + a__XOZ) & (__UINTEGER_32)(~ a__XOZ));
    ptr_table__UVZ=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__YOZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
    next__TVZ=((__POINTER )(NULL));
    result__VVZ=((__POINTER *)ptr_table__UVZ)[ 0];
    if ((result__VVZ == (void *)NULL)) {
      result__VVZ=new_lab__IQB(new_size__YOZ);
      next__TVZ=(void *)((unsigned long)result__VVZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__YOZ)));
      ((__POINTER *)next__TVZ)[ 0]=NULL;
      ((__POINTER *)ptr_table__UVZ)[ 0]=next__TVZ;
    } else {
      next__TVZ=((__POINTER *)result__VVZ)[ 0];
      if ((next__TVZ == (void *)NULL)) {
        if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__VVZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__YOZ <<  1)) <=  4096)) {
          next__TVZ=(void *)((unsigned long)result__VVZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__YOZ)));
        } else {
          next__TVZ=new_lab__IQB(new_size__YOZ);
        };
        ((__POINTER *)next__TVZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__UVZ)[ 0]=next__TVZ;
      } else {
        ((__POINTER *)result__VVZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__TVZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
        result__VVZ=next__TVZ;
      };
    };
    ((__POINTER *)result__VVZ)[ 0]=((__POINTER ) 3);
    result__VKZ=(void *)((unsigned long)result__VVZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__VKZ=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__3JG(new_size__XKZ))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__E3G=((void **)result__VKZ);
  Self__WGJ=(__INTEGER)(nb_elements__ARG -  1);
  while ((Self__WGJ >=  0)) {
    Result__E3G[Self__WGJ]=NULL;
    Self__WGJ=(__INTEGER)(Self__WGJ -  1);
  };
  return(Result__E3G);
}

static __CHARACTER* create__MKM(__INTEGER nb_elements__OKM)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__0KZ,a__APZ,new_size__1KZ,new_size2__2KZ,a__FPZ;
  __UINTEGER_32 new_size__GPZ;
  __POINTER result__ZKZ,ptr_table__ZVZ,next__YVZ,result__0VZ;
  __INTEGER Self__XQP;
  __CHARACTER *Result__A5M;
  sz__0KZ=((__UINTEGER_32 )nb_elements__OKM);
  result__ZKZ=((__POINTER )(NULL));
  a__APZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__1KZ=(__UINTEGER_32)((__UINTEGER_32)(sz__0KZ + a__APZ) & (__UINTEGER_32)(~ a__APZ));
  new_size2__2KZ=(__UINTEGER_32)(new_size__1KZ + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__2KZ <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__FPZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__GPZ=(__UINTEGER_32)((__UINTEGER_32)(new_size2__2KZ + a__FPZ) & (__UINTEGER_32)(~ a__FPZ));
    ptr_table__ZVZ=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__GPZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
    next__YVZ=((__POINTER )(NULL));
    result__0VZ=((__POINTER *)ptr_table__ZVZ)[ 0];
    if ((result__0VZ == (void *)NULL)) {
      result__0VZ=new_lab__IQB(new_size__GPZ);
      next__YVZ=(void *)((unsigned long)result__0VZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__GPZ)));
      ((__POINTER *)next__YVZ)[ 0]=NULL;
      ((__POINTER *)ptr_table__ZVZ)[ 0]=next__YVZ;
    } else {
      next__YVZ=((__POINTER *)result__0VZ)[ 0];
      if ((next__YVZ == (void *)NULL)) {
        if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__0VZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__GPZ <<  1)) <=  4096)) {
          next__YVZ=(void *)((unsigned long)result__0VZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__GPZ)));
        } else {
          next__YVZ=new_lab__IQB(new_size__GPZ);
        };
        ((__POINTER *)next__YVZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__ZVZ)[ 0]=next__YVZ;
      } else {
        ((__POINTER *)result__0VZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__YVZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
        result__0VZ=next__YVZ;
      };
    };
    ((__POINTER *)result__0VZ)[ 0]=((__POINTER ) 3);
    result__ZKZ=(void *)((unsigned long)result__0VZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__ZKZ=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__3JG(new_size__1KZ))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__A5M=((__CHARACTER *)result__ZKZ);
  Self__XQP=(__INTEGER)(nb_elements__OKM -  1);
  while ((Self__XQP >=  0)) {
    Result__A5M[Self__XQP]='\0';
    Self__XQP=(__INTEGER)(Self__XQP -  1);
  };
  return(Result__A5M);
}

static __POINTER realloc_dynamic__old_size__new_size__Y4I(__POINTER p__04I,__UINTEGER_32 old_sz__14I,__UINTEGER_32 new_sz__24I)
// ({POINTER},{UINTEGER_32},{UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *mem__H5I,*Self__5YL,*nxt__DZL,*result__EZL,*Self__YCI;
  __MEMORY *new__BDI,*prev__QDJ,*next__RDJ,*Self__YVH,*Self__OVY;
  __MEMORY *next__U2N,*new_free__T2N,*prev__SQZ,*next__TQZ;
  __POINTER result__I5I,result__3KZ,ptr_table__4VZ,next__3VZ;
  __POINTER result__5VZ,p__VXL,last__EUM,src__PWL,dst__QWL;
  __UINTEGER_32 a__OPZ,old_size__44I,old_size2__B5I,a__SPZ;
  __UINTEGER_32 new_size__E5I,a__WPZ,new_size__5KZ,new_size2__ALZ;
  __UINTEGER_32 a__1PZ,new_size__2PZ,a__S4,__tmp__ZAJ,sz__IZL;
  __UINTEGER_32 old_size__FZL,siz__1CI,new_size__4CI,prev__V2N;
  __UINTEGER_32 new_size__Y2N;
  __INTEGER siz__5XZ,Self__EYZ,siz__UWL,Self__XRM;
  __POINTER *na_src__BYZ,*na_dst__DYZ,*na_src__SWL,*na_dst__TWL;
  mem__H5I=NULL;
  result__I5I=((__POINTER )(NULL));
  a__OPZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  old_size__44I=(__UINTEGER_32)((__UINTEGER_32)(old_sz__14I + a__OPZ) & (__UINTEGER_32)(~ a__OPZ));
  old_size2__B5I=(__UINTEGER_32)(old_size__44I + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  a__SPZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__E5I=(__UINTEGER_32)((__UINTEGER_32)(new_sz__24I + a__SPZ) & (__UINTEGER_32)(~ a__SPZ));
  if ((old_size2__B5I <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    result__3KZ=((__POINTER )(NULL));
    a__WPZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__5KZ=(__UINTEGER_32)((__UINTEGER_32)(new_size__E5I + a__WPZ) & (__UINTEGER_32)(~ a__WPZ));
    new_size2__ALZ=(__UINTEGER_32)(new_size__5KZ + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
    if ((new_size2__ALZ <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
      a__1PZ=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__2PZ=(__UINTEGER_32)((__UINTEGER_32)(new_size2__ALZ + a__1PZ) & (__UINTEGER_32)(~ a__1PZ));
      ptr_table__4VZ=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__2PZ / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__3VZ=((__POINTER )(NULL));
      result__5VZ=((__POINTER *)ptr_table__4VZ)[ 0];
      if ((result__5VZ == (void *)NULL)) {
        result__5VZ=new_lab__IQB(new_size__2PZ);
        next__3VZ=(void *)((unsigned long)result__5VZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__2PZ)));
        ((__POINTER *)next__3VZ)[ 0]=NULL;
        ((__POINTER *)ptr_table__4VZ)[ 0]=next__3VZ;
      } else {
        next__3VZ=((__POINTER *)result__5VZ)[ 0];
        if ((next__3VZ == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__5VZ - (unsigned long)begin_memory__PCB)))) &  4095) + (__UINTEGER_32)(new_size__2PZ <<  1)) <=  4096)) {
            next__3VZ=(void *)((unsigned long)result__5VZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__2PZ)));
          } else {
            next__3VZ=new_lab__IQB(new_size__2PZ);
          };
          ((__POINTER *)next__3VZ)[ 0]=NULL;
          ((__POINTER *)ptr_table__4VZ)[ 0]=next__3VZ;
        } else {
          ((__POINTER *)result__5VZ)[ 0]=(void *)((unsigned long)((__POINTER *)next__3VZ)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__5VZ=next__3VZ;
        };
      };
      ((__POINTER *)result__5VZ)[ 0]=((__POINTER ) 3);
      result__3KZ=(void *)((unsigned long)result__5VZ - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
    } else {
      result__3KZ=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__3JG(new_size__5KZ))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
    };
    result__I5I=result__3KZ;
    siz__5XZ=((__INTEGER )old_size__44I);
    siz__5XZ=(__INTEGER)(siz__5XZ / ((__INTEGER )(sizeof(void *))));
    na_src__BYZ=((__POINTER *)p__04I);
    na_dst__DYZ=((__POINTER *)result__3KZ);
    Self__EYZ=(__INTEGER)(siz__5XZ -  1);
    while ((Self__EYZ >=  0)) {
      na_dst__DYZ[Self__EYZ]=na_src__BYZ[Self__EYZ];
      Self__EYZ=(__INTEGER)(Self__EYZ -  1);
    };
    p__VXL=(void *)((unsigned long)p__04I - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))));
    a__S4=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    last__EUM=((__POINTER *)((__POINTER )(&(table_size[((__UINTEGER_32)((__UINTEGER_32)((__UINTEGER_32)(old_size2__B5I + a__S4) & (__UINTEGER_32)(~ a__S4)) / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))))[ 0];
    ((__POINTER *)p__VXL)[ 0]=(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)(void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER *)last__EUM)[ 0]) - (unsigned long)((__POINTER ) 1)) & (unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 3)) - (unsigned long)((__POINTER ) 1)))) - (unsigned long)((__POINTER ) 1));
    ((__POINTER *)last__EUM)[ 0]=p__VXL;
  } else {
    mem__H5I=((__MEMORY *)(void *)((unsigned long)p__04I - (unsigned long)((__POINTER ) 8)));
    __tmp__ZAJ=(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)p__04I - (unsigned long)begin_memory__PCB)))) >>  26);
    Self__5YL=((__MEMORY *)mem__H5I);
    nxt__DZL=NULL;
    result__EZL=NULL;
    sz__IZL= 0;
    old_size__FZL=(__UINTEGER_32)(Self__5YL->size_and_id__IK &  4294967292LU);
    if ((new_size__E5I > old_size__FZL)) {
      if ((! ((__UINTEGER_32)(Self__5YL->size_and_id__IK &  2) !=  0))) {
        nxt__DZL=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__5YL) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__5YL->size_and_id__IK &  4294967292LU)))));
        sz__IZL=(__UINTEGER_32)((__UINTEGER_32)(new_size__E5I - old_size__FZL) -  8);
        if ((((__UINTEGER_32)(((__MEMORY *)nxt__DZL)->size_and_id__IK &  1) ==  0) && ((__UINTEGER_32)(((__MEMORY *)nxt__DZL)->size_and_id__IK &  4294967292LU) >= sz__IZL))) {
          Self__YCI=((__MEMORY *)nxt__DZL);
          new__BDI=NULL;
          prev__QDJ=Self__YCI->previous_free__KK;
          next__RDJ=Self__YCI->next_free__JK;
          if (((void *)prev__QDJ == (void *)NULL)) {
            first_free__ALG=next__RDJ;
          } else {
            ((__MEMORY *)prev__QDJ)->next_free__JK=next__RDJ;
          };
          if (((void *)next__RDJ != (void *)NULL)) {
            ((__MEMORY *)next__RDJ)->previous_free__KK=prev__QDJ;
          };
          siz__1CI=Self__YCI->size_and_id__IK;
          new_size__4CI=(__UINTEGER_32)(siz__1CI - sz__IZL);
          if ((new_size__4CI > (__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )(MINIMUM_SIZE)) +  2) +  8))) {
            siz__1CI=sz__IZL;
            new__BDI=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__YCI) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )sz__IZL))));
            ((__MEMORY *)new__BDI)->previous_linear__HK=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__YCI) - (unsigned long)begin_memory__PCB))));
            ((__MEMORY *)new__BDI)->size_and_id__IK=(__UINTEGER_32)(new_size__4CI -  8);
            Self__YVH=((__MEMORY *)new__BDI);
            Self__YVH->next_free__JK=first_free__ALG;
            Self__YVH->previous_free__KK=NULL;
            if (((void *)first_free__ALG != (void *)NULL)) {
              ((__MEMORY *)first_free__ALG)->previous_free__KK=Self__YVH;
            };
            first_free__ALG=Self__YVH;
            if (((__UINTEGER_32)(((__MEMORY *)new__BDI)->size_and_id__IK &  2) !=  0)) {
              last_block[(__tmp__ZAJ)] = (new__BDI);
            } else {
              Self__OVY=((__MEMORY *)new__BDI);
              ((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__OVY) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__OVY->size_and_id__IK &  4294967292LU)))))->previous_linear__HK=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)new__BDI)) - (unsigned long)begin_memory__PCB))));
            };
          };
          Self__YCI->size_and_id__IK=(__UINTEGER_32)(siz__1CI |  1);
          Self__5YL->size_and_id__IK=(__UINTEGER_32)((__UINTEGER_32)(Self__5YL->size_and_id__IK + (__UINTEGER_32)(nxt__DZL->size_and_id__IK &  4294967294LU)) +  8);
          if (((__UINTEGER_32)(Self__5YL->size_and_id__IK &  2) !=  0)) {
            last_block[(__tmp__ZAJ)] = (Self__5YL);
          } else {
            nxt__DZL=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__5YL) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__5YL->size_and_id__IK &  4294967292LU)))));
            ((__MEMORY *)nxt__DZL)->previous_linear__HK=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__5YL) - (unsigned long)begin_memory__PCB))));
          };
          result__EZL=Self__5YL;
        };
      };
      if (((void *)result__EZL == (void *)NULL)) {
        result__EZL=search__3JG(new_size__E5I);
        src__PWL=(void *)((unsigned long)((__POINTER )Self__5YL) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
        dst__QWL=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__EZL)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
        siz__UWL=((__INTEGER )old_size__FZL);
        siz__UWL=(__INTEGER)(siz__UWL / ((__INTEGER )(sizeof(void *))));
        na_src__SWL=((__POINTER *)src__PWL);
        na_dst__TWL=((__POINTER *)dst__QWL);
        Self__XRM=(__INTEGER)(siz__UWL -  1);
        while ((Self__XRM >=  0)) {
          na_dst__TWL[Self__XRM]=na_src__SWL[Self__XRM];
          Self__XRM=(__INTEGER)(Self__XRM -  1);
        };
        prev__V2N=Self__5YL->previous_linear__HK;
        next__U2N=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__5YL) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__5YL->size_and_id__IK &  4294967292LU)))));
        new_free__T2N=((__MEMORY *)(void *)((unsigned long)begin_memory__PCB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )prev__V2N))));
        new_size__Y2N=(__UINTEGER_32)(Self__5YL->size_and_id__IK &  4294967294LU);
        if (((prev__V2N ==  4294967295LU) || ((__UINTEGER_32)(new_free__T2N->size_and_id__IK &  1) !=  0))) {
          new_free__T2N=Self__5YL;
          Self__5YL->next_free__JK=first_free__ALG;
          Self__5YL->previous_free__KK=NULL;
          if (((void *)first_free__ALG != (void *)NULL)) {
            ((__MEMORY *)first_free__ALG)->previous_free__KK=Self__5YL;
          };
          first_free__ALG=Self__5YL;
        } else {
          new_size__Y2N=(__UINTEGER_32)((__UINTEGER_32)(new_size__Y2N + new_free__T2N->size_and_id__IK) +  8);
        };
        if (((! ((__UINTEGER_32)(Self__5YL->size_and_id__IK &  2) !=  0)) && ((__UINTEGER_32)(next__U2N->size_and_id__IK &  1) ==  0))) {
          new_size__Y2N=(__UINTEGER_32)((__UINTEGER_32)(new_size__Y2N + next__U2N->size_and_id__IK) +  8);
          prev__SQZ=next__U2N->previous_free__KK;
          next__TQZ=next__U2N->next_free__JK;
          if (((void *)prev__SQZ == (void *)NULL)) {
            first_free__ALG=next__TQZ;
          } else {
            ((__MEMORY *)prev__SQZ)->next_free__JK=next__TQZ;
          };
          if (((void *)next__TQZ != (void *)NULL)) {
            ((__MEMORY *)next__TQZ)->previous_free__KK=prev__SQZ;
          };
        };
        new_free__T2N->size_and_id__IK=new_size__Y2N;
        if (((__UINTEGER_32)(new_free__T2N->size_and_id__IK &  2) !=  0)) {
          last_block[(__tmp__ZAJ)] = (new_free__T2N);
        } else {
          next__U2N=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__5YL) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__5YL->size_and_id__IK &  4294967292LU)))));
          next__U2N->previous_linear__HK=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )new_free__T2N) - (unsigned long)begin_memory__PCB))));
        };
      };
    } else {
      result__EZL=Self__5YL;
    };
    result__I5I=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__EZL)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  return(result__I5I);
}

__POINTER thread(__POINTER num__HF)
// ({POINTER}) With resultNo recursive, No inlinable.
{
  __INTEGER token__LF,l__JF,r__KF,Self__B2;
  __BOOLEAN __tmp__I2;
  token__LF= 0;
  l__JF=((__INTEGER )num__HF);
  r__KF=(__INTEGER)((__INTEGER)(l__JF +  1) %  503);
  while (((__BOOLEAN )((1)))) {
    pthread_mutex_lock(&(((__MUTEX *)((__FAST_ARRAYoExpanded_MUTEXo *)mutex__WB)->parent_arrayed_collection__VB.storage__RCC)[l__JF]));
    token__LF=((__INTEGER *)((__FAST_ARRAYoExpanded_INTEGERo *)data__5)->parent_arrayed_collection__4.storage__QBC)[l__JF];
    if ((token__LF !=  0)) {
      ((__INTEGER *)((__FAST_ARRAYoExpanded_INTEGERo *)data__5)->parent_arrayed_collection__4.storage__QBC)[r__KF]=(__INTEGER)(token__LF -  1);
      pthread_mutex_unlock(&(((__MUTEX *)((__FAST_ARRAYoExpanded_MUTEXo *)mutex__WB)->parent_arrayed_collection__VB.storage__RCC)[r__KF]));
    } else {
      Self__B2=(__INTEGER)(l__JF +  1);
      if ((Self__B2 ==  0)) {
        fputc((int)('0'),stdout);
        __tmp__I2=TRUE__;
      } else {
        __tmp__I2=FALSE__;
      };
      if ((! __tmp__I2)) {
        if ((Self__B2 <  0)) {
          fputc((int)('-'),stdout);
          print_positif__CMK((__INTEGER)(- Self__B2));
        } else {
          print_positif__CMK(Self__B2);
        };
      };
      fputc((int)('\n'),stdout);
      exit(( 0));
    };
  };
  return(NULL);
}

static __MEMORY* new_page__PQD()
// () With resultNo recursive, No inlinable.
{
  __POINTER mem__JLF;
  __UINTEGER_32 cap__GLF,old_size__SQD;
  __INTEGER Self__2FG,limit_up__3FG;
  __MEMORY *block__YQD;
  __CHARACTER *__tmp__1RZ;
  if ((capacity_max__ZQD ==  0)) {
    mem__JLF=((__POINTER )(NULL));
    cap__GLF= 33554432;
    do {
      cap__GLF=(__UINTEGER_32)(cap__GLF <<  1);
      mem__JLF=((__POINTER )(malloc((cap__GLF))));
      if ((mem__JLF != (void *)NULL)) {
        free((mem__JLF));
      };
    } while ((! ((mem__JLF == (void *)NULL) || (cap__GLF ==  2147483648LU))));
    if ((mem__JLF == (void *)NULL)) {
      cap__GLF=(__UINTEGER_32)(cap__GLF >>  1);
    };
    capacity_max__ZQD=cap__GLF;
    begin_memory__PCB=((__POINTER )(malloc((cap__GLF))));
  };
  old_size__SQD=(__UINTEGER_32)(nb_page__0QB <<  26);
  nb_page__0QB=(__UINTEGER_32)(nb_page__0QB +  1);
  if (((__UINTEGER_32)(old_size__SQD +  67108864) > capacity_max__ZQD)) {
    Self__2FG= 1;
    limit_up__3FG=((__STRING_CONSTANT *)(&__string_1))->count__XFG;
    __tmp__1RZ=((__STRING_CONSTANT *)(&__string_1))->storage__GMH;
    while ((Self__2FG <= limit_up__3FG)) {
      fputc((int)(((__CHARACTER *)__tmp__1RZ)[(__INTEGER)(Self__2FG -  1)]),stdout);
      Self__2FG=(__INTEGER)(Self__2FG +  1);
    };
    exit(( 1));
  };
  block__YQD=((__MEMORY *)(void *)((unsigned long)begin_memory__PCB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )old_size__SQD))));
  block__YQD->previous_linear__HK= 4294967295LU;
  block__YQD->size_and_id__IK= 67108858;
  block__YQD->next_free__JK=first_free__ALG;
  block__YQD->previous_free__KK=NULL;
  if (((void *)first_free__ALG != (void *)NULL)) {
    ((__MEMORY *)first_free__ALG)->previous_free__KK=block__YQD;
  };
  first_free__ALG=block__YQD;
  last_block[((__UINTEGER_32)(nb_page__0QB -  1))] = (block__YQD);
  return(block__YQD);
}

static void print_positif__CMK(__INTEGER Self__DMK)
// ({INTEGER}) VoidRecursive, No inlinable.
{
  __INTEGER val__MMK;
  __CHARACTER Result__RGL;
  Result__RGL=((__CHARACTER )(((__INTEGER_8)(((__INTEGER_8 )(__INTEGER)(Self__DMK %  10)) + ((__INTEGER_8 )'0')))));
  val__MMK=(__INTEGER)(Self__DMK /  10);
  if ((val__MMK !=  0)) {
    print_positif__CMK(val__MMK);
  };
  fputc((int)(Result__RGL),stdout);
}

//==========================//
// DEBUG MANAGER            //
//==========================//

void print_string(char *str) 
{ 
  while (*str!=0) {
    print_char(*str); 
    str++; 
  };
}  

