Index: lisaac-0.13.1/Makefile
===================================================================
--- lisaac-0.13.1.orig/Makefile	2008-08-02 09:38:49.000000000 +0200
+++ lisaac-0.13.1/Makefile	2008-08-02 09:39:53.000000000 +0200
@@ -54,12 +54,13 @@
 #  bug tracker system: https://gna.org/bugs/?func=additem&group=isaac
 #  mail to: Xavier Oswald <x.oswald@free.fr>
 
-LIB=/usr/lib/lisaac
+LIB=/usr/share/lisaac
 EXAMPLE=/examples
 HTML=/html
 BIN=/usr/bin
 MAN=/usr/share/man/man1
-DOC=/usr/share/doc/lisaac
+DOC=/usr/share/doc/lisaac-doc
+EMACS=/usr/share/emacs/site-lisp/lisaac-mode
 DESTDIR=
 CC=gcc
 CFLAGS=-O2
@@ -81,23 +82,21 @@
 	mkdir -p $(DESTDIR)$(MAN)
 	mkdir -p $(DESTDIR)$(DOC)$(HTML)
 	mkdir -p $(DESTDIR)$(DOC)$(EXAMPLE)
+	mkdir -p $(DESTDIR)$(EMACS)
 	cp bin/lisaac  $(DESTDIR)$(BIN) 
 	cp bin/shorter  $(DESTDIR)$(BIN)
 	cp path.li  $(DESTDIR)$(LIB)
 	cp -rf lib/  $(DESTDIR)$(LIB)
 	cp -rf lib_os/  $(DESTDIR)$(LIB)
+	cp -rf lib_html/* $(DESTDIR)$(DOC)$(HTML)
 	cp -rf example/* $(DESTDIR)$(DOC)$(EXAMPLE)
+	rm -rf $(DESTDIR)$(DOC)$(EXAMPLE)/shootout
 	cp -rf shorter/  $(DESTDIR)$(LIB)
 	cp -rf manpage/*.gz  $(DESTDIR)$(MAN)
+	cp -f editor/emacs/lisaac-mode.el $(DESTDIR)$(EMACS)
 	#$(DESTDIR)$(BIN)/shorter -r -f html lib -o $(DESTDIR)$(DOC)$(HTML) 
 
 clean:
 	rm -rf bin/lisaac
 	rm -rf bin/shorter
 	rm -rf bin/path.h
-	rm -rf $(DESTDIR)$(BIN)/lisaac
-	rm -rf $(DESTDIR)$(BIN)/shorter
-	rm -rf $(DESTDIR)$(LIB)
-	rm -rf $(DESTDIR)$(DOC)
-	rm -rf $(DESTDIR)$(MAN)/lisaac.1.gz
-	rm -rf $(DESTDIR)$(MAN)/shorter.1.gz
