// C code generated by Lisaac compiler (www.isaacOS.com) //
int arg_count;
char **arg_vector;

//==========================//
// EXTERNAL                 //
//==========================//

// MEMORY

#define MINIMUM_SIZE 256  
void *table_size[MINIMUM_SIZE/sizeof(void *)];
void *last_block[64];

// FLOAT_REAL
#include <math.h>
// SYSTEM
#include <time.h>
// SYSTEM_IO

#include <stdio.h>
#include <stdlib.h>
  
// Hardware 'print_char'
void print_char(char car)
{
  fputc(car,stdout);
}

// Hardware 'exit'
int die_with_code(int code)
{
  exit(code);
}



//==========================//
// TYPE                     //
//==========================//

// Generic Object
struct ___OBJ {
  unsigned long __id;
};

// NULL
#ifndef NULL
#define NULL ((void *)0)
#endif

// POINTER
typedef void * __POINTER;

// UINTEGER_32
typedef unsigned long __UINTEGER_32;

// CHARACTER
typedef char __CHARACTER;

// INTEGER
typedef int __INTEGER;

// INODE
#define __INODE__ 0
typedef struct INODE_struct __INODE;
struct INODE_struct {
  void *parent_guii__0;
  void *name__B2B;
  void *list__Q1B;
  __CHARACTER operator__Q2B;
};
__INODE INODE_;
#define INODE__ (&INODE_)

// MEMORY
#define __MEMORY__ 1
typedef struct MEMORY_struct __MEMORY;
struct MEMORY_struct {
  volatile __UINTEGER_32 previous_linear__4M;
  volatile __UINTEGER_32 size_and_id__5M;
  __MEMORY *next_free__AN;
  __MEMORY *previous_free__BN;
} __attribute__ ((packed));
__MEMORY MEMORY_;
#define MEMORY__ (&MEMORY_)

// STRING_CONSTANT
#define __STRING_CONSTANT__ 4
typedef struct STRING_CONSTANT_struct __STRING_CONSTANT;
struct STRING_CONSTANT_struct {
  unsigned long __id;
  __INTEGER count__MNC;
  __CHARACTER *storage__4PE;
};
__STRING_CONSTANT STRING_CONSTANT_={__STRING_CONSTANT__};
#define STRING_CONSTANT__ (&STRING_CONSTANT_)

// STRING
#define __STRING__ 5
typedef struct STRING_struct __STRING;
struct STRING_struct {
  unsigned long __id;
  __INTEGER capacity__Y0D;
  __INTEGER count__G1D;
  __CHARACTER *storage__B1D;
};
__STRING STRING_={__STRING__};
#define STRING__ (&STRING_)

// NUMERIC
#define __NUMERIC__ 2
typedef struct NUMERIC_struct __NUMERIC;
struct NUMERIC_struct {
  void *Nothing;
};
__NUMERIC NUMERIC_;
#define NUMERIC__ (&NUMERIC_)

// INTERNAL_INODE
#define __INTERNAL_INODE__ 6
typedef struct INTERNAL_INODE_struct __INTERNAL_INODE;
struct INTERNAL_INODE_struct {
  unsigned long __id;
};
__INTERNAL_INODE INTERNAL_INODE_={__INTERNAL_INODE__};
#define INTERNAL_INODE__ (&INTERNAL_INODE_)

// OBJECT
#define __OBJECT__ 3
typedef struct OBJECT_struct __OBJECT;
struct OBJECT_struct {
  void *Nothing;
};
__OBJECT OBJECT_;
#define OBJECT__ (&OBJECT_)

// LINKED_COLLECTION[INODE]
#define __LINKED_COLLECTIONoINODEo__ 4
typedef struct LINKED_COLLECTIONoINODEo_struct __LINKED_COLLECTIONoINODEo;
struct LINKED_COLLECTIONoINODEo_struct {
  __INTEGER upper__L3B;
};
__LINKED_COLLECTIONoINODEo LINKED_COLLECTIONoINODEo_;
#define LINKED_COLLECTIONoINODEo__ (&LINKED_COLLECTIONoINODEo_)

// LINKED_LIST[INODE]
#define __LINKED_LISToINODEo__ 5
typedef struct LINKED_LISToINODEo_struct __LINKED_LISToINODEo;
struct LINKED_LISToINODEo_struct {
  __LINKED_COLLECTIONoINODEo parent_linked_collection__P1B;
  __INTEGER mem_idx__VWD;
  void *first_link__LWD;
  void *last_link__UWD;
  void *mem_lnk__XWD;
};
__LINKED_LISToINODEo LINKED_LISToINODEo_;
#define LINKED_LISToINODEo__ (&LINKED_LISToINODEo_)

// LINKED_LIST_NODE[INODE]
#define __LINKED_LIST_NODEoINODEo__ 6
typedef struct LINKED_LIST_NODEoINODEo_struct __LINKED_LIST_NODEoINODEo;
struct LINKED_LIST_NODEoINODEo_struct {
  void *item__YRE;
  void *next__4MF;
};
__LINKED_LIST_NODEoINODEo LINKED_LIST_NODEoINODEo_;
#define LINKED_LIST_NODEoINODEo__ (&LINKED_LIST_NODEoINODEo_)

// MENU_H
#define __MENU_H__ 7
typedef struct MENU_H_struct __MENU_H;
struct MENU_H_struct {
  unsigned long __id;
};
__MENU_H MENU_H_={__MENU_H__};
#define MENU_H__ (&MENU_H_)

// MENU_V
#define __MENU_V__ 8
typedef struct MENU_V_struct __MENU_V;
struct MENU_V_struct {
  unsigned long __id;
};
__MENU_V MENU_V_={__MENU_V__};
#define MENU_V__ (&MENU_V_)

// FALSE
#define FALSE__ 0

// BOOLEAN
typedef char __BOOLEAN;


void *table_type[7];

//==========================//
// GLOBAL                   //
//==========================//

void *parent_numeric__H;
__POINTER begin_memory__22;
__UINTEGER_32 nb_page__OKB;
__UINTEGER_32 capacity_max__HJC;
__MEMORY *first_free__2YD;
void *base__O2B;
__UINTEGER_32 clone_allocation_size__UM;

//==========================//
// STRING CONSTANT          //
//==========================//

__STRING_CONSTANT __string_1={__STRING_CONSTANT__,5,"Paint"};
__STRING_CONSTANT __string_2={__STRING_CONSTANT__,4,"Menu"};
__STRING_CONSTANT __string_3={__STRING_CONSTANT__,4,"File"};
__STRING_CONSTANT __string_4={__STRING_CONSTANT__,10,"Clear file"};
__STRING_CONSTANT __string_5={__STRING_CONSTANT__,3,"New"};
__STRING_CONSTANT __string_6={__STRING_CONSTANT__,11,"Intern file"};
__STRING_CONSTANT __string_7={__STRING_CONSTANT__,4,"Open"};
__STRING_CONSTANT __string_8={__STRING_CONSTANT__,4,"Save"};
__STRING_CONSTANT __string_9={__STRING_CONSTANT__,7,"Save as"};
__STRING_CONSTANT __string_10={__STRING_CONSTANT__,11,"Extern file"};
__STRING_CONSTANT __string_11={__STRING_CONSTANT__,6,"Import"};
__STRING_CONSTANT __string_12={__STRING_CONSTANT__,6,"Export"};
__STRING_CONSTANT __string_13={__STRING_CONSTANT__,11,"Output file"};
__STRING_CONSTANT __string_14={__STRING_CONSTANT__,5,"Print"};
__STRING_CONSTANT __string_15={__STRING_CONSTANT__,12,"Exit manager"};
__STRING_CONSTANT __string_16={__STRING_CONSTANT__,4,"EXit"};
__STRING_CONSTANT __string_17={__STRING_CONSTANT__,4,"Edit"};
__STRING_CONSTANT __string_18={__STRING_CONSTANT__,7,"History"};
__STRING_CONSTANT __string_19={__STRING_CONSTANT__,4,"Undo"};
__STRING_CONSTANT __string_20={__STRING_CONSTANT__,4,"Redo"};
__STRING_CONSTANT __string_21={__STRING_CONSTANT__,11,"Edit object"};
__STRING_CONSTANT __string_22={__STRING_CONSTANT__,6,"Delete"};
__STRING_CONSTANT __string_23={__STRING_CONSTANT__,9,"Duplicate"};
__STRING_CONSTANT __string_24={__STRING_CONSTANT__,10,"Select all"};
__STRING_CONSTANT __string_25={__STRING_CONSTANT__,12,"Presentation"};
__STRING_CONSTANT __string_26={__STRING_CONSTANT__,14,"Representation"};
__STRING_CONSTANT __string_27={__STRING_CONSTANT__,15,"Magnetic locate"};
__STRING_CONSTANT __string_28={__STRING_CONSTANT__,7,"Contour"};
__STRING_CONSTANT __string_29={__STRING_CONSTANT__,11,"Disposition"};
__STRING_CONSTANT __string_30={__STRING_CONSTANT__,6,"Modify"};
__STRING_CONSTANT __string_31={__STRING_CONSTANT__,11,"Text editor"};
__STRING_CONSTANT __string_32={__STRING_CONSTANT__,9,"Alignment"};
__STRING_CONSTANT __string_33={__STRING_CONSTANT__,8,"To curve"};
__STRING_CONSTANT __string_34={__STRING_CONSTANT__,5,"Order"};
__STRING_CONSTANT __string_35={__STRING_CONSTANT__,10,"First plan"};
__STRING_CONSTANT __string_36={__STRING_CONSTANT__,9,"Last plan"};
__STRING_CONSTANT __string_37={__STRING_CONSTANT__,4,"Link"};
__STRING_CONSTANT __string_38={__STRING_CONSTANT__,5,"Group"};
__STRING_CONSTANT __string_39={__STRING_CONSTANT__,7,"Degroup"};
__STRING_CONSTANT __string_40={__STRING_CONSTANT__,7,"Combine"};
__STRING_CONSTANT __string_41={__STRING_CONSTANT__,9,"Decombine"};
__STRING_CONSTANT __string_42={__STRING_CONSTANT__,12,"Auto-combine"};
__STRING_CONSTANT __string_43={__STRING_CONSTANT__,6,"Window"};
__STRING_CONSTANT __string_44={__STRING_CONSTANT__,7,"Display"};
__STRING_CONSTANT __string_45={__STRING_CONSTANT__,12,"Refresh draw"};
__STRING_CONSTANT __string_46={__STRING_CONSTANT__,4,"Help"};
__STRING_CONSTANT __string_47={__STRING_CONSTANT__,11,"Information"};
__STRING_CONSTANT __string_48={__STRING_CONSTANT__,5,"About"};
__STRING_CONSTANT __string_49={__STRING_CONSTANT__,11,"Bugs report"};
__STRING_CONSTANT __string_50={__STRING_CONSTANT__,4,"News"};
__STRING_CONSTANT __string_51={__STRING_CONSTANT__,5,"Tools"};
__STRING_CONSTANT __string_52={__STRING_CONSTANT__,11,"Tools group"};
__STRING_CONSTANT __string_53={__STRING_CONSTANT__,6,"Select"};
__STRING_CONSTANT __string_54={__STRING_CONSTANT__,4,"Zoom"};
__STRING_CONSTANT __string_55={__STRING_CONSTANT__,10,"Zoom tools"};
__STRING_CONSTANT __string_56={__STRING_CONSTANT__,7,"Zoom in"};
__STRING_CONSTANT __string_57={__STRING_CONSTANT__,8,"Zoom out"};
__STRING_CONSTANT __string_58={__STRING_CONSTANT__,11,"Zoom select"};
__STRING_CONSTANT __string_59={__STRING_CONSTANT__,9,"Zoom page"};
__STRING_CONSTANT __string_60={__STRING_CONSTANT__,8,"Zoom 1:1"};
__STRING_CONSTANT __string_61={__STRING_CONSTANT__,4,"line"};
__STRING_CONSTANT __string_62={__STRING_CONSTANT__,9,"Rectangle"};
__STRING_CONSTANT __string_63={__STRING_CONSTANT__,6,"Circle"};
__STRING_CONSTANT __string_64={__STRING_CONSTANT__,4,"Text"};
__STRING_CONSTANT __string_65={__STRING_CONSTANT__,5,"Color"};
__STRING_CONSTANT __string_66={__STRING_CONSTANT__,4,"Page"};
__STRING_CONSTANT __string_67={__STRING_CONSTANT__,2," ("};
__STRING_CONSTANT __string_68={__STRING_CONSTANT__,4,"None"};
__STRING_CONSTANT __string_69={__STRING_CONSTANT__,6,"MENU_H"};
__STRING_CONSTANT __string_70={__STRING_CONSTANT__,6,"MENU_V"};
__STRING_CONSTANT __string_71={__STRING_CONSTANT__,2,")\n"};
__STRING_CONSTANT __string_72={__STRING_CONSTANT__,6,"(OR )\n"};
__STRING_CONSTANT __string_73={__STRING_CONSTANT__,6,"(AND)\n"};
__STRING_CONSTANT __string_74={__STRING_CONSTANT__,6,"(XOR)\n"};
__STRING_CONSTANT __string_75={__STRING_CONSTANT__,4," | \n"};
__STRING_CONSTANT __string_76={__STRING_CONSTANT__,4," +- "};
__STRING_CONSTANT __string_77={__STRING_CONSTANT__,4," |  "};
__STRING_CONSTANT __string_78={__STRING_CONSTANT__,4,"    "};
__STRING_CONSTANT __string_79={__STRING_CONSTANT__,19,"Not enough memory.\n"};

//==========================//
// FUNCTION HEADER          //
//==========================//

// Debug Manager
void print_string(char *str);
// Source code
static __POINTER new_lab__2JB(__UINTEGER_32 t__4JB);
static __CHARACTER* create__BNG(__INTEGER nb_elements__DNG);
static __INODE* clone__3L();
static void* __infix_add__I1B(__INODE *Self__J1B,void *other__K1B);
static void display__51B(__INODE *Self__A2B);
static __MEMORY* new_page__3IC();
static void to_busy__index__LAI(__MEMORY *Self__MAI,__UINTEGER_32 sz__NAI,__UINTEGER_32 idx__OAI);
static void print__CHC(__STRING_CONSTANT *Self__DHC);
static void put_string__4HC(void *s__AIC);
static void append__KFF(__STRING *Self__LFF,void *other__MFF);

//==========================//
// SOURCE CODE              //
//==========================//

int main(int argc,char **argv)
{
  __STRING *result__FCD,*Self__J0D;
  __POINTER ptr__GCD,ptr_table__1VO,next__0VO,result__2VO,ptr_table__C1;
  __POINTER next__H1,result__F1;
  __INTEGER typ_id__LCD;
  __UINTEGER_32 sz__ICD,a__ZGO,new_size__3U,t__GW,a__5Y,new_size__B1;
  __UINTEGER_32 lab_type__D1;
  __INODE *__tmp__JKO,*Self__KKO,*__tmp__NKO,*Self__OKO,*__tmp__RKO;
  __INODE *Self__SKO,*__tmp__VKO,*Self__WKO,*__tmp__ZKO,*Self__0KO;
  __INODE *__tmp__3KO,*Self__4KO,*__tmp__BLO,*Self__CLO,*__tmp__FLO;
  __INODE *Self__GLO,*__tmp__JLO,*Self__KLO,*__tmp__NLO,*Self__OLO;
  __INODE *__tmp__RLO,*Self__SLO,*__tmp__VLO,*Self__WLO,*__tmp__ZLO;
  __INODE *Self__0LO,*__tmp__3LO,*Self__4LO,*__tmp__BMO,*Self__CMO;
  __INODE *__tmp__FMO,*Self__GMO,*__tmp__JMO,*Self__KMO,*__tmp__NMO;
  __INODE *Self__OMO,*__tmp__RMO,*Self__SMO,*__tmp__VMO,*Self__WMO;
  __INODE *__tmp__ZMO,*Self__0MO,*__tmp__3MO,*Self__4MO,*__tmp__BNO;
  __INODE *Self__CNO,*__tmp__FNO,*Self__GNO,*__tmp__JNO,*Self__KNO;
  __INODE *__tmp__NNO,*Self__ONO,*__tmp__RNO,*Self__SNO,*__tmp__VNO;
  __INODE *Self__WNO,*__tmp__ZNO,*Self__0NO,*__tmp__3NO,*Self__4NO;
  __INODE *__tmp__BOO,*Self__COO,*__tmp__FOO,*Self__GOO,*__tmp__JOO;
  __INODE *Self__KOO,*__tmp__NOO,*Self__OOO,*__tmp__ROO,*Self__SOO;
  __INODE *__tmp__VOO,*Self__WOO,*__tmp__ZOO,*Self__0OO,*__tmp__3OO;
  __INODE *Self__4OO,*__tmp__BPO,*Self__CPO,*__tmp__FPO,*Self__GPO;
  __INODE *__tmp__JPO,*Self__KPO,*__tmp__NPO,*Self__OPO,*__tmp__RPO;
  __INODE *Self__SPO,*__tmp__VPO,*Self__WPO,*__tmp__ZPO,*Self__0PO;
  __INODE *__tmp__3PO,*Self__4PO,*__tmp__BQO,*Self__CQO,*__tmp__FQO;
  __INODE *Self__GQO,*__tmp__JQO,*Self__KQO,*__tmp__NQO,*Self__OQO;
  __INODE *__tmp__RQO,*Self__SQO,*__tmp__VQO,*Self__WQO,*__tmp__ZQO;
  __INODE *Self__0QO,*__tmp__3QO,*Self__4QO,*__tmp__BRO,*Self__CRO;
  __INODE *__tmp__FRO,*Self__GRO,*__tmp__JRO,*Self__KRO,*__tmp__NRO;
  __INODE *Self__ORO,*__tmp__RRO,*Self__SRO,*__tmp__VRO,*Self__WRO;
  __INODE *__tmp__ZRO,*Self__0RO,*__tmp__3RO,*Self__4RO,*__tmp__BSO;
  __INODE *Self__CSO,*__tmp__FSO,*Self__GSO,*__tmp__JSO,*Self__KSO;
  __INODE *__tmp__SI,*Self__K4B;
  void *__tmp__AC,*__tmp__SC,*__tmp__1C,*__tmp__ED,*__tmp__KD,*__tmp__0D;
  void *menu__2,*tools__3,*base__1;
  arg_count  = argc;
  arg_vector = argv;
  parent_numeric__H=NUMERIC__;
  STRING_CONSTANT__->count__MNC=((__INTEGER )((0)));
  STRING__->count__G1D= 0;
  STRING_CONSTANT__->storage__4PE=((__CHARACTER *)(NULL));
  STRING__->storage__B1D=NULL;
  INODE__->parent_guii__0=INTERNAL_INODE__;
  clone_allocation_size__UM= 0;
  nb_page__OKB= 0;
  MEMORY__->size_and_id__5M= 0;
  capacity_max__HJC= 0;
  begin_memory__22=((__POINTER )(NULL));
  MEMORY__->previous_linear__4M= 0;
  first_free__2YD=NULL;
  MEMORY__->next_free__AN=NULL;
  MEMORY__->previous_free__BN=NULL;
  INODE__->operator__Q2B='\0';
  INODE__->name__B2B=NULL;
  INODE__->list__Q1B=NULL;
  LINKED_COLLECTIONoINODEo__->upper__L3B= 0;
  LINKED_LISToINODEo__->parent_linked_collection__P1B=(*LINKED_COLLECTIONoINODEo__);
  LINKED_LISToINODEo__->first_link__LWD=NULL;
  LINKED_LIST_NODEoINODEo__->item__YRE=NULL;
  LINKED_LIST_NODEoINODEo__->next__4MF=NULL;
  LINKED_LISToINODEo__->last_link__UWD=NULL;
  LINKED_LISToINODEo__->mem_idx__VWD= 0;
  LINKED_LISToINODEo__->mem_lnk__XWD=NULL;
  STRING__->capacity__Y0D= 0;
  result__FCD=NULL;
  ptr__GCD=((__POINTER )(NULL));
  typ_id__LCD= 0;
  sz__ICD=((__UINTEGER_32 )sizeof(__STRING));
  if ((sz__ICD ==  0)) {
    result__FCD=STRING__;
  } else {
    typ_id__LCD=-1;
    clone_allocation_size__UM=sz__ICD;
    if ((typ_id__LCD == (__INTEGER)(-  1))) {
      a__ZGO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__3U=(__UINTEGER_32)((__UINTEGER_32)(sz__ICD + a__ZGO) & (__UINTEGER_32)(~ a__ZGO));
      ptr_table__1VO=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__3U / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__0VO=((__POINTER )(NULL));
      result__2VO=((__POINTER *)ptr_table__1VO)[ 0];
      if ((result__2VO == (void *)NULL)) {
        result__2VO=new_lab__2JB(new_size__3U);
        next__0VO=(void *)((unsigned long)result__2VO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__3U)));
        ((__POINTER *)next__0VO)[ 0]=NULL;
        ((__POINTER *)ptr_table__1VO)[ 0]=next__0VO;
      } else {
        next__0VO=((__POINTER *)result__2VO)[ 0];
        if ((next__0VO == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__2VO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__3U <<  1)) <=  4096)) {
            next__0VO=(void *)((unsigned long)result__2VO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__3U)));
          } else {
            next__0VO=new_lab__2JB(new_size__3U);
          };
          ((__POINTER *)next__0VO)[ 0]=NULL;
          ((__POINTER *)ptr_table__1VO)[ 0]=next__0VO;
        } else {
          ((__POINTER *)result__2VO)[ 0]=(void *)((unsigned long)((__POINTER *)next__0VO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__2VO=next__0VO;
        };
      };
      ptr__GCD=result__2VO;
    } else {
      t__GW=((__UINTEGER_32 )typ_id__LCD);
      a__5Y=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__B1=(__UINTEGER_32)((__UINTEGER_32)(sz__ICD + a__5Y) & (__UINTEGER_32)(~ a__5Y));
      ptr_table__C1=((__POINTER )(&(table_type[(t__GW)])));
      lab_type__D1=(__UINTEGER_32)(t__GW |  1);
      next__H1=((__POINTER )(NULL));
      result__F1=((__POINTER *)ptr_table__C1)[ 0];
      if ((result__F1 == (void *)NULL)) {
        result__F1=new_lab__2JB(lab_type__D1);
        next__H1=(void *)((unsigned long)result__F1 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__B1)));
        ((__POINTER *)next__H1)[ 0]=NULL;
        ((__POINTER *)ptr_table__C1)[ 0]=next__H1;
      } else {
        next__H1=((__POINTER *)result__F1)[ 0];
        if ((next__H1 == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__F1 - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__B1 <<  1)) <=  4096)) {
            next__H1=(void *)((unsigned long)result__F1 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__B1)));
          } else {
            next__H1=new_lab__2JB(lab_type__D1);
          };
          ((__POINTER *)next__H1)[ 0]=NULL;
          ((__POINTER *)ptr_table__C1)[ 0]=next__H1;
        } else {
          ((__POINTER *)result__F1)[ 0]=(void *)((unsigned long)((__POINTER *)next__H1)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__F1=next__H1;
        };
      };
      ptr__GCD=result__F1;
    };
    result__FCD=((__STRING *)ptr__GCD);
    *(result__FCD) = *(STRING__);
  };
  Self__J0D=((__STRING *)result__FCD);
  if ((Self__J0D->capacity__Y0D <  250)) {
    Self__J0D->storage__B1D=create__BNG( 250);
    Self__J0D->capacity__Y0D= 250;
  };
  Self__J0D->count__G1D= 0;
  base__O2B=result__FCD;
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__JKO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__JKO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__JKO=clone__3L();
  } break;
  };
  Self__KKO=((__INODE *)__tmp__JKO);
  Self__KKO->operator__Q2B='|';
  Self__KKO->name__B2B=(&__string_1);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__NKO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__NKO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__NKO=clone__3L();
  } break;
  };
  Self__OKO=((__INODE *)__tmp__NKO);
  Self__OKO->operator__Q2B='^';
  Self__OKO->name__B2B=(&__string_2);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__RKO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__RKO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__RKO=clone__3L();
  } break;
  };
  Self__SKO=((__INODE *)__tmp__RKO);
  Self__SKO->operator__Q2B='^';
  Self__SKO->name__B2B=(&__string_3);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__VKO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__VKO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__VKO=clone__3L();
  } break;
  };
  Self__WKO=((__INODE *)__tmp__VKO);
  Self__WKO->operator__Q2B='^';
  Self__WKO->name__B2B=(&__string_4);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__ZKO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__ZKO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__ZKO=clone__3L();
  } break;
  };
  Self__0KO=((__INODE *)__tmp__ZKO);
  Self__0KO->operator__Q2B='^';
  Self__0KO->name__B2B=(&__string_5);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__3KO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__3KO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__3KO=clone__3L();
  } break;
  };
  Self__4KO=((__INODE *)__tmp__3KO);
  Self__4KO->operator__Q2B='^';
  Self__4KO->name__B2B=(&__string_6);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__BLO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__BLO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__BLO=clone__3L();
  } break;
  };
  Self__CLO=((__INODE *)__tmp__BLO);
  Self__CLO->operator__Q2B='^';
  Self__CLO->name__B2B=(&__string_7);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__FLO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__FLO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__FLO=clone__3L();
  } break;
  };
  Self__GLO=((__INODE *)__tmp__FLO);
  Self__GLO->operator__Q2B='^';
  Self__GLO->name__B2B=(&__string_8);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__JLO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__JLO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__JLO=clone__3L();
  } break;
  };
  Self__KLO=((__INODE *)__tmp__JLO);
  Self__KLO->operator__Q2B='^';
  Self__KLO->name__B2B=(&__string_9);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__NLO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__NLO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__NLO=clone__3L();
  } break;
  };
  Self__OLO=((__INODE *)__tmp__NLO);
  Self__OLO->operator__Q2B='^';
  Self__OLO->name__B2B=(&__string_10);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__RLO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__RLO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__RLO=clone__3L();
  } break;
  };
  Self__SLO=((__INODE *)__tmp__RLO);
  Self__SLO->operator__Q2B='^';
  Self__SLO->name__B2B=(&__string_11);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__VLO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__VLO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__VLO=clone__3L();
  } break;
  };
  Self__WLO=((__INODE *)__tmp__VLO);
  Self__WLO->operator__Q2B='^';
  Self__WLO->name__B2B=(&__string_12);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__ZLO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__ZLO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__ZLO=clone__3L();
  } break;
  };
  Self__0LO=((__INODE *)__tmp__ZLO);
  Self__0LO->operator__Q2B='^';
  Self__0LO->name__B2B=(&__string_13);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__3LO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__3LO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__3LO=clone__3L();
  } break;
  };
  Self__4LO=((__INODE *)__tmp__3LO);
  Self__4LO->operator__Q2B='^';
  Self__4LO->name__B2B=(&__string_14);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__BMO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__BMO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__BMO=clone__3L();
  } break;
  };
  Self__CMO=((__INODE *)__tmp__BMO);
  Self__CMO->operator__Q2B='^';
  Self__CMO->name__B2B=(&__string_15);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__FMO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__FMO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__FMO=clone__3L();
  } break;
  };
  Self__GMO=((__INODE *)__tmp__FMO);
  Self__GMO->operator__Q2B='^';
  Self__GMO->name__B2B=(&__string_16);
  __tmp__AC=__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__RKO,__infix_add__I1B(__tmp__VKO,__tmp__ZKO)),__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__3KO,__tmp__BLO),__tmp__FLO),__tmp__JLO)),__infix_add__I1B(__infix_add__I1B(__tmp__NLO,__tmp__RLO),__tmp__VLO)),__infix_add__I1B(__tmp__ZLO,__tmp__3LO)),__infix_add__I1B(__tmp__BMO,__tmp__FMO));
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__JMO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__JMO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__JMO=clone__3L();
  } break;
  };
  Self__KMO=((__INODE *)__tmp__JMO);
  Self__KMO->operator__Q2B='^';
  Self__KMO->name__B2B=(&__string_17);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__NMO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__NMO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__NMO=clone__3L();
  } break;
  };
  Self__OMO=((__INODE *)__tmp__NMO);
  Self__OMO->operator__Q2B='^';
  Self__OMO->name__B2B=(&__string_18);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__RMO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__RMO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__RMO=clone__3L();
  } break;
  };
  Self__SMO=((__INODE *)__tmp__RMO);
  Self__SMO->operator__Q2B='^';
  Self__SMO->name__B2B=(&__string_19);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__VMO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__VMO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__VMO=clone__3L();
  } break;
  };
  Self__WMO=((__INODE *)__tmp__VMO);
  Self__WMO->operator__Q2B='^';
  Self__WMO->name__B2B=(&__string_20);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__ZMO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__ZMO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__ZMO=clone__3L();
  } break;
  };
  Self__0MO=((__INODE *)__tmp__ZMO);
  Self__0MO->operator__Q2B='^';
  Self__0MO->name__B2B=(&__string_21);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__3MO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__3MO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__3MO=clone__3L();
  } break;
  };
  Self__4MO=((__INODE *)__tmp__3MO);
  Self__4MO->operator__Q2B='^';
  Self__4MO->name__B2B=(&__string_22);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__BNO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__BNO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__BNO=clone__3L();
  } break;
  };
  Self__CNO=((__INODE *)__tmp__BNO);
  Self__CNO->operator__Q2B='^';
  Self__CNO->name__B2B=(&__string_23);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__FNO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__FNO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__FNO=clone__3L();
  } break;
  };
  Self__GNO=((__INODE *)__tmp__FNO);
  Self__GNO->operator__Q2B='^';
  Self__GNO->name__B2B=(&__string_24);
  __tmp__SC=__infix_add__I1B(__infix_add__I1B(__tmp__JMO,__infix_add__I1B(__infix_add__I1B(__tmp__NMO,__tmp__RMO),__tmp__VMO)),__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__ZMO,__tmp__3MO),__tmp__BNO),__tmp__FNO));
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__JNO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__JNO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__JNO=clone__3L();
  } break;
  };
  Self__KNO=((__INODE *)__tmp__JNO);
  Self__KNO->operator__Q2B='^';
  Self__KNO->name__B2B=(&__string_25);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__NNO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__NNO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__NNO=clone__3L();
  } break;
  };
  Self__ONO=((__INODE *)__tmp__NNO);
  Self__ONO->operator__Q2B='^';
  Self__ONO->name__B2B=(&__string_26);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__RNO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__RNO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__RNO=clone__3L();
  } break;
  };
  Self__SNO=((__INODE *)__tmp__RNO);
  Self__SNO->operator__Q2B='^';
  Self__SNO->name__B2B=(&__string_27);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__VNO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__VNO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__VNO=clone__3L();
  } break;
  };
  Self__WNO=((__INODE *)__tmp__VNO);
  Self__WNO->operator__Q2B='^';
  Self__WNO->name__B2B=(&__string_28);
  __tmp__1C=__infix_add__I1B(__tmp__JNO,__infix_add__I1B(__infix_add__I1B(__tmp__NNO,__tmp__RNO),__tmp__VNO));
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__ZNO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__ZNO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__ZNO=clone__3L();
  } break;
  };
  Self__0NO=((__INODE *)__tmp__ZNO);
  Self__0NO->operator__Q2B='^';
  Self__0NO->name__B2B=(&__string_29);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__3NO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__3NO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__3NO=clone__3L();
  } break;
  };
  Self__4NO=((__INODE *)__tmp__3NO);
  Self__4NO->operator__Q2B='^';
  Self__4NO->name__B2B=(&__string_30);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__BOO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__BOO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__BOO=clone__3L();
  } break;
  };
  Self__COO=((__INODE *)__tmp__BOO);
  Self__COO->operator__Q2B='^';
  Self__COO->name__B2B=(&__string_31);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__FOO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__FOO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__FOO=clone__3L();
  } break;
  };
  Self__GOO=((__INODE *)__tmp__FOO);
  Self__GOO->operator__Q2B='^';
  Self__GOO->name__B2B=(&__string_32);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__JOO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__JOO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__JOO=clone__3L();
  } break;
  };
  Self__KOO=((__INODE *)__tmp__JOO);
  Self__KOO->operator__Q2B='^';
  Self__KOO->name__B2B=(&__string_33);
  __tmp__ED=__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__3NO,__tmp__BOO),__tmp__FOO),__tmp__JOO);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__NOO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__NOO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__NOO=clone__3L();
  } break;
  };
  Self__OOO=((__INODE *)__tmp__NOO);
  Self__OOO->operator__Q2B='^';
  Self__OOO->name__B2B=(&__string_34);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__ROO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__ROO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__ROO=clone__3L();
  } break;
  };
  Self__SOO=((__INODE *)__tmp__ROO);
  Self__SOO->operator__Q2B='^';
  Self__SOO->name__B2B=(&__string_35);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__VOO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__VOO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__VOO=clone__3L();
  } break;
  };
  Self__WOO=((__INODE *)__tmp__VOO);
  Self__WOO->operator__Q2B='^';
  Self__WOO->name__B2B=(&__string_36);
  __tmp__KD=__infix_add__I1B(__infix_add__I1B(__tmp__NOO,__tmp__ROO),__tmp__VOO);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__ZOO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__ZOO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__ZOO=clone__3L();
  } break;
  };
  Self__0OO=((__INODE *)__tmp__ZOO);
  Self__0OO->operator__Q2B='^';
  Self__0OO->name__B2B=(&__string_37);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__3OO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__3OO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__3OO=clone__3L();
  } break;
  };
  Self__4OO=((__INODE *)__tmp__3OO);
  Self__4OO->operator__Q2B='^';
  Self__4OO->name__B2B=(&__string_38);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__BPO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__BPO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__BPO=clone__3L();
  } break;
  };
  Self__CPO=((__INODE *)__tmp__BPO);
  Self__CPO->operator__Q2B='^';
  Self__CPO->name__B2B=(&__string_39);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__FPO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__FPO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__FPO=clone__3L();
  } break;
  };
  Self__GPO=((__INODE *)__tmp__FPO);
  Self__GPO->operator__Q2B='^';
  Self__GPO->name__B2B=(&__string_40);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__JPO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__JPO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__JPO=clone__3L();
  } break;
  };
  Self__KPO=((__INODE *)__tmp__JPO);
  Self__KPO->operator__Q2B='^';
  Self__KPO->name__B2B=(&__string_41);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__NPO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__NPO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__NPO=clone__3L();
  } break;
  };
  Self__OPO=((__INODE *)__tmp__NPO);
  Self__OPO->operator__Q2B='^';
  Self__OPO->name__B2B=(&__string_42);
  __tmp__0D=__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__ZNO,__tmp__ED),__tmp__KD),__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__ZOO,__tmp__3OO),__tmp__BPO),__tmp__FPO),__tmp__JPO),__tmp__NPO));
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__RPO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__RPO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__RPO=clone__3L();
  } break;
  };
  Self__SPO=((__INODE *)__tmp__RPO);
  Self__SPO->operator__Q2B='^';
  Self__SPO->name__B2B=(&__string_43);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__VPO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__VPO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__VPO=clone__3L();
  } break;
  };
  Self__WPO=((__INODE *)__tmp__VPO);
  Self__WPO->operator__Q2B='^';
  Self__WPO->name__B2B=(&__string_44);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__ZPO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__ZPO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__ZPO=clone__3L();
  } break;
  };
  Self__0PO=((__INODE *)__tmp__ZPO);
  Self__0PO->operator__Q2B='^';
  Self__0PO->name__B2B=(&__string_45);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__3PO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__3PO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__3PO=clone__3L();
  } break;
  };
  Self__4PO=((__INODE *)__tmp__3PO);
  Self__4PO->operator__Q2B='^';
  Self__4PO->name__B2B=(&__string_46);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__BQO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__BQO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__BQO=clone__3L();
  } break;
  };
  Self__CQO=((__INODE *)__tmp__BQO);
  Self__CQO->operator__Q2B='^';
  Self__CQO->name__B2B=(&__string_47);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__FQO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__FQO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__FQO=clone__3L();
  } break;
  };
  Self__GQO=((__INODE *)__tmp__FQO);
  Self__GQO->operator__Q2B='^';
  Self__GQO->name__B2B=(&__string_48);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__JQO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__JQO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__JQO=clone__3L();
  } break;
  };
  Self__KQO=((__INODE *)__tmp__JQO);
  Self__KQO->operator__Q2B='^';
  Self__KQO->name__B2B=(&__string_49);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__NQO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__NQO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__NQO=clone__3L();
  } break;
  };
  Self__OQO=((__INODE *)__tmp__NQO);
  Self__OQO->operator__Q2B='^';
  Self__OQO->name__B2B=(&__string_50);
  menu__2=__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__NKO,__tmp__AC),__tmp__SC),__tmp__1C),__tmp__0D),__infix_add__I1B(__tmp__RPO,__infix_add__I1B(__tmp__VPO,__tmp__ZPO))),__infix_add__I1B(__tmp__3PO,__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__BQO,__tmp__FQO),__tmp__JQO),__tmp__NQO)));
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__RQO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__RQO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__RQO=clone__3L();
  } break;
  };
  Self__SQO=((__INODE *)__tmp__RQO);
  Self__SQO->operator__Q2B='^';
  Self__SQO->name__B2B=(&__string_51);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__VQO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__VQO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__VQO=clone__3L();
  } break;
  };
  Self__WQO=((__INODE *)__tmp__VQO);
  Self__WQO->operator__Q2B='^';
  Self__WQO->name__B2B=(&__string_52);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__ZQO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__ZQO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__ZQO=clone__3L();
  } break;
  };
  Self__0QO=((__INODE *)__tmp__ZQO);
  Self__0QO->operator__Q2B='^';
  Self__0QO->name__B2B=(&__string_53);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__3QO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__3QO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__3QO=clone__3L();
  } break;
  };
  Self__4QO=((__INODE *)__tmp__3QO);
  Self__4QO->operator__Q2B='^';
  Self__4QO->name__B2B=(&__string_54);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__BRO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__BRO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__BRO=clone__3L();
  } break;
  };
  Self__CRO=((__INODE *)__tmp__BRO);
  Self__CRO->operator__Q2B='^';
  Self__CRO->name__B2B=(&__string_55);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__FRO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__FRO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__FRO=clone__3L();
  } break;
  };
  Self__GRO=((__INODE *)__tmp__FRO);
  Self__GRO->operator__Q2B='^';
  Self__GRO->name__B2B=(&__string_56);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__JRO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__JRO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__JRO=clone__3L();
  } break;
  };
  Self__KRO=((__INODE *)__tmp__JRO);
  Self__KRO->operator__Q2B='^';
  Self__KRO->name__B2B=(&__string_57);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__NRO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__NRO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__NRO=clone__3L();
  } break;
  };
  Self__ORO=((__INODE *)__tmp__NRO);
  Self__ORO->operator__Q2B='^';
  Self__ORO->name__B2B=(&__string_58);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__RRO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__RRO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__RRO=clone__3L();
  } break;
  };
  Self__SRO=((__INODE *)__tmp__RRO);
  Self__SRO->operator__Q2B='^';
  Self__SRO->name__B2B=(&__string_59);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__VRO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__VRO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__VRO=clone__3L();
  } break;
  };
  Self__WRO=((__INODE *)__tmp__VRO);
  Self__WRO->operator__Q2B='^';
  Self__WRO->name__B2B=(&__string_60);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__ZRO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__ZRO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__ZRO=clone__3L();
  } break;
  };
  Self__0RO=((__INODE *)__tmp__ZRO);
  Self__0RO->operator__Q2B='^';
  Self__0RO->name__B2B=(&__string_61);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__3RO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__3RO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__3RO=clone__3L();
  } break;
  };
  Self__4RO=((__INODE *)__tmp__3RO);
  Self__4RO->operator__Q2B='^';
  Self__4RO->name__B2B=(&__string_62);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__BSO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__BSO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__BSO=clone__3L();
  } break;
  };
  Self__CSO=((__INODE *)__tmp__BSO);
  Self__CSO->operator__Q2B='^';
  Self__CSO->name__B2B=(&__string_63);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__FSO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__FSO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__FSO=clone__3L();
  } break;
  };
  Self__GSO=((__INODE *)__tmp__FSO);
  Self__GSO->operator__Q2B='^';
  Self__GSO->name__B2B=(&__string_64);
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__JSO=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__JSO=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__JSO=clone__3L();
  } break;
  };
  Self__KSO=((__INODE *)__tmp__JSO);
  Self__KSO->operator__Q2B='^';
  Self__KSO->name__B2B=(&__string_65);
  tools__3=__infix_add__I1B(__tmp__RQO,__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__VQO,__tmp__ZQO),__tmp__3QO),__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__BRO,__tmp__FRO),__tmp__JRO),__tmp__NRO),__tmp__RRO),__tmp__VRO)),__tmp__ZRO),__tmp__3RO),__tmp__BSO),__tmp__FSO),__tmp__JSO));
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__SI=clone__3L();
  } break;
  case __MENU_H__: {
    __tmp__SI=clone__3L();
  } break;
  case __MENU_V__: {
    __tmp__SI=clone__3L();
  } break;
  };
  Self__K4B=((__INODE *)__tmp__SI);
  Self__K4B->operator__Q2B='^';
  Self__K4B->name__B2B=(&__string_66);
  base__1=__infix_add__I1B(__infix_add__I1B(__infix_add__I1B(__tmp__JKO,menu__2),tools__3),__tmp__SI);
  ((__INODE *)menu__2)->parent_guii__0=MENU_H__;
  ((__INODE *)tools__3)->parent_guii__0=MENU_V__;
  switch (((struct ___OBJ *)((__INODE *)base__1)->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    display__51B(base__1);
  } break;
  case __MENU_H__: {
    display__51B(base__1);
  } break;
  case __MENU_V__: {
    display__51B(base__1);
  } break;
  };
  return( 0);
}

static __POINTER new_lab__2JB(__UINTEGER_32 t__4JB)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 idx__AKB,pv__HKB;
  __MEMORY *blc__DKB,*prev__EKB,*Self__2UD,*Self__3JO,*prev__4JO;
  __MEMORY *next__5JO;
  __POINTER result__FKB;
  __BOOLEAN __tmp__HLB;
  idx__AKB= 0;
  blc__DKB=NULL;
  prev__EKB=NULL;
  pv__HKB= 0;
  while_do__5OB:
  {
    if ((idx__AKB < nb_page__OKB)) {
      blc__DKB=((__MEMORY *)(last_block[(idx__AKB)]));
      __tmp__HLB=(((__UINTEGER_32)(((__MEMORY *)blc__DKB)->size_and_id__5M &  4294967292LU) <  4096) || ((__UINTEGER_32)(((__MEMORY *)blc__DKB)->size_and_id__5M &  1) ==  1));
    } else {
      __tmp__HLB=FALSE__;
    };
    if (__tmp__HLB) {
      idx__AKB=(__UINTEGER_32)(idx__AKB +  1);
      goto while_do__5OB;
    };
  };
  if ((idx__AKB >= nb_page__OKB)) {
    blc__DKB=new_page__3IC();
  };
  ((__MEMORY *)blc__DKB)->size_and_id__5M=(__UINTEGER_32)(blc__DKB->size_and_id__5M -  4096);
  Self__2UD=((__MEMORY *)blc__DKB);
  result__FKB=((__POINTER )((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__2UD) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__2UD->size_and_id__5M &  4294967292LU))))));
  if (((__UINTEGER_32)(((__MEMORY *)blc__DKB)->size_and_id__5M &  4294967292LU) < ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    Self__3JO=((__MEMORY *)blc__DKB);
    prev__4JO=Self__3JO->previous_free__BN;
    next__5JO=Self__3JO->next_free__AN;
    if (((void *)prev__4JO == (void *)NULL)) {
      first_free__2YD=next__5JO;
    } else {
      ((__MEMORY *)prev__4JO)->next_free__AN=next__5JO;
    };
    if (((void *)next__5JO != (void *)NULL)) {
      ((__MEMORY *)next__5JO)->previous_free__BN=prev__4JO;
    };
    pv__HKB=blc__DKB->previous_linear__4M;
    if ((pv__HKB !=  4294967295LU)) {
      prev__EKB=((__MEMORY *)(void *)((unsigned long)begin_memory__22 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )pv__HKB))));
      ((__MEMORY *)prev__EKB)->size_and_id__5M=(__UINTEGER_32)((__UINTEGER_32)(prev__EKB->size_and_id__5M + blc__DKB->size_and_id__5M) +  8);
      last_block[(idx__AKB)] = (prev__EKB);
    };
  };
  ((__POINTER *)result__FKB)[ 0]=((__POINTER )t__4JB);
  return((void *)((unsigned long)result__FKB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))))));
}

static __CHARACTER* create__BNG(__INTEGER nb_elements__DNG)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__ZGH,a__BFO,new_size__1GH,new_size2__4GH,a__4GO;
  __UINTEGER_32 new_size__5GO;
  __POINTER result__BHH,ptr_table__3SO,next__2SO,result__4SO;
  __MEMORY *result__VQH;
  __INTEGER Self__PGI;
  __CHARACTER *Result__4ZG;
  sz__ZGH=((__UINTEGER_32 )nb_elements__DNG);
  result__BHH=((__POINTER )(NULL));
  a__BFO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__1GH=(__UINTEGER_32)((__UINTEGER_32)(sz__ZGH + a__BFO) & (__UINTEGER_32)(~ a__BFO));
  new_size2__4GH=(__UINTEGER_32)(new_size__1GH + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__4GH <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__4GO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__5GO=(__UINTEGER_32)((__UINTEGER_32)(new_size2__4GH + a__4GO) & (__UINTEGER_32)(~ a__4GO));
    ptr_table__3SO=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__5GO / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
    next__2SO=((__POINTER )(NULL));
    result__4SO=((__POINTER *)ptr_table__3SO)[ 0];
    if ((result__4SO == (void *)NULL)) {
      result__4SO=new_lab__2JB(new_size__5GO);
      next__2SO=(void *)((unsigned long)result__4SO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__5GO)));
      ((__POINTER *)next__2SO)[ 0]=NULL;
      ((__POINTER *)ptr_table__3SO)[ 0]=next__2SO;
    } else {
      next__2SO=((__POINTER *)result__4SO)[ 0];
      if ((next__2SO == (void *)NULL)) {
        if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__4SO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__5GO <<  1)) <=  4096)) {
          next__2SO=(void *)((unsigned long)result__4SO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__5GO)));
        } else {
          next__2SO=new_lab__2JB(new_size__5GO);
        };
        ((__POINTER *)next__2SO)[ 0]=NULL;
        ((__POINTER *)ptr_table__3SO)[ 0]=next__2SO;
      } else {
        ((__POINTER *)result__4SO)[ 0]=(void *)((unsigned long)((__POINTER *)next__2SO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
        result__4SO=next__2SO;
      };
    };
    ((__POINTER *)result__4SO)[ 0]=((__POINTER ) 3);
    result__BHH=(void *)((unsigned long)result__4SO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__VQH=first_free__2YD;
    while ((((void *)result__VQH != (void *)NULL) && ((__UINTEGER_32)(((__MEMORY *)result__VQH)->size_and_id__5M &  4294967292LU) < new_size__1GH))) {
      result__VQH=result__VQH->next_free__AN;
    };
    if (((void *)result__VQH == (void *)NULL)) {
      result__VQH=new_page__3IC();
    };
    to_busy__index__LAI(result__VQH,new_size__1GH,(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)result__VQH)) - (unsigned long)begin_memory__22)))) >>  26));
    result__BHH=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__VQH)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__4ZG=((__CHARACTER *)result__BHH);
  Self__PGI=(__INTEGER)(nb_elements__DNG -  1);
  while ((Self__PGI >=  0)) {
    Result__4ZG[Self__PGI]='\0';
    Self__PGI=(__INTEGER)(Self__PGI -  1);
  };
  return(Result__4ZG);
}

static __INODE* clone__3L()
// () With resultNo recursive, No inlinable.
{
  __INODE *result__AM;
  __POINTER ptr__BM,ptr_table__ETO,next__DTO,result__FTO,ptr_table__LTO;
  __POINTER next__KTO,result__MTO;
  __INTEGER __tmp__HM,__tmp__TM;
  __UINTEGER_32 sz__DM,__tmp__VM,__tmp__WM,a__2HO,new_size__3HO,t__GIO;
  __UINTEGER_32 a__DIO,new_size__OTO,lab_type__NTO;
  result__AM=NULL;
  ptr__BM=((__POINTER )(NULL));
  switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__HM=sizeof(__INODE);
  } break;
  case __MENU_H__: {
    __tmp__HM=sizeof(__INODE);
  } break;
  case __MENU_V__: {
    __tmp__HM=sizeof(__INODE);
  } break;
  };
  sz__DM=((__UINTEGER_32 )__tmp__HM);
  if ((sz__DM ==  0)) {
    result__AM=INODE__;
  } else {
    switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
    case __INTERNAL_INODE__: {
      __tmp__TM=__INODE__;
    } break;
    case __MENU_H__: {
      __tmp__TM=__INODE__;
    } break;
    case __MENU_V__: {
      __tmp__TM=__INODE__;
    } break;
    };
    switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
    case __INTERNAL_INODE__: {
      __tmp__VM=clone_allocation_size__UM;
    } break;
    case __MENU_H__: {
      __tmp__VM=clone_allocation_size__UM;
    } break;
    case __MENU_V__: {
      __tmp__VM=clone_allocation_size__UM;
    } break;
    };
    __tmp__WM=(__UINTEGER_32)(__tmp__VM + sz__DM);
    switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
    case __INTERNAL_INODE__: {
      clone_allocation_size__UM=__tmp__WM;
    } break;
    case __MENU_H__: {
      clone_allocation_size__UM=__tmp__WM;
    } break;
    case __MENU_V__: {
      clone_allocation_size__UM=__tmp__WM;
    } break;
    };
    if ((__tmp__TM == (__INTEGER)(-  1))) {
      a__2HO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__3HO=(__UINTEGER_32)((__UINTEGER_32)(sz__DM + a__2HO) & (__UINTEGER_32)(~ a__2HO));
      ptr_table__ETO=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__3HO / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__DTO=((__POINTER )(NULL));
      result__FTO=((__POINTER *)ptr_table__ETO)[ 0];
      if ((result__FTO == (void *)NULL)) {
        result__FTO=new_lab__2JB(new_size__3HO);
        next__DTO=(void *)((unsigned long)result__FTO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__3HO)));
        ((__POINTER *)next__DTO)[ 0]=NULL;
        ((__POINTER *)ptr_table__ETO)[ 0]=next__DTO;
      } else {
        next__DTO=((__POINTER *)result__FTO)[ 0];
        if ((next__DTO == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__FTO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__3HO <<  1)) <=  4096)) {
            next__DTO=(void *)((unsigned long)result__FTO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__3HO)));
          } else {
            next__DTO=new_lab__2JB(new_size__3HO);
          };
          ((__POINTER *)next__DTO)[ 0]=NULL;
          ((__POINTER *)ptr_table__ETO)[ 0]=next__DTO;
        } else {
          ((__POINTER *)result__FTO)[ 0]=(void *)((unsigned long)((__POINTER *)next__DTO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__FTO=next__DTO;
        };
      };
      ptr__BM=result__FTO;
    } else {
      t__GIO=((__UINTEGER_32 )__tmp__TM);
      a__DIO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__OTO=(__UINTEGER_32)((__UINTEGER_32)(sz__DM + a__DIO) & (__UINTEGER_32)(~ a__DIO));
      ptr_table__LTO=((__POINTER )(&(table_type[(t__GIO)])));
      lab_type__NTO=(__UINTEGER_32)(t__GIO |  1);
      next__KTO=((__POINTER )(NULL));
      result__MTO=((__POINTER *)ptr_table__LTO)[ 0];
      if ((result__MTO == (void *)NULL)) {
        result__MTO=new_lab__2JB(lab_type__NTO);
        next__KTO=(void *)((unsigned long)result__MTO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__OTO)));
        ((__POINTER *)next__KTO)[ 0]=NULL;
        ((__POINTER *)ptr_table__LTO)[ 0]=next__KTO;
      } else {
        next__KTO=((__POINTER *)result__MTO)[ 0];
        if ((next__KTO == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__MTO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__OTO <<  1)) <=  4096)) {
            next__KTO=(void *)((unsigned long)result__MTO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__OTO)));
          } else {
            next__KTO=new_lab__2JB(lab_type__NTO);
          };
          ((__POINTER *)next__KTO)[ 0]=NULL;
          ((__POINTER *)ptr_table__LTO)[ 0]=next__KTO;
        } else {
          ((__POINTER *)result__MTO)[ 0]=(void *)((unsigned long)((__POINTER *)next__KTO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__MTO=next__KTO;
        };
      };
      ptr__BM=result__MTO;
    };
    result__AM=((__INODE *)ptr__BM);
    switch (((struct ___OBJ *)INODE__->parent_guii__0)->__id) {
    case __INTERNAL_INODE__: {
      *(result__AM) = *(INODE__);
    } break;
    case __MENU_H__: {
      *(result__AM) = *(INODE__);
    } break;
    case __MENU_V__: {
      *(result__AM) = *(INODE__);
    } break;
    };
  };
  return(result__AM);
}

static void* __infix_add__I1B(__INODE *Self__J1B,void *other__K1B)
// ({INODE},{NULLxINODE}) With resultNo recursive, No inlinable.
{
  __POINTER ptr__SYC,ptr_table__STO,next__RTO,result__TTO;
  __POINTER ptr_table__ZTO,next__YTO,result__0TO,ptr__AUO;
  __POINTER ptr_table__KUO,next__JUO,result__LUO,ptr_table__RUO;
  __POINTER next__QUO,result__SUO,ptr__WZE,ptr_table__YUO,next__XUO;
  __POINTER result__ZUO,ptr_table__5UO,next__4UO,result__AVO;
  __INTEGER typ_id__XYC,typ_id__BUO,typ_id__1ZE;
  __UINTEGER_32 sz__UYC,a__FHO,new_size__GHO,t__PHO,a__MHO;
  __UINTEGER_32 new_size__2TO,lab_type__1TO,sz__CUO,a__DUO;
  __UINTEGER_32 new_size__EUO,t__FUO,a__GUO,new_size__UUO,lab_type__TUO;
  __UINTEGER_32 sz__YZE,a__KIO,new_size__LIO,t__UIO,a__RIO;
  __UINTEGER_32 new_size__CVO,lab_type__BVO;
  __LINKED_LISToINODEo *result__RYC,*Self__GWD;
  __LINKED_LIST_NODEoINODEo *result__5TO,*Self__HUO,*result__VZE;
  __LINKED_LIST_NODEoINODEo *Self__QFG;
  if (((void *)Self__J1B->list__Q1B == (void *)NULL)) {
    result__RYC=NULL;
    ptr__SYC=((__POINTER )(NULL));
    typ_id__XYC= 0;
    sz__UYC=((__UINTEGER_32 )sizeof(__LINKED_LISToINODEo));
    if ((sz__UYC ==  0)) {
      result__RYC=LINKED_LISToINODEo__;
    } else {
      typ_id__XYC=__LINKED_LISToINODEo__;
      clone_allocation_size__UM=(__UINTEGER_32)(clone_allocation_size__UM + sz__UYC);
      if ((typ_id__XYC == (__INTEGER)(-  1))) {
        a__FHO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        new_size__GHO=(__UINTEGER_32)((__UINTEGER_32)(sz__UYC + a__FHO) & (__UINTEGER_32)(~ a__FHO));
        ptr_table__STO=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__GHO / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
        next__RTO=((__POINTER )(NULL));
        result__TTO=((__POINTER *)ptr_table__STO)[ 0];
        if ((result__TTO == (void *)NULL)) {
          result__TTO=new_lab__2JB(new_size__GHO);
          next__RTO=(void *)((unsigned long)result__TTO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__GHO)));
          ((__POINTER *)next__RTO)[ 0]=NULL;
          ((__POINTER *)ptr_table__STO)[ 0]=next__RTO;
        } else {
          next__RTO=((__POINTER *)result__TTO)[ 0];
          if ((next__RTO == (void *)NULL)) {
            if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__TTO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__GHO <<  1)) <=  4096)) {
              next__RTO=(void *)((unsigned long)result__TTO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__GHO)));
            } else {
              next__RTO=new_lab__2JB(new_size__GHO);
            };
            ((__POINTER *)next__RTO)[ 0]=NULL;
            ((__POINTER *)ptr_table__STO)[ 0]=next__RTO;
          } else {
            ((__POINTER *)result__TTO)[ 0]=(void *)((unsigned long)((__POINTER *)next__RTO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
            result__TTO=next__RTO;
          };
        };
        ptr__SYC=result__TTO;
      } else {
        t__PHO=((__UINTEGER_32 )typ_id__XYC);
        a__MHO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        new_size__2TO=(__UINTEGER_32)((__UINTEGER_32)(sz__UYC + a__MHO) & (__UINTEGER_32)(~ a__MHO));
        ptr_table__ZTO=((__POINTER )(&(table_type[(t__PHO)])));
        lab_type__1TO=(__UINTEGER_32)(t__PHO |  1);
        next__YTO=((__POINTER )(NULL));
        result__0TO=((__POINTER *)ptr_table__ZTO)[ 0];
        if ((result__0TO == (void *)NULL)) {
          result__0TO=new_lab__2JB(lab_type__1TO);
          next__YTO=(void *)((unsigned long)result__0TO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__2TO)));
          ((__POINTER *)next__YTO)[ 0]=NULL;
          ((__POINTER *)ptr_table__ZTO)[ 0]=next__YTO;
        } else {
          next__YTO=((__POINTER *)result__0TO)[ 0];
          if ((next__YTO == (void *)NULL)) {
            if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__0TO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__2TO <<  1)) <=  4096)) {
              next__YTO=(void *)((unsigned long)result__0TO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__2TO)));
            } else {
              next__YTO=new_lab__2JB(lab_type__1TO);
            };
            ((__POINTER *)next__YTO)[ 0]=NULL;
            ((__POINTER *)ptr_table__ZTO)[ 0]=next__YTO;
          } else {
            ((__POINTER *)result__0TO)[ 0]=(void *)((unsigned long)((__POINTER *)next__YTO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
            result__0TO=next__YTO;
          };
        };
        ptr__SYC=result__0TO;
      };
      result__RYC=((__LINKED_LISToINODEo *)ptr__SYC);
      *(result__RYC) = *(LINKED_LISToINODEo__);
    };
    Self__J1B->list__Q1B=result__RYC;
  };
  Self__GWD=((__LINKED_LISToINODEo *)Self__J1B->list__Q1B);
  if (((void *)Self__GWD->first_link__LWD == (void *)NULL)) {
    result__5TO=NULL;
    ptr__AUO=((__POINTER )(NULL));
    typ_id__BUO= 0;
    sz__CUO=((__UINTEGER_32 )sizeof(__LINKED_LIST_NODEoINODEo));
    if ((sz__CUO ==  0)) {
      result__5TO=LINKED_LIST_NODEoINODEo__;
    } else {
      typ_id__BUO=__LINKED_LIST_NODEoINODEo__;
      clone_allocation_size__UM=(__UINTEGER_32)(clone_allocation_size__UM + sz__CUO);
      if ((typ_id__BUO == (__INTEGER)(-  1))) {
        a__DUO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        new_size__EUO=(__UINTEGER_32)((__UINTEGER_32)(sz__CUO + a__DUO) & (__UINTEGER_32)(~ a__DUO));
        ptr_table__KUO=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__EUO / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
        next__JUO=((__POINTER )(NULL));
        result__LUO=((__POINTER *)ptr_table__KUO)[ 0];
        if ((result__LUO == (void *)NULL)) {
          result__LUO=new_lab__2JB(new_size__EUO);
          next__JUO=(void *)((unsigned long)result__LUO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__EUO)));
          ((__POINTER *)next__JUO)[ 0]=NULL;
          ((__POINTER *)ptr_table__KUO)[ 0]=next__JUO;
        } else {
          next__JUO=((__POINTER *)result__LUO)[ 0];
          if ((next__JUO == (void *)NULL)) {
            if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__LUO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__EUO <<  1)) <=  4096)) {
              next__JUO=(void *)((unsigned long)result__LUO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__EUO)));
            } else {
              next__JUO=new_lab__2JB(new_size__EUO);
            };
            ((__POINTER *)next__JUO)[ 0]=NULL;
            ((__POINTER *)ptr_table__KUO)[ 0]=next__JUO;
          } else {
            ((__POINTER *)result__LUO)[ 0]=(void *)((unsigned long)((__POINTER *)next__JUO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
            result__LUO=next__JUO;
          };
        };
        ptr__AUO=result__LUO;
      } else {
        t__FUO=((__UINTEGER_32 )typ_id__BUO);
        a__GUO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        new_size__UUO=(__UINTEGER_32)((__UINTEGER_32)(sz__CUO + a__GUO) & (__UINTEGER_32)(~ a__GUO));
        ptr_table__RUO=((__POINTER )(&(table_type[(t__FUO)])));
        lab_type__TUO=(__UINTEGER_32)(t__FUO |  1);
        next__QUO=((__POINTER )(NULL));
        result__SUO=((__POINTER *)ptr_table__RUO)[ 0];
        if ((result__SUO == (void *)NULL)) {
          result__SUO=new_lab__2JB(lab_type__TUO);
          next__QUO=(void *)((unsigned long)result__SUO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__UUO)));
          ((__POINTER *)next__QUO)[ 0]=NULL;
          ((__POINTER *)ptr_table__RUO)[ 0]=next__QUO;
        } else {
          next__QUO=((__POINTER *)result__SUO)[ 0];
          if ((next__QUO == (void *)NULL)) {
            if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__SUO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__UUO <<  1)) <=  4096)) {
              next__QUO=(void *)((unsigned long)result__SUO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__UUO)));
            } else {
              next__QUO=new_lab__2JB(lab_type__TUO);
            };
            ((__POINTER *)next__QUO)[ 0]=NULL;
            ((__POINTER *)ptr_table__RUO)[ 0]=next__QUO;
          } else {
            ((__POINTER *)result__SUO)[ 0]=(void *)((unsigned long)((__POINTER *)next__QUO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
            result__SUO=next__QUO;
          };
        };
        ptr__AUO=result__SUO;
      };
      result__5TO=((__LINKED_LIST_NODEoINODEo *)ptr__AUO);
      *(result__5TO) = *(LINKED_LIST_NODEoINODEo__);
    };
    Self__HUO=((__LINKED_LIST_NODEoINODEo *)result__5TO);
    Self__HUO->item__YRE=other__K1B;
    Self__HUO->next__4MF=NULL;
    Self__GWD->first_link__LWD=result__5TO;
    Self__GWD->parent_linked_collection__P1B.upper__L3B= 1;
    Self__GWD->last_link__UWD=result__5TO;
    Self__GWD->mem_idx__VWD= 1;
    Self__GWD->mem_lnk__XWD=result__5TO;
  } else {
    result__VZE=NULL;
    ptr__WZE=((__POINTER )(NULL));
    typ_id__1ZE= 0;
    sz__YZE=((__UINTEGER_32 )sizeof(__LINKED_LIST_NODEoINODEo));
    if ((sz__YZE ==  0)) {
      result__VZE=LINKED_LIST_NODEoINODEo__;
    } else {
      typ_id__1ZE=__LINKED_LIST_NODEoINODEo__;
      clone_allocation_size__UM=(__UINTEGER_32)(clone_allocation_size__UM + sz__YZE);
      if ((typ_id__1ZE == (__INTEGER)(-  1))) {
        a__KIO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        new_size__LIO=(__UINTEGER_32)((__UINTEGER_32)(sz__YZE + a__KIO) & (__UINTEGER_32)(~ a__KIO));
        ptr_table__YUO=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__LIO / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
        next__XUO=((__POINTER )(NULL));
        result__ZUO=((__POINTER *)ptr_table__YUO)[ 0];
        if ((result__ZUO == (void *)NULL)) {
          result__ZUO=new_lab__2JB(new_size__LIO);
          next__XUO=(void *)((unsigned long)result__ZUO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__LIO)));
          ((__POINTER *)next__XUO)[ 0]=NULL;
          ((__POINTER *)ptr_table__YUO)[ 0]=next__XUO;
        } else {
          next__XUO=((__POINTER *)result__ZUO)[ 0];
          if ((next__XUO == (void *)NULL)) {
            if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__ZUO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__LIO <<  1)) <=  4096)) {
              next__XUO=(void *)((unsigned long)result__ZUO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__LIO)));
            } else {
              next__XUO=new_lab__2JB(new_size__LIO);
            };
            ((__POINTER *)next__XUO)[ 0]=NULL;
            ((__POINTER *)ptr_table__YUO)[ 0]=next__XUO;
          } else {
            ((__POINTER *)result__ZUO)[ 0]=(void *)((unsigned long)((__POINTER *)next__XUO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
            result__ZUO=next__XUO;
          };
        };
        ptr__WZE=result__ZUO;
      } else {
        t__UIO=((__UINTEGER_32 )typ_id__1ZE);
        a__RIO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        new_size__CVO=(__UINTEGER_32)((__UINTEGER_32)(sz__YZE + a__RIO) & (__UINTEGER_32)(~ a__RIO));
        ptr_table__5UO=((__POINTER )(&(table_type[(t__UIO)])));
        lab_type__BVO=(__UINTEGER_32)(t__UIO |  1);
        next__4UO=((__POINTER )(NULL));
        result__AVO=((__POINTER *)ptr_table__5UO)[ 0];
        if ((result__AVO == (void *)NULL)) {
          result__AVO=new_lab__2JB(lab_type__BVO);
          next__4UO=(void *)((unsigned long)result__AVO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__CVO)));
          ((__POINTER *)next__4UO)[ 0]=NULL;
          ((__POINTER *)ptr_table__5UO)[ 0]=next__4UO;
        } else {
          next__4UO=((__POINTER *)result__AVO)[ 0];
          if ((next__4UO == (void *)NULL)) {
            if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__AVO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__CVO <<  1)) <=  4096)) {
              next__4UO=(void *)((unsigned long)result__AVO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__CVO)));
            } else {
              next__4UO=new_lab__2JB(lab_type__BVO);
            };
            ((__POINTER *)next__4UO)[ 0]=NULL;
            ((__POINTER *)ptr_table__5UO)[ 0]=next__4UO;
          } else {
            ((__POINTER *)result__AVO)[ 0]=(void *)((unsigned long)((__POINTER *)next__4UO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
            result__AVO=next__4UO;
          };
        };
        ptr__WZE=result__AVO;
      };
      result__VZE=((__LINKED_LIST_NODEoINODEo *)ptr__WZE);
      *(result__VZE) = *(LINKED_LIST_NODEoINODEo__);
    };
    Self__QFG=((__LINKED_LIST_NODEoINODEo *)result__VZE);
    Self__QFG->item__YRE=other__K1B;
    Self__QFG->next__4MF=NULL;
    ((__LINKED_LIST_NODEoINODEo *)Self__GWD->last_link__UWD)->next__4MF=result__VZE;
    Self__GWD->parent_linked_collection__P1B.upper__L3B=(__INTEGER)(Self__GWD->parent_linked_collection__P1B.upper__L3B +  1);
    Self__GWD->last_link__UWD=result__VZE;
  };
  return(Self__J1B);
}

static void display__51B(__INODE *Self__A2B)
// ({INODE}) VoidRecursive, No inlinable.
{
  void *__tmp__E2B;
  void *__tmp__P2B,*__tmp__F3B,*__tmp__T3B,*__tmp__13B,*__tmp__B4B;
  void *__tmp__F4B;
  __INTEGER __tmp__N3B,Self__BPC,i__GRE;
  void *__tmp__E4B;
  __STRING *Self__4RE;
  __CHARACTER Self__HOC;
  __LINKED_LISToINODEo *Self__FRE;
  print__CHC(Self__A2B->name__B2B);
  print__CHC((&__string_67));
  switch (((struct ___OBJ *)Self__A2B->parent_guii__0)->__id) {
  case __INTERNAL_INODE__: {
    __tmp__E2B=(&__string_68);
  } break;
  case __MENU_H__: {
    __tmp__E2B=(&__string_69);
  } break;
  case __MENU_V__: {
    __tmp__E2B=(&__string_70);
  } break;
  };
  print__CHC(__tmp__E2B);
  print__CHC((&__string_71));
  if (((void *)Self__A2B->list__Q1B != (void *)NULL)) {
    switch (((struct ___OBJ *)Self__A2B->parent_guii__0)->__id) {
    case __INTERNAL_INODE__: {
      __tmp__P2B=base__O2B;
    } break;
    case __MENU_H__: {
      __tmp__P2B=base__O2B;
    } break;
    case __MENU_V__: {
      __tmp__P2B=base__O2B;
    } break;
    };
    put_string__4HC(((__STRING *)__tmp__P2B));
    Self__HOC=Self__A2B->operator__Q2B;
    if ((Self__HOC == '|')) {
      print__CHC((&__string_72));
    };
    if ((Self__HOC == '&')) {
      print__CHC((&__string_73));
    };
    if ((Self__HOC == '^')) {
      print__CHC((&__string_74));
    };
    switch (((struct ___OBJ *)Self__A2B->parent_guii__0)->__id) {
    case __INTERNAL_INODE__: {
      __tmp__F3B=base__O2B;
    } break;
    case __MENU_H__: {
      __tmp__F3B=base__O2B;
    } break;
    case __MENU_V__: {
      __tmp__F3B=base__O2B;
    } break;
    };
    put_string__4HC(((__STRING *)__tmp__F3B));
    print__CHC((&__string_75));
    __tmp__N3B=((__LINKED_LISToINODEo *)Self__A2B->list__Q1B)->parent_linked_collection__P1B.upper__L3B;
    Self__BPC= 1;
    while ((Self__BPC <= __tmp__N3B)) {
      switch (((struct ___OBJ *)Self__A2B->parent_guii__0)->__id) {
      case __INTERNAL_INODE__: {
        __tmp__T3B=base__O2B;
      } break;
      case __MENU_H__: {
        __tmp__T3B=base__O2B;
      } break;
      case __MENU_V__: {
        __tmp__T3B=base__O2B;
      } break;
      };
      put_string__4HC(((__STRING *)__tmp__T3B));
      print__CHC((&__string_76));
      if ((Self__BPC != ((__LINKED_LISToINODEo *)Self__A2B->list__Q1B)->parent_linked_collection__P1B.upper__L3B)) {
        switch (((struct ___OBJ *)Self__A2B->parent_guii__0)->__id) {
        case __INTERNAL_INODE__: {
          __tmp__13B=base__O2B;
        } break;
        case __MENU_H__: {
          __tmp__13B=base__O2B;
        } break;
        case __MENU_V__: {
          __tmp__13B=base__O2B;
        } break;
        };
        append__KFF(__tmp__13B,(&__string_77));
      } else {
        switch (((struct ___OBJ *)Self__A2B->parent_guii__0)->__id) {
        case __INTERNAL_INODE__: {
          __tmp__B4B=base__O2B;
        } break;
        case __MENU_H__: {
          __tmp__B4B=base__O2B;
        } break;
        case __MENU_V__: {
          __tmp__B4B=base__O2B;
        } break;
        };
        append__KFF(__tmp__B4B,(&__string_78));
      };
      Self__FRE=((__LINKED_LISToINODEo *)Self__A2B->list__Q1B);
      i__GRE=Self__BPC;
      if ((Self__BPC != Self__FRE->mem_idx__VWD)) {
        if ((Self__FRE->mem_idx__VWD > Self__BPC)) {
          Self__FRE->mem_idx__VWD= 1;
          Self__FRE->mem_lnk__XWD=Self__FRE->first_link__LWD;
        };
        while ((i__GRE != Self__FRE->mem_idx__VWD)) {
          Self__FRE->mem_lnk__XWD=((__LINKED_LIST_NODEoINODEo *)Self__FRE->mem_lnk__XWD)->next__4MF;
          Self__FRE->mem_idx__VWD=(__INTEGER)(Self__FRE->mem_idx__VWD +  1);
        };
      };
      __tmp__E4B=((__LINKED_LIST_NODEoINODEo *)Self__FRE->mem_lnk__XWD)->item__YRE;
      switch (((struct ___OBJ *)((__INODE *)__tmp__E4B)->parent_guii__0)->__id) {
      case __INTERNAL_INODE__: {
        display__51B(__tmp__E4B);
      } break;
      case __MENU_H__: {
        display__51B(__tmp__E4B);
      } break;
      case __MENU_V__: {
        display__51B(__tmp__E4B);
      } break;
      };
      switch (((struct ___OBJ *)Self__A2B->parent_guii__0)->__id) {
      case __INTERNAL_INODE__: {
        __tmp__F4B=base__O2B;
      } break;
      case __MENU_H__: {
        __tmp__F4B=base__O2B;
      } break;
      case __MENU_V__: {
        __tmp__F4B=base__O2B;
      } break;
      };
      Self__4RE=((__STRING *)__tmp__F4B);
      if (( 4 > Self__4RE->count__G1D)) {
        Self__4RE->count__G1D= 0;
      } else {
        Self__4RE->count__G1D=(__INTEGER)(Self__4RE->count__G1D -  4);
      };
      Self__BPC=(__INTEGER)(Self__BPC +  1);
    };
  };
}

static __MEMORY* new_page__3IC()
// () With resultNo recursive, No inlinable.
{
  __POINTER mem__RED;
  __UINTEGER_32 cap__OED,old_size__AJC;
  __MEMORY *block__GJC;
  if ((capacity_max__HJC ==  0)) {
    mem__RED=((__POINTER )(NULL));
    cap__OED= 33554432;
    do {
      cap__OED=(__UINTEGER_32)(cap__OED <<  1);
      mem__RED=((__POINTER )(malloc((cap__OED))));
      if ((mem__RED != (void *)NULL)) {
        free((mem__RED));
      };
    } while ((! ((mem__RED == (void *)NULL) || (cap__OED ==  2147483648LU))));
    if ((mem__RED == (void *)NULL)) {
      cap__OED=(__UINTEGER_32)(cap__OED >>  1);
    };
    capacity_max__HJC=cap__OED;
    begin_memory__22=((__POINTER )(malloc((cap__OED))));
  };
  old_size__AJC=(__UINTEGER_32)(nb_page__OKB <<  26);
  nb_page__OKB=(__UINTEGER_32)(nb_page__OKB +  1);
  if (((__UINTEGER_32)(old_size__AJC +  67108864) > capacity_max__HJC)) {
    print__CHC((&__string_79));
    exit(( 1));
  };
  block__GJC=((__MEMORY *)(void *)((unsigned long)begin_memory__22 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )old_size__AJC))));
  block__GJC->previous_linear__4M= 4294967295LU;
  block__GJC->size_and_id__5M= 67108858;
  block__GJC->next_free__AN=first_free__2YD;
  block__GJC->previous_free__BN=NULL;
  if (((void *)first_free__2YD != (void *)NULL)) {
    ((__MEMORY *)first_free__2YD)->previous_free__BN=block__GJC;
  };
  first_free__2YD=block__GJC;
  last_block[((__UINTEGER_32)(nb_page__OKB -  1))] = (block__GJC);
  return(block__GJC);
}

static void to_busy__index__LAI(__MEMORY *Self__MAI,__UINTEGER_32 sz__NAI,__UINTEGER_32 idx__OAI)
// ({MEMORY},{UINTEGER_32},{UINTEGER_32}) VoidNo recursive, No inlinable.
{
  __MEMORY *new__VAI,*prev__KCE,*next__LCE,*Self__1YD,*Self__BXN;
  __UINTEGER_32 siz__PAI,new_size__SAI;
  new__VAI=NULL;
  prev__KCE=Self__MAI->previous_free__BN;
  next__LCE=Self__MAI->next_free__AN;
  if (((void *)prev__KCE == (void *)NULL)) {
    first_free__2YD=next__LCE;
  } else {
    ((__MEMORY *)prev__KCE)->next_free__AN=next__LCE;
  };
  if (((void *)next__LCE != (void *)NULL)) {
    ((__MEMORY *)next__LCE)->previous_free__BN=prev__KCE;
  };
  siz__PAI=Self__MAI->size_and_id__5M;
  new_size__SAI=(__UINTEGER_32)(siz__PAI - sz__NAI);
  if ((new_size__SAI > (__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )(MINIMUM_SIZE)) +  2) +  8))) {
    siz__PAI=sz__NAI;
    new__VAI=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__MAI) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )sz__NAI))));
    ((__MEMORY *)new__VAI)->previous_linear__4M=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__MAI) - (unsigned long)begin_memory__22))));
    ((__MEMORY *)new__VAI)->size_and_id__5M=(__UINTEGER_32)(new_size__SAI -  8);
    Self__1YD=((__MEMORY *)new__VAI);
    Self__1YD->next_free__AN=first_free__2YD;
    Self__1YD->previous_free__BN=NULL;
    if (((void *)first_free__2YD != (void *)NULL)) {
      ((__MEMORY *)first_free__2YD)->previous_free__BN=Self__1YD;
    };
    first_free__2YD=Self__1YD;
    if (((__UINTEGER_32)(((__MEMORY *)new__VAI)->size_and_id__5M &  2) !=  0)) {
      last_block[(idx__OAI)] = (new__VAI);
    } else {
      Self__BXN=((__MEMORY *)new__VAI);
      ((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__BXN) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__BXN->size_and_id__5M &  4294967292LU)))))->previous_linear__4M=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)new__VAI)) - (unsigned long)begin_memory__22))));
    };
  };
  Self__MAI->size_and_id__5M=(__UINTEGER_32)(siz__PAI |  1);
}

static void print__CHC(__STRING_CONSTANT *Self__DHC)
// ({STRING_CONSTANT}) VoidRecursive, No inlinable.
{
  put_string__4HC(Self__DHC);
}

static void put_string__4HC(void *s__AIC)
// ({STRING_CONSTANTxSTRING}) VoidNo recursive, No inlinable.
{
  __INTEGER __tmp__TIC,Self__RNC,limit_up__SNC;
  __CHARACTER __tmp__0IC;
  if (((struct ___OBJ *)s__AIC)->__id==__STRING_CONSTANT__) {
  };
  if (((struct ___OBJ *)s__AIC)->__id==__STRING_CONSTANT__) {
    __tmp__TIC=((__STRING_CONSTANT *)s__AIC)->count__MNC;
  } else {
    __tmp__TIC=((__STRING *)s__AIC)->count__G1D;
  };
  Self__RNC= 1;
  limit_up__SNC=__tmp__TIC;
  while ((Self__RNC <= limit_up__SNC)) {
    if (((struct ___OBJ *)s__AIC)->__id==__STRING_CONSTANT__) {
      __tmp__0IC=((__CHARACTER *)((__STRING_CONSTANT *)s__AIC)->storage__4PE)[(__INTEGER)(Self__RNC -  1)];
    } else {
      __tmp__0IC=((__CHARACTER *)((__STRING *)s__AIC)->storage__B1D)[(__INTEGER)(Self__RNC -  1)];
    };
    fputc((int)(__tmp__0IC),stdout);
    Self__RNC=(__INTEGER)(Self__RNC +  1);
  };
}

static void append__KFF(__STRING *Self__LFF,void *other__MFF)
// ({STRING},{STRING_CONSTANT}) VoidNo recursive, No inlinable.
{
  __INTEGER other_count__NFF,needed_capacity__OFF,__tmp__NGF,siz__QVO;
  __INTEGER Self__VVO,siz__NPJ,Self__YYJ,__tmp__V4H,Self__DZK;
  __INTEGER __tmp__WGF,i2__P1H,i1__O1H;
  __POINTER old_ptr__D4H,result__2JI,result__LFO,ptr_table__GVO;
  __POINTER next__FVO,result__HVO,p__OQJ,last__F1J,src__IPJ,dst__JPJ;
  __UINTEGER_32 __tmp__P4H,__tmp__R4H,a__FFO,old_size__SJI;
  __UINTEGER_32 old_size2__VJI,a__JFO,new_size__YJI,a__PFO;
  __UINTEGER_32 new_size__QFO,new_size2__RFO,a__4IO,new_size__5IO;
  __UINTEGER_32 a__UFO,__tmp__NLI,sz__BSJ,old_size__4RJ,prev__AMK;
  __UINTEGER_32 new_size__DMK;
  __MEMORY *mem__1JI,*result__MVO,*Self__YRJ,*nxt__2RJ,*result__3RJ;
  __MEMORY *result__XVO,*next__5LK,*new_free__4LK,*prev__SJO,*next__TJO;
  __CHARACTER *__tmp__MGF,*new__C4H,*__tmp__SGF,*__tmp__VGF,*Self__20H;
  __POINTER *na_src__SVO,*na_dst__UVO,*na_src__LPJ,*na_dst__MPJ;
  other_count__NFF=((__STRING_CONSTANT *)other__MFF)->count__MNC;
  needed_capacity__OFF=(__INTEGER)(Self__LFF->count__G1D + other_count__NFF);
  if ((Self__LFF->capacity__Y0D < needed_capacity__OFF)) {
    if ((Self__LFF->capacity__Y0D ==  0)) {
      Self__LFF->capacity__Y0D=needed_capacity__OFF;
      Self__LFF->storage__B1D=create__BNG(needed_capacity__OFF);
    } else {
      __tmp__MGF=Self__LFF->storage__B1D;
      __tmp__NGF=Self__LFF->capacity__Y0D;
      old_ptr__D4H=((__POINTER )((__CHARACTER *)__tmp__MGF));
      __tmp__P4H=((__UINTEGER_32 )__tmp__NGF);
      __tmp__R4H=((__UINTEGER_32 )needed_capacity__OFF);
      mem__1JI=NULL;
      result__2JI=((__POINTER )(NULL));
      a__FFO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      old_size__SJI=(__UINTEGER_32)((__UINTEGER_32)(__tmp__P4H + a__FFO) & (__UINTEGER_32)(~ a__FFO));
      old_size2__VJI=(__UINTEGER_32)(old_size__SJI + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
      a__JFO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__YJI=(__UINTEGER_32)((__UINTEGER_32)(__tmp__R4H + a__JFO) & (__UINTEGER_32)(~ a__JFO));
      if ((old_size2__VJI <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
        result__LFO=((__POINTER )(NULL));
        a__PFO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        new_size__QFO=(__UINTEGER_32)((__UINTEGER_32)(new_size__YJI + a__PFO) & (__UINTEGER_32)(~ a__PFO));
        new_size2__RFO=(__UINTEGER_32)(new_size__QFO + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
        if ((new_size2__RFO <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
          a__4IO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
          new_size__5IO=(__UINTEGER_32)((__UINTEGER_32)(new_size2__RFO + a__4IO) & (__UINTEGER_32)(~ a__4IO));
          ptr_table__GVO=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__5IO / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
          next__FVO=((__POINTER )(NULL));
          result__HVO=((__POINTER *)ptr_table__GVO)[ 0];
          if ((result__HVO == (void *)NULL)) {
            result__HVO=new_lab__2JB(new_size__5IO);
            next__FVO=(void *)((unsigned long)result__HVO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__5IO)));
            ((__POINTER *)next__FVO)[ 0]=NULL;
            ((__POINTER *)ptr_table__GVO)[ 0]=next__FVO;
          } else {
            next__FVO=((__POINTER *)result__HVO)[ 0];
            if ((next__FVO == (void *)NULL)) {
              if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__HVO - (unsigned long)begin_memory__22)))) &  4095) + (__UINTEGER_32)(new_size__5IO <<  1)) <=  4096)) {
                next__FVO=(void *)((unsigned long)result__HVO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__5IO)));
              } else {
                next__FVO=new_lab__2JB(new_size__5IO);
              };
              ((__POINTER *)next__FVO)[ 0]=NULL;
              ((__POINTER *)ptr_table__GVO)[ 0]=next__FVO;
            } else {
              ((__POINTER *)result__HVO)[ 0]=(void *)((unsigned long)((__POINTER *)next__FVO)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
              result__HVO=next__FVO;
            };
          };
          ((__POINTER *)result__HVO)[ 0]=((__POINTER ) 3);
          result__LFO=(void *)((unsigned long)result__HVO - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
        } else {
          result__MVO=first_free__2YD;
          while ((((void *)result__MVO != (void *)NULL) && ((__UINTEGER_32)(((__MEMORY *)result__MVO)->size_and_id__5M &  4294967292LU) < new_size__QFO))) {
            result__MVO=result__MVO->next_free__AN;
          };
          if (((void *)result__MVO == (void *)NULL)) {
            result__MVO=new_page__3IC();
          };
          to_busy__index__LAI(result__MVO,new_size__QFO,(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)result__MVO)) - (unsigned long)begin_memory__22)))) >>  26));
          result__LFO=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__MVO)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
        };
        result__2JI=result__LFO;
        siz__QVO=((__INTEGER )old_size__SJI);
        siz__QVO=(__INTEGER)(siz__QVO / ((__INTEGER )(sizeof(void *))));
        na_src__SVO=((__POINTER *)old_ptr__D4H);
        na_dst__UVO=((__POINTER *)result__LFO);
        Self__VVO=(__INTEGER)(siz__QVO -  1);
        while ((Self__VVO >=  0)) {
          na_dst__UVO[Self__VVO]=na_src__SVO[Self__VVO];
          Self__VVO=(__INTEGER)(Self__VVO -  1);
        };
        p__OQJ=(void *)((unsigned long)old_ptr__D4H - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))));
        a__UFO=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
        last__F1J=((__POINTER *)((__POINTER )(&(table_size[((__UINTEGER_32)((__UINTEGER_32)((__UINTEGER_32)(old_size2__VJI + a__UFO) & (__UINTEGER_32)(~ a__UFO)) / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))))[ 0];
        ((__POINTER *)p__OQJ)[ 0]=(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)(void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER *)last__F1J)[ 0]) - (unsigned long)((__POINTER ) 1)) & (unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 3)) - (unsigned long)((__POINTER ) 1)))) - (unsigned long)((__POINTER ) 1));
        ((__POINTER *)last__F1J)[ 0]=p__OQJ;
      } else {
        mem__1JI=((__MEMORY *)(void *)((unsigned long)old_ptr__D4H - (unsigned long)((__POINTER ) 8)));
        __tmp__NLI=(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)old_ptr__D4H - (unsigned long)begin_memory__22)))) >>  26);
        Self__YRJ=((__MEMORY *)mem__1JI);
        nxt__2RJ=NULL;
        result__3RJ=NULL;
        sz__BSJ= 0;
        old_size__4RJ=(__UINTEGER_32)(Self__YRJ->size_and_id__5M &  4294967292LU);
        if ((new_size__YJI > old_size__4RJ)) {
          if ((! ((__UINTEGER_32)(Self__YRJ->size_and_id__5M &  2) !=  0))) {
            nxt__2RJ=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__YRJ) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__YRJ->size_and_id__5M &  4294967292LU)))));
            sz__BSJ=(__UINTEGER_32)((__UINTEGER_32)(new_size__YJI - old_size__4RJ) -  8);
            if ((((__UINTEGER_32)(((__MEMORY *)nxt__2RJ)->size_and_id__5M &  1) ==  0) && ((__UINTEGER_32)(((__MEMORY *)nxt__2RJ)->size_and_id__5M &  4294967292LU) >= sz__BSJ))) {
              to_busy__index__LAI(nxt__2RJ,sz__BSJ,__tmp__NLI);
              Self__YRJ->size_and_id__5M=(__UINTEGER_32)((__UINTEGER_32)(Self__YRJ->size_and_id__5M + (__UINTEGER_32)(nxt__2RJ->size_and_id__5M &  4294967294LU)) +  8);
              if (((__UINTEGER_32)(Self__YRJ->size_and_id__5M &  2) !=  0)) {
                last_block[(__tmp__NLI)] = (Self__YRJ);
              } else {
                nxt__2RJ=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__YRJ) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__YRJ->size_and_id__5M &  4294967292LU)))));
                ((__MEMORY *)nxt__2RJ)->previous_linear__4M=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__YRJ) - (unsigned long)begin_memory__22))));
              };
              result__3RJ=Self__YRJ;
            };
          };
          if (((void *)result__3RJ == (void *)NULL)) {
            result__XVO=first_free__2YD;
            while ((((void *)result__XVO != (void *)NULL) && ((__UINTEGER_32)(((__MEMORY *)result__XVO)->size_and_id__5M &  4294967292LU) < new_size__YJI))) {
              result__XVO=result__XVO->next_free__AN;
            };
            if (((void *)result__XVO == (void *)NULL)) {
              result__XVO=new_page__3IC();
            };
            to_busy__index__LAI(result__XVO,new_size__YJI,(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)result__XVO)) - (unsigned long)begin_memory__22)))) >>  26));
            result__3RJ=result__XVO;
            src__IPJ=(void *)((unsigned long)((__POINTER )Self__YRJ) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
            dst__JPJ=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__XVO)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
            siz__NPJ=((__INTEGER )old_size__4RJ);
            siz__NPJ=(__INTEGER)(siz__NPJ / ((__INTEGER )(sizeof(void *))));
            na_src__LPJ=((__POINTER *)src__IPJ);
            na_dst__MPJ=((__POINTER *)dst__JPJ);
            Self__YYJ=(__INTEGER)(siz__NPJ -  1);
            while ((Self__YYJ >=  0)) {
              na_dst__MPJ[Self__YYJ]=na_src__LPJ[Self__YYJ];
              Self__YYJ=(__INTEGER)(Self__YYJ -  1);
            };
            prev__AMK=Self__YRJ->previous_linear__4M;
            next__5LK=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__YRJ) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__YRJ->size_and_id__5M &  4294967292LU)))));
            new_free__4LK=((__MEMORY *)(void *)((unsigned long)begin_memory__22 - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )prev__AMK))));
            new_size__DMK=(__UINTEGER_32)(Self__YRJ->size_and_id__5M &  4294967294LU);
            if (((prev__AMK ==  4294967295LU) || ((__UINTEGER_32)(new_free__4LK->size_and_id__5M &  1) !=  0))) {
              new_free__4LK=Self__YRJ;
              Self__YRJ->next_free__AN=first_free__2YD;
              Self__YRJ->previous_free__BN=NULL;
              if (((void *)first_free__2YD != (void *)NULL)) {
                ((__MEMORY *)first_free__2YD)->previous_free__BN=Self__YRJ;
              };
              first_free__2YD=Self__YRJ;
            } else {
              new_size__DMK=(__UINTEGER_32)((__UINTEGER_32)(new_size__DMK + new_free__4LK->size_and_id__5M) +  8);
            };
            if (((! ((__UINTEGER_32)(Self__YRJ->size_and_id__5M &  2) !=  0)) && ((__UINTEGER_32)(next__5LK->size_and_id__5M &  1) ==  0))) {
              new_size__DMK=(__UINTEGER_32)((__UINTEGER_32)(new_size__DMK + next__5LK->size_and_id__5M) +  8);
              prev__SJO=next__5LK->previous_free__BN;
              next__TJO=next__5LK->next_free__AN;
              if (((void *)prev__SJO == (void *)NULL)) {
                first_free__2YD=next__TJO;
              } else {
                ((__MEMORY *)prev__SJO)->next_free__AN=next__TJO;
              };
              if (((void *)next__TJO != (void *)NULL)) {
                ((__MEMORY *)next__TJO)->previous_free__BN=prev__SJO;
              };
            };
            new_free__4LK->size_and_id__5M=new_size__DMK;
            if (((__UINTEGER_32)(new_free__4LK->size_and_id__5M &  2) !=  0)) {
              last_block[(__tmp__NLI)] = (new_free__4LK);
            } else {
              next__5LK=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__YRJ) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__YRJ->size_and_id__5M &  4294967292LU)))));
              next__5LK->previous_linear__4M=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )new_free__4LK) - (unsigned long)begin_memory__22))));
            };
          };
        } else {
          result__3RJ=Self__YRJ;
        };
        result__2JI=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__3RJ)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
      };
      new__C4H=((__CHARACTER *)result__2JI);
      __tmp__V4H=(__INTEGER)(needed_capacity__OFF -  1);
      Self__DZK=__tmp__NGF;
      while ((Self__DZK <= __tmp__V4H)) {
        new__C4H[Self__DZK]='\0';
        Self__DZK=(__INTEGER)(Self__DZK +  1);
      };
      Self__LFF->storage__B1D=new__C4H;
      Self__LFF->capacity__Y0D=needed_capacity__OFF;
    };
  };
  __tmp__SGF=Self__LFF->storage__B1D;
  __tmp__VGF=((__STRING_CONSTANT *)other__MFF)->storage__4PE;
  __tmp__WGF=Self__LFF->count__G1D;
  Self__20H=((__CHARACTER *)__tmp__SGF);
  i2__P1H= 0;
  i1__O1H=__tmp__WGF;
  while ((i2__P1H != other_count__NFF)) {
    Self__20H[i1__O1H]=((__CHARACTER *)__tmp__VGF)[i2__P1H];
    i2__P1H=(__INTEGER)(i2__P1H +  1);
    i1__O1H=(__INTEGER)(i1__O1H +  1);
  };
  Self__LFF->count__G1D=needed_capacity__OFF;
}

//==========================//
// DEBUG MANAGER            //
//==========================//

void print_string(char *str) 
{ 
  while (*str!=0) {
    print_char(*str); 
    str++; 
  };
}  

