.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LISAAC 1 "October 28, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
shorter \- The lisaac documentation generator
.SH SYNOPSIS
.B shorter
.RI "<input_file[.li]> [ options ]"
.SH DESCRIPTION
This manual page documents briefly the
.B shorter
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBshorter\fP generate for a .li file the corresponding documentation in different format.
.SH OPTIONS
.TP
.B \-o <output>
output file or directory (default: <input_file.ext>).
.TP
.B \-p
include `Section Private'.
.TP
.B \-c
include code source.
.TP
.B \-r
recurcive builder documentation
.TP
.B \-f <format_file>
formatting description file (html, html_raw, latex)                   
.SH EXAMPLE
* Build latex documentation:                                     
  shorter -c -p -f latex hello_world.li                   
                                                          
* Build html documentation:                               
  shorter -r -f html ~/lisaac/lib
.SH AUTHOR
shorter was written by Benoit SONNTAG <bsonntag@loria.fr>.
.PP
This manual page was written by picca frederic <picca@synchrotron-soleil.fr>,
for the Debian project (but may be used by others).
