// C code generated by Lisaac compiler (www.isaacOS.com) //
int arg_count;
char **arg_vector;

//==========================//
// EXTERNAL                 //
//==========================//

// FLOAT_REAL
#include <math.h>
// MEMORY

#define MINIMUM_SIZE 256  
void *table_size[MINIMUM_SIZE/sizeof(void *)];
void *last_block[64];

// SYSTEM
#include <time.h>
// SYSTEM_IO

#include <stdio.h>
#include <stdlib.h>
  
// Hardware 'print_char'
void print_char(char car)
{
  fputc(car,stdout);
}

// Hardware 'exit'
int die_with_code(int code)
{
  exit(code);
}



//==========================//
// TYPE                     //
//==========================//

// Generic Object
struct ___OBJ {
  unsigned long __id;
};

// NULL
#ifndef NULL
#define NULL ((void *)0)
#endif

// POINTER
typedef void * __POINTER;

// UINTEGER_32
typedef unsigned long __UINTEGER_32;

// INTEGER
typedef int __INTEGER;

// CHARACTER
typedef char __CHARACTER;

// STRING
#define __STRING__ 4
typedef struct STRING_struct __STRING;
struct STRING_struct {
  unsigned long __id;
  __INTEGER count__EW;
  __INTEGER capacity__GW;
  __CHARACTER *storage__3QC;
};
__STRING STRING_={__STRING__};
#define STRING__ (&STRING_)

// MEMORY
#define __MEMORY__ 0
typedef struct MEMORY_struct __MEMORY;
struct MEMORY_struct {
  volatile __UINTEGER_32 previous_linear__ND;
  volatile __UINTEGER_32 size_and_id__OD;
  __MEMORY *next_free__PD;
  __MEMORY *previous_free__QD;
} __attribute__ ((packed));
__MEMORY MEMORY_;
#define MEMORY__ (&MEMORY_)

// REAL_64
typedef double __REAL_64;

// ARRAYED_COLLECTION[STRING]
#define __ARRAYED_COLLECTIONoSTRINGo__ 1
typedef struct ARRAYED_COLLECTIONoSTRINGo_struct __ARRAYED_COLLECTIONoSTRINGo;
struct ARRAYED_COLLECTIONoSTRINGo_struct {
  __INTEGER capacity__JSC;
  __INTEGER upper__VSC;
  void **storage__GNC;
};
__ARRAYED_COLLECTIONoSTRINGo ARRAYED_COLLECTIONoSTRINGo_;
#define ARRAYED_COLLECTIONoSTRINGo__ (&ARRAYED_COLLECTIONoSTRINGo_)

// FAST_ARRAY[STRING]
#define __FAST_ARRAYoSTRINGo__ 2
typedef struct FAST_ARRAYoSTRINGo_struct __FAST_ARRAYoSTRINGo;
struct FAST_ARRAYoSTRINGo_struct {
  __ARRAYED_COLLECTIONoSTRINGo parent_arrayed_collection__WC;
};
__FAST_ARRAYoSTRINGo FAST_ARRAYoSTRINGo_;
#define FAST_ARRAYoSTRINGo__ (&FAST_ARRAYoSTRINGo_)

// NUMERIC
#define __NUMERIC__ 3
typedef struct NUMERIC_struct __NUMERIC;
struct NUMERIC_struct {
  void *Nothing;
};
__NUMERIC NUMERIC_;
#define NUMERIC__ (&NUMERIC_)

// OBJECT
#define __OBJECT__ 4
typedef struct OBJECT_struct __OBJECT;
struct OBJECT_struct {
  void *Nothing;
};
__OBJECT OBJECT_;
#define OBJECT__ (&OBJECT_)

// STRING_CONSTANT
#define __STRING_CONSTANT__ 5
typedef struct STRING_CONSTANT_struct __STRING_CONSTANT;
struct STRING_CONSTANT_struct {
  unsigned long __id;
  __INTEGER count__YHB;
  __CHARACTER *storage__0LE;
};
__STRING_CONSTANT STRING_CONSTANT_={__STRING_CONSTANT__};
#define STRING_CONSTANT__ (&STRING_CONSTANT_)

// TRUE
#define TRUE__ 1

// FALSE
#define FALSE__ 0

// NBODY
#define __NBODY__ 5
typedef struct NBODY_struct __NBODY;
struct NBODY_struct {
  void *Nothing;
};
__NBODY NBODY_;
#define NBODY__ (&NBODY_)

// PLANET
#define __PLANET__ 6
typedef struct PLANET_struct __PLANET;
struct PLANET_struct {
  __REAL_64 mass__AE;
  __REAL_64 x__EE;
  __REAL_64 y__GE;
  __REAL_64 z__IE;
  __REAL_64 vx__NE;
  __REAL_64 vy__RE;
  __REAL_64 vz__VE;
};
__PLANET PLANET_;
#define PLANET__ (&PLANET_)

// INTEGER_8
typedef signed char __INTEGER_8;

// BOOLEAN
typedef char __BOOLEAN;


void *table_type[7];

//==========================//
// GLOBAL                   //
//==========================//

void *parent_numeric__H;
__POINTER begin_memory__3RB;
__UINTEGER_32 nb_page__M2B;
__MEMORY *first_free__MMD;
__UINTEGER_32 capacity_max__OTD;
void *string_tmp__UK;
__UINTEGER_32 clone_allocation_size__F5;
__INTEGER nbodies__AB;
__PLANET *bodies__GB;
__PLANET *b__XXD;
__PLANET *b2__CYD;
__REAL_64 dx__IYD;
__REAL_64 dy__OYD;
__REAL_64 dz__UYD;
__REAL_64 distance__CZD;
__REAL_64 mag__KZD;
__REAL_64 solar_mass__4D;
__REAL_64 days_per_year__KE;
__REAL_64 pi__HR;

//==========================//
// STRING CONSTANT          //
//==========================//

__STRING_CONSTANT __string_1={__STRING_CONSTANT__,5,"%.9f\n"};
__STRING_CONSTANT __string_2={__STRING_CONSTANT__,19,"Not enough memory.\n"};

//==========================//
// FUNCTION HEADER          //
//==========================//

// Debug Manager
void print_string(char *str);
// Source code
static __POINTER new_lab__01B(__UINTEGER_32 t__21B);
static void** create__UGG(__INTEGER nb_elements__WGG);
static __STRING* create__R3(__INTEGER needed_capacity__T3);
static void add_last__ZDE(__STRING *Self__0DE,__CHARACTER ch__1DE);
static __POINTER realloc_dynamic__old_size__new_size__EGI(__POINTER p__GGI,__UINTEGER_32 old_sz__HGI,__UINTEGER_32 new_sz__IGI);
static __MEMORY* search__JLD(__UINTEGER_32 new_size__LLD);
void offset_momentum(__INTEGER n__NG);
__REAL_64 energy(__INTEGER n__2H);
static void print_format_c__RK(__REAL_64 Self__SK);
void advance(__REAL_64 dt__NXD,__INTEGER n__OXD);
static __MEMORY* new_page__ETD();
static __CHARACTER* create__MDG(__INTEGER nb_elements__ODG);
static void to_busy__index__XIH(__MEMORY *Self__YIH,__UINTEGER_32 sz__ZIH,__UINTEGER_32 idx__0IH);
static void put_string__B5C(void *s__D5C);

//==========================//
// SOURCE CODE              //
//==========================//

int main(int argc,char **argv)
{
  void *str__NL;
  __INTEGER new_count__3W,typ_id__X4,Self__IX,limit_up__JX,idx__QFE;
  __INTEGER i__DHE,new_capacity__3HE,__tmp__BJE,__tmp__OUH,Self__T0L;
  __INTEGER state__OIL,result__RIL,i__NIL,__tmp__OTS,__tmp__QTS;
  __INTEGER Self__1K,limit_up__2K;
  __POINTER ptr__S4,ptr_table__RWS,next__QWS,result__SWS,ptr_table__XWS;
  __POINTER next__WWS,result__YWS,result__2US,ptr_table__DQB,next__IQB;
  __POINTER result__GQB;
  __UINTEGER_32 sz__U4,a__2QS,new_size__YKB,t__BMB,a__CRS,new_size__0WS;
  __UINTEGER_32 lab_type__ZWS,sz__4US,a__3US,new_size__5US;
  __UINTEGER_32 new_size2__AVS,a__BVS,new_size__CVS;
  __STRING *Self__BHE,*Self__LIL;
  __PLANET *Self__CE,*Self__0E,*Self__LF,*Self__2F;
  __CHARACTER *arg__ML,*Self__EFE,*p__CHE,*__tmp__PTS;
  __FAST_ARRAYoSTRINGo *result__R4,*Self__ASC,*Self__1HE;
  void *result__LL;
  __BOOLEAN __tmp__LIE,negative__QIL,__tmp__3JL,result__V3P,__tmp__QKL;
  __BOOLEAN __tmp__FLL,result__SRO,__tmp__MML,result__ESO,result__LFP;
  void **__tmp__AJE,**new__1TH;
  __CHARACTER cc__PIL;
  __PLANET *Result__4C;
  arg_count  = argc;
  arg_vector = argv;
  ARRAYED_COLLECTIONoSTRINGo__->storage__GNC=NULL;
  ARRAYED_COLLECTIONoSTRINGo__->capacity__JSC= 0;
  ARRAYED_COLLECTIONoSTRINGo__->upper__VSC= 0;
  FAST_ARRAYoSTRINGo__->parent_arrayed_collection__WC=(*ARRAYED_COLLECTIONoSTRINGo__);
  parent_numeric__H=NUMERIC__;
  clone_allocation_size__F5= 0;
  STRING_CONSTANT__->count__YHB=((__INTEGER )((0)));
  STRING__->count__EW= 0;
  STRING_CONSTANT__->storage__0LE=((__CHARACTER *)(NULL));
  STRING__->storage__3QC=NULL;
  nb_page__M2B= 0;
  MEMORY__->size_and_id__OD= 0;
  capacity_max__OTD= 0;
  begin_memory__3RB=((__POINTER )(NULL));
  MEMORY__->previous_linear__ND= 0;
  first_free__MMD=NULL;
  MEMORY__->next_free__PD=NULL;
  MEMORY__->previous_free__QD=NULL;
  STRING__->capacity__GW= 0;
  arg__ML=NULL;
  str__NL=NULL;
  new_count__3W=((__INTEGER )(arg_count));
  result__R4=NULL;
  ptr__S4=((__POINTER )(NULL));
  typ_id__X4= 0;
  sz__U4=((__UINTEGER_32 )sizeof(__FAST_ARRAYoSTRINGo));
  if ((sz__U4 ==  0)) {
    result__R4=FAST_ARRAYoSTRINGo__;
  } else {
    typ_id__X4=__FAST_ARRAYoSTRINGo__;
    clone_allocation_size__F5=sz__U4;
    if ((typ_id__X4 == (__INTEGER)(-  1))) {
      a__2QS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__YKB=(__UINTEGER_32)((__UINTEGER_32)(sz__U4 + a__2QS) & (__UINTEGER_32)(~ a__2QS));
      ptr_table__RWS=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__YKB / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__QWS=((__POINTER )(NULL));
      result__SWS=((__POINTER *)ptr_table__RWS)[ 0];
      if ((result__SWS == (void *)NULL)) {
        result__SWS=new_lab__01B(new_size__YKB);
        next__QWS=(void *)((unsigned long)result__SWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__YKB)));
        ((__POINTER *)next__QWS)[ 0]=NULL;
        ((__POINTER *)ptr_table__RWS)[ 0]=next__QWS;
      } else {
        next__QWS=((__POINTER *)result__SWS)[ 0];
        if ((next__QWS == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__SWS - (unsigned long)begin_memory__3RB)))) &  4095) + (__UINTEGER_32)(new_size__YKB <<  1)) <=  4096)) {
            next__QWS=(void *)((unsigned long)result__SWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__YKB)));
          } else {
            next__QWS=new_lab__01B(new_size__YKB);
          };
          ((__POINTER *)next__QWS)[ 0]=NULL;
          ((__POINTER *)ptr_table__RWS)[ 0]=next__QWS;
        } else {
          ((__POINTER *)result__SWS)[ 0]=(void *)((unsigned long)((__POINTER *)next__QWS)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__SWS=next__QWS;
        };
      };
      ptr__S4=result__SWS;
    } else {
      t__BMB=((__UINTEGER_32 )typ_id__X4);
      a__CRS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__0WS=(__UINTEGER_32)((__UINTEGER_32)(sz__U4 + a__CRS) & (__UINTEGER_32)(~ a__CRS));
      ptr_table__XWS=((__POINTER )(&(table_type[(t__BMB)])));
      lab_type__ZWS=(__UINTEGER_32)(t__BMB |  1);
      next__WWS=((__POINTER )(NULL));
      result__YWS=((__POINTER *)ptr_table__XWS)[ 0];
      if ((result__YWS == (void *)NULL)) {
        result__YWS=new_lab__01B(lab_type__ZWS);
        next__WWS=(void *)((unsigned long)result__YWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__0WS)));
        ((__POINTER *)next__WWS)[ 0]=NULL;
        ((__POINTER *)ptr_table__XWS)[ 0]=next__WWS;
      } else {
        next__WWS=((__POINTER *)result__YWS)[ 0];
        if ((next__WWS == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__YWS - (unsigned long)begin_memory__3RB)))) &  4095) + (__UINTEGER_32)(new_size__0WS <<  1)) <=  4096)) {
            next__WWS=(void *)((unsigned long)result__YWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__0WS)));
          } else {
            next__WWS=new_lab__01B(lab_type__ZWS);
          };
          ((__POINTER *)next__WWS)[ 0]=NULL;
          ((__POINTER *)ptr_table__XWS)[ 0]=next__WWS;
        } else {
          ((__POINTER *)result__YWS)[ 0]=(void *)((unsigned long)((__POINTER *)next__WWS)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__YWS=next__WWS;
        };
      };
      ptr__S4=result__YWS;
    };
    result__R4=((__FAST_ARRAYoSTRINGo *)ptr__S4);
    *(result__R4) = *(FAST_ARRAYoSTRINGo__);
  };
  Self__ASC=((__FAST_ARRAYoSTRINGo *)result__R4);
  if ((Self__ASC->parent_arrayed_collection__WC.capacity__JSC < new_count__3W)) {
    Self__ASC->parent_arrayed_collection__WC.storage__GNC=create__UGG(new_count__3W);
    Self__ASC->parent_arrayed_collection__WC.capacity__JSC=new_count__3W;
  };
  Self__ASC->parent_arrayed_collection__WC.upper__VSC=(__INTEGER)(-  1);
  result__LL=result__R4;
  Self__IX= 0;
  limit_up__JX=(__INTEGER)(((__INTEGER )(arg_count)) -  1);
  while ((Self__IX <= limit_up__JX)) {
    arg__ML=((__CHARACTER *)(arg_vector[(Self__IX)]));
    Self__EFE=((__CHARACTER *)arg__ML);
    idx__QFE= 0;
    while ((! ((idx__QFE >  1024) || ('\0' == Self__EFE[idx__QFE])))) {
      idx__QFE=(__INTEGER)(idx__QFE +  1);
    };
    str__NL=create__R3(idx__QFE);
    Self__BHE=((__STRING *)str__NL);
    p__CHE=arg__ML;
    i__DHE= 0;
    Self__BHE->count__EW= 0;
    while ((((__CHARACTER *)p__CHE)[i__DHE] != '\0')) {
      add_last__ZDE(Self__BHE,((__CHARACTER *)p__CHE)[i__DHE]);
      i__DHE=(__INTEGER)(i__DHE +  1);
    };
    Self__1HE=((__FAST_ARRAYoSTRINGo *)result__LL);
    new_capacity__3HE= 0;
    if (((__INTEGER)(Self__1HE->parent_arrayed_collection__WC.upper__VSC +  1) <= (__INTEGER)(Self__1HE->parent_arrayed_collection__WC.capacity__JSC -  1))) {
      Self__1HE->parent_arrayed_collection__WC.upper__VSC=(__INTEGER)(Self__1HE->parent_arrayed_collection__WC.upper__VSC +  1);
      __tmp__LIE=TRUE__;
    } else {
      __tmp__LIE=FALSE__;
    };
    if ((! __tmp__LIE)) {
      if ((Self__1HE->parent_arrayed_collection__WC.capacity__JSC ==  0)) {
        Self__1HE->parent_arrayed_collection__WC.storage__GNC=create__UGG( 2);
        Self__1HE->parent_arrayed_collection__WC.capacity__JSC= 2;
        Self__1HE->parent_arrayed_collection__WC.upper__VSC= 0;
      } else {
        new_capacity__3HE=(__INTEGER)(Self__1HE->parent_arrayed_collection__WC.capacity__JSC <<  1);
        __tmp__AJE=Self__1HE->parent_arrayed_collection__WC.storage__GNC;
        __tmp__BJE=Self__1HE->parent_arrayed_collection__WC.capacity__JSC;
        new__1TH=((void **)realloc_dynamic__old_size__new_size__EGI(((__POINTER )((void **)__tmp__AJE)),((__UINTEGER_32 )(__INTEGER)(__tmp__BJE * ((__INTEGER )(sizeof(void *))))),((__UINTEGER_32 )(__INTEGER)(new_capacity__3HE * ((__INTEGER )(sizeof(void *)))))));
        __tmp__OUH=(__INTEGER)(new_capacity__3HE -  1);
        Self__T0L=__tmp__BJE;
        while ((Self__T0L <= __tmp__OUH)) {
          new__1TH[Self__T0L]=NULL;
          Self__T0L=(__INTEGER)(Self__T0L +  1);
        };
        Self__1HE->parent_arrayed_collection__WC.storage__GNC=new__1TH;
        Self__1HE->parent_arrayed_collection__WC.capacity__JSC=new_capacity__3HE;
        Self__1HE->parent_arrayed_collection__WC.upper__VSC=(__INTEGER)(Self__1HE->parent_arrayed_collection__WC.upper__VSC +  1);
      };
    };
    ((void **)Self__1HE->parent_arrayed_collection__WC.storage__GNC)[Self__1HE->parent_arrayed_collection__WC.upper__VSC]=str__NL;
    Self__IX=(__INTEGER)(Self__IX +  1);
  };
  nbodies__AB= 0;
  bodies__GB=NULL;
  pi__HR=((__REAL_64 )(3.141592653589793));
  solar_mass__4D=(__REAL_64)((__REAL_64)(pi__HR * pi__HR) * ((__REAL_64 )4.0));
  PLANET__->mass__AE=((__REAL_64 ) 0);
  PLANET__->x__EE=((__REAL_64 ) 0);
  PLANET__->y__GE=((__REAL_64 ) 0);
  PLANET__->z__IE=((__REAL_64 ) 0);
  days_per_year__KE=((__REAL_64 )365.24);
  PLANET__->vx__NE=((__REAL_64 ) 0);
  PLANET__->vy__RE=((__REAL_64 ) 0);
  PLANET__->vz__VE=((__REAL_64 ) 0);
  string_tmp__UK=create__R3( 32);
  b__XXD=NULL;
  b2__CYD=NULL;
  dx__IYD=((__REAL_64 ) 0);
  dy__OYD=((__REAL_64 ) 0);
  dz__UYD=((__REAL_64 ) 0);
  distance__CZD=((__REAL_64 ) 0);
  mag__KZD=((__REAL_64 ) 0);
  Self__LIL=((__STRING *)((void **)((__FAST_ARRAYoSTRINGo *)result__R4)->parent_arrayed_collection__WC.storage__GNC)[ 1]);
  state__OIL= 0;
  cc__PIL='\0';
  negative__QIL=FALSE__;
  result__RIL= 0;
  i__NIL= 1;
  __tmp__OTS=Self__LIL->count__EW;
  __tmp__PTS=Self__LIL->storage__3QC;
  __tmp__QTS=Self__LIL->count__EW;
  while ((i__NIL <= __tmp__OTS)) {
    cc__PIL=((__CHARACTER *)__tmp__PTS)[(__INTEGER)(i__NIL -  1)];
    if ((state__OIL ==  0)) {
      if ((((((((cc__PIL == ' ') || (cc__PIL == '\t')) || (cc__PIL == '\n')) || (cc__PIL == '\r')) || (cc__PIL == '\0')) || (cc__PIL == '\f')) || (cc__PIL == '\v'))) {
        __tmp__3JL=TRUE__;
      } else {
        result__V3P=(cc__PIL == '+');
        if (result__V3P) {
          state__OIL= 1;
        };
        __tmp__3JL=result__V3P;
      };
      if ((! __tmp__3JL)) {
        if ((cc__PIL == '-')) {
          negative__QIL=TRUE__;
          state__OIL= 1;
        } else {
          result__RIL=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__PIL)) -  48);
          state__OIL= 2;
        };
      };
      __tmp__QKL=TRUE__;
    } else {
      __tmp__QKL=FALSE__;
    };
    if (__tmp__QKL) {
      __tmp__FLL=TRUE__;
    } else {
      result__SRO=(state__OIL ==  1);
      if (result__SRO) {
        result__RIL=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__PIL)) -  48);
        if (negative__QIL) {
          result__RIL=(__INTEGER)(- result__RIL);
        };
        state__OIL= 2;
      };
      __tmp__FLL=result__SRO;
    };
    if (__tmp__FLL) {
      __tmp__MML=TRUE__;
    } else {
      result__ESO=(state__OIL ==  2);
      if (result__ESO) {
        result__LFP=FALSE__;
        if ((((__INTEGER_8 )cc__PIL) >= ((__INTEGER_8 )'0'))) {
          result__LFP=(((__INTEGER_8 )cc__PIL) <= ((__INTEGER_8 )'9'));
        };
        if (result__LFP) {
          if (negative__QIL) {
            result__RIL=(__INTEGER)((__INTEGER)( 10 * result__RIL) - (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__PIL)) -  48));
          } else {
            result__RIL=(__INTEGER)((__INTEGER)( 10 * result__RIL) + (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__PIL)) -  48));
          };
        } else {
          state__OIL= 3;
        };
      };
      __tmp__MML=result__ESO;
    };
    if ((! __tmp__MML)) {
      if ((state__OIL ==  3)) {
        i__NIL=__tmp__QTS;
      };
    };
    i__NIL=(__INTEGER)(i__NIL +  1);
  };
  nbodies__AB= 4;
  sz__4US=((__UINTEGER_32 )(__INTEGER)(sizeof(__PLANET) <<  2));
  result__2US=((__POINTER )(NULL));
  a__3US=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__5US=(__UINTEGER_32)((__UINTEGER_32)(sz__4US + a__3US) & (__UINTEGER_32)(~ a__3US));
  new_size2__AVS=(__UINTEGER_32)(new_size__5US + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__AVS <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__BVS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__CVS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__AVS + a__BVS) & (__UINTEGER_32)(~ a__BVS));
    ptr_table__DQB=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__CVS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
    next__IQB=((__POINTER )(NULL));
    result__GQB=((__POINTER *)ptr_table__DQB)[ 0];
    if ((result__GQB == (void *)NULL)) {
      result__GQB=new_lab__01B(new_size__CVS);
      next__IQB=(void *)((unsigned long)result__GQB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__CVS)));
      ((__POINTER *)next__IQB)[ 0]=NULL;
      ((__POINTER *)ptr_table__DQB)[ 0]=next__IQB;
    } else {
      next__IQB=((__POINTER *)result__GQB)[ 0];
      if ((next__IQB == (void *)NULL)) {
        if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__GQB - (unsigned long)begin_memory__3RB)))) &  4095) + (__UINTEGER_32)(new_size__CVS <<  1)) <=  4096)) {
          next__IQB=(void *)((unsigned long)result__GQB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__CVS)));
        } else {
          next__IQB=new_lab__01B(new_size__CVS);
        };
        ((__POINTER *)next__IQB)[ 0]=NULL;
        ((__POINTER *)ptr_table__DQB)[ 0]=next__IQB;
      } else {
        ((__POINTER *)result__GQB)[ 0]=(void *)((unsigned long)((__POINTER *)next__IQB)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
        result__GQB=next__IQB;
      };
    };
    ((__POINTER *)result__GQB)[ 0]=((__POINTER ) 3);
    result__2US=(void *)((unsigned long)result__GQB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__2US=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__JLD(new_size__5US))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__4C=((__PLANET *)result__2US);
  bodies__GB=Result__4C;
  Result__4C[ 0].mass__AE=solar_mass__4D;
  Self__CE=&(Result__4C[ 1]);
  Self__CE->x__EE=((__REAL_64 )(4.84143144246472090E+00));
  Self__CE->y__GE=((__REAL_64 )(-1.16032004402742839E+00));
  Self__CE->z__IE=((__REAL_64 )(-1.03622044471123109E-01));
  Self__CE->vx__NE=(__REAL_64)(((__REAL_64 )(1.66007664274403694E-03)) * days_per_year__KE);
  Self__CE->vy__RE=(__REAL_64)(((__REAL_64 )(7.69901118419740425E-03)) * days_per_year__KE);
  Self__CE->vz__VE=(__REAL_64)(((__REAL_64 )(-6.90460016972063023E-05)) * days_per_year__KE);
  Self__CE->mass__AE=(__REAL_64)(((__REAL_64 )(9.54791938424326609E-04)) * solar_mass__4D);
  Self__0E=&(Result__4C[ 2]);
  Self__0E->x__EE=((__REAL_64 )(8.34336671824457987E+00));
  Self__0E->y__GE=((__REAL_64 )(4.12479856412430479E+00));
  Self__0E->z__IE=((__REAL_64 )(-4.03523417114321381E-01));
  Self__0E->vx__NE=(__REAL_64)(((__REAL_64 )(-2.76742510726862411E-03)) * days_per_year__KE);
  Self__0E->vy__RE=(__REAL_64)(((__REAL_64 )(4.99852801234917238E-03)) * days_per_year__KE);
  Self__0E->vz__VE=(__REAL_64)(((__REAL_64 )(2.30417297573763929E-05)) * days_per_year__KE);
  Self__0E->mass__AE=(__REAL_64)(((__REAL_64 )(2.85885980666130812E-04)) * solar_mass__4D);
  Self__LF=&(Result__4C[ 3]);
  Self__LF->x__EE=((__REAL_64 )(1.28943695621391310E+01));
  Self__LF->y__GE=((__REAL_64 )(-1.51111514016986312E+01));
  Self__LF->z__IE=((__REAL_64 )(-2.23307578892655734E-01));
  Self__LF->vx__NE=(__REAL_64)(((__REAL_64 )(2.96460137564761618E-03)) * days_per_year__KE);
  Self__LF->vy__RE=(__REAL_64)(((__REAL_64 )(2.37847173959480950E-03)) * days_per_year__KE);
  Self__LF->vz__VE=(__REAL_64)(((__REAL_64 )(-2.96589568540237556E-05)) * days_per_year__KE);
  Self__LF->mass__AE=(__REAL_64)(((__REAL_64 )(4.36624404335156298E-05)) * solar_mass__4D);
  Self__2F=&(Result__4C[ 4]);
  Self__2F->x__EE=((__REAL_64 )(1.53796971148509165E+01));
  Self__2F->y__GE=((__REAL_64 )(-2.59193146099879641E+01));
  Self__2F->z__IE=((__REAL_64 )(1.79258772950371181E-01));
  Self__2F->vx__NE=(__REAL_64)(((__REAL_64 )(2.68067772490389322E-03)) * days_per_year__KE);
  Self__2F->vy__RE=(__REAL_64)(((__REAL_64 )(1.62824170038242295E-03)) * days_per_year__KE);
  Self__2F->vz__VE=(__REAL_64)(((__REAL_64 )(-9.51592254519715870E-05)) * days_per_year__KE);
  Self__2F->mass__AE=(__REAL_64)(((__REAL_64 )(5.15138902046611451E-05)) * solar_mass__4D);
  offset_momentum(nbodies__AB);
  print_format_c__RK(energy(nbodies__AB));
  Self__1K= 1;
  limit_up__2K=result__RIL;
  while ((Self__1K <= limit_up__2K)) {
    advance(((__REAL_64 )0.01),nbodies__AB);
    Self__1K=(__INTEGER)(Self__1K +  1);
  };
  print_format_c__RK(energy(nbodies__AB));
  return( 0);
}

static __POINTER new_lab__01B(__UINTEGER_32 t__21B)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 idx__41B,pv__F2B;
  __MEMORY *blc__B2B,*prev__C2B,*Self__YES,*Self__5PS,*prev__AQS;
  __MEMORY *next__BQS;
  __POINTER result__D2B;
  __BOOLEAN __tmp__F3B;
  idx__41B= 0;
  blc__B2B=NULL;
  prev__C2B=NULL;
  pv__F2B= 0;
  while_do__3AC:
  {
    if ((idx__41B < nb_page__M2B)) {
      blc__B2B=((__MEMORY *)(last_block[(idx__41B)]));
      __tmp__F3B=(((__UINTEGER_32)(((__MEMORY *)blc__B2B)->size_and_id__OD &  4294967292LU) <  4096) || ((__UINTEGER_32)(((__MEMORY *)blc__B2B)->size_and_id__OD &  1) ==  1));
    } else {
      __tmp__F3B=FALSE__;
    };
    if (__tmp__F3B) {
      idx__41B=(__UINTEGER_32)(idx__41B +  1);
      goto while_do__3AC;
    };
  };
  if ((idx__41B >= nb_page__M2B)) {
    blc__B2B=new_page__ETD();
  };
  ((__MEMORY *)blc__B2B)->size_and_id__OD=(__UINTEGER_32)(blc__B2B->size_and_id__OD -  4096);
  Self__YES=((__MEMORY *)blc__B2B);
  result__D2B=((__POINTER )((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__YES) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__YES->size_and_id__OD &  4294967292LU))))));
  if (((__UINTEGER_32)(((__MEMORY *)blc__B2B)->size_and_id__OD &  4294967292LU) < ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    Self__5PS=((__MEMORY *)blc__B2B);
    prev__AQS=Self__5PS->previous_free__QD;
    next__BQS=Self__5PS->next_free__PD;
    if (((void *)prev__AQS == (void *)NULL)) {
      first_free__MMD=next__BQS;
    } else {
      ((__MEMORY *)prev__AQS)->next_free__PD=next__BQS;
    };
    if (((void *)next__BQS != (void *)NULL)) {
      ((__MEMORY *)next__BQS)->previous_free__QD=prev__AQS;
    };
    pv__F2B=blc__B2B->previous_linear__ND;
    if ((pv__F2B !=  4294967295LU)) {
      prev__C2B=((__MEMORY *)(void *)((unsigned long)begin_memory__3RB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )pv__F2B))));
      ((__MEMORY *)prev__C2B)->size_and_id__OD=(__UINTEGER_32)((__UINTEGER_32)(prev__C2B->size_and_id__OD + blc__B2B->size_and_id__OD) +  8);
      last_block[(idx__41B)] = (prev__C2B);
    };
  };
  ((__POINTER *)result__D2B)[ 0]=((__POINTER )t__21B);
  return((void *)((unsigned long)result__D2B - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))))));
}

static void** create__UGG(__INTEGER nb_elements__WGG)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__IVS,a__HVS,new_size__JVS,new_size2__KVS,a__LVS;
  __UINTEGER_32 new_size__MVS;
  __POINTER result__GVS,ptr_table__TVS,next__SVS,result__UVS;
  __INTEGER Self__MOI;
  void **Result__FOG;
  sz__IVS=((__UINTEGER_32 )(__INTEGER)(nb_elements__WGG * ((__INTEGER )(sizeof(void *)))));
  result__GVS=((__POINTER )(NULL));
  a__HVS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__JVS=(__UINTEGER_32)((__UINTEGER_32)(sz__IVS + a__HVS) & (__UINTEGER_32)(~ a__HVS));
  new_size2__KVS=(__UINTEGER_32)(new_size__JVS + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__KVS <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__LVS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__MVS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__KVS + a__LVS) & (__UINTEGER_32)(~ a__LVS));
    ptr_table__TVS=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__MVS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
    next__SVS=((__POINTER )(NULL));
    result__UVS=((__POINTER *)ptr_table__TVS)[ 0];
    if ((result__UVS == (void *)NULL)) {
      result__UVS=new_lab__01B(new_size__MVS);
      next__SVS=(void *)((unsigned long)result__UVS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__MVS)));
      ((__POINTER *)next__SVS)[ 0]=NULL;
      ((__POINTER *)ptr_table__TVS)[ 0]=next__SVS;
    } else {
      next__SVS=((__POINTER *)result__UVS)[ 0];
      if ((next__SVS == (void *)NULL)) {
        if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__UVS - (unsigned long)begin_memory__3RB)))) &  4095) + (__UINTEGER_32)(new_size__MVS <<  1)) <=  4096)) {
          next__SVS=(void *)((unsigned long)result__UVS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__MVS)));
        } else {
          next__SVS=new_lab__01B(new_size__MVS);
        };
        ((__POINTER *)next__SVS)[ 0]=NULL;
        ((__POINTER *)ptr_table__TVS)[ 0]=next__SVS;
      } else {
        ((__POINTER *)result__UVS)[ 0]=(void *)((unsigned long)((__POINTER *)next__SVS)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
        result__UVS=next__SVS;
      };
    };
    ((__POINTER *)result__UVS)[ 0]=((__POINTER ) 3);
    result__GVS=(void *)((unsigned long)result__UVS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__GVS=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__JLD(new_size__JVS))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__FOG=((void **)result__GVS);
  Self__MOI=(__INTEGER)(nb_elements__WGG -  1);
  while ((Self__MOI >=  0)) {
    Result__FOG[Self__MOI]=NULL;
    Self__MOI=(__INTEGER)(Self__MOI -  1);
  };
  return(Result__FOG);
}

static __STRING* create__R3(__INTEGER needed_capacity__T3)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __STRING *result__0DB,*Self__IUC;
  __POINTER ptr__1DB,ptr_table__ZVS,next__YVS,result__0VS;
  __POINTER ptr_table__5VS,next__4VS,result__AWS;
  __INTEGER typ_id__AEB;
  __UINTEGER_32 sz__3DB,a__HRS,new_size__IRS,t__RRS,a__ORS;
  __UINTEGER_32 new_size__CWS,lab_type__BWS;
  result__0DB=NULL;
  ptr__1DB=((__POINTER )(NULL));
  typ_id__AEB= 0;
  sz__3DB=((__UINTEGER_32 )sizeof(__STRING));
  if ((sz__3DB ==  0)) {
    result__0DB=STRING__;
  } else {
    typ_id__AEB=-1;
    clone_allocation_size__F5=(__UINTEGER_32)(clone_allocation_size__F5 + sz__3DB);
    if ((typ_id__AEB == (__INTEGER)(-  1))) {
      a__HRS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__IRS=(__UINTEGER_32)((__UINTEGER_32)(sz__3DB + a__HRS) & (__UINTEGER_32)(~ a__HRS));
      ptr_table__ZVS=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__IRS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__YVS=((__POINTER )(NULL));
      result__0VS=((__POINTER *)ptr_table__ZVS)[ 0];
      if ((result__0VS == (void *)NULL)) {
        result__0VS=new_lab__01B(new_size__IRS);
        next__YVS=(void *)((unsigned long)result__0VS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__IRS)));
        ((__POINTER *)next__YVS)[ 0]=NULL;
        ((__POINTER *)ptr_table__ZVS)[ 0]=next__YVS;
      } else {
        next__YVS=((__POINTER *)result__0VS)[ 0];
        if ((next__YVS == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__0VS - (unsigned long)begin_memory__3RB)))) &  4095) + (__UINTEGER_32)(new_size__IRS <<  1)) <=  4096)) {
            next__YVS=(void *)((unsigned long)result__0VS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__IRS)));
          } else {
            next__YVS=new_lab__01B(new_size__IRS);
          };
          ((__POINTER *)next__YVS)[ 0]=NULL;
          ((__POINTER *)ptr_table__ZVS)[ 0]=next__YVS;
        } else {
          ((__POINTER *)result__0VS)[ 0]=(void *)((unsigned long)((__POINTER *)next__YVS)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__0VS=next__YVS;
        };
      };
      ptr__1DB=result__0VS;
    } else {
      t__RRS=((__UINTEGER_32 )typ_id__AEB);
      a__ORS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__CWS=(__UINTEGER_32)((__UINTEGER_32)(sz__3DB + a__ORS) & (__UINTEGER_32)(~ a__ORS));
      ptr_table__5VS=((__POINTER )(&(table_type[(t__RRS)])));
      lab_type__BWS=(__UINTEGER_32)(t__RRS |  1);
      next__4VS=((__POINTER )(NULL));
      result__AWS=((__POINTER *)ptr_table__5VS)[ 0];
      if ((result__AWS == (void *)NULL)) {
        result__AWS=new_lab__01B(lab_type__BWS);
        next__4VS=(void *)((unsigned long)result__AWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__CWS)));
        ((__POINTER *)next__4VS)[ 0]=NULL;
        ((__POINTER *)ptr_table__5VS)[ 0]=next__4VS;
      } else {
        next__4VS=((__POINTER *)result__AWS)[ 0];
        if ((next__4VS == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__AWS - (unsigned long)begin_memory__3RB)))) &  4095) + (__UINTEGER_32)(new_size__CWS <<  1)) <=  4096)) {
            next__4VS=(void *)((unsigned long)result__AWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__CWS)));
          } else {
            next__4VS=new_lab__01B(lab_type__BWS);
          };
          ((__POINTER *)next__4VS)[ 0]=NULL;
          ((__POINTER *)ptr_table__5VS)[ 0]=next__4VS;
        } else {
          ((__POINTER *)result__AWS)[ 0]=(void *)((unsigned long)((__POINTER *)next__4VS)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__AWS=next__4VS;
        };
      };
      ptr__1DB=result__AWS;
    };
    result__0DB=((__STRING *)ptr__1DB);
    *(result__0DB) = *(STRING__);
  };
  Self__IUC=((__STRING *)result__0DB);
  if ((needed_capacity__T3 >  0)) {
    if ((Self__IUC->capacity__GW < needed_capacity__T3)) {
      Self__IUC->storage__3QC=create__MDG(needed_capacity__T3);
      Self__IUC->capacity__GW=needed_capacity__T3;
    };
  };
  Self__IUC->count__EW= 0;
  return(result__0DB);
}

static void add_last__ZDE(__STRING *Self__0DE,__CHARACTER ch__1DE)
// ({STRING},{CHARACTER}) VoidNo recursive, No inlinable.
{
  __INTEGER new_capacity__2DE,__tmp__VEE,__tmp__XSH,Self__UYL;
  __CHARACTER *__tmp__UEE,*new__ESH;
  new_capacity__2DE= 0;
  if ((Self__0DE->capacity__GW <= Self__0DE->count__EW)) {
    if ((Self__0DE->capacity__GW ==  0)) {
      Self__0DE->capacity__GW= 32;
      Self__0DE->storage__3QC=create__MDG( 32);
    } else {
      new_capacity__2DE=(__INTEGER)(Self__0DE->capacity__GW <<  1);
      __tmp__UEE=Self__0DE->storage__3QC;
      __tmp__VEE=Self__0DE->capacity__GW;
      new__ESH=((__CHARACTER *)realloc_dynamic__old_size__new_size__EGI(((__POINTER )((__CHARACTER *)__tmp__UEE)),((__UINTEGER_32 )__tmp__VEE),((__UINTEGER_32 )new_capacity__2DE)));
      __tmp__XSH=(__INTEGER)(new_capacity__2DE -  1);
      Self__UYL=__tmp__VEE;
      while ((Self__UYL <= __tmp__XSH)) {
        new__ESH[Self__UYL]='\0';
        Self__UYL=(__INTEGER)(Self__UYL +  1);
      };
      Self__0DE->storage__3QC=new__ESH;
      Self__0DE->capacity__GW=new_capacity__2DE;
    };
  };
  ((__CHARACTER *)Self__0DE->storage__3QC)[Self__0DE->count__EW]=ch__1DE;
  Self__0DE->count__EW=(__INTEGER)(Self__0DE->count__EW +  1);
}

static __POINTER realloc_dynamic__old_size__new_size__EGI(__POINTER p__GGI,__UINTEGER_32 old_sz__HGI,__UINTEGER_32 new_sz__IGI)
// ({POINTER},{UINTEGER_32},{UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *mem__TGI,*Self__OKK,*nxt__SKK,*result__TKK,*next__1AL;
  __MEMORY *new_free__0AL,*prev__ISS,*next__JSS;
  __POINTER result__UGI,result__PO,ptr_table__FWS,next__EWS,result__GWS;
  __POINTER p__EJK,last__HUK,src__4HK,dst__5HK;
  __UINTEGER_32 a__URS,old_size__KGI,old_size2__NGI,a__YRS;
  __UINTEGER_32 new_size__QGI,a__B1,new_size__JO,new_size2__MO,a__QSS;
  __UINTEGER_32 new_size__RSS,a__2RS,__tmp__FII,sz__XKK,old_size__UKK;
  __UINTEGER_32 prev__2AL,new_size__5AL;
  __INTEGER siz__3WS,Self__CXS,siz__DIK,Self__0RK;
  __POINTER *na_src__5WS,*na_dst__BXS,*na_src__BIK,*na_dst__CIK;
  mem__TGI=NULL;
  result__UGI=((__POINTER )(NULL));
  a__URS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  old_size__KGI=(__UINTEGER_32)((__UINTEGER_32)(old_sz__HGI + a__URS) & (__UINTEGER_32)(~ a__URS));
  old_size2__NGI=(__UINTEGER_32)(old_size__KGI + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  a__YRS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__QGI=(__UINTEGER_32)((__UINTEGER_32)(new_sz__IGI + a__YRS) & (__UINTEGER_32)(~ a__YRS));
  if ((old_size2__NGI <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    result__PO=((__POINTER )(NULL));
    a__B1=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__JO=(__UINTEGER_32)((__UINTEGER_32)(new_size__QGI + a__B1) & (__UINTEGER_32)(~ a__B1));
    new_size2__MO=(__UINTEGER_32)(new_size__JO + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
    if ((new_size2__MO <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
      a__QSS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__RSS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__MO + a__QSS) & (__UINTEGER_32)(~ a__QSS));
      ptr_table__FWS=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__RSS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__EWS=((__POINTER )(NULL));
      result__GWS=((__POINTER *)ptr_table__FWS)[ 0];
      if ((result__GWS == (void *)NULL)) {
        result__GWS=new_lab__01B(new_size__RSS);
        next__EWS=(void *)((unsigned long)result__GWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__RSS)));
        ((__POINTER *)next__EWS)[ 0]=NULL;
        ((__POINTER *)ptr_table__FWS)[ 0]=next__EWS;
      } else {
        next__EWS=((__POINTER *)result__GWS)[ 0];
        if ((next__EWS == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__GWS - (unsigned long)begin_memory__3RB)))) &  4095) + (__UINTEGER_32)(new_size__RSS <<  1)) <=  4096)) {
            next__EWS=(void *)((unsigned long)result__GWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__RSS)));
          } else {
            next__EWS=new_lab__01B(new_size__RSS);
          };
          ((__POINTER *)next__EWS)[ 0]=NULL;
          ((__POINTER *)ptr_table__FWS)[ 0]=next__EWS;
        } else {
          ((__POINTER *)result__GWS)[ 0]=(void *)((unsigned long)((__POINTER *)next__EWS)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__GWS=next__EWS;
        };
      };
      ((__POINTER *)result__GWS)[ 0]=((__POINTER ) 3);
      result__PO=(void *)((unsigned long)result__GWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
    } else {
      result__PO=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__JLD(new_size__JO))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
    };
    result__UGI=result__PO;
    siz__3WS=((__INTEGER )old_size__KGI);
    siz__3WS=(__INTEGER)(siz__3WS / ((__INTEGER )(sizeof(void *))));
    na_src__5WS=((__POINTER *)p__GGI);
    na_dst__BXS=((__POINTER *)result__PO);
    Self__CXS=(__INTEGER)(siz__3WS -  1);
    while ((Self__CXS >=  0)) {
      na_dst__BXS[Self__CXS]=na_src__5WS[Self__CXS];
      Self__CXS=(__INTEGER)(Self__CXS -  1);
    };
    p__EJK=(void *)((unsigned long)p__GGI - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))));
    a__2RS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    last__HUK=((__POINTER *)((__POINTER )(&(table_size[((__UINTEGER_32)((__UINTEGER_32)((__UINTEGER_32)(old_size2__NGI + a__2RS) & (__UINTEGER_32)(~ a__2RS)) / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))))[ 0];
    ((__POINTER *)p__EJK)[ 0]=(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)(void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER *)last__HUK)[ 0]) - (unsigned long)((__POINTER ) 1)) & (unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 3)) - (unsigned long)((__POINTER ) 1)))) - (unsigned long)((__POINTER ) 1));
    ((__POINTER *)last__HUK)[ 0]=p__EJK;
  } else {
    mem__TGI=((__MEMORY *)(void *)((unsigned long)p__GGI - (unsigned long)((__POINTER ) 8)));
    __tmp__FII=(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)p__GGI - (unsigned long)begin_memory__3RB)))) >>  26);
    Self__OKK=((__MEMORY *)mem__TGI);
    nxt__SKK=NULL;
    result__TKK=NULL;
    sz__XKK= 0;
    old_size__UKK=(__UINTEGER_32)(Self__OKK->size_and_id__OD &  4294967292LU);
    if ((new_size__QGI > old_size__UKK)) {
      if ((! ((__UINTEGER_32)(Self__OKK->size_and_id__OD &  2) !=  0))) {
        nxt__SKK=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__OKK) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__OKK->size_and_id__OD &  4294967292LU)))));
        sz__XKK=(__UINTEGER_32)((__UINTEGER_32)(new_size__QGI - old_size__UKK) -  8);
        if ((((__UINTEGER_32)(((__MEMORY *)nxt__SKK)->size_and_id__OD &  1) ==  0) && ((__UINTEGER_32)(((__MEMORY *)nxt__SKK)->size_and_id__OD &  4294967292LU) >= sz__XKK))) {
          to_busy__index__XIH(nxt__SKK,sz__XKK,__tmp__FII);
          Self__OKK->size_and_id__OD=(__UINTEGER_32)((__UINTEGER_32)(Self__OKK->size_and_id__OD + (__UINTEGER_32)(nxt__SKK->size_and_id__OD &  4294967294LU)) +  8);
          if (((__UINTEGER_32)(Self__OKK->size_and_id__OD &  2) !=  0)) {
            last_block[(__tmp__FII)] = (Self__OKK);
          } else {
            nxt__SKK=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__OKK) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__OKK->size_and_id__OD &  4294967292LU)))));
            ((__MEMORY *)nxt__SKK)->previous_linear__ND=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__OKK) - (unsigned long)begin_memory__3RB))));
          };
          result__TKK=Self__OKK;
        };
      };
      if (((void *)result__TKK == (void *)NULL)) {
        result__TKK=search__JLD(new_size__QGI);
        src__4HK=(void *)((unsigned long)((__POINTER )Self__OKK) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
        dst__5HK=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__TKK)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
        siz__DIK=((__INTEGER )old_size__UKK);
        siz__DIK=(__INTEGER)(siz__DIK / ((__INTEGER )(sizeof(void *))));
        na_src__BIK=((__POINTER *)src__4HK);
        na_dst__CIK=((__POINTER *)dst__5HK);
        Self__0RK=(__INTEGER)(siz__DIK -  1);
        while ((Self__0RK >=  0)) {
          na_dst__CIK[Self__0RK]=na_src__BIK[Self__0RK];
          Self__0RK=(__INTEGER)(Self__0RK -  1);
        };
        prev__2AL=Self__OKK->previous_linear__ND;
        next__1AL=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__OKK) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__OKK->size_and_id__OD &  4294967292LU)))));
        new_free__0AL=((__MEMORY *)(void *)((unsigned long)begin_memory__3RB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )prev__2AL))));
        new_size__5AL=(__UINTEGER_32)(Self__OKK->size_and_id__OD &  4294967294LU);
        if (((prev__2AL ==  4294967295LU) || ((__UINTEGER_32)(new_free__0AL->size_and_id__OD &  1) !=  0))) {
          new_free__0AL=Self__OKK;
          Self__OKK->next_free__PD=first_free__MMD;
          Self__OKK->previous_free__QD=NULL;
          if (((void *)first_free__MMD != (void *)NULL)) {
            ((__MEMORY *)first_free__MMD)->previous_free__QD=Self__OKK;
          };
          first_free__MMD=Self__OKK;
        } else {
          new_size__5AL=(__UINTEGER_32)((__UINTEGER_32)(new_size__5AL + new_free__0AL->size_and_id__OD) +  8);
        };
        if (((! ((__UINTEGER_32)(Self__OKK->size_and_id__OD &  2) !=  0)) && ((__UINTEGER_32)(next__1AL->size_and_id__OD &  1) ==  0))) {
          new_size__5AL=(__UINTEGER_32)((__UINTEGER_32)(new_size__5AL + next__1AL->size_and_id__OD) +  8);
          prev__ISS=next__1AL->previous_free__QD;
          next__JSS=next__1AL->next_free__PD;
          if (((void *)prev__ISS == (void *)NULL)) {
            first_free__MMD=next__JSS;
          } else {
            ((__MEMORY *)prev__ISS)->next_free__PD=next__JSS;
          };
          if (((void *)next__JSS != (void *)NULL)) {
            ((__MEMORY *)next__JSS)->previous_free__QD=prev__ISS;
          };
        };
        new_free__0AL->size_and_id__OD=new_size__5AL;
        if (((__UINTEGER_32)(new_free__0AL->size_and_id__OD &  2) !=  0)) {
          last_block[(__tmp__FII)] = (new_free__0AL);
        } else {
          next__1AL=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__OKK) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__OKK->size_and_id__OD &  4294967292LU)))));
          next__1AL->previous_linear__ND=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )new_free__0AL) - (unsigned long)begin_memory__3RB))));
        };
      };
    } else {
      result__TKK=Self__OKK;
    };
    result__UGI=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__TKK)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  return(result__UGI);
}

static __MEMORY* search__JLD(__UINTEGER_32 new_size__LLD)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *result__NLD;
  result__NLD=first_free__MMD;
  while ((((void *)result__NLD != (void *)NULL) && ((__UINTEGER_32)(((__MEMORY *)result__NLD)->size_and_id__OD &  4294967292LU) < new_size__LLD))) {
    result__NLD=result__NLD->next_free__PD;
  };
  if (((void *)result__NLD == (void *)NULL)) {
    result__NLD=new_page__ETD();
  };
  to_busy__index__XIH(result__NLD,new_size__LLD,(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)result__NLD)) - (unsigned long)begin_memory__3RB)))) >>  26));
  return(result__NLD);
}

void offset_momentum(__INTEGER n__NG)
// ({INTEGER}) VoidNo recursive, Inlinable.
{
  __REAL_64 px__OG,py__RG,pz__UG,__tmp__SH,__tmp__WH,__tmp__0H;
  __PLANET *b__XG;
  __INTEGER Self__PT;
  __PLANET *__tmp__OH;
  px__OG=((__REAL_64 ) 0);
  py__RG=((__REAL_64 ) 0);
  pz__UG=((__REAL_64 ) 0);
  b__XG=NULL;
  Self__PT= 0;
  while ((Self__PT <= n__NG)) {
    b__XG=((__PLANET *)(&(((__PLANET *)bodies__GB)[Self__PT])));
    px__OG=((__REAL_64 )((px__OG) + ((__REAL_64)(b__XG->vx__NE * b__XG->mass__AE))));
    py__RG=((__REAL_64 )((py__RG) + ((__REAL_64)(b__XG->vy__RE * b__XG->mass__AE))));
    pz__UG=((__REAL_64 )((pz__UG) + ((__REAL_64)(b__XG->vz__VE * b__XG->mass__AE))));
    Self__PT=(__INTEGER)(Self__PT +  1);
  };
  __tmp__OH=&(((__PLANET *)bodies__GB)[ 0]);
  __tmp__SH=(__REAL_64)((__REAL_64)(((__REAL_64 ) 0) - px__OG) / solar_mass__4D);
  __tmp__WH=(__REAL_64)((__REAL_64)(((__REAL_64 ) 0) - py__RG) / solar_mass__4D);
  __tmp__0H=(__REAL_64)((__REAL_64)(((__REAL_64 ) 0) - pz__UG) / solar_mass__4D);
  __tmp__OH->vx__NE=__tmp__SH;
  __tmp__OH->vy__RE=__tmp__WH;
  __tmp__OH->vz__VE=__tmp__0H;
}

__REAL_64 energy(__INTEGER n__2H)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __REAL_64 e__4H,dx__DI,dy__GI,dz__JI,__tmp__YOS,__tmp__ZOS,__tmp__0OS;
  __REAL_64 __tmp__1OS;
  __PLANET *b__BI,*b2__CI;
  __INTEGER __tmp__PI,Self__FV,__tmp__LJ,__tmp__MJ,Self__TCE;
  e__4H=((__REAL_64 ) 0);
  b__BI=NULL;
  b2__CI=NULL;
  dx__DI=((__REAL_64 ) 0);
  dy__GI=((__REAL_64 ) 0);
  dz__JI=((__REAL_64 ) 0);
  __tmp__PI=nbodies__AB;
  Self__FV= 0;
  while ((Self__FV <= __tmp__PI)) {
    b__BI=((__PLANET *)(&(((__PLANET *)bodies__GB)[Self__FV])));
    e__4H=((__REAL_64 )((e__4H) + ((__REAL_64)((__REAL_64)(b__BI->mass__AE * ((__REAL_64 )0.5)) * ((__REAL_64 )((((__REAL_64 )(((__REAL_64)(b__BI->vx__NE * b__BI->vx__NE)) + ((__REAL_64)(b__BI->vy__RE * b__BI->vy__RE))))) + ((__REAL_64)(b__BI->vz__VE * b__BI->vz__VE))))))));
    __tmp__LJ=(__INTEGER)(Self__FV +  1);
    __tmp__MJ=nbodies__AB;
    Self__TCE=__tmp__LJ;
    __tmp__YOS=b__BI->x__EE;
    __tmp__ZOS=b__BI->y__GE;
    __tmp__0OS=b__BI->z__IE;
    __tmp__1OS=b__BI->mass__AE;
    while ((Self__TCE <= __tmp__MJ)) {
      b2__CI=((__PLANET *)(&(((__PLANET *)bodies__GB)[Self__TCE])));
      dx__DI=(__REAL_64)(__tmp__YOS - b2__CI->x__EE);
      dy__GI=(__REAL_64)(__tmp__ZOS - b2__CI->y__GE);
      dz__JI=(__REAL_64)(__tmp__0OS - b2__CI->z__IE);
      e__4H=(__REAL_64)(e__4H - (__REAL_64)((__REAL_64)(__tmp__1OS * b2__CI->mass__AE) / ((__REAL_64 )(sqrt((((__REAL_64 )((((__REAL_64 )(((__REAL_64)(dx__DI * dx__DI)) + ((__REAL_64)(dy__GI * dy__GI))))) + ((__REAL_64)(dz__JI * dz__JI))))))))));
      Self__TCE=(__INTEGER)(Self__TCE +  1);
    };
    Self__FV=(__INTEGER)(Self__FV +  1);
  };
  return(e__4H);
}

static void print_format_c__RK(__REAL_64 Self__SK)
// ({REAL_64}) VoidNo recursive, No inlinable.
{
  __INTEGER old_count__CW,cap__DW,__tmp__PWC,Self__U4H;
  __STRING *Self__QVS,*new__FFB,*Self__RVC,*Self__2PC,*Self__ORC;
  __POINTER ptr__1EH;
  __CHARACTER *nc_buf__AW,*__tmp__JWC,*__tmp__MWC,*Self__KMH,*__tmp__CPS;
  ((__STRING *)string_tmp__UK)->count__EW= 0;
  old_count__CW=((__STRING *)string_tmp__UK)->count__EW;
  cap__DW=(__INTEGER)(((__STRING *)string_tmp__UK)->capacity__GW - old_count__CW);
  Self__QVS=((__STRING *)string_tmp__UK);
  if ((Self__QVS->capacity__GW > Self__QVS->count__EW)) {
    Self__QVS->count__EW=(__INTEGER)(Self__QVS->count__EW +  1);
    if ((((__CHARACTER *)Self__QVS->storage__3QC)[(__INTEGER)(Self__QVS->count__EW -  1)] != '\0')) {
      ((__CHARACTER *)Self__QVS->storage__3QC)[(__INTEGER)(Self__QVS->count__EW -  1)]='\0';
    };
  } else {
    add_last__ZDE(Self__QVS,'\0');
  };
  Self__QVS->count__EW=(__INTEGER)(Self__QVS->count__EW -  1);
  ptr__1EH=((__POINTER )((__CHARACTER *)Self__QVS->storage__3QC));
  ptr__1EH=(void *)((unsigned long)ptr__1EH - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )old_count__CW)));
  nc_buf__AW=((__CHARACTER *)ptr__1EH);
  new__FFB=create__R3(((__STRING_CONSTANT *)(&__string_1))->count__YHB);
  Self__RVC=((__STRING *)new__FFB);
  Self__RVC->count__EW=((__STRING_CONSTANT *)(&__string_1))->count__YHB;
  if ((Self__RVC->count__EW >  0)) {
    if ((Self__RVC->capacity__GW < Self__RVC->count__EW)) {
      Self__RVC->storage__3QC=create__MDG(Self__RVC->count__EW);
      Self__RVC->capacity__GW=Self__RVC->count__EW;
    };
    __tmp__JWC=Self__RVC->storage__3QC;
    __tmp__MWC=((__STRING_CONSTANT *)(&__string_1))->storage__0LE;
    __tmp__PWC=(__INTEGER)(Self__RVC->count__EW -  1);
    Self__KMH=((__CHARACTER *)__tmp__JWC);
    Self__U4H=__tmp__PWC;
    while ((Self__U4H >=  0)) {
      Self__KMH[Self__U4H]=((__CHARACTER *)__tmp__MWC)[Self__U4H];
      Self__U4H=(__INTEGER)(Self__U4H -  1);
    };
  };
  Self__2PC=((__STRING *)new__FFB);
  if ((Self__2PC->capacity__GW > Self__2PC->count__EW)) {
    Self__2PC->count__EW=(__INTEGER)(Self__2PC->count__EW +  1);
    if ((((__CHARACTER *)Self__2PC->storage__3QC)[(__INTEGER)(Self__2PC->count__EW -  1)] != '\0')) {
      ((__CHARACTER *)Self__2PC->storage__3QC)[(__INTEGER)(Self__2PC->count__EW -  1)]='\0';
    };
  } else {
    add_last__ZDE(Self__2PC,'\0');
  };
  Self__2PC->count__EW=(__INTEGER)(Self__2PC->count__EW -  1);
  snprintf((nc_buf__AW),(cap__DW),(Self__2PC->storage__3QC),(Self__SK));
  Self__ORC=((__STRING *)string_tmp__UK);
  Self__ORC->count__EW= 0;
  __tmp__CPS=Self__ORC->storage__3QC;
  while ((((__CHARACTER *)__tmp__CPS)[Self__ORC->count__EW] != '\0')) {
    Self__ORC->count__EW=(__INTEGER)(Self__ORC->count__EW +  1);
  };
  put_string__B5C(((__STRING *)string_tmp__UK));
}

void advance(__REAL_64 dt__NXD,__INTEGER n__OXD)
// ({REAL_64},{INTEGER}) VoidNo recursive, No inlinable.
{
  __INTEGER Self__BSE,Self__GBG,Self__QSE;
  __REAL_64 __tmp__JPS,__tmp__KPS,__tmp__LPS,__tmp__MPS,__tmp__NPS;
  __REAL_64 __tmp__OPS;
  /* debut */;
  Self__BSE= 0;
  while ((Self__BSE <= n__OXD)) {
    b__XXD=((__PLANET *)(&(((__PLANET *)bodies__GB)[Self__BSE])));
    Self__GBG=(__INTEGER)(Self__BSE +  1);
    __tmp__JPS=b__XXD->x__EE;
    __tmp__KPS=b__XXD->y__GE;
    __tmp__LPS=b__XXD->z__IE;
    __tmp__MPS=b__XXD->mass__AE;
    __tmp__NPS=b__XXD->mass__AE;
    __tmp__OPS=b__XXD->mass__AE;
    while ((Self__GBG <= n__OXD)) {
      b2__CYD=((__PLANET *)(&(((__PLANET *)bodies__GB)[Self__GBG])));
      dx__IYD=(__REAL_64)(__tmp__JPS - b2__CYD->x__EE);
      dy__OYD=(__REAL_64)(__tmp__KPS - b2__CYD->y__GE);
      dz__UYD=(__REAL_64)(__tmp__LPS - b2__CYD->z__IE);
      distance__CZD=((__REAL_64 )(sqrt((((__REAL_64 )((((__REAL_64 )(((__REAL_64)(dx__IYD * dx__IYD)) + ((__REAL_64)(dy__OYD * dy__OYD))))) + ((__REAL_64)(dz__UYD * dz__UYD))))))));
      mag__KZD=(__REAL_64)(dt__NXD / (__REAL_64)((__REAL_64)(distance__CZD * distance__CZD) * distance__CZD));
      ((__PLANET *)b__XXD)->vx__NE=(__REAL_64)(b__XXD->vx__NE - (__REAL_64)((__REAL_64)(dx__IYD * b2__CYD->mass__AE) * mag__KZD));
      ((__PLANET *)b__XXD)->vy__RE=(__REAL_64)(b__XXD->vy__RE - (__REAL_64)((__REAL_64)(dy__OYD * b2__CYD->mass__AE) * mag__KZD));
      ((__PLANET *)b__XXD)->vz__VE=(__REAL_64)(b__XXD->vz__VE - (__REAL_64)((__REAL_64)(dz__UYD * b2__CYD->mass__AE) * mag__KZD));
      ((__PLANET *)b2__CYD)->vx__NE=((__REAL_64 )((b2__CYD->vx__NE) + ((__REAL_64)((__REAL_64)(dx__IYD * __tmp__MPS) * mag__KZD))));
      ((__PLANET *)b2__CYD)->vy__RE=((__REAL_64 )((b2__CYD->vy__RE) + ((__REAL_64)((__REAL_64)(dy__OYD * __tmp__NPS) * mag__KZD))));
      ((__PLANET *)b2__CYD)->vz__VE=((__REAL_64 )((b2__CYD->vz__VE) + ((__REAL_64)((__REAL_64)(dz__UYD * __tmp__OPS) * mag__KZD))));
      Self__GBG=(__INTEGER)(Self__GBG +  1);
    };
    Self__BSE=(__INTEGER)(Self__BSE +  1);
  };
  Self__QSE= 0;
  while ((Self__QSE <= n__OXD)) {
    b__XXD=((__PLANET *)(&(((__PLANET *)bodies__GB)[Self__QSE])));
    ((__PLANET *)b__XXD)->x__EE=((__REAL_64 )((b__XXD->x__EE) + ((__REAL_64)(dt__NXD * b__XXD->vx__NE))));
    ((__PLANET *)b__XXD)->y__GE=((__REAL_64 )((b__XXD->y__GE) + ((__REAL_64)(dt__NXD * b__XXD->vy__RE))));
    ((__PLANET *)b__XXD)->z__IE=((__REAL_64 )((b__XXD->z__IE) + ((__REAL_64)(dt__NXD * b__XXD->vz__VE))));
    Self__QSE=(__INTEGER)(Self__QSE +  1);
  };
}

static __MEMORY* new_page__ETD()
// () With resultNo recursive, No inlinable.
{
  __POINTER mem__BNF;
  __UINTEGER_32 cap__4MF,old_size__HTD;
  __MEMORY *block__NTD;
  if ((capacity_max__OTD ==  0)) {
    mem__BNF=((__POINTER )(NULL));
    cap__4MF= 33554432;
    do {
      cap__4MF=(__UINTEGER_32)(cap__4MF <<  1);
      mem__BNF=((__POINTER )(malloc((cap__4MF))));
      if ((mem__BNF != (void *)NULL)) {
        free((mem__BNF));
      };
    } while ((! ((mem__BNF == (void *)NULL) || (cap__4MF ==  2147483648LU))));
    if ((mem__BNF == (void *)NULL)) {
      cap__4MF=(__UINTEGER_32)(cap__4MF >>  1);
    };
    capacity_max__OTD=cap__4MF;
    begin_memory__3RB=((__POINTER )(malloc((cap__4MF))));
  };
  old_size__HTD=(__UINTEGER_32)(nb_page__M2B <<  26);
  nb_page__M2B=(__UINTEGER_32)(nb_page__M2B +  1);
  if (((__UINTEGER_32)(old_size__HTD +  67108864) > capacity_max__OTD)) {
    put_string__B5C((&__string_2));
    exit(( 1));
  };
  block__NTD=((__MEMORY *)(void *)((unsigned long)begin_memory__3RB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )old_size__HTD))));
  block__NTD->previous_linear__ND= 4294967295LU;
  block__NTD->size_and_id__OD= 67108858;
  block__NTD->next_free__PD=first_free__MMD;
  block__NTD->previous_free__QD=NULL;
  if (((void *)first_free__MMD != (void *)NULL)) {
    ((__MEMORY *)first_free__MMD)->previous_free__QD=block__NTD;
  };
  first_free__MMD=block__NTD;
  last_block[((__UINTEGER_32)(nb_page__M2B -  1))] = (block__NTD);
  return(block__NTD);
}

static __CHARACTER* create__MDG(__INTEGER nb_elements__ODG)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__UUS,a__TUS,new_size__VUS,new_size2__WUS,a__XUS;
  __UINTEGER_32 new_size__YUS;
  __POINTER result__SUS,ptr_table__LWS,next__KWS,result__MWS;
  __INTEGER Self__FNI;
  __CHARACTER *Result__ELG;
  sz__UUS=((__UINTEGER_32 )nb_elements__ODG);
  result__SUS=((__POINTER )(NULL));
  a__TUS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__VUS=(__UINTEGER_32)((__UINTEGER_32)(sz__UUS + a__TUS) & (__UINTEGER_32)(~ a__TUS));
  new_size2__WUS=(__UINTEGER_32)(new_size__VUS + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__WUS <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__XUS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__YUS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__WUS + a__XUS) & (__UINTEGER_32)(~ a__XUS));
    ptr_table__LWS=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__YUS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
    next__KWS=((__POINTER )(NULL));
    result__MWS=((__POINTER *)ptr_table__LWS)[ 0];
    if ((result__MWS == (void *)NULL)) {
      result__MWS=new_lab__01B(new_size__YUS);
      next__KWS=(void *)((unsigned long)result__MWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__YUS)));
      ((__POINTER *)next__KWS)[ 0]=NULL;
      ((__POINTER *)ptr_table__LWS)[ 0]=next__KWS;
    } else {
      next__KWS=((__POINTER *)result__MWS)[ 0];
      if ((next__KWS == (void *)NULL)) {
        if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__MWS - (unsigned long)begin_memory__3RB)))) &  4095) + (__UINTEGER_32)(new_size__YUS <<  1)) <=  4096)) {
          next__KWS=(void *)((unsigned long)result__MWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__YUS)));
        } else {
          next__KWS=new_lab__01B(new_size__YUS);
        };
        ((__POINTER *)next__KWS)[ 0]=NULL;
        ((__POINTER *)ptr_table__LWS)[ 0]=next__KWS;
      } else {
        ((__POINTER *)result__MWS)[ 0]=(void *)((unsigned long)((__POINTER *)next__KWS)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
        result__MWS=next__KWS;
      };
    };
    ((__POINTER *)result__MWS)[ 0]=((__POINTER ) 3);
    result__SUS=(void *)((unsigned long)result__MWS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__SUS=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__JLD(new_size__VUS))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__ELG=((__CHARACTER *)result__SUS);
  Self__FNI=(__INTEGER)(nb_elements__ODG -  1);
  while ((Self__FNI >=  0)) {
    Result__ELG[Self__FNI]='\0';
    Self__FNI=(__INTEGER)(Self__FNI -  1);
  };
  return(Result__ELG);
}

static void to_busy__index__XIH(__MEMORY *Self__YIH,__UINTEGER_32 sz__ZIH,__UINTEGER_32 idx__0IH)
// ({MEMORY},{UINTEGER_32},{UINTEGER_32}) VoidNo recursive, No inlinable.
{
  __MEMORY *new__BJH,*prev__O1H,*next__P1H,*Self__BNH,*Self__MAS;
  __UINTEGER_32 siz__1IH,new_size__4IH;
  new__BJH=NULL;
  prev__O1H=Self__YIH->previous_free__QD;
  next__P1H=Self__YIH->next_free__PD;
  if (((void *)prev__O1H == (void *)NULL)) {
    first_free__MMD=next__P1H;
  } else {
    ((__MEMORY *)prev__O1H)->next_free__PD=next__P1H;
  };
  if (((void *)next__P1H != (void *)NULL)) {
    ((__MEMORY *)next__P1H)->previous_free__QD=prev__O1H;
  };
  siz__1IH=Self__YIH->size_and_id__OD;
  new_size__4IH=(__UINTEGER_32)(siz__1IH - sz__ZIH);
  if ((new_size__4IH > (__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )(MINIMUM_SIZE)) +  2) +  8))) {
    siz__1IH=sz__ZIH;
    new__BJH=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__YIH) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )sz__ZIH))));
    ((__MEMORY *)new__BJH)->previous_linear__ND=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__YIH) - (unsigned long)begin_memory__3RB))));
    ((__MEMORY *)new__BJH)->size_and_id__OD=(__UINTEGER_32)(new_size__4IH -  8);
    Self__BNH=((__MEMORY *)new__BJH);
    Self__BNH->next_free__PD=first_free__MMD;
    Self__BNH->previous_free__QD=NULL;
    if (((void *)first_free__MMD != (void *)NULL)) {
      ((__MEMORY *)first_free__MMD)->previous_free__QD=Self__BNH;
    };
    first_free__MMD=Self__BNH;
    if (((__UINTEGER_32)(((__MEMORY *)new__BJH)->size_and_id__OD &  2) !=  0)) {
      last_block[(idx__0IH)] = (new__BJH);
    } else {
      Self__MAS=((__MEMORY *)new__BJH);
      ((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__MAS) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__MAS->size_and_id__OD &  4294967292LU)))))->previous_linear__ND=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)new__BJH)) - (unsigned long)begin_memory__3RB))));
    };
  };
  Self__YIH->size_and_id__OD=(__UINTEGER_32)(siz__1IH |  1);
}

static void put_string__B5C(void *s__D5C)
// ({STRING_CONSTANTxSTRING}) VoidNo recursive, No inlinable.
{
  __INTEGER __tmp__V5C,Self__SKD,limit_up__TKD;
  __CHARACTER *__tmp__ATS,*__tmp__BTS;
  __CHARACTER __tmp__25C;
  if (((struct ___OBJ *)s__D5C)->__id==__STRING_CONSTANT__) {
  };
  if (((struct ___OBJ *)s__D5C)->__id==__STRING_CONSTANT__) {
    __tmp__V5C=((__STRING_CONSTANT *)s__D5C)->count__YHB;
  } else {
    __tmp__V5C=((__STRING *)s__D5C)->count__EW;
  };
  Self__SKD= 1;
  limit_up__TKD=__tmp__V5C;
  __tmp__ATS=((__STRING_CONSTANT *)s__D5C)->storage__0LE;
  __tmp__BTS=((__STRING *)s__D5C)->storage__3QC;
  while ((Self__SKD <= limit_up__TKD)) {
    if (((struct ___OBJ *)s__D5C)->__id==__STRING_CONSTANT__) {
      __tmp__25C=((__CHARACTER *)__tmp__ATS)[(__INTEGER)(Self__SKD -  1)];
    } else {
      __tmp__25C=((__CHARACTER *)__tmp__BTS)[(__INTEGER)(Self__SKD -  1)];
    };
    fputc((int)(__tmp__25C),stdout);
    Self__SKD=(__INTEGER)(Self__SKD +  1);
  };
}

//==========================//
// DEBUG MANAGER            //
//==========================//

void print_string(char *str) 
{ 
  while (*str!=0) {
    print_char(*str); 
    str++; 
  };
}  

