// C code generated by Lisaac compiler (www.isaacOS.com) //
int arg_count;
char **arg_vector;

//==========================//
// EXTERNAL                 //
//==========================//

// CTX
#include <gmp.h>
// MEMORY

#define MINIMUM_SIZE 256  
void *table_size[MINIMUM_SIZE/sizeof(void *)];
void *last_block[64];

// FLOAT_REAL
#include <math.h>
// SYSTEM
#include <time.h>
// SYSTEM_IO

#include <stdio.h>
#include <stdlib.h>
  
// Hardware 'print_char'
void print_char(char car)
{
  fputc(car,stdout);
}

// Hardware 'exit'
int die_with_code(int code)
{
  exit(code);
}



//==========================//
// TYPE                     //
//==========================//

// Generic Object
struct ___OBJ {
  unsigned long __id;
};

// NULL
#ifndef NULL
#define NULL ((void *)0)
#endif

// POINTER
typedef void * __POINTER;

// UINTEGER_32
typedef unsigned long __UINTEGER_32;

// INTEGER
typedef int __INTEGER;

// CHARACTER
typedef char __CHARACTER;

// STRING
#define __STRING__ 4
typedef struct STRING_struct __STRING;
struct STRING_struct {
  unsigned long __id;
  __INTEGER count__UT;
  __INTEGER capacity__U1C;
  __CHARACTER *storage__31C;
};
__STRING STRING_={__STRING__};
#define STRING__ (&STRING_)

// MEMORY
#define __MEMORY__ 0
typedef struct MEMORY_struct __MEMORY;
struct MEMORY_struct {
  volatile __UINTEGER_32 previous_linear__IJ;
  volatile __UINTEGER_32 size_and_id__JJ;
  __MEMORY *next_free__KJ;
  __MEMORY *previous_free__LJ;
} __attribute__ ((packed));
__MEMORY MEMORY_;
#define MEMORY__ (&MEMORY_)

// ARRAYED_COLLECTION[STRING]
#define __ARRAYED_COLLECTIONoSTRINGo__ 1
typedef struct ARRAYED_COLLECTIONoSTRINGo_struct __ARRAYED_COLLECTIONoSTRINGo;
struct ARRAYED_COLLECTIONoSTRINGo_struct {
  __INTEGER upper__V0C;
  __INTEGER capacity__U2C;
  void **storage__52C;
};
__ARRAYED_COLLECTIONoSTRINGo ARRAYED_COLLECTIONoSTRINGo_;
#define ARRAYED_COLLECTIONoSTRINGo__ (&ARRAYED_COLLECTIONoSTRINGo_)

// FAST_ARRAY[STRING]
#define __FAST_ARRAYoSTRINGo__ 2
typedef struct FAST_ARRAYoSTRINGo_struct __FAST_ARRAYoSTRINGo;
struct FAST_ARRAYoSTRINGo_struct {
  __ARRAYED_COLLECTIONoSTRINGo parent_arrayed_collection__TB;
};
__FAST_ARRAYoSTRINGo FAST_ARRAYoSTRINGo_;
#define FAST_ARRAYoSTRINGo__ (&FAST_ARRAYoSTRINGo_)

// NUMERIC
#define __NUMERIC__ 3
typedef struct NUMERIC_struct __NUMERIC;
struct NUMERIC_struct {
  void *Nothing;
};
__NUMERIC NUMERIC_;
#define NUMERIC__ (&NUMERIC_)

// OBJECT
#define __OBJECT__ 4
typedef struct OBJECT_struct __OBJECT;
struct OBJECT_struct {
  void *Nothing;
};
__OBJECT OBJECT_;
#define OBJECT__ (&OBJECT_)

// STRING_CONSTANT
#define __STRING_CONSTANT__ 5
typedef struct STRING_CONSTANT_struct __STRING_CONSTANT;
struct STRING_CONSTANT_struct {
  unsigned long __id;
  __INTEGER count__LDE;
  __CHARACTER *storage__JDE;
};
__STRING_CONSTANT STRING_CONSTANT_={__STRING_CONSTANT__};
#define STRING_CONSTANT__ (&STRING_CONSTANT_)

// TRUE
#define TRUE__ 1

// FALSE
#define FALSE__ 0

// CTX
#define __CTX__ 5
typedef struct CTX_struct __CTX;
struct CTX_struct {
  void *Nothing;
};
__CTX CTX_;
#define CTX__ (&CTX_)

// MPZ
typedef mpz_t __MPZ;

// INTEGER_8
typedef signed char __INTEGER_8;

// INTEGER_32
typedef signed long __INTEGER_32;

// BOOLEAN
typedef char __BOOLEAN;


void *table_type[6];

//==========================//
// GLOBAL                   //
//==========================//

void *parent_numeric__G;
__POINTER begin_memory__GJB;
__UINTEGER_32 nb_page__J5B;
__UINTEGER_32 capacity_max__QZD;
__MEMORY *first_free__IFH;
__UINTEGER_32 clone_allocation_size__4I;
__INTEGER n__LC;
__INTEGER i__MC;
void *digits__PC;
__MPZ q__QC;
__MPZ r__UC;
__MPZ s__YC;
__MPZ t__2C;
__MPZ u__AD;
__MPZ v__CD;
__MPZ w__ED;

//==========================//
// STRING CONSTANT          //
//==========================//

__STRING_CONSTANT __string_1={__STRING_CONSTANT__,19,"Not enough memory.\n"};

//==========================//
// FUNCTION HEADER          //
//==========================//

// Debug Manager
void print_string(char *str);
// Source code
static __POINTER new_lab__X4B(__UINTEGER_32 t__Z4B);
static void** create__EQG(__INTEGER nb_elements__GQG);
static __STRING* create__WF(__INTEGER needed_capacity__YF);
static void add_last__U4C(__STRING *Self__V4C,__CHARACTER ch__W4C);
static __POINTER realloc_dynamic__old_size__new_size__VOI(__POINTER p__XOI,__UINTEGER_32 old_sz__YOI,__UINTEGER_32 new_sz__ZOI);
static void put_string__OQD(void *s__QQD);
static __MEMORY* new_page__GZD();
static __MEMORY* search__FEH(__UINTEGER_32 new_size__HEH);
static __CHARACTER* create__YLF(__INTEGER nb_elements__0LF);

//==========================//
// SOURCE CODE              //
//==========================//

int main(int argc,char **argv)
{
  void *str__FF,*__tmp__IU;
  __INTEGER new_count__DH,typ_id__HK,Self__OH,limit_up__PH,idx__B3D;
  __INTEGER i__U4D,new_capacity__O5D,__tmp__SAE,__tmp__H5H,Self__YMM;
  __INTEGER n__Y,state__NZL,result__QZL,i__MZL,__tmp__XYS,__tmp__ZYS;
  __INTEGER y__JC,k__IC,i__1XB,j__2XB,br__DCB,__tmp__TE,__tmp__XE;
  __POINTER ptr__CK,ptr_table__I1S,next__H1S,result__J1S,ptr_table__MHB;
  __POINTER next__RHB,result__PHB;
  __UINTEGER_32 sz__EK,a__BWS,new_size__X1,t__A3,a__HWS,new_size__LHB;
  __UINTEGER_32 lab_type__NHB;
  __STRING *Self__S4D,*Self__KZL,*Self__5ME;
  __INTEGER_32 Self__QXB,val__YXB;
  __CHARACTER *arg__EF,*Self__V2D,*p__T4D,*__tmp__YYS;
  __FAST_ARRAYoSTRINGo *result__BK,*Self__L2C,*Self__M5D;
  void *result__DF;
  __BOOLEAN __tmp__25D,negative__PZL,__tmp__20L,result__ZEQ,__tmp__P1L;
  __BOOLEAN __tmp__E2L,result__QKP,__tmp__L3L,result__CLP,result__HWG;
  __BOOLEAN stop__KC;
  void **__tmp__RAE,**new__U4H;
  __CHARACTER cc__OZL,tmp__CNE;
  arg_count  = argc;
  arg_vector = argv;
  ARRAYED_COLLECTIONoSTRINGo__->upper__V0C= 0;
  ARRAYED_COLLECTIONoSTRINGo__->capacity__U2C= 0;
  ARRAYED_COLLECTIONoSTRINGo__->storage__52C=NULL;
  FAST_ARRAYoSTRINGo__->parent_arrayed_collection__TB=(*ARRAYED_COLLECTIONoSTRINGo__);
  parent_numeric__G=NUMERIC__;
  clone_allocation_size__4I= 0;
  STRING_CONSTANT__->count__LDE=((__INTEGER )((0)));
  STRING__->count__UT= 0;
  STRING_CONSTANT__->storage__JDE=((__CHARACTER *)(NULL));
  STRING__->storage__31C=NULL;
  nb_page__J5B= 0;
  MEMORY__->size_and_id__JJ= 0;
  capacity_max__QZD= 0;
  begin_memory__GJB=((__POINTER )(NULL));
  MEMORY__->previous_linear__IJ= 0;
  first_free__IFH=NULL;
  MEMORY__->next_free__KJ=NULL;
  MEMORY__->previous_free__LJ=NULL;
  STRING__->capacity__U1C= 0;
  arg__EF=NULL;
  str__FF=NULL;
  new_count__DH=((__INTEGER )(arg_count));
  result__BK=NULL;
  ptr__CK=((__POINTER )(NULL));
  typ_id__HK= 0;
  sz__EK=((__UINTEGER_32 )sizeof(__FAST_ARRAYoSTRINGo));
  if ((sz__EK ==  0)) {
    result__BK=FAST_ARRAYoSTRINGo__;
  } else {
    typ_id__HK=__FAST_ARRAYoSTRINGo__;
    clone_allocation_size__4I=sz__EK;
    if ((typ_id__HK == (__INTEGER)(-  1))) {
      a__BWS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__X1=(__UINTEGER_32)((__UINTEGER_32)(sz__EK + a__BWS) & (__UINTEGER_32)(~ a__BWS));
      ptr_table__I1S=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__X1 / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__H1S=((__POINTER )(NULL));
      result__J1S=((__POINTER *)ptr_table__I1S)[ 0];
      if ((result__J1S == (void *)NULL)) {
        result__J1S=new_lab__X4B(new_size__X1);
        next__H1S=(void *)((unsigned long)result__J1S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__X1)));
        ((__POINTER *)next__H1S)[ 0]=NULL;
        ((__POINTER *)ptr_table__I1S)[ 0]=next__H1S;
      } else {
        next__H1S=((__POINTER *)result__J1S)[ 0];
        if ((next__H1S == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__J1S - (unsigned long)begin_memory__GJB)))) &  4095) + (__UINTEGER_32)(new_size__X1 <<  1)) <=  4096)) {
            next__H1S=(void *)((unsigned long)result__J1S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__X1)));
          } else {
            next__H1S=new_lab__X4B(new_size__X1);
          };
          ((__POINTER *)next__H1S)[ 0]=NULL;
          ((__POINTER *)ptr_table__I1S)[ 0]=next__H1S;
        } else {
          ((__POINTER *)result__J1S)[ 0]=(void *)((unsigned long)((__POINTER *)next__H1S)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__J1S=next__H1S;
        };
      };
      ptr__CK=result__J1S;
    } else {
      t__A3=((__UINTEGER_32 )typ_id__HK);
      a__HWS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__LHB=(__UINTEGER_32)((__UINTEGER_32)(sz__EK + a__HWS) & (__UINTEGER_32)(~ a__HWS));
      ptr_table__MHB=((__POINTER )(&(table_type[(t__A3)])));
      lab_type__NHB=(__UINTEGER_32)(t__A3 |  1);
      next__RHB=((__POINTER )(NULL));
      result__PHB=((__POINTER *)ptr_table__MHB)[ 0];
      if ((result__PHB == (void *)NULL)) {
        result__PHB=new_lab__X4B(lab_type__NHB);
        next__RHB=(void *)((unsigned long)result__PHB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__LHB)));
        ((__POINTER *)next__RHB)[ 0]=NULL;
        ((__POINTER *)ptr_table__MHB)[ 0]=next__RHB;
      } else {
        next__RHB=((__POINTER *)result__PHB)[ 0];
        if ((next__RHB == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__PHB - (unsigned long)begin_memory__GJB)))) &  4095) + (__UINTEGER_32)(new_size__LHB <<  1)) <=  4096)) {
            next__RHB=(void *)((unsigned long)result__PHB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__LHB)));
          } else {
            next__RHB=new_lab__X4B(lab_type__NHB);
          };
          ((__POINTER *)next__RHB)[ 0]=NULL;
          ((__POINTER *)ptr_table__MHB)[ 0]=next__RHB;
        } else {
          ((__POINTER *)result__PHB)[ 0]=(void *)((unsigned long)((__POINTER *)next__RHB)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__PHB=next__RHB;
        };
      };
      ptr__CK=result__PHB;
    };
    result__BK=((__FAST_ARRAYoSTRINGo *)ptr__CK);
    *(result__BK) = *(FAST_ARRAYoSTRINGo__);
  };
  Self__L2C=((__FAST_ARRAYoSTRINGo *)result__BK);
  if ((Self__L2C->parent_arrayed_collection__TB.capacity__U2C < new_count__DH)) {
    Self__L2C->parent_arrayed_collection__TB.storage__52C=create__EQG(new_count__DH);
    Self__L2C->parent_arrayed_collection__TB.capacity__U2C=new_count__DH;
  };
  Self__L2C->parent_arrayed_collection__TB.upper__V0C=(__INTEGER)(-  1);
  result__DF=result__BK;
  Self__OH= 0;
  limit_up__PH=(__INTEGER)(((__INTEGER )(arg_count)) -  1);
  while ((Self__OH <= limit_up__PH)) {
    arg__EF=((__CHARACTER *)(arg_vector[(Self__OH)]));
    Self__V2D=((__CHARACTER *)arg__EF);
    idx__B3D= 0;
    while ((! ((idx__B3D >  1024) || ('\0' == Self__V2D[idx__B3D])))) {
      idx__B3D=(__INTEGER)(idx__B3D +  1);
    };
    str__FF=create__WF(idx__B3D);
    Self__S4D=((__STRING *)str__FF);
    p__T4D=arg__EF;
    i__U4D= 0;
    Self__S4D->count__UT= 0;
    while ((((__CHARACTER *)p__T4D)[i__U4D] != '\0')) {
      add_last__U4C(Self__S4D,((__CHARACTER *)p__T4D)[i__U4D]);
      i__U4D=(__INTEGER)(i__U4D +  1);
    };
    Self__M5D=((__FAST_ARRAYoSTRINGo *)result__DF);
    new_capacity__O5D= 0;
    if (((__INTEGER)(Self__M5D->parent_arrayed_collection__TB.upper__V0C +  1) <= (__INTEGER)(Self__M5D->parent_arrayed_collection__TB.capacity__U2C -  1))) {
      Self__M5D->parent_arrayed_collection__TB.upper__V0C=(__INTEGER)(Self__M5D->parent_arrayed_collection__TB.upper__V0C +  1);
      __tmp__25D=TRUE__;
    } else {
      __tmp__25D=FALSE__;
    };
    if ((! __tmp__25D)) {
      if ((Self__M5D->parent_arrayed_collection__TB.capacity__U2C ==  0)) {
        Self__M5D->parent_arrayed_collection__TB.storage__52C=create__EQG( 2);
        Self__M5D->parent_arrayed_collection__TB.capacity__U2C= 2;
        Self__M5D->parent_arrayed_collection__TB.upper__V0C= 0;
      } else {
        new_capacity__O5D=(__INTEGER)(Self__M5D->parent_arrayed_collection__TB.capacity__U2C <<  1);
        __tmp__RAE=Self__M5D->parent_arrayed_collection__TB.storage__52C;
        __tmp__SAE=Self__M5D->parent_arrayed_collection__TB.capacity__U2C;
        new__U4H=((void **)realloc_dynamic__old_size__new_size__VOI(((__POINTER )((void **)__tmp__RAE)),((__UINTEGER_32 )(__INTEGER)(__tmp__SAE * ((__INTEGER )(sizeof(void *))))),((__UINTEGER_32 )(__INTEGER)(new_capacity__O5D * ((__INTEGER )(sizeof(void *)))))));
        __tmp__H5H=(__INTEGER)(new_capacity__O5D -  1);
        Self__YMM=__tmp__SAE;
        while ((Self__YMM <= __tmp__H5H)) {
          new__U4H[Self__YMM]=NULL;
          Self__YMM=(__INTEGER)(Self__YMM +  1);
        };
        Self__M5D->parent_arrayed_collection__TB.storage__52C=new__U4H;
        Self__M5D->parent_arrayed_collection__TB.capacity__U2C=new_capacity__O5D;
        Self__M5D->parent_arrayed_collection__TB.upper__V0C=(__INTEGER)(Self__M5D->parent_arrayed_collection__TB.upper__V0C +  1);
      };
    };
    ((void **)Self__M5D->parent_arrayed_collection__TB.storage__52C)[Self__M5D->parent_arrayed_collection__TB.upper__V0C]=str__FF;
    Self__OH=(__INTEGER)(Self__OH +  1);
  };
  n__LC= 0;
  i__MC= 0;
  digits__PC=NULL;
  ((/*;
  q__QC=((__MPZ )(n));
  r__UC=((__MPZ )(n));
  s__YC=((__MPZ )(n));
  t__2C=((__MPZ )(n));
  u__AD=((__MPZ )(n));
  v__CD=((__MPZ )(n));
  w__ED=((__MPZ )(*/NULL));
  n__Y= 0;
  if (((__INTEGER)(((__FAST_ARRAYoSTRINGo *)result__BK)->parent_arrayed_collection__TB.upper__V0C +  1) >  1)) {
    Self__KZL=((__STRING *)((void **)((__FAST_ARRAYoSTRINGo *)result__BK)->parent_arrayed_collection__TB.storage__52C)[ 1]);
    state__NZL= 0;
    cc__OZL='\0';
    negative__PZL=FALSE__;
    result__QZL= 0;
    i__MZL= 1;
    __tmp__XYS=Self__KZL->count__UT;
    __tmp__YYS=Self__KZL->storage__31C;
    __tmp__ZYS=Self__KZL->count__UT;
    while ((i__MZL <= __tmp__XYS)) {
      cc__OZL=((__CHARACTER *)__tmp__YYS)[(__INTEGER)(i__MZL -  1)];
      if ((state__NZL ==  0)) {
        if ((((((((cc__OZL == ' ') || (cc__OZL == '\t')) || (cc__OZL == '\n')) || (cc__OZL == '\r')) || (cc__OZL == '\0')) || (cc__OZL == '\f')) || (cc__OZL == '\v'))) {
          __tmp__20L=TRUE__;
        } else {
          result__ZEQ=(cc__OZL == '+');
          if (result__ZEQ) {
            state__NZL= 1;
          };
          __tmp__20L=result__ZEQ;
        };
        if ((! __tmp__20L)) {
          if ((cc__OZL == '-')) {
            negative__PZL=TRUE__;
            state__NZL= 1;
          } else {
            result__QZL=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__OZL)) -  48);
            state__NZL= 2;
          };
        };
        __tmp__P1L=TRUE__;
      } else {
        __tmp__P1L=FALSE__;
      };
      if (__tmp__P1L) {
        __tmp__E2L=TRUE__;
      } else {
        result__QKP=(state__NZL ==  1);
        if (result__QKP) {
          result__QZL=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__OZL)) -  48);
          if (negative__PZL) {
            result__QZL=(__INTEGER)(- result__QZL);
          };
          state__NZL= 2;
        };
        __tmp__E2L=result__QKP;
      };
      if (__tmp__E2L) {
        __tmp__L3L=TRUE__;
      } else {
        result__CLP=(state__NZL ==  2);
        if (result__CLP) {
          result__HWG=FALSE__;
          if ((((__INTEGER_8 )cc__OZL) >= ((__INTEGER_8 )'0'))) {
            result__HWG=(((__INTEGER_8 )cc__OZL) <= ((__INTEGER_8 )'9'));
          };
          if (result__HWG) {
            if (negative__PZL) {
              result__QZL=(__INTEGER)((__INTEGER)( 10 * result__QZL) - (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__OZL)) -  48));
            } else {
              result__QZL=(__INTEGER)((__INTEGER)( 10 * result__QZL) + (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__OZL)) -  48));
            };
          } else {
            state__NZL= 3;
          };
        };
        __tmp__L3L=result__CLP;
      };
      if ((! __tmp__L3L)) {
        if ((state__NZL ==  3)) {
          i__MZL=__tmp__ZYS;
        };
      };
      i__MZL=(__INTEGER)(i__MZL +  1);
    };
    n__Y=result__QZL;
  } else {
    n__Y= 27;
  };
  y__JC= 0;
  stop__KC=FALSE__;
  k__IC= 1;
  n__LC=n__Y;
  i__MC= 0;
  digits__PC=create__WF( 20);
  mpz_init_set_ui((q__QC), ( 1));
  mpz_init_set_ui((r__UC), ( 0));
  mpz_init_set_ui((s__YC), ( 0));
  mpz_init_set_ui((t__2C), ( 1));
  mpz_init((u__AD));
  mpz_init((v__CD));
  mpz_init((w__ED));
  do {
    mpz_mul_ui((u__AD),(q__QC), ( 3));
    mpz_add((u__AD),(u__AD),(r__UC));
    mpz_mul_ui((v__CD),(s__YC), ( 3));
    mpz_add((v__CD),(v__CD),(t__2C));
    mpz_tdiv_q((w__ED),(u__AD),(v__CD));
    y__JC=((__INTEGER )(mpz_get_ui((w__ED))));
    mpz_mul_ui((u__AD),(q__QC), ( 4));
    mpz_add((u__AD),(u__AD),(r__UC));
    mpz_mul_ui((v__CD),(s__YC), ( 4));
    mpz_add((v__CD),(v__CD),(t__2C));
    mpz_tdiv_q((w__ED),(u__AD),(v__CD));
    if ((y__JC == ((__INTEGER )(mpz_get_ui((w__ED)))))) {
      add_last__U4C(digits__PC,((__CHARACTER )(((__INTEGER_8)(((__INTEGER_8 )y__JC) + ((__INTEGER_8 )'0'))))));
      i__MC=(__INTEGER)(i__MC +  1);
      if (((((__STRING *)digits__PC)->count__UT ==  10) || (i__MC == n__LC))) {
        add_last__U4C(digits__PC,'\t');
        add_last__U4C(digits__PC,':');
        __tmp__IU=digits__PC;
        Self__QXB=((__INTEGER_32 )i__MC);
        val__YXB= 0;
        i__1XB= 0;
        j__2XB= 0;
        if ((Self__QXB ==  0)) {
          add_last__U4C(((__STRING *)digits__PC),'0');
        } else {
          if ((Self__QXB >  0)) {
            val__YXB=Self__QXB;
          } else {
            val__YXB=(__INTEGER_32)(- Self__QXB);
            add_last__U4C(((__STRING *)__tmp__IU),'-');
          };
          i__1XB=(__INTEGER)(((__STRING *)__tmp__IU)->count__UT +  1);
          while ((val__YXB !=  0)) {
            add_last__U4C(((__STRING *)__tmp__IU),((__CHARACTER )(((__INTEGER_8)(((__INTEGER_8 )(__INTEGER_32)(val__YXB %  10)) + ((__INTEGER_8 )'0'))))));
            val__YXB=(__INTEGER_32)(val__YXB /  10);
          };
          j__2XB=((__STRING *)__tmp__IU)->count__UT;
          while ((i__1XB < j__2XB)) {
            Self__5ME=((__STRING *)__tmp__IU);
            tmp__CNE=((__CHARACTER *)Self__5ME->storage__31C)[(__INTEGER)(i__1XB -  1)];
            ((__CHARACTER *)Self__5ME->storage__31C)[(__INTEGER)(i__1XB -  1)]=((__CHARACTER *)Self__5ME->storage__31C)[(__INTEGER)(j__2XB -  1)];
            ((__CHARACTER *)Self__5ME->storage__31C)[(__INTEGER)(j__2XB -  1)]=tmp__CNE;
            j__2XB=(__INTEGER)(j__2XB -  1);
            i__1XB=(__INTEGER)(i__1XB +  1);
          };
        };
        add_last__U4C(digits__PC,'\n');
        put_string__OQD(((__STRING *)digits__PC));
        ((__STRING *)digits__PC)->count__UT= 0;
      };
      if ((i__MC == n__LC)) {
        stop__KC=TRUE__;
      } else {
        br__DCB=(__INTEGER)((__INTEGER)(-  10) * y__JC);
        mpz_mul_si((u__AD),(r__UC),( 0));
        mpz_mul_si((r__UC),(r__UC),( 10));
        mpz_mul_si((v__CD),(t__2C),(br__DCB));
        mpz_add((r__UC),(r__UC),(v__CD));
        mpz_mul_si((t__2C),(t__2C),( 1));
        mpz_add((t__2C),(t__2C),(u__AD));
        mpz_mul_si((s__YC),(s__YC),( 1));
        mpz_mul_si((u__AD),(q__QC),( 0));
        mpz_add((s__YC),(s__YC),(u__AD));
        mpz_mul_si((q__QC),(q__QC),( 10));
      };
    } else {
      __tmp__TE=(__INTEGER)((__INTEGER)(k__IC <<  2) +  2);
      __tmp__XE=(__INTEGER)((__INTEGER)(k__IC <<  1) +  1);
      mpz_mul_si((r__UC),(r__UC),(__tmp__XE));
      mpz_mul_si((u__AD),(q__QC),(__tmp__TE));
      mpz_add((r__UC),(r__UC),(u__AD));
      mpz_mul_si((u__AD),(t__2C),( 0));
      mpz_mul_si((t__2C),(t__2C),(__tmp__XE));
      mpz_mul_si((v__CD),(s__YC),(__tmp__TE));
      mpz_add((t__2C),(t__2C),(v__CD));
      mpz_mul_si((s__YC),(s__YC),(k__IC));
      mpz_add((s__YC),(s__YC),(u__AD));
      mpz_mul_si((q__QC),(q__QC),(k__IC));
      k__IC=(__INTEGER)(k__IC +  1);
    };
  } while ((! stop__KC));
  return( 0);
}

static __POINTER new_lab__X4B(__UINTEGER_32 t__Z4B)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 idx__14B,pv__C5B;
  __MEMORY *blc__44B,*prev__54B,*Self__BIS,*Self__YUS,*prev__ZUS;
  __MEMORY *next__0US;
  __POINTER result__A5B;
  __BOOLEAN __tmp__CAC;
  idx__14B= 0;
  blc__44B=NULL;
  prev__54B=NULL;
  pv__C5B= 0;
  while_do__QEC:
  {
    if ((idx__14B < nb_page__J5B)) {
      blc__44B=((__MEMORY *)(last_block[(idx__14B)]));
      __tmp__CAC=(((__UINTEGER_32)(((__MEMORY *)blc__44B)->size_and_id__JJ &  4294967292LU) <  4096) || ((__UINTEGER_32)(((__MEMORY *)blc__44B)->size_and_id__JJ &  1) ==  1));
    } else {
      __tmp__CAC=FALSE__;
    };
    if (__tmp__CAC) {
      idx__14B=(__UINTEGER_32)(idx__14B +  1);
      goto while_do__QEC;
    };
  };
  if ((idx__14B >= nb_page__J5B)) {
    blc__44B=new_page__GZD();
  };
  ((__MEMORY *)blc__44B)->size_and_id__JJ=(__UINTEGER_32)(blc__44B->size_and_id__JJ -  4096);
  Self__BIS=((__MEMORY *)blc__44B);
  result__A5B=((__POINTER )((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__BIS) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__BIS->size_and_id__JJ &  4294967292LU))))));
  if (((__UINTEGER_32)(((__MEMORY *)blc__44B)->size_and_id__JJ &  4294967292LU) < ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    Self__YUS=((__MEMORY *)blc__44B);
    prev__ZUS=Self__YUS->previous_free__LJ;
    next__0US=Self__YUS->next_free__KJ;
    if (((void *)prev__ZUS == (void *)NULL)) {
      first_free__IFH=next__0US;
    } else {
      ((__MEMORY *)prev__ZUS)->next_free__KJ=next__0US;
    };
    if (((void *)next__0US != (void *)NULL)) {
      ((__MEMORY *)next__0US)->previous_free__LJ=prev__ZUS;
    };
    pv__C5B=blc__44B->previous_linear__IJ;
    if ((pv__C5B !=  4294967295LU)) {
      prev__54B=((__MEMORY *)(void *)((unsigned long)begin_memory__GJB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )pv__C5B))));
      ((__MEMORY *)prev__54B)->size_and_id__JJ=(__UINTEGER_32)((__UINTEGER_32)(prev__54B->size_and_id__JJ + blc__44B->size_and_id__JJ) +  8);
      last_block[(idx__14B)] = (prev__54B);
    };
  };
  ((__POINTER *)result__A5B)[ 0]=((__POINTER )t__Z4B);
  return((void *)((unsigned long)result__A5B - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))))));
}

static void** create__EQG(__INTEGER nb_elements__GQG)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__RZS,a__QZS,new_size__SZS,new_size2__TZS,a__VZS;
  __UINTEGER_32 new_size__WZS;
  __POINTER result__PZS,ptr_table__K0S,next__J0S,result__L0S;
  __INTEGER Self__WXI;
  void **Result__VZG;
  sz__RZS=((__UINTEGER_32 )(__INTEGER)(nb_elements__GQG * ((__INTEGER )(sizeof(void *)))));
  result__PZS=((__POINTER )(NULL));
  a__QZS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__SZS=(__UINTEGER_32)((__UINTEGER_32)(sz__RZS + a__QZS) & (__UINTEGER_32)(~ a__QZS));
  new_size2__TZS=(__UINTEGER_32)(new_size__SZS + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__TZS <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__VZS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__WZS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__TZS + a__VZS) & (__UINTEGER_32)(~ a__VZS));
    ptr_table__K0S=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__WZS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
    next__J0S=((__POINTER )(NULL));
    result__L0S=((__POINTER *)ptr_table__K0S)[ 0];
    if ((result__L0S == (void *)NULL)) {
      result__L0S=new_lab__X4B(new_size__WZS);
      next__J0S=(void *)((unsigned long)result__L0S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__WZS)));
      ((__POINTER *)next__J0S)[ 0]=NULL;
      ((__POINTER *)ptr_table__K0S)[ 0]=next__J0S;
    } else {
      next__J0S=((__POINTER *)result__L0S)[ 0];
      if ((next__J0S == (void *)NULL)) {
        if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__L0S - (unsigned long)begin_memory__GJB)))) &  4095) + (__UINTEGER_32)(new_size__WZS <<  1)) <=  4096)) {
          next__J0S=(void *)((unsigned long)result__L0S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__WZS)));
        } else {
          next__J0S=new_lab__X4B(new_size__WZS);
        };
        ((__POINTER *)next__J0S)[ 0]=NULL;
        ((__POINTER *)ptr_table__K0S)[ 0]=next__J0S;
      } else {
        ((__POINTER *)result__L0S)[ 0]=(void *)((unsigned long)((__POINTER *)next__J0S)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
        result__L0S=next__J0S;
      };
    };
    ((__POINTER *)result__L0S)[ 0]=((__POINTER ) 3);
    result__PZS=(void *)((unsigned long)result__L0S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__PZS=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__FEH(new_size__SZS))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__VZG=((void **)result__PZS);
  Self__WXI=(__INTEGER)(nb_elements__GQG -  1);
  while ((Self__WXI >=  0)) {
    Result__VZG[Self__WXI]=NULL;
    Self__WXI=(__INTEGER)(Self__WXI -  1);
  };
  return(Result__VZG);
}

static __STRING* create__WF(__INTEGER needed_capacity__YF)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __STRING *result__KI,*Self__F1C;
  __POINTER ptr__LI,ptr_table__Q0S,next__P0S,result__R0S,ptr_table__W0S;
  __POINTER next__V0S,result__X0S;
  __INTEGER typ_id__QI;
  __UINTEGER_32 sz__NI,a__MWS,new_size__NWS,t__WWS,a__TWS,new_size__Z0S;
  __UINTEGER_32 lab_type__Y0S;
  result__KI=NULL;
  ptr__LI=((__POINTER )(NULL));
  typ_id__QI= 0;
  sz__NI=((__UINTEGER_32 )sizeof(__STRING));
  if ((sz__NI ==  0)) {
    result__KI=STRING__;
  } else {
    typ_id__QI=-1;
    clone_allocation_size__4I=(__UINTEGER_32)(clone_allocation_size__4I + sz__NI);
    if ((typ_id__QI == (__INTEGER)(-  1))) {
      a__MWS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__NWS=(__UINTEGER_32)((__UINTEGER_32)(sz__NI + a__MWS) & (__UINTEGER_32)(~ a__MWS));
      ptr_table__Q0S=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__NWS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__P0S=((__POINTER )(NULL));
      result__R0S=((__POINTER *)ptr_table__Q0S)[ 0];
      if ((result__R0S == (void *)NULL)) {
        result__R0S=new_lab__X4B(new_size__NWS);
        next__P0S=(void *)((unsigned long)result__R0S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__NWS)));
        ((__POINTER *)next__P0S)[ 0]=NULL;
        ((__POINTER *)ptr_table__Q0S)[ 0]=next__P0S;
      } else {
        next__P0S=((__POINTER *)result__R0S)[ 0];
        if ((next__P0S == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__R0S - (unsigned long)begin_memory__GJB)))) &  4095) + (__UINTEGER_32)(new_size__NWS <<  1)) <=  4096)) {
            next__P0S=(void *)((unsigned long)result__R0S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__NWS)));
          } else {
            next__P0S=new_lab__X4B(new_size__NWS);
          };
          ((__POINTER *)next__P0S)[ 0]=NULL;
          ((__POINTER *)ptr_table__Q0S)[ 0]=next__P0S;
        } else {
          ((__POINTER *)result__R0S)[ 0]=(void *)((unsigned long)((__POINTER *)next__P0S)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__R0S=next__P0S;
        };
      };
      ptr__LI=result__R0S;
    } else {
      t__WWS=((__UINTEGER_32 )typ_id__QI);
      a__TWS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__Z0S=(__UINTEGER_32)((__UINTEGER_32)(sz__NI + a__TWS) & (__UINTEGER_32)(~ a__TWS));
      ptr_table__W0S=((__POINTER )(&(table_type[(t__WWS)])));
      lab_type__Y0S=(__UINTEGER_32)(t__WWS |  1);
      next__V0S=((__POINTER )(NULL));
      result__X0S=((__POINTER *)ptr_table__W0S)[ 0];
      if ((result__X0S == (void *)NULL)) {
        result__X0S=new_lab__X4B(lab_type__Y0S);
        next__V0S=(void *)((unsigned long)result__X0S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__Z0S)));
        ((__POINTER *)next__V0S)[ 0]=NULL;
        ((__POINTER *)ptr_table__W0S)[ 0]=next__V0S;
      } else {
        next__V0S=((__POINTER *)result__X0S)[ 0];
        if ((next__V0S == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__X0S - (unsigned long)begin_memory__GJB)))) &  4095) + (__UINTEGER_32)(new_size__Z0S <<  1)) <=  4096)) {
            next__V0S=(void *)((unsigned long)result__X0S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__Z0S)));
          } else {
            next__V0S=new_lab__X4B(lab_type__Y0S);
          };
          ((__POINTER *)next__V0S)[ 0]=NULL;
          ((__POINTER *)ptr_table__W0S)[ 0]=next__V0S;
        } else {
          ((__POINTER *)result__X0S)[ 0]=(void *)((unsigned long)((__POINTER *)next__V0S)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__X0S=next__V0S;
        };
      };
      ptr__LI=result__X0S;
    };
    result__KI=((__STRING *)ptr__LI);
    *(result__KI) = *(STRING__);
  };
  Self__F1C=((__STRING *)result__KI);
  if ((needed_capacity__YF >  0)) {
    if ((Self__F1C->capacity__U1C < needed_capacity__YF)) {
      Self__F1C->storage__31C=create__YLF(needed_capacity__YF);
      Self__F1C->capacity__U1C=needed_capacity__YF;
    };
  };
  Self__F1C->count__UT= 0;
  return(result__KI);
}

static void add_last__U4C(__STRING *Self__V4C,__CHARACTER ch__W4C)
// ({STRING},{CHARACTER}) VoidNo recursive, No inlinable.
{
  __INTEGER new_capacity__X4C,__tmp__Q5C,__tmp__40H,Self__ZKM;
  __CHARACTER *__tmp__P5C,*new__L0H;
  new_capacity__X4C= 0;
  if ((Self__V4C->capacity__U1C <= Self__V4C->count__UT)) {
    if ((Self__V4C->capacity__U1C ==  0)) {
      Self__V4C->capacity__U1C= 32;
      Self__V4C->storage__31C=create__YLF( 32);
    } else {
      new_capacity__X4C=(__INTEGER)(Self__V4C->capacity__U1C <<  1);
      __tmp__P5C=Self__V4C->storage__31C;
      __tmp__Q5C=Self__V4C->capacity__U1C;
      new__L0H=((__CHARACTER *)realloc_dynamic__old_size__new_size__VOI(((__POINTER )((__CHARACTER *)__tmp__P5C)),((__UINTEGER_32 )__tmp__Q5C),((__UINTEGER_32 )new_capacity__X4C)));
      __tmp__40H=(__INTEGER)(new_capacity__X4C -  1);
      Self__ZKM=__tmp__Q5C;
      while ((Self__ZKM <= __tmp__40H)) {
        new__L0H[Self__ZKM]='\0';
        Self__ZKM=(__INTEGER)(Self__ZKM +  1);
      };
      Self__V4C->storage__31C=new__L0H;
      Self__V4C->capacity__U1C=new_capacity__X4C;
    };
  };
  ((__CHARACTER *)Self__V4C->storage__31C)[Self__V4C->count__UT]=ch__W4C;
  Self__V4C->count__UT=(__INTEGER)(Self__V4C->count__UT +  1);
}

static __POINTER realloc_dynamic__old_size__new_size__VOI(__POINTER p__XOI,__UINTEGER_32 old_sz__YOI,__UINTEGER_32 new_sz__ZOI)
// ({POINTER},{UINTEGER_32},{UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *mem__EPI,*Self__QYK,*nxt__UYK,*result__VYK,*Self__W1S;
  __MEMORY *new__V1S,*prev__X1S,*next__Y1S,*Self__21S,*Self__41S;
  __MEMORY *next__0RL,*new_free__ZRL,*prev__JXS,*next__KXS;
  __POINTER result__FPI,result__OJG,ptr_table__20S,next__10S;
  __POINTER result__30S,p__GXK,last__UEL,src__AWK,dst__BWK;
  __UINTEGER_32 a__ZWS,old_size__1OI,old_size2__4OI,a__3WS;
  __UINTEGER_32 new_size__BPI,a__SUS,new_size__IJG,new_size2__LJG;
  __UINTEGER_32 a__2XS,new_size__3XS,a__JFB,__tmp__WQI,sz__ZYK;
  __UINTEGER_32 old_size__WYK,siz__Z1S,new_size__11S,prev__1RL;
  __UINTEGER_32 new_size__4RL;
  __INTEGER siz__O1S,Self__T1S,siz__FWK,Self__HCL;
  __POINTER *na_src__Q1S,*na_dst__S1S,*na_src__DWK,*na_dst__EWK;
  mem__EPI=NULL;
  result__FPI=((__POINTER )(NULL));
  a__ZWS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  old_size__1OI=(__UINTEGER_32)((__UINTEGER_32)(old_sz__YOI + a__ZWS) & (__UINTEGER_32)(~ a__ZWS));
  old_size2__4OI=(__UINTEGER_32)(old_size__1OI + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  a__3WS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__BPI=(__UINTEGER_32)((__UINTEGER_32)(new_sz__ZOI + a__3WS) & (__UINTEGER_32)(~ a__3WS));
  if ((old_size2__4OI <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    result__OJG=((__POINTER )(NULL));
    a__SUS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__IJG=(__UINTEGER_32)((__UINTEGER_32)(new_size__BPI + a__SUS) & (__UINTEGER_32)(~ a__SUS));
    new_size2__LJG=(__UINTEGER_32)(new_size__IJG + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
    if ((new_size2__LJG <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
      a__2XS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__3XS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__LJG + a__2XS) & (__UINTEGER_32)(~ a__2XS));
      ptr_table__20S=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__3XS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
      next__10S=((__POINTER )(NULL));
      result__30S=((__POINTER *)ptr_table__20S)[ 0];
      if ((result__30S == (void *)NULL)) {
        result__30S=new_lab__X4B(new_size__3XS);
        next__10S=(void *)((unsigned long)result__30S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__3XS)));
        ((__POINTER *)next__10S)[ 0]=NULL;
        ((__POINTER *)ptr_table__20S)[ 0]=next__10S;
      } else {
        next__10S=((__POINTER *)result__30S)[ 0];
        if ((next__10S == (void *)NULL)) {
          if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__30S - (unsigned long)begin_memory__GJB)))) &  4095) + (__UINTEGER_32)(new_size__3XS <<  1)) <=  4096)) {
            next__10S=(void *)((unsigned long)result__30S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__3XS)));
          } else {
            next__10S=new_lab__X4B(new_size__3XS);
          };
          ((__POINTER *)next__10S)[ 0]=NULL;
          ((__POINTER *)ptr_table__20S)[ 0]=next__10S;
        } else {
          ((__POINTER *)result__30S)[ 0]=(void *)((unsigned long)((__POINTER *)next__10S)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
          result__30S=next__10S;
        };
      };
      ((__POINTER *)result__30S)[ 0]=((__POINTER ) 3);
      result__OJG=(void *)((unsigned long)result__30S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
    } else {
      result__OJG=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__FEH(new_size__IJG))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
    };
    result__FPI=result__OJG;
    siz__O1S=((__INTEGER )old_size__1OI);
    siz__O1S=(__INTEGER)(siz__O1S / ((__INTEGER )(sizeof(void *))));
    na_src__Q1S=((__POINTER *)p__XOI);
    na_dst__S1S=((__POINTER *)result__OJG);
    Self__T1S=(__INTEGER)(siz__O1S -  1);
    while ((Self__T1S >=  0)) {
      na_dst__S1S[Self__T1S]=na_src__Q1S[Self__T1S];
      Self__T1S=(__INTEGER)(Self__T1S -  1);
    };
    p__GXK=(void *)((unsigned long)p__XOI - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))));
    a__JFB=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    last__UEL=((__POINTER *)((__POINTER )(&(table_size[((__UINTEGER_32)((__UINTEGER_32)((__UINTEGER_32)(old_size2__4OI + a__JFB) & (__UINTEGER_32)(~ a__JFB)) / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))))[ 0];
    ((__POINTER *)p__GXK)[ 0]=(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)(void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER *)last__UEL)[ 0]) - (unsigned long)((__POINTER ) 1)) & (unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 3)) - (unsigned long)((__POINTER ) 1)))) - (unsigned long)((__POINTER ) 1));
    ((__POINTER *)last__UEL)[ 0]=p__GXK;
  } else {
    mem__EPI=((__MEMORY *)(void *)((unsigned long)p__XOI - (unsigned long)((__POINTER ) 8)));
    __tmp__WQI=(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)p__XOI - (unsigned long)begin_memory__GJB)))) >>  26);
    Self__QYK=((__MEMORY *)mem__EPI);
    nxt__UYK=NULL;
    result__VYK=NULL;
    sz__ZYK= 0;
    old_size__WYK=(__UINTEGER_32)(Self__QYK->size_and_id__JJ &  4294967292LU);
    if ((new_size__BPI > old_size__WYK)) {
      if ((! ((__UINTEGER_32)(Self__QYK->size_and_id__JJ &  2) !=  0))) {
        nxt__UYK=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__QYK) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__QYK->size_and_id__JJ &  4294967292LU)))));
        sz__ZYK=(__UINTEGER_32)((__UINTEGER_32)(new_size__BPI - old_size__WYK) -  8);
        if ((((__UINTEGER_32)(((__MEMORY *)nxt__UYK)->size_and_id__JJ &  1) ==  0) && ((__UINTEGER_32)(((__MEMORY *)nxt__UYK)->size_and_id__JJ &  4294967292LU) >= sz__ZYK))) {
          Self__W1S=((__MEMORY *)nxt__UYK);
          new__V1S=NULL;
          prev__X1S=Self__W1S->previous_free__LJ;
          next__Y1S=Self__W1S->next_free__KJ;
          if (((void *)prev__X1S == (void *)NULL)) {
            first_free__IFH=next__Y1S;
          } else {
            ((__MEMORY *)prev__X1S)->next_free__KJ=next__Y1S;
          };
          if (((void *)next__Y1S != (void *)NULL)) {
            ((__MEMORY *)next__Y1S)->previous_free__LJ=prev__X1S;
          };
          siz__Z1S=Self__W1S->size_and_id__JJ;
          new_size__11S=(__UINTEGER_32)(siz__Z1S - sz__ZYK);
          if ((new_size__11S > (__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )(MINIMUM_SIZE)) +  2) +  8))) {
            siz__Z1S=sz__ZYK;
            new__V1S=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__W1S) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )sz__ZYK))));
            ((__MEMORY *)new__V1S)->previous_linear__IJ=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__W1S) - (unsigned long)begin_memory__GJB))));
            ((__MEMORY *)new__V1S)->size_and_id__JJ=(__UINTEGER_32)(new_size__11S -  8);
            Self__21S=((__MEMORY *)new__V1S);
            Self__21S->next_free__KJ=first_free__IFH;
            Self__21S->previous_free__LJ=NULL;
            if (((void *)first_free__IFH != (void *)NULL)) {
              ((__MEMORY *)first_free__IFH)->previous_free__LJ=Self__21S;
            };
            first_free__IFH=Self__21S;
            if (((__UINTEGER_32)(((__MEMORY *)new__V1S)->size_and_id__JJ &  2) !=  0)) {
              last_block[(__tmp__WQI)] = (new__V1S);
            } else {
              Self__41S=((__MEMORY *)new__V1S);
              ((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__41S) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__41S->size_and_id__JJ &  4294967292LU)))))->previous_linear__IJ=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)new__V1S)) - (unsigned long)begin_memory__GJB))));
            };
          };
          Self__W1S->size_and_id__JJ=(__UINTEGER_32)(siz__Z1S |  1);
          Self__QYK->size_and_id__JJ=(__UINTEGER_32)((__UINTEGER_32)(Self__QYK->size_and_id__JJ + (__UINTEGER_32)(nxt__UYK->size_and_id__JJ &  4294967294LU)) +  8);
          if (((__UINTEGER_32)(Self__QYK->size_and_id__JJ &  2) !=  0)) {
            last_block[(__tmp__WQI)] = (Self__QYK);
          } else {
            nxt__UYK=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__QYK) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__QYK->size_and_id__JJ &  4294967292LU)))));
            ((__MEMORY *)nxt__UYK)->previous_linear__IJ=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__QYK) - (unsigned long)begin_memory__GJB))));
          };
          result__VYK=Self__QYK;
        };
      };
      if (((void *)result__VYK == (void *)NULL)) {
        result__VYK=search__FEH(new_size__BPI);
        src__AWK=(void *)((unsigned long)((__POINTER )Self__QYK) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
        dst__BWK=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__VYK)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
        siz__FWK=((__INTEGER )old_size__WYK);
        siz__FWK=(__INTEGER)(siz__FWK / ((__INTEGER )(sizeof(void *))));
        na_src__DWK=((__POINTER *)src__AWK);
        na_dst__EWK=((__POINTER *)dst__BWK);
        Self__HCL=(__INTEGER)(siz__FWK -  1);
        while ((Self__HCL >=  0)) {
          na_dst__EWK[Self__HCL]=na_src__DWK[Self__HCL];
          Self__HCL=(__INTEGER)(Self__HCL -  1);
        };
        prev__1RL=Self__QYK->previous_linear__IJ;
        next__0RL=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__QYK) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__QYK->size_and_id__JJ &  4294967292LU)))));
        new_free__ZRL=((__MEMORY *)(void *)((unsigned long)begin_memory__GJB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )prev__1RL))));
        new_size__4RL=(__UINTEGER_32)(Self__QYK->size_and_id__JJ &  4294967294LU);
        if (((prev__1RL ==  4294967295LU) || ((__UINTEGER_32)(new_free__ZRL->size_and_id__JJ &  1) !=  0))) {
          new_free__ZRL=Self__QYK;
          Self__QYK->next_free__KJ=first_free__IFH;
          Self__QYK->previous_free__LJ=NULL;
          if (((void *)first_free__IFH != (void *)NULL)) {
            ((__MEMORY *)first_free__IFH)->previous_free__LJ=Self__QYK;
          };
          first_free__IFH=Self__QYK;
        } else {
          new_size__4RL=(__UINTEGER_32)((__UINTEGER_32)(new_size__4RL + new_free__ZRL->size_and_id__JJ) +  8);
        };
        if (((! ((__UINTEGER_32)(Self__QYK->size_and_id__JJ &  2) !=  0)) && ((__UINTEGER_32)(next__0RL->size_and_id__JJ &  1) ==  0))) {
          new_size__4RL=(__UINTEGER_32)((__UINTEGER_32)(new_size__4RL + next__0RL->size_and_id__JJ) +  8);
          prev__JXS=next__0RL->previous_free__LJ;
          next__KXS=next__0RL->next_free__KJ;
          if (((void *)prev__JXS == (void *)NULL)) {
            first_free__IFH=next__KXS;
          } else {
            ((__MEMORY *)prev__JXS)->next_free__KJ=next__KXS;
          };
          if (((void *)next__KXS != (void *)NULL)) {
            ((__MEMORY *)next__KXS)->previous_free__LJ=prev__JXS;
          };
        };
        new_free__ZRL->size_and_id__JJ=new_size__4RL;
        if (((__UINTEGER_32)(new_free__ZRL->size_and_id__JJ &  2) !=  0)) {
          last_block[(__tmp__WQI)] = (new_free__ZRL);
        } else {
          next__0RL=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__QYK) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__QYK->size_and_id__JJ &  4294967292LU)))));
          next__0RL->previous_linear__IJ=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )new_free__ZRL) - (unsigned long)begin_memory__GJB))));
        };
      };
    } else {
      result__VYK=Self__QYK;
    };
    result__FPI=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__VYK)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  return(result__FPI);
}

static void put_string__OQD(void *s__QQD)
// ({STRING_CONSTANTxSTRING}) VoidNo recursive, No inlinable.
{
  __INTEGER __tmp__DRD,Self__DYD,limit_up__EYD;
  __CHARACTER *__tmp__OXS,*__tmp__PXS;
  __CHARACTER __tmp__KRD;
  if (((struct ___OBJ *)s__QQD)->__id==__STRING_CONSTANT__) {
  };
  if (((struct ___OBJ *)s__QQD)->__id==__STRING_CONSTANT__) {
    __tmp__DRD=((__STRING_CONSTANT *)s__QQD)->count__LDE;
  } else {
    __tmp__DRD=((__STRING *)s__QQD)->count__UT;
  };
  Self__DYD= 1;
  limit_up__EYD=__tmp__DRD;
  __tmp__OXS=((__STRING_CONSTANT *)s__QQD)->storage__JDE;
  __tmp__PXS=((__STRING *)s__QQD)->storage__31C;
  while ((Self__DYD <= limit_up__EYD)) {
    if (((struct ___OBJ *)s__QQD)->__id==__STRING_CONSTANT__) {
      __tmp__KRD=((__CHARACTER *)__tmp__OXS)[(__INTEGER)(Self__DYD -  1)];
    } else {
      __tmp__KRD=((__CHARACTER *)__tmp__PXS)[(__INTEGER)(Self__DYD -  1)];
    };
    fputc((int)(__tmp__KRD),stdout);
    Self__DYD=(__INTEGER)(Self__DYD +  1);
  };
}

static __MEMORY* new_page__GZD()
// () With resultNo recursive, No inlinable.
{
  __POINTER mem__XQF;
  __UINTEGER_32 cap__UQF,old_size__JZD;
  __MEMORY *block__PZD;
  if ((capacity_max__QZD ==  0)) {
    mem__XQF=((__POINTER )(NULL));
    cap__UQF= 33554432;
    do {
      cap__UQF=(__UINTEGER_32)(cap__UQF <<  1);
      mem__XQF=((__POINTER )(malloc((cap__UQF))));
      if ((mem__XQF != (void *)NULL)) {
        free((mem__XQF));
      };
    } while ((! ((mem__XQF == (void *)NULL) || (cap__UQF ==  2147483648LU))));
    if ((mem__XQF == (void *)NULL)) {
      cap__UQF=(__UINTEGER_32)(cap__UQF >>  1);
    };
    capacity_max__QZD=cap__UQF;
    begin_memory__GJB=((__POINTER )(malloc((cap__UQF))));
  };
  old_size__JZD=(__UINTEGER_32)(nb_page__J5B <<  26);
  nb_page__J5B=(__UINTEGER_32)(nb_page__J5B +  1);
  if (((__UINTEGER_32)(old_size__JZD +  67108864) > capacity_max__QZD)) {
    put_string__OQD((&__string_1));
    exit(( 1));
  };
  block__PZD=((__MEMORY *)(void *)((unsigned long)begin_memory__GJB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )old_size__JZD))));
  block__PZD->previous_linear__IJ= 4294967295LU;
  block__PZD->size_and_id__JJ= 67108858;
  block__PZD->next_free__KJ=first_free__IFH;
  block__PZD->previous_free__LJ=NULL;
  if (((void *)first_free__IFH != (void *)NULL)) {
    ((__MEMORY *)first_free__IFH)->previous_free__LJ=block__PZD;
  };
  first_free__IFH=block__PZD;
  last_block[((__UINTEGER_32)(nb_page__J5B -  1))] = (block__PZD);
  return(block__PZD);
}

static __MEMORY* search__FEH(__UINTEGER_32 new_size__HEH)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *result__JEH,*Self__RCI,*new__0CI,*prev__41I,*next__51I;
  __MEMORY *Self__UXH,*Self__HES;
  __UINTEGER_32 idx__TCI,siz__UCI,new_size__XCI;
  result__JEH=first_free__IFH;
  while ((((void *)result__JEH != (void *)NULL) && ((__UINTEGER_32)(((__MEMORY *)result__JEH)->size_and_id__JJ &  4294967292LU) < new_size__HEH))) {
    result__JEH=result__JEH->next_free__KJ;
  };
  if (((void *)result__JEH == (void *)NULL)) {
    result__JEH=new_page__GZD();
  };
  Self__RCI=((__MEMORY *)result__JEH);
  idx__TCI=(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)result__JEH)) - (unsigned long)begin_memory__GJB)))) >>  26);
  new__0CI=NULL;
  prev__41I=Self__RCI->previous_free__LJ;
  next__51I=Self__RCI->next_free__KJ;
  if (((void *)prev__41I == (void *)NULL)) {
    first_free__IFH=next__51I;
  } else {
    ((__MEMORY *)prev__41I)->next_free__KJ=next__51I;
  };
  if (((void *)next__51I != (void *)NULL)) {
    ((__MEMORY *)next__51I)->previous_free__LJ=prev__41I;
  };
  siz__UCI=Self__RCI->size_and_id__JJ;
  new_size__XCI=(__UINTEGER_32)(siz__UCI - new_size__HEH);
  if ((new_size__XCI > (__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )(MINIMUM_SIZE)) +  2) +  8))) {
    siz__UCI=new_size__HEH;
    new__0CI=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__RCI) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__HEH))));
    ((__MEMORY *)new__0CI)->previous_linear__IJ=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__RCI) - (unsigned long)begin_memory__GJB))));
    ((__MEMORY *)new__0CI)->size_and_id__JJ=(__UINTEGER_32)(new_size__XCI -  8);
    Self__UXH=((__MEMORY *)new__0CI);
    Self__UXH->next_free__KJ=first_free__IFH;
    Self__UXH->previous_free__LJ=NULL;
    if (((void *)first_free__IFH != (void *)NULL)) {
      ((__MEMORY *)first_free__IFH)->previous_free__LJ=Self__UXH;
    };
    first_free__IFH=Self__UXH;
    if (((__UINTEGER_32)(((__MEMORY *)new__0CI)->size_and_id__JJ &  2) !=  0)) {
      last_block[(idx__TCI)] = (new__0CI);
    } else {
      Self__HES=((__MEMORY *)new__0CI);
      ((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__HES) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__HES->size_and_id__JJ &  4294967292LU)))))->previous_linear__IJ=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)new__0CI)) - (unsigned long)begin_memory__GJB))));
    };
  };
  Self__RCI->size_and_id__JJ=(__UINTEGER_32)(siz__UCI |  1);
  return(result__JEH);
}

static __CHARACTER* create__YLF(__INTEGER nb_elements__0LF)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__CYS,a__BYS,new_size__DYS,new_size2__EYS,a__GYS;
  __UINTEGER_32 new_size__HYS;
  __POINTER result__AYS,ptr_table__C1S,next__B1S,result__D1S;
  __INTEGER Self__NSI;
  __CHARACTER *Result__01F;
  sz__CYS=((__UINTEGER_32 )nb_elements__0LF);
  result__AYS=((__POINTER )(NULL));
  a__BYS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__DYS=(__UINTEGER_32)((__UINTEGER_32)(sz__CYS + a__BYS) & (__UINTEGER_32)(~ a__BYS));
  new_size2__EYS=(__UINTEGER_32)(new_size__DYS + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__EYS <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__GYS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__HYS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__EYS + a__GYS) & (__UINTEGER_32)(~ a__GYS));
    ptr_table__C1S=((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__HYS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1])));
    next__B1S=((__POINTER )(NULL));
    result__D1S=((__POINTER *)ptr_table__C1S)[ 0];
    if ((result__D1S == (void *)NULL)) {
      result__D1S=new_lab__X4B(new_size__HYS);
      next__B1S=(void *)((unsigned long)result__D1S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__HYS)));
      ((__POINTER *)next__B1S)[ 0]=NULL;
      ((__POINTER *)ptr_table__C1S)[ 0]=next__B1S;
    } else {
      next__B1S=((__POINTER *)result__D1S)[ 0];
      if ((next__B1S == (void *)NULL)) {
        if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__D1S - (unsigned long)begin_memory__GJB)))) &  4095) + (__UINTEGER_32)(new_size__HYS <<  1)) <=  4096)) {
          next__B1S=(void *)((unsigned long)result__D1S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__HYS)));
        } else {
          next__B1S=new_lab__X4B(new_size__HYS);
        };
        ((__POINTER *)next__B1S)[ 0]=NULL;
        ((__POINTER *)ptr_table__C1S)[ 0]=next__B1S;
      } else {
        ((__POINTER *)result__D1S)[ 0]=(void *)((unsigned long)((__POINTER *)next__B1S)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
        result__D1S=next__B1S;
      };
    };
    ((__POINTER *)result__D1S)[ 0]=((__POINTER ) 3);
    result__AYS=(void *)((unsigned long)result__D1S - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__AYS=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__FEH(new_size__DYS))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__01F=((__CHARACTER *)result__AYS);
  Self__NSI=(__INTEGER)(nb_elements__0LF -  1);
  while ((Self__NSI >=  0)) {
    Result__01F[Self__NSI]='\0';
    Self__NSI=(__INTEGER)(Self__NSI -  1);
  };
  return(Result__01F);
}

//==========================//
// DEBUG MANAGER            //
//==========================//

void print_string(char *str) 
{ 
  while (*str!=0) {
    print_char(*str); 
    str++; 
  };
}  

