// C code generated by Lisaac compiler (www.isaacOS.com) //
int arg_count;
char **arg_vector;

//==========================//
// EXTERNAL                 //
//==========================//

// FLOAT_REAL
#include <math.h>
// MEMORY

#define MINIMUM_SIZE 256  
void *table_size[MINIMUM_SIZE/sizeof(void *)];
void *last_block[64];

// SYSTEM
#include <time.h>
// SYSTEM_IO

#include <stdio.h>
#include <stdlib.h>
  
// Hardware 'print_char'
void print_char(char car)
{
  fputc(car,stdout);
}

// Hardware 'exit'
int die_with_code(int code)
{
  exit(code);
}



//==========================//
// TYPE                     //
//==========================//

// Generic Object
struct ___OBJ {
  unsigned long __id;
};

// NULL
#ifndef NULL
#define NULL ((void *)0)
#endif

// POINTER
typedef void * __POINTER;

// UINTEGER_32
typedef unsigned long __UINTEGER_32;

// INTEGER
typedef int __INTEGER;

// CHARACTER
typedef char __CHARACTER;

// STRING
#define __STRING__ 4
typedef struct STRING_struct __STRING;
struct STRING_struct {
  unsigned long __id;
  __INTEGER count__ZO;
  __INTEGER capacity__1O;
  __CHARACTER *storage__EHC;
};
__STRING STRING_={__STRING__};
#define STRING__ (&STRING_)

// MEMORY
#define __MEMORY__ 0
typedef struct MEMORY_struct __MEMORY;
struct MEMORY_struct {
  volatile __UINTEGER_32 previous_linear__PF;
  volatile __UINTEGER_32 size_and_id__QF;
  __MEMORY *next_free__RF;
  __MEMORY *previous_free__SF;
} __attribute__ ((packed));
__MEMORY MEMORY_;
#define MEMORY__ (&MEMORY_)

// REAL_64
typedef double __REAL_64;

// NUMERIC
#define __NUMERIC__ 1
typedef struct NUMERIC_struct __NUMERIC;
struct NUMERIC_struct {
  void *Nothing;
};
__NUMERIC NUMERIC_;
#define NUMERIC__ (&NUMERIC_)

// ARRAYED_COLLECTION[STRING]
#define __ARRAYED_COLLECTIONoSTRINGo__ 2
typedef struct ARRAYED_COLLECTIONoSTRINGo_struct __ARRAYED_COLLECTIONoSTRINGo;
struct ARRAYED_COLLECTIONoSTRINGo_struct {
  __INTEGER upper__SE;
  __INTEGER capacity__QIC;
  void **storage__1IC;
};
__ARRAYED_COLLECTIONoSTRINGo ARRAYED_COLLECTIONoSTRINGo_;
#define ARRAYED_COLLECTIONoSTRINGo__ (&ARRAYED_COLLECTIONoSTRINGo_)

// FAST_ARRAY[STRING]
#define __FAST_ARRAYoSTRINGo__ 3
typedef struct FAST_ARRAYoSTRINGo_struct __FAST_ARRAYoSTRINGo;
struct FAST_ARRAYoSTRINGo_struct {
  __ARRAYED_COLLECTIONoSTRINGo parent_arrayed_collection__PE;
};
__FAST_ARRAYoSTRINGo FAST_ARRAYoSTRINGo_;
#define FAST_ARRAYoSTRINGo__ (&FAST_ARRAYoSTRINGo_)

// OBJECT
#define __OBJECT__ 4
typedef struct OBJECT_struct __OBJECT;
struct OBJECT_struct {
  void *Nothing;
};
__OBJECT OBJECT_;
#define OBJECT__ (&OBJECT_)

// STRING_CONSTANT
#define __STRING_CONSTANT__ 5
typedef struct STRING_CONSTANT_struct __STRING_CONSTANT;
struct STRING_CONSTANT_struct {
  unsigned long __id;
  __INTEGER count__24;
  __CHARACTER *storage__A1D;
};
__STRING_CONSTANT STRING_CONSTANT_={__STRING_CONSTANT__};
#define STRING_CONSTANT__ (&STRING_CONSTANT_)

// TRUE
#define TRUE__ 1

// FALSE
#define FALSE__ 0

// SPECTRAL_NORM
#define __SPECTRAL_NORM__ 5
typedef struct SPECTRAL_NORM_struct __SPECTRAL_NORM;
struct SPECTRAL_NORM_struct {
  void *Nothing;
};
__SPECTRAL_NORM SPECTRAL_NORM_;
#define SPECTRAL_NORM__ (&SPECTRAL_NORM_)

// INTEGER_8
typedef signed char __INTEGER_8;

// BOOLEAN
typedef char __BOOLEAN;

// REAL
typedef float __REAL;


void *table_type[6];

//==========================//
// GLOBAL                   //
//==========================//

void *parent_numeric__H;
__POINTER begin_memory__BJB;
__UINTEGER_32 nb_page__QTB;
__MEMORY *first_free__CBD;
__UINTEGER_32 capacity_max__WID;
void *string_tmp__EI;
__UINTEGER_32 clone_allocation_size__UW;
__INTEGER n__XB;
__REAL_64 *vtmp__CC;

//==========================//
// STRING CONSTANT          //
//==========================//

__STRING_CONSTANT __string_1={__STRING_CONSTANT__,5,"%.9f\n"};
__STRING_CONSTANT __string_2={__STRING_CONSTANT__,19,"Not enough memory.\n"};

//==========================//
// FUNCTION HEADER          //
//==========================//

// Debug Manager
void print_string(char *str);
// Source code
static __POINTER micro_alloc__table__lab__EHB(__UINTEGER_32 new_size__GHB,__POINTER ptr_table__HHB,__UINTEGER_32 lab_type__IHB);
static void** create__JYF(__INTEGER nb_elements__LYF);
static __STRING* create__LV(__INTEGER needed_capacity__NV);
static void add_last__5SD(__STRING *Self__ATD,__CHARACTER ch__BTD);
static __POINTER realloc_dynamic__old_size__new_size__JXH(__POINTER p__LXH,__UINTEGER_32 old_sz__MXH,__UINTEGER_32 new_sz__NXH);
static __MEMORY* search__55C(__UINTEGER_32 new_size__BAD);
static void eval_ata_times_u__XLD(__REAL_64 *u__ZLD,__REAL_64 *atau__0LD);
static __CHARACTER* create__BVF(__INTEGER nb_elements__DVF);
static void put_string__FUC(void *s__HUC);
static __POINTER new_lab__4SB(__UINTEGER_32 t__ATB);
static void copy__to__size__ZZJ(__POINTER src__1ZJ,__POINTER dst__2ZJ,__UINTEGER_32 sz__3ZJ);
static void to_busy__index__YZG(__MEMORY *Self__ZZG,__UINTEGER_32 sz__0ZG,__UINTEGER_32 idx__1ZG);
static __MEMORY* new_page__MID();

//==========================//
// SOURCE CODE              //
//==========================//

int main(int argc,char **argv)
{
  void *str__PI;
  __INTEGER new_count__KP,typ_id__GW,Self__RP,limit_up__SP,idx__WUD;
  __INTEGER i__JWD,new_capacity__DXD,__tmp__HYD,__tmp__PFH,Self__3ML;
  __INTEGER state__Q0K,result__T0K,i__P0K,__tmp__OFS,__tmp__QFS;
  __INTEGER Self__EG,limit_up__FG,Self__TG,Self__CH,limit_up__DH;
  __INTEGER old_count__XO,cap__YO,__tmp__FNC,Self__ZPH;
  __POINTER ptr__BW,result__O5R,result__W5R,result__35R,ptr__2VG;
  __UINTEGER_32 sz__DW,a__BFS,new_size__CFS,t__FDB,a__2AS,sz__Q5R;
  __UINTEGER_32 a__S5R,new_size__T5R,new_size2__U5R,a__UFS;
  __UINTEGER_32 new_size__VFS,sz__Y5R,a__05R,new_size__15R;
  __UINTEGER_32 new_size2__25R,a__4FS,new_size__5FS,sz__55R,a__BAS;
  __UINTEGER_32 new_size__CAS,new_size2__DAS,a__WAS,new_size__2BB;
  __STRING *Self__HWD,*Self__N0K,*Self__3GS,*new__K2,*Self__HMC;
  __STRING *Self__DGC,*Self__VHC;
  __REAL_64 vbv__BB,vv__EB,Self__CI;
  __CHARACTER *arg__OI,*Self__KUD,*p__IWD,*__tmp__PFS,*nc_buf__VO;
  __CHARACTER *__tmp__5MC,*__tmp__CNC,*Self__L3G,*__tmp__TAS;
  __FAST_ARRAYoSTRINGo *result__AW,*Self__HIC,*Self__BXD;
  void *result__NI;
  __BOOLEAN __tmp__RXD,negative__S0K,__tmp__51K,result__BSP,__tmp__S2K;
  __BOOLEAN __tmp__H3K,result__4FO,__tmp__O4K,result__QGO,result__XZO;
  void **__tmp__GYD,**new__2EH;
  __CHARACTER cc__R0K;
  __REAL_64 *u__JB,*v__KB;
  arg_count  = argc;
  arg_vector = argv;
  parent_numeric__H=NUMERIC__;
  ARRAYED_COLLECTIONoSTRINGo__->upper__SE= 0;
  ARRAYED_COLLECTIONoSTRINGo__->capacity__QIC= 0;
  ARRAYED_COLLECTIONoSTRINGo__->storage__1IC=NULL;
  FAST_ARRAYoSTRINGo__->parent_arrayed_collection__PE=(*ARRAYED_COLLECTIONoSTRINGo__);
  clone_allocation_size__UW= 0;
  STRING_CONSTANT__->count__24=((__INTEGER )((0)));
  STRING__->count__ZO= 0;
  STRING_CONSTANT__->storage__A1D=((__CHARACTER *)(NULL));
  STRING__->storage__EHC=NULL;
  nb_page__QTB= 0;
  MEMORY__->size_and_id__QF= 0;
  capacity_max__WID= 0;
  begin_memory__BJB=((__POINTER )(NULL));
  MEMORY__->previous_linear__PF= 0;
  first_free__CBD=NULL;
  MEMORY__->next_free__RF=NULL;
  MEMORY__->previous_free__SF=NULL;
  STRING__->capacity__1O= 0;
  arg__OI=NULL;
  str__PI=NULL;
  new_count__KP=((__INTEGER )(arg_count));
  result__AW=NULL;
  ptr__BW=((__POINTER )(NULL));
  typ_id__GW= 0;
  sz__DW=((__UINTEGER_32 )sizeof(__FAST_ARRAYoSTRINGo));
  if ((sz__DW ==  0)) {
    result__AW=FAST_ARRAYoSTRINGo__;
  } else {
    typ_id__GW=__FAST_ARRAYoSTRINGo__;
    clone_allocation_size__UW=sz__DW;
    if ((typ_id__GW == (__INTEGER)(-  1))) {
      a__BFS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__CFS=(__UINTEGER_32)((__UINTEGER_32)(sz__DW + a__BFS) & (__UINTEGER_32)(~ a__BFS));
      ptr__BW=micro_alloc__table__lab__EHB(new_size__CFS,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__CFS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__CFS);
    } else {
      t__FDB=((__UINTEGER_32 )typ_id__GW);
      a__2AS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      ptr__BW=micro_alloc__table__lab__EHB((__UINTEGER_32)((__UINTEGER_32)(sz__DW + a__2AS) & (__UINTEGER_32)(~ a__2AS)),((__POINTER )(&(table_type[(t__FDB)]))),(__UINTEGER_32)(t__FDB |  1));
    };
    result__AW=((__FAST_ARRAYoSTRINGo *)ptr__BW);
    *(result__AW) = *(FAST_ARRAYoSTRINGo__);
  };
  Self__HIC=((__FAST_ARRAYoSTRINGo *)result__AW);
  if ((Self__HIC->parent_arrayed_collection__PE.capacity__QIC < new_count__KP)) {
    Self__HIC->parent_arrayed_collection__PE.storage__1IC=create__JYF(new_count__KP);
    Self__HIC->parent_arrayed_collection__PE.capacity__QIC=new_count__KP;
  };
  Self__HIC->parent_arrayed_collection__PE.upper__SE=(__INTEGER)(-  1);
  result__NI=result__AW;
  Self__RP= 0;
  limit_up__SP=(__INTEGER)(((__INTEGER )(arg_count)) -  1);
  while ((Self__RP <= limit_up__SP)) {
    arg__OI=((__CHARACTER *)(arg_vector[(Self__RP)]));
    Self__KUD=((__CHARACTER *)arg__OI);
    idx__WUD= 0;
    while ((! ((idx__WUD >  1024) || ('\0' == Self__KUD[idx__WUD])))) {
      idx__WUD=(__INTEGER)(idx__WUD +  1);
    };
    str__PI=create__LV(idx__WUD);
    Self__HWD=((__STRING *)str__PI);
    p__IWD=arg__OI;
    i__JWD= 0;
    Self__HWD->count__ZO= 0;
    while ((((__CHARACTER *)p__IWD)[i__JWD] != '\0')) {
      add_last__5SD(Self__HWD,((__CHARACTER *)p__IWD)[i__JWD]);
      i__JWD=(__INTEGER)(i__JWD +  1);
    };
    Self__BXD=((__FAST_ARRAYoSTRINGo *)result__NI);
    new_capacity__DXD= 0;
    if (((__INTEGER)(Self__BXD->parent_arrayed_collection__PE.upper__SE +  1) <= (__INTEGER)(Self__BXD->parent_arrayed_collection__PE.capacity__QIC -  1))) {
      Self__BXD->parent_arrayed_collection__PE.upper__SE=(__INTEGER)(Self__BXD->parent_arrayed_collection__PE.upper__SE +  1);
      __tmp__RXD=TRUE__;
    } else {
      __tmp__RXD=FALSE__;
    };
    if ((! __tmp__RXD)) {
      if ((Self__BXD->parent_arrayed_collection__PE.capacity__QIC ==  0)) {
        Self__BXD->parent_arrayed_collection__PE.storage__1IC=create__JYF( 2);
        Self__BXD->parent_arrayed_collection__PE.capacity__QIC= 2;
        Self__BXD->parent_arrayed_collection__PE.upper__SE= 0;
      } else {
        new_capacity__DXD=(__INTEGER)(Self__BXD->parent_arrayed_collection__PE.capacity__QIC <<  1);
        __tmp__GYD=Self__BXD->parent_arrayed_collection__PE.storage__1IC;
        __tmp__HYD=Self__BXD->parent_arrayed_collection__PE.capacity__QIC;
        new__2EH=((void **)realloc_dynamic__old_size__new_size__JXH(((__POINTER )((void **)__tmp__GYD)),((__UINTEGER_32 )(__INTEGER)(__tmp__HYD * ((__INTEGER )(sizeof(void *))))),((__UINTEGER_32 )(__INTEGER)(new_capacity__DXD * ((__INTEGER )(sizeof(void *)))))));
        __tmp__PFH=(__INTEGER)(new_capacity__DXD -  1);
        Self__3ML=__tmp__HYD;
        while ((Self__3ML <= __tmp__PFH)) {
          new__2EH[Self__3ML]=NULL;
          Self__3ML=(__INTEGER)(Self__3ML +  1);
        };
        Self__BXD->parent_arrayed_collection__PE.storage__1IC=new__2EH;
        Self__BXD->parent_arrayed_collection__PE.capacity__QIC=new_capacity__DXD;
        Self__BXD->parent_arrayed_collection__PE.upper__SE=(__INTEGER)(Self__BXD->parent_arrayed_collection__PE.upper__SE +  1);
      };
    };
    ((void **)Self__BXD->parent_arrayed_collection__PE.storage__1IC)[Self__BXD->parent_arrayed_collection__PE.upper__SE]=str__PI;
    Self__RP=(__INTEGER)(Self__RP +  1);
  };
  n__XB= 0;
  vtmp__CC=NULL;
  string_tmp__EI=create__LV( 32);
  vbv__BB=((__REAL_64 ) 0);
  vv__EB=((__REAL_64 ) 0);
  if ((result__AW->parent_arrayed_collection__PE.upper__SE ==  1)) {
    Self__N0K=((__STRING *)((void **)((__FAST_ARRAYoSTRINGo *)result__AW)->parent_arrayed_collection__PE.storage__1IC)[ 1]);
    state__Q0K= 0;
    cc__R0K='\0';
    negative__S0K=FALSE__;
    result__T0K= 0;
    i__P0K= 1;
    __tmp__OFS=Self__N0K->count__ZO;
    __tmp__PFS=Self__N0K->storage__EHC;
    __tmp__QFS=Self__N0K->count__ZO;
    while ((i__P0K <= __tmp__OFS)) {
      cc__R0K=((__CHARACTER *)__tmp__PFS)[(__INTEGER)(i__P0K -  1)];
      if ((state__Q0K ==  0)) {
        if ((((((((cc__R0K == ' ') || (cc__R0K == '\t')) || (cc__R0K == '\n')) || (cc__R0K == '\r')) || (cc__R0K == '\0')) || (cc__R0K == '\f')) || (cc__R0K == '\v'))) {
          __tmp__51K=TRUE__;
        } else {
          result__BSP=(cc__R0K == '+');
          if (result__BSP) {
            state__Q0K= 1;
          };
          __tmp__51K=result__BSP;
        };
        if ((! __tmp__51K)) {
          if ((cc__R0K == '-')) {
            negative__S0K=TRUE__;
            state__Q0K= 1;
          } else {
            result__T0K=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__R0K)) -  48);
            state__Q0K= 2;
          };
        };
        __tmp__S2K=TRUE__;
      } else {
        __tmp__S2K=FALSE__;
      };
      if (__tmp__S2K) {
        __tmp__H3K=TRUE__;
      } else {
        result__4FO=(state__Q0K ==  1);
        if (result__4FO) {
          result__T0K=(__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__R0K)) -  48);
          if (negative__S0K) {
            result__T0K=(__INTEGER)(- result__T0K);
          };
          state__Q0K= 2;
        };
        __tmp__H3K=result__4FO;
      };
      if (__tmp__H3K) {
        __tmp__O4K=TRUE__;
      } else {
        result__QGO=(state__Q0K ==  2);
        if (result__QGO) {
          result__XZO=FALSE__;
          if ((((__INTEGER_8 )cc__R0K) >= ((__INTEGER_8 )'0'))) {
            result__XZO=(((__INTEGER_8 )cc__R0K) <= ((__INTEGER_8 )'9'));
          };
          if (result__XZO) {
            if (negative__S0K) {
              result__T0K=(__INTEGER)((__INTEGER)( 10 * result__T0K) - (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__R0K)) -  48));
            } else {
              result__T0K=(__INTEGER)((__INTEGER)( 10 * result__T0K) + (__INTEGER)(((__INTEGER )((__INTEGER_8 )cc__R0K)) -  48));
            };
          } else {
            state__Q0K= 3;
          };
        };
        __tmp__O4K=result__QGO;
      };
      if ((! __tmp__O4K)) {
        if ((state__Q0K ==  3)) {
          i__P0K=__tmp__QFS;
        };
      };
      i__P0K=(__INTEGER)(i__P0K +  1);
    };
    n__XB=result__T0K;
  } else {
    n__XB= 2000;
  };
  sz__Q5R=((__UINTEGER_32 )(__INTEGER)(n__XB * sizeof(__REAL_64)));
  result__O5R=((__POINTER )(NULL));
  a__S5R=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__T5R=(__UINTEGER_32)((__UINTEGER_32)(sz__Q5R + a__S5R) & (__UINTEGER_32)(~ a__S5R));
  new_size2__U5R=(__UINTEGER_32)(new_size__T5R + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__U5R <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__UFS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__VFS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__U5R + a__UFS) & (__UINTEGER_32)(~ a__UFS));
    result__O5R=micro_alloc__table__lab__EHB(new_size__VFS,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__VFS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__VFS);
    ((__POINTER *)result__O5R)[ 0]=((__POINTER ) 3);
    result__O5R=(void *)((unsigned long)result__O5R - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__O5R=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__55C(new_size__T5R))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  u__JB=((__REAL_64 *)result__O5R);
  sz__Y5R=((__UINTEGER_32 )(__INTEGER)(n__XB * sizeof(__REAL_64)));
  result__W5R=((__POINTER )(NULL));
  a__05R=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__15R=(__UINTEGER_32)((__UINTEGER_32)(sz__Y5R + a__05R) & (__UINTEGER_32)(~ a__05R));
  new_size2__25R=(__UINTEGER_32)(new_size__15R + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__25R <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__4FS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__5FS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__25R + a__4FS) & (__UINTEGER_32)(~ a__4FS));
    result__W5R=micro_alloc__table__lab__EHB(new_size__5FS,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__5FS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__5FS);
    ((__POINTER *)result__W5R)[ 0]=((__POINTER ) 3);
    result__W5R=(void *)((unsigned long)result__W5R - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__W5R=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__55C(new_size__15R))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  vtmp__CC=((__REAL_64 *)result__W5R);
  sz__55R=((__UINTEGER_32 )(__INTEGER)(n__XB * sizeof(__REAL_64)));
  result__35R=((__POINTER )(NULL));
  a__BAS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__CAS=(__UINTEGER_32)((__UINTEGER_32)(sz__55R + a__BAS) & (__UINTEGER_32)(~ a__BAS));
  new_size2__DAS=(__UINTEGER_32)(new_size__CAS + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__DAS <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__WAS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__2BB=(__UINTEGER_32)((__UINTEGER_32)(new_size2__DAS + a__WAS) & (__UINTEGER_32)(~ a__WAS));
    result__35R=micro_alloc__table__lab__EHB(new_size__2BB,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__2BB / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__2BB);
    ((__POINTER *)result__35R)[ 0]=((__POINTER ) 3);
    result__35R=(void *)((unsigned long)result__35R - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__35R=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__55C(new_size__CAS))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  v__KB=((__REAL_64 *)result__35R);
  n__XB=(__INTEGER)(n__XB -  1);
  Self__EG= 0;
  limit_up__FG=n__XB;
  while ((Self__EG <= limit_up__FG)) {
    u__JB[Self__EG]=((__REAL_64 ) 1);
    Self__EG=(__INTEGER)(Self__EG +  1);
  };
  Self__TG= 0;
  while ((Self__TG <=  9)) {
    eval_ata_times_u__XLD(u__JB,v__KB);
    eval_ata_times_u__XLD(v__KB,u__JB);
    Self__TG=(__INTEGER)(Self__TG +  1);
  };
  Self__CH= 0;
  limit_up__DH=n__XB;
  while ((Self__CH <= limit_up__DH)) {
    vbv__BB=((__REAL_64 )((vbv__BB) + ((__REAL_64)(u__JB[Self__CH] * v__KB[Self__CH]))));
    vv__EB=((__REAL_64 )((vv__EB) + ((__REAL_64)(v__KB[Self__CH] * v__KB[Self__CH]))));
    Self__CH=(__INTEGER)(Self__CH +  1);
  };
  Self__CI=((__REAL_64 )(sqrt(((__REAL_64)(vbv__BB / vv__EB)))));
  ((__STRING *)string_tmp__EI)->count__ZO= 0;
  old_count__XO=((__STRING *)string_tmp__EI)->count__ZO;
  cap__YO=(__INTEGER)(((__STRING *)string_tmp__EI)->capacity__1O - old_count__XO);
  Self__3GS=((__STRING *)string_tmp__EI);
  if ((Self__3GS->capacity__1O > Self__3GS->count__ZO)) {
    Self__3GS->count__ZO=(__INTEGER)(Self__3GS->count__ZO +  1);
    if ((((__CHARACTER *)Self__3GS->storage__EHC)[(__INTEGER)(Self__3GS->count__ZO -  1)] != '\0')) {
      ((__CHARACTER *)Self__3GS->storage__EHC)[(__INTEGER)(Self__3GS->count__ZO -  1)]='\0';
    };
  } else {
    add_last__5SD(Self__3GS,'\0');
  };
  Self__3GS->count__ZO=(__INTEGER)(Self__3GS->count__ZO -  1);
  ptr__2VG=((__POINTER )((__CHARACTER *)Self__3GS->storage__EHC));
  ptr__2VG=(void *)((unsigned long)ptr__2VG - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )old_count__XO)));
  nc_buf__VO=((__CHARACTER *)ptr__2VG);
  new__K2=create__LV(((__STRING_CONSTANT *)(&__string_1))->count__24);
  Self__HMC=((__STRING *)new__K2);
  Self__HMC->count__ZO=((__STRING_CONSTANT *)(&__string_1))->count__24;
  if ((Self__HMC->count__ZO >  0)) {
    if ((Self__HMC->capacity__1O < Self__HMC->count__ZO)) {
      Self__HMC->storage__EHC=create__BVF(Self__HMC->count__ZO);
      Self__HMC->capacity__1O=Self__HMC->count__ZO;
    };
    __tmp__5MC=Self__HMC->storage__EHC;
    __tmp__CNC=((__STRING_CONSTANT *)(&__string_1))->storage__A1D;
    __tmp__FNC=(__INTEGER)(Self__HMC->count__ZO -  1);
    Self__L3G=((__CHARACTER *)__tmp__5MC);
    Self__ZPH=__tmp__FNC;
    while ((Self__ZPH >=  0)) {
      Self__L3G[Self__ZPH]=((__CHARACTER *)__tmp__CNC)[Self__ZPH];
      Self__ZPH=(__INTEGER)(Self__ZPH -  1);
    };
  };
  Self__DGC=((__STRING *)new__K2);
  if ((Self__DGC->capacity__1O > Self__DGC->count__ZO)) {
    Self__DGC->count__ZO=(__INTEGER)(Self__DGC->count__ZO +  1);
    if ((((__CHARACTER *)Self__DGC->storage__EHC)[(__INTEGER)(Self__DGC->count__ZO -  1)] != '\0')) {
      ((__CHARACTER *)Self__DGC->storage__EHC)[(__INTEGER)(Self__DGC->count__ZO -  1)]='\0';
    };
  } else {
    add_last__5SD(Self__DGC,'\0');
  };
  Self__DGC->count__ZO=(__INTEGER)(Self__DGC->count__ZO -  1);
  snprintf((nc_buf__VO),(cap__YO),(Self__DGC->storage__EHC),(Self__CI));
  Self__VHC=((__STRING *)string_tmp__EI);
  Self__VHC->count__ZO= 0;
  __tmp__TAS=Self__VHC->storage__EHC;
  while ((((__CHARACTER *)__tmp__TAS)[Self__VHC->count__ZO] != '\0')) {
    Self__VHC->count__ZO=(__INTEGER)(Self__VHC->count__ZO +  1);
  };
  put_string__FUC(((__STRING *)string_tmp__EI));
  return( 0);
}

static __POINTER micro_alloc__table__lab__EHB(__UINTEGER_32 new_size__GHB,__POINTER ptr_table__HHB,__UINTEGER_32 lab_type__IHB)
// ({UINTEGER_32},{POINTER},{UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __POINTER next__MHB,result__KHB;
  next__MHB=((__POINTER )(NULL));
  result__KHB=((__POINTER *)ptr_table__HHB)[ 0];
  if ((result__KHB == (void *)NULL)) {
    result__KHB=new_lab__4SB(lab_type__IHB);
    next__MHB=(void *)((unsigned long)result__KHB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__GHB)));
    ((__POINTER *)next__MHB)[ 0]=NULL;
    ((__POINTER *)ptr_table__HHB)[ 0]=next__MHB;
  } else {
    next__MHB=((__POINTER *)result__KHB)[ 0];
    if ((next__MHB == (void *)NULL)) {
      if (((__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)result__KHB - (unsigned long)begin_memory__BJB)))) &  4095) + (__UINTEGER_32)(new_size__GHB <<  1)) <=  4096)) {
        next__MHB=(void *)((unsigned long)result__KHB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )new_size__GHB)));
      } else {
        next__MHB=new_lab__4SB(lab_type__IHB);
      };
      ((__POINTER *)next__MHB)[ 0]=NULL;
      ((__POINTER *)ptr_table__HHB)[ 0]=next__MHB;
    } else {
      ((__POINTER *)result__KHB)[ 0]=(void *)((unsigned long)((__POINTER *)next__MHB)[ 0] & (unsigned long)((__POINTER )(__INTEGER)(~  3)));
      result__KHB=next__MHB;
    };
  };
  return(result__KHB);
}

static void** create__JYF(__INTEGER nb_elements__LYF)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__ABS,a__CBS,new_size__DBS,new_size2__EBS,a__IBS;
  __UINTEGER_32 new_size__JBS;
  __POINTER result__4AS;
  __INTEGER Self__R5H;
  void **Result__EBG;
  sz__ABS=((__UINTEGER_32 )(__INTEGER)(nb_elements__LYF * ((__INTEGER )(sizeof(void *)))));
  result__4AS=((__POINTER )(NULL));
  a__CBS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__DBS=(__UINTEGER_32)((__UINTEGER_32)(sz__ABS + a__CBS) & (__UINTEGER_32)(~ a__CBS));
  new_size2__EBS=(__UINTEGER_32)(new_size__DBS + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__EBS <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__IBS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__JBS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__EBS + a__IBS) & (__UINTEGER_32)(~ a__IBS));
    result__4AS=micro_alloc__table__lab__EHB(new_size__JBS,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__JBS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__JBS);
    ((__POINTER *)result__4AS)[ 0]=((__POINTER ) 3);
    result__4AS=(void *)((unsigned long)result__4AS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__4AS=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__55C(new_size__DBS))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__EBG=((void **)result__4AS);
  Self__R5H=(__INTEGER)(nb_elements__LYF -  1);
  while ((Self__R5H >=  0)) {
    Result__EBG[Self__R5H]=NULL;
    Self__R5H=(__INTEGER)(Self__R5H -  1);
  };
  return(Result__EBG);
}

static __STRING* create__LV(__INTEGER needed_capacity__NV)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __STRING *result__50,*Self__4KC;
  __POINTER ptr__A1;
  __INTEGER typ_id__F1;
  __UINTEGER_32 sz__C1,a__PBS,new_size__QBS,t__ZBS,a__WBS;
  result__50=NULL;
  ptr__A1=((__POINTER )(NULL));
  typ_id__F1= 0;
  sz__C1=((__UINTEGER_32 )sizeof(__STRING));
  if ((sz__C1 ==  0)) {
    result__50=STRING__;
  } else {
    typ_id__F1=-1;
    clone_allocation_size__UW=(__UINTEGER_32)(clone_allocation_size__UW + sz__C1);
    if ((typ_id__F1 == (__INTEGER)(-  1))) {
      a__PBS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__QBS=(__UINTEGER_32)((__UINTEGER_32)(sz__C1 + a__PBS) & (__UINTEGER_32)(~ a__PBS));
      ptr__A1=micro_alloc__table__lab__EHB(new_size__QBS,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__QBS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__QBS);
    } else {
      t__ZBS=((__UINTEGER_32 )typ_id__F1);
      a__WBS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      ptr__A1=micro_alloc__table__lab__EHB((__UINTEGER_32)((__UINTEGER_32)(sz__C1 + a__WBS) & (__UINTEGER_32)(~ a__WBS)),((__POINTER )(&(table_type[(t__ZBS)]))),(__UINTEGER_32)(t__ZBS |  1));
    };
    result__50=((__STRING *)ptr__A1);
    *(result__50) = *(STRING__);
  };
  Self__4KC=((__STRING *)result__50);
  if ((needed_capacity__NV >  0)) {
    if ((Self__4KC->capacity__1O < needed_capacity__NV)) {
      Self__4KC->storage__EHC=create__BVF(needed_capacity__NV);
      Self__4KC->capacity__1O=needed_capacity__NV;
    };
  };
  Self__4KC->count__ZO= 0;
  return(result__50);
}

static void add_last__5SD(__STRING *Self__ATD,__CHARACTER ch__BTD)
// ({STRING},{CHARACTER}) VoidNo recursive, No inlinable.
{
  __INTEGER new_capacity__CTD,__tmp__1TD,__tmp__YDH,Self__4KL;
  __CHARACTER *__tmp__0TD,*new__FDH;
  new_capacity__CTD= 0;
  if ((Self__ATD->capacity__1O <= Self__ATD->count__ZO)) {
    if ((Self__ATD->capacity__1O ==  0)) {
      Self__ATD->capacity__1O= 32;
      Self__ATD->storage__EHC=create__BVF( 32);
    } else {
      new_capacity__CTD=(__INTEGER)(Self__ATD->capacity__1O <<  1);
      __tmp__0TD=Self__ATD->storage__EHC;
      __tmp__1TD=Self__ATD->capacity__1O;
      new__FDH=((__CHARACTER *)realloc_dynamic__old_size__new_size__JXH(((__POINTER )((__CHARACTER *)__tmp__0TD)),((__UINTEGER_32 )__tmp__1TD),((__UINTEGER_32 )new_capacity__CTD)));
      __tmp__YDH=(__INTEGER)(new_capacity__CTD -  1);
      Self__4KL=__tmp__1TD;
      while ((Self__4KL <= __tmp__YDH)) {
        new__FDH[Self__4KL]='\0';
        Self__4KL=(__INTEGER)(Self__4KL +  1);
      };
      Self__ATD->storage__EHC=new__FDH;
      Self__ATD->capacity__1O=new_capacity__CTD;
    };
  };
  ((__CHARACTER *)Self__ATD->storage__EHC)[Self__ATD->count__ZO]=ch__BTD;
  Self__ATD->count__ZO=(__INTEGER)(Self__ATD->count__ZO +  1);
}

static __POINTER realloc_dynamic__old_size__new_size__JXH(__POINTER p__LXH,__UINTEGER_32 old_sz__MXH,__UINTEGER_32 new_sz__NXH)
// ({POINTER},{UINTEGER_32},{UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *mem__YXH,*Self__L2J,*nxt__P2J,*result__Q2J,*next__3SK;
  __MEMORY *new_free__2SK,*prev__0CS,*next__1CS;
  __POINTER result__ZXH,result__CCS,p__B1J,last__JGK;
  __UINTEGER_32 a__2BS,old_size__PXH,old_size2__SXH,a__ACS;
  __UINTEGER_32 new_size__VXH,a__GCS,new_size__HCS,new_size2__ICS;
  __UINTEGER_32 a__MCS,new_size__NCS,a__UT,__tmp__KZH,sz__U2J;
  __UINTEGER_32 old_size__R2J,prev__4SK,new_size__BTK;
  mem__YXH=NULL;
  result__ZXH=((__POINTER )(NULL));
  a__2BS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  old_size__PXH=(__UINTEGER_32)((__UINTEGER_32)(old_sz__MXH + a__2BS) & (__UINTEGER_32)(~ a__2BS));
  old_size2__SXH=(__UINTEGER_32)(old_size__PXH + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  a__ACS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__VXH=(__UINTEGER_32)((__UINTEGER_32)(new_sz__NXH + a__ACS) & (__UINTEGER_32)(~ a__ACS));
  if ((old_size2__SXH <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    result__CCS=((__POINTER )(NULL));
    a__GCS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__HCS=(__UINTEGER_32)((__UINTEGER_32)(new_size__VXH + a__GCS) & (__UINTEGER_32)(~ a__GCS));
    new_size2__ICS=(__UINTEGER_32)(new_size__HCS + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
    if ((new_size2__ICS <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
      a__MCS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
      new_size__NCS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__ICS + a__MCS) & (__UINTEGER_32)(~ a__MCS));
      result__CCS=micro_alloc__table__lab__EHB(new_size__NCS,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__NCS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__NCS);
      ((__POINTER *)result__CCS)[ 0]=((__POINTER ) 3);
      result__CCS=(void *)((unsigned long)result__CCS - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
    } else {
      result__CCS=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__55C(new_size__HCS))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
    };
    result__ZXH=result__CCS;
    copy__to__size__ZZJ(p__LXH,result__CCS,old_size__PXH);
    p__B1J=(void *)((unsigned long)p__LXH - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))));
    a__UT=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    last__JGK=((__POINTER *)((__POINTER )(&(table_size[((__UINTEGER_32)((__UINTEGER_32)((__UINTEGER_32)(old_size2__SXH + a__UT) & (__UINTEGER_32)(~ a__UT)) / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))))[ 0];
    ((__POINTER *)p__B1J)[ 0]=(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)(void *)((unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER *)last__JGK)[ 0]) - (unsigned long)((__POINTER ) 1)) & (unsigned long)(void *)((unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 3)) - (unsigned long)((__POINTER ) 1)))) - (unsigned long)((__POINTER ) 1));
    ((__POINTER *)last__JGK)[ 0]=p__B1J;
  } else {
    mem__YXH=((__MEMORY *)(void *)((unsigned long)p__LXH - (unsigned long)((__POINTER ) 8)));
    __tmp__KZH=(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)p__LXH - (unsigned long)begin_memory__BJB)))) >>  26);
    Self__L2J=((__MEMORY *)mem__YXH);
    nxt__P2J=NULL;
    result__Q2J=NULL;
    sz__U2J= 0;
    old_size__R2J=(__UINTEGER_32)(Self__L2J->size_and_id__QF &  4294967292LU);
    if ((new_size__VXH > old_size__R2J)) {
      if ((! ((__UINTEGER_32)(Self__L2J->size_and_id__QF &  2) !=  0))) {
        nxt__P2J=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__L2J) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__L2J->size_and_id__QF &  4294967292LU)))));
        sz__U2J=(__UINTEGER_32)((__UINTEGER_32)(new_size__VXH - old_size__R2J) -  8);
        if ((((__UINTEGER_32)(((__MEMORY *)nxt__P2J)->size_and_id__QF &  1) ==  0) && ((__UINTEGER_32)(((__MEMORY *)nxt__P2J)->size_and_id__QF &  4294967292LU) >= sz__U2J))) {
          to_busy__index__YZG(nxt__P2J,sz__U2J,__tmp__KZH);
          Self__L2J->size_and_id__QF=(__UINTEGER_32)((__UINTEGER_32)(Self__L2J->size_and_id__QF + (__UINTEGER_32)(nxt__P2J->size_and_id__QF &  4294967294LU)) +  8);
          if (((__UINTEGER_32)(Self__L2J->size_and_id__QF &  2) !=  0)) {
            last_block[(__tmp__KZH)] = (Self__L2J);
          } else {
            nxt__P2J=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__L2J) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__L2J->size_and_id__QF &  4294967292LU)))));
            ((__MEMORY *)nxt__P2J)->previous_linear__PF=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__L2J) - (unsigned long)begin_memory__BJB))));
          };
          result__Q2J=Self__L2J;
        };
      };
      if (((void *)result__Q2J == (void *)NULL)) {
        result__Q2J=search__55C(new_size__VXH);
        copy__to__size__ZZJ((void *)((unsigned long)((__POINTER )Self__L2J) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))),(void *)((unsigned long)((__POINTER )((__MEMORY *)result__Q2J)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))),old_size__R2J);
        prev__4SK=Self__L2J->previous_linear__PF;
        next__3SK=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__L2J) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__L2J->size_and_id__QF &  4294967292LU)))));
        new_free__2SK=((__MEMORY *)(void *)((unsigned long)begin_memory__BJB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )prev__4SK))));
        new_size__BTK=(__UINTEGER_32)(Self__L2J->size_and_id__QF &  4294967294LU);
        if (((prev__4SK ==  4294967295LU) || ((__UINTEGER_32)(new_free__2SK->size_and_id__QF &  1) !=  0))) {
          new_free__2SK=Self__L2J;
          Self__L2J->next_free__RF=first_free__CBD;
          Self__L2J->previous_free__SF=NULL;
          if (((void *)first_free__CBD != (void *)NULL)) {
            ((__MEMORY *)first_free__CBD)->previous_free__SF=Self__L2J;
          };
          first_free__CBD=Self__L2J;
        } else {
          new_size__BTK=(__UINTEGER_32)((__UINTEGER_32)(new_size__BTK + new_free__2SK->size_and_id__QF) +  8);
        };
        if (((! ((__UINTEGER_32)(Self__L2J->size_and_id__QF &  2) !=  0)) && ((__UINTEGER_32)(next__3SK->size_and_id__QF &  1) ==  0))) {
          new_size__BTK=(__UINTEGER_32)((__UINTEGER_32)(new_size__BTK + next__3SK->size_and_id__QF) +  8);
          prev__0CS=next__3SK->previous_free__SF;
          next__1CS=next__3SK->next_free__RF;
          if (((void *)prev__0CS == (void *)NULL)) {
            first_free__CBD=next__1CS;
          } else {
            ((__MEMORY *)prev__0CS)->next_free__RF=next__1CS;
          };
          if (((void *)next__1CS != (void *)NULL)) {
            ((__MEMORY *)next__1CS)->previous_free__SF=prev__0CS;
          };
        };
        new_free__2SK->size_and_id__QF=new_size__BTK;
        if (((__UINTEGER_32)(new_free__2SK->size_and_id__QF &  2) !=  0)) {
          last_block[(__tmp__KZH)] = (new_free__2SK);
        } else {
          next__3SK=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__L2J) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__L2J->size_and_id__QF &  4294967292LU)))));
          next__3SK->previous_linear__PF=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )new_free__2SK) - (unsigned long)begin_memory__BJB))));
        };
      };
    } else {
      result__Q2J=Self__L2J;
    };
    result__ZXH=(void *)((unsigned long)((__POINTER )((__MEMORY *)result__Q2J)) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  return(result__ZXH);
}

static __MEMORY* search__55C(__UINTEGER_32 new_size__BAD)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __MEMORY *result__DAD;
  result__DAD=first_free__CBD;
  while ((((void *)result__DAD != (void *)NULL) && ((__UINTEGER_32)(((__MEMORY *)result__DAD)->size_and_id__QF &  4294967292LU) < new_size__BAD))) {
    result__DAD=result__DAD->next_free__RF;
  };
  if (((void *)result__DAD == (void *)NULL)) {
    result__DAD=new_page__MID();
  };
  to_busy__index__YZG(result__DAD,new_size__BAD,(__UINTEGER_32)(((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)result__DAD)) - (unsigned long)begin_memory__BJB)))) >>  26));
  return(result__DAD);
}

static void eval_ata_times_u__XLD(__REAL_64 *u__ZLD,__REAL_64 *atau__0LD)
// ({NATIVE_ARRAYoExpanded_REAL_64o},{NATIVE_ARRAYoExpanded_REAL_64o}) VoidNo recursive, No inlinable.
{
  __INTEGER __tmp__GDE,Self__VWE,i__KDE,__tmp__ODE,Self__J2F,__tmp__CEE;
  __INTEGER Self__EXE,i__GEE,__tmp__KEE,Self__Z2F;
  __REAL_64 *__tmp__3LD,*u__AEE;
  __tmp__3LD=vtmp__CC;
  __tmp__GDE=n__XB;
  Self__VWE= 0;
  while ((Self__VWE <= __tmp__GDE)) {
    i__KDE=Self__VWE;
    ((__REAL_64 *)__tmp__3LD)[Self__VWE]=((__REAL_64 ) 0);
    __tmp__ODE=n__XB;
    Self__J2F= 0;
    while ((Self__J2F <= __tmp__ODE)) {
      ((__REAL_64 *)__tmp__3LD)[i__KDE]=((__REAL_64 )((((__REAL_64 *)__tmp__3LD)[i__KDE]) + ((__REAL_64)(((__REAL_64 )(__REAL)(1.0 / ((__REAL )(__INTEGER)((__INTEGER)((__INTEGER)((__INTEGER)((__INTEGER)(i__KDE + Self__J2F) * (__INTEGER)((__INTEGER)(i__KDE + Self__J2F) +  1)) >>  1) + i__KDE) +  1)))) * u__ZLD[Self__J2F]))));
      Self__J2F=(__INTEGER)(Self__J2F +  1);
    };
    Self__VWE=(__INTEGER)(Self__VWE +  1);
  };
  u__AEE=vtmp__CC;
  __tmp__CEE=n__XB;
  Self__EXE= 0;
  while ((Self__EXE <= __tmp__CEE)) {
    i__GEE=Self__EXE;
    atau__0LD[Self__EXE]=((__REAL_64 ) 0);
    __tmp__KEE=n__XB;
    Self__Z2F= 0;
    while ((Self__Z2F <= __tmp__KEE)) {
      atau__0LD[i__GEE]=((__REAL_64 )((atau__0LD[i__GEE]) + ((__REAL_64)(((__REAL_64 )(__REAL)(1.0 / ((__REAL )(__INTEGER)((__INTEGER)((__INTEGER)((__INTEGER)((__INTEGER)(Self__Z2F + i__GEE) * (__INTEGER)((__INTEGER)(Self__Z2F + i__GEE) +  1)) >>  1) + Self__Z2F) +  1)))) * ((__REAL_64 *)u__AEE)[Self__Z2F]))));
      Self__Z2F=(__INTEGER)(Self__Z2F +  1);
    };
    Self__EXE=(__INTEGER)(Self__EXE +  1);
  };
}

static __CHARACTER* create__BVF(__INTEGER nb_elements__DVF)
// ({INTEGER}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 sz__ML,a__Z4R,new_size__OL,new_size2__RL,a__XDS;
  __UINTEGER_32 new_size__YDS;
  __POINTER result__UL;
  __INTEGER Self__K4H;
  __CHARACTER *Result__D4F;
  sz__ML=((__UINTEGER_32 )nb_elements__DVF);
  result__UL=((__POINTER )(NULL));
  a__Z4R=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
  new_size__OL=(__UINTEGER_32)((__UINTEGER_32)(sz__ML + a__Z4R) & (__UINTEGER_32)(~ a__Z4R));
  new_size2__RL=(__UINTEGER_32)(new_size__OL + ((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))));
  if ((new_size2__RL <= ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    a__XDS=(__UINTEGER_32)(((__UINTEGER_32 )((__INTEGER )(sizeof(void *)))) -  1);
    new_size__YDS=(__UINTEGER_32)((__UINTEGER_32)(new_size2__RL + a__XDS) & (__UINTEGER_32)(~ a__XDS));
    result__UL=micro_alloc__table__lab__EHB(new_size__YDS,((__POINTER )(&(table_size[((__UINTEGER_32)(new_size__YDS / ((__UINTEGER_32 )((__INTEGER )(sizeof(void *))))))-1]))),new_size__YDS);
    ((__POINTER *)result__UL)[ 0]=((__POINTER ) 3);
    result__UL=(void *)((unsigned long)result__UL - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *))))));
  } else {
    result__UL=(void *)((unsigned long)((__POINTER )((__MEMORY *)search__55C(new_size__OL))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8)));
  };
  Result__D4F=((__CHARACTER *)result__UL);
  Self__K4H=(__INTEGER)(nb_elements__DVF -  1);
  while ((Self__K4H >=  0)) {
    Result__D4F[Self__K4H]='\0';
    Self__K4H=(__INTEGER)(Self__K4H -  1);
  };
  return(Result__D4F);
}

static void put_string__FUC(void *s__HUC)
// ({STRING_CONSTANTxSTRING}) VoidNo recursive, No inlinable.
{
  __INTEGER __tmp__ZUC,Self__Q5C,limit_up__R5C;
  __CHARACTER *__tmp__4DS,*__tmp__5DS;
  __CHARACTER __tmp__AVC;
  if (((struct ___OBJ *)s__HUC)->__id==__STRING_CONSTANT__) {
  };
  if (((struct ___OBJ *)s__HUC)->__id==__STRING_CONSTANT__) {
    __tmp__ZUC=((__STRING_CONSTANT *)s__HUC)->count__24;
  } else {
    __tmp__ZUC=((__STRING *)s__HUC)->count__ZO;
  };
  Self__Q5C= 1;
  limit_up__R5C=__tmp__ZUC;
  __tmp__4DS=((__STRING_CONSTANT *)s__HUC)->storage__A1D;
  __tmp__5DS=((__STRING *)s__HUC)->storage__EHC;
  while ((Self__Q5C <= limit_up__R5C)) {
    if (((struct ___OBJ *)s__HUC)->__id==__STRING_CONSTANT__) {
      __tmp__AVC=((__CHARACTER *)__tmp__4DS)[(__INTEGER)(Self__Q5C -  1)];
    } else {
      __tmp__AVC=((__CHARACTER *)__tmp__5DS)[(__INTEGER)(Self__Q5C -  1)];
    };
    fputc((int)(__tmp__AVC),stdout);
    Self__Q5C=(__INTEGER)(Self__Q5C +  1);
  };
}

static __POINTER new_lab__4SB(__UINTEGER_32 t__ATB)
// ({UINTEGER_32}) With resultNo recursive, No inlinable.
{
  __UINTEGER_32 idx__CTB,pv__JTB;
  __MEMORY *blc__FTB,*prev__GTB,*Self__4UR,*Self__14R,*prev__24R;
  __MEMORY *next__34R;
  __POINTER result__HTB;
  __BOOLEAN __tmp__JUB;
  idx__CTB= 0;
  blc__FTB=NULL;
  prev__GTB=NULL;
  pv__JTB= 0;
  while_do__BYB:
  {
    if ((idx__CTB < nb_page__QTB)) {
      blc__FTB=((__MEMORY *)(last_block[(idx__CTB)]));
      __tmp__JUB=(((__UINTEGER_32)(((__MEMORY *)blc__FTB)->size_and_id__QF &  4294967292LU) <  4096) || ((__UINTEGER_32)(((__MEMORY *)blc__FTB)->size_and_id__QF &  1) ==  1));
    } else {
      __tmp__JUB=FALSE__;
    };
    if (__tmp__JUB) {
      idx__CTB=(__UINTEGER_32)(idx__CTB +  1);
      goto while_do__BYB;
    };
  };
  if ((idx__CTB >= nb_page__QTB)) {
    blc__FTB=new_page__MID();
  };
  ((__MEMORY *)blc__FTB)->size_and_id__QF=(__UINTEGER_32)(blc__FTB->size_and_id__QF -  4096);
  Self__4UR=((__MEMORY *)blc__FTB);
  result__HTB=((__POINTER )((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__4UR) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__4UR->size_and_id__QF &  4294967292LU))))));
  if (((__UINTEGER_32)(((__MEMORY *)blc__FTB)->size_and_id__QF &  4294967292LU) < ((__UINTEGER_32 )(MINIMUM_SIZE)))) {
    Self__14R=((__MEMORY *)blc__FTB);
    prev__24R=Self__14R->previous_free__SF;
    next__34R=Self__14R->next_free__RF;
    if (((void *)prev__24R == (void *)NULL)) {
      first_free__CBD=next__34R;
    } else {
      ((__MEMORY *)prev__24R)->next_free__RF=next__34R;
    };
    if (((void *)next__34R != (void *)NULL)) {
      ((__MEMORY *)next__34R)->previous_free__SF=prev__24R;
    };
    pv__JTB=blc__FTB->previous_linear__PF;
    if ((pv__JTB !=  4294967295LU)) {
      prev__GTB=((__MEMORY *)(void *)((unsigned long)begin_memory__BJB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )pv__JTB))));
      ((__MEMORY *)prev__GTB)->size_and_id__QF=(__UINTEGER_32)((__UINTEGER_32)(prev__GTB->size_and_id__QF + blc__FTB->size_and_id__QF) +  8);
      last_block[(idx__CTB)] = (prev__GTB);
    };
  };
  ((__POINTER *)result__HTB)[ 0]=((__POINTER )t__ATB);
  return((void *)((unsigned long)result__HTB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )((__INTEGER )(sizeof(void *)))))));
}

static void copy__to__size__ZZJ(__POINTER src__1ZJ,__POINTER dst__2ZJ,__UINTEGER_32 sz__3ZJ)
// ({POINTER},{POINTER},{UINTEGER_32}) VoidNo recursive, No inlinable.
{
  __INTEGER siz__A0J,Self__2DK;
  __POINTER *na_src__4ZJ,*na_dst__5ZJ;
  siz__A0J=((__INTEGER )sz__3ZJ);
  siz__A0J=(__INTEGER)(siz__A0J / ((__INTEGER )(sizeof(void *))));
  na_src__4ZJ=((__POINTER *)src__1ZJ);
  na_dst__5ZJ=((__POINTER *)dst__2ZJ);
  Self__2DK=(__INTEGER)(siz__A0J -  1);
  while ((Self__2DK >=  0)) {
    na_dst__5ZJ[Self__2DK]=na_src__4ZJ[Self__2DK];
    Self__2DK=(__INTEGER)(Self__2DK -  1);
  };
}

static void to_busy__index__YZG(__MEMORY *Self__ZZG,__UINTEGER_32 sz__0ZG,__UINTEGER_32 idx__1ZG)
// ({MEMORY},{UINTEGER_32},{UINTEGER_32}) VoidNo recursive, No inlinable.
{
  __MEMORY *new__C0G,*prev__TMH,*next__UMH,*Self__C4G,*Self__DRR;
  __UINTEGER_32 siz__2ZG,new_size__5ZG;
  new__C0G=NULL;
  prev__TMH=Self__ZZG->previous_free__SF;
  next__UMH=Self__ZZG->next_free__RF;
  if (((void *)prev__TMH == (void *)NULL)) {
    first_free__CBD=next__UMH;
  } else {
    ((__MEMORY *)prev__TMH)->next_free__RF=next__UMH;
  };
  if (((void *)next__UMH != (void *)NULL)) {
    ((__MEMORY *)next__UMH)->previous_free__SF=prev__TMH;
  };
  siz__2ZG=Self__ZZG->size_and_id__QF;
  new_size__5ZG=(__UINTEGER_32)(siz__2ZG - sz__0ZG);
  if ((new_size__5ZG > (__UINTEGER_32)((__UINTEGER_32)(((__UINTEGER_32 )(MINIMUM_SIZE)) +  2) +  8))) {
    siz__2ZG=sz__0ZG;
    new__C0G=((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__ZZG) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )sz__0ZG))));
    ((__MEMORY *)new__C0G)->previous_linear__PF=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )Self__ZZG) - (unsigned long)begin_memory__BJB))));
    ((__MEMORY *)new__C0G)->size_and_id__QF=(__UINTEGER_32)(new_size__5ZG -  8);
    Self__C4G=((__MEMORY *)new__C0G);
    Self__C4G->next_free__RF=first_free__CBD;
    Self__C4G->previous_free__SF=NULL;
    if (((void *)first_free__CBD != (void *)NULL)) {
      ((__MEMORY *)first_free__CBD)->previous_free__SF=Self__C4G;
    };
    first_free__CBD=Self__C4G;
    if (((__UINTEGER_32)(((__MEMORY *)new__C0G)->size_and_id__QF &  2) !=  0)) {
      last_block[(idx__1ZG)] = (new__C0G);
    } else {
      Self__DRR=((__MEMORY *)new__C0G);
      ((__MEMORY *)(void *)((unsigned long)(void *)((unsigned long)((__POINTER )Self__DRR) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER ) 8))) - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )(__UINTEGER_32)(Self__DRR->size_and_id__QF &  4294967292LU)))))->previous_linear__PF=((__UINTEGER_32 )((unsigned int)((void *)((unsigned long)((__POINTER )((__MEMORY *)new__C0G)) - (unsigned long)begin_memory__BJB))));
    };
  };
  Self__ZZG->size_and_id__QF=(__UINTEGER_32)(siz__2ZG |  1);
}

static __MEMORY* new_page__MID()
// () With resultNo recursive, No inlinable.
{
  __POINTER mem__ECF;
  __UINTEGER_32 cap__BCF,old_size__PID;
  __MEMORY *block__VID;
  if ((capacity_max__WID ==  0)) {
    mem__ECF=((__POINTER )(NULL));
    cap__BCF= 33554432;
    do {
      cap__BCF=(__UINTEGER_32)(cap__BCF <<  1);
      mem__ECF=((__POINTER )(malloc((cap__BCF))));
      if ((mem__ECF != (void *)NULL)) {
        free((mem__ECF));
      };
    } while ((! ((mem__ECF == (void *)NULL) || (cap__BCF ==  2147483648LU))));
    if ((mem__ECF == (void *)NULL)) {
      cap__BCF=(__UINTEGER_32)(cap__BCF >>  1);
    };
    capacity_max__WID=cap__BCF;
    begin_memory__BJB=((__POINTER )(malloc((cap__BCF))));
  };
  old_size__PID=(__UINTEGER_32)(nb_page__QTB <<  26);
  nb_page__QTB=(__UINTEGER_32)(nb_page__QTB +  1);
  if (((__UINTEGER_32)(old_size__PID +  67108864) > capacity_max__WID)) {
    put_string__FUC((&__string_2));
    exit(( 1));
  };
  block__VID=((__MEMORY *)(void *)((unsigned long)begin_memory__BJB - (unsigned long)(void *)((unsigned long)((__POINTER ) 0) - (unsigned long)((__POINTER )old_size__PID))));
  block__VID->previous_linear__PF= 4294967295LU;
  block__VID->size_and_id__QF= 67108858;
  block__VID->next_free__RF=first_free__CBD;
  block__VID->previous_free__SF=NULL;
  if (((void *)first_free__CBD != (void *)NULL)) {
    ((__MEMORY *)first_free__CBD)->previous_free__SF=block__VID;
  };
  first_free__CBD=block__VID;
  last_block[((__UINTEGER_32)(nb_page__QTB -  1))] = (block__VID);
  return(block__VID);
}

//==========================//
// DEBUG MANAGER            //
//==========================//

void print_string(char *str) 
{ 
  while (*str!=0) {
    print_char(*str); 
    str++; 
  };
}  

